STIR: stir::TimeFrameMotion Class Reference
stir::TimeFrameMotion Class Reference abstract
STIR » STIR library » Items relating to motion and motion correction
A class for encoding average motion in the frames.
#include "stir_experimental/motion/TimeFrameMotion.h"
Public Member Functions
virtual Succeeded process_data ()=0
void move_to_reference (const bool)
void set_frame_num_to_process (const int)
int get_frame_num_to_process () const
const RigidObject3DTransformation & get_current_rigid_object_transformation () const
get transformation from (or to) reference for current frame
const RigidObject3DTransformation & get_rigid_object_transformation_to_reference () const
Get the transformation to the reference as returned by the RigidObject3DMotion object.
const TimeFrameDefinitions & get_time_frame_defs () const
double get_frame_start_time (unsigned frame_num) const
double get_frame_end_time (unsigned frame_num) const
const RigidObject3DMotion & get_motion () const
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
Protected Member Functions
void set_defaults () override
parsing functions
void initialise_keymap () override
Initialise all keywords.
bool post_processing () override
This will be called at the end of the parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Additional Inherited Members
KeyParser parser
Detailed Description
A class for encoding average motion in the frames.
Example par file
These are the parameters set by this class. The derived classes will add more.
  ; see stir::TimeFrameDefinitions
  time frame_definition filename := frame_definition_filename
  ; next parameter is optional (and not normally necessary)
  ; it can be used if the frame definitions are relative to another scan as what
  ; is used to for the rigid object motion (i.e. currently the list mode data used
  ;  for the Polaris synchronisation)
  ; scan_start_time_secs_since_1970_UTC
  ; next parameter defines transformation 'direction', defaults to 1
  ;move_to_reference := 1
  ; next can be set to do only 1 frame, defaults means all frames
  ;frame_num_to_process := -1
  ; specify motion, see stir::RigidObject3DMotion
  Rigid Object 3D Motion Type := type
  ; specify reference position, see stir::AbsTimeInterval
  time interval for reference position type:= type
  END :=
Member Function Documentation
get_current_rigid_object_transformation()
const RigidObject3DTransformation & stir::TimeFrameMotion::get_current_rigid_object_transformation () const
get transformation from (or to) reference for current frame
This is computed using RigidObject3DTransformation::compute_average_motion_in_scanner_coords for the current frame.
References get_current_rigid_object_transformation().
Referenced by get_current_rigid_object_transformation().
set_defaults()
void stir::TimeFrameMotion::set_defaults () override protected virtual
parsing functions
Reimplemented from stir::ParsingObject.
References set_defaults().
Referenced by stir::MoveImage::set_defaults(), stir::MoveProjData::set_defaults(), stir::ReportMovement::set_defaults(), and set_defaults().
initialise_keymap()
void stir::TimeFrameMotion::initialise_keymap () override protected virtual
Initialise all keywords.
Reimplemented from stir::ParsingObject.
References initialise_keymap().
Referenced by stir::MoveImage::initialise_keymap(), stir::MoveProjData::initialise_keymap(), stir::ReportMovement::initialise_keymap(), and initialise_keymap().
post_processing()
bool stir::TimeFrameMotion::post_processing () override protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented from stir::ParsingObject.
References stir::RigidObject3DTransformation::inverse(), post_processing(), and stir::warning().
Referenced by stir::MoveImage::post_processing(), stir::MoveProjData::post_processing(), stir::ReportMovement::post_processing(), and post_processing().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir_experimental/motion/TimeFrameMotion.h
/home/kris/devel/STIRdistrib/STIR/src/experimental/motion/TimeFrameMotion.cxx