STIR: stir::ParsingObject Class Reference
stir::ParsingObject Class Reference
STIR » STIR library » Basic building blocks
A base class for objects that want to be able to parse parameter files.
#include "stir/ParsingObject.h"
Public Member Functions
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
parsing functions
parse() returns false if there is some error, true otherwise.
KeyParser parser
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
virtual void set_defaults ()
Set defaults before parsing.
virtual void initialise_keymap ()
Initialise all keywords.
virtual bool post_processing ()
This will be called at the end of the parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Detailed Description
A base class for objects that want to be able to parse parameter files.
This class is essentially a wrapper for KeyParser, such that it is safe to copy ParsingObject objects. The problem with KeyParser is that it stores pointers to the variables it needs to fill in. So, if you copy one KeyParser object to another, both will fill in the same variables (unless add_key is called afterwards). ParsingObject solves this by having a copy constructor that reinitialises all keys in its own (protected) KeyParser object.
Warning
All this only works when all keys are set in the initialise_keymap() function, and only there.
See also
KeyParser
Member Function Documentation
parameter_info()
std::string stir::ParsingObject::parameter_info () virtual
Reimplemented in stir::RegisteredParsingObject< AbsTimeIntervalFromDynamicData, AbsTimeInterval, AbsTimeInterval >, stir::RegisteredParsingObject< AbsTimeIntervalFromECAT7ACF, AbsTimeInterval, AbsTimeInterval >, stir::RegisteredParsingObject< AbsTimeIntervalWithParsing, AbsTimeInterval, AbsTimeInterval >, stir::RegisteredParsingObject< BackProjectorByBinNiftyPET, BackProjectorByBin >, stir::RegisteredParsingObject< BackProjectorByBinParallelproj, BackProjectorByBin >, stir::RegisteredParsingObject< BackProjectorByBinUsingInterpolation, BackProjectorByBin >, stir::RegisteredParsingObject< BackProjectorByBinUsingProjMatrixByBin, BackProjectorByBin >, stir::RegisteredParsingObject< BackProjectorByBinUsingSquareProjMatrixByBin, BackProjectorByBin >, stir::RegisteredParsingObject< BinNormalisationFromAttenuationImage, BinNormalisation >, stir::RegisteredParsingObject< BinNormalisationFromECAT7, BinNormalisation, BinNormalisationWithCalibration >, stir::RegisteredParsingObject< BinNormalisationFromECAT8, BinNormalisation, BinNormalisationWithCalibration >, stir::RegisteredParsingObject< BinNormalisationFromGEHDF5, BinNormalisation, BinNormalisationWithCalibration >, stir::RegisteredParsingObject< BinNormalisationFromML2D, BinNormalisation >, stir::RegisteredParsingObject< BinNormalisationFromProjData, BinNormalisation >, stir::RegisteredParsingObject< BinNormalisationSinogramRescaling, BinNormalisation >, stir::RegisteredParsingObject< BinNormalisationSPECT, BinNormalisation, BinNormalisationWithCalibration >, stir::RegisteredParsingObject< BinNormalisationUsingProfile, BinNormalisation >, stir::RegisteredParsingObject< Box3D, Shape3D, Shape3DWithOrientation >, stir::RegisteredParsingObject< ChainedBinNormalisation, BinNormalisation >, stir::RegisteredParsingObject< ChainedDataProcessor< DataT >, DataProcessor< DataT >, DataProcessor< DataT > >, stir::RegisteredParsingObject< ChainedDataProcessor< DataT >, DataProcessor< DataT >, DataProcessor< DataT > >, stir::RegisteredParsingObject< CombinedShape3D, Shape3D, Shape3D >, stir::RegisteredParsingObject< CudaRelativeDifferencePrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, RelativeDifferencePrior< elemT > >, stir::RegisteredParsingObject< CudaRelativeDifferencePrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, RelativeDifferencePrior< elemT > >, stir::RegisteredParsingObject< DAVImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< DDSR2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< DDSR2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< DiscretisedShape3D, Shape3D, Shape3D >, stir::RegisteredParsingObject< ECAT6OutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< ECAT6OutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< ECAT7DynamicDiscretisedDensityOutputFileFormat, OutputFileFormat< DynamicDiscretisedDensity >, OutputFileFormat< DynamicDiscretisedDensity > >, stir::RegisteredParsingObject< ECAT7DynamicDiscretisedDensityOutputFileFormat, OutputFileFormat< DynamicDiscretisedDensity >, OutputFileFormat< DynamicDiscretisedDensity > >, stir::RegisteredParsingObject< ECAT7OutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< ECAT7OutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< ECAT7ParametricDensityOutputFileFormat< DiscretisedDensityT >, OutputFileFormat< ParametricDiscretisedDensity< DiscretisedDensityT > >, OutputFileFormat< ParametricDiscretisedDensity< DiscretisedDensityT > > >, stir::RegisteredParsingObject< ECAT7ParametricDensityOutputFileFormat< DiscretisedDensityT >, OutputFileFormat< ParametricDiscretisedDensity< DiscretisedDensityT > >, OutputFileFormat< ParametricDiscretisedDensity< DiscretisedDensityT > > >, stir::RegisteredParsingObject< Ellipsoid, Shape3D, Shape3DWithOrientation >, stir::RegisteredParsingObject< EllipsoidalCylinder, Shape3D, Shape3DWithOrientation >, stir::RegisteredParsingObject< FBP2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< FBP2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< FBP3DRPReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< FBP3DRPReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< FilterRootPrior< DataT >, GeneralisedPrior< DataT >, GeneralisedPrior< DataT > >, stir::RegisteredParsingObject< FilterRootPrior< DataT >, GeneralisedPrior< DataT >, GeneralisedPrior< DataT > >, stir::RegisteredParsingObject< ForwardProjectorByBinNiftyPET, ForwardProjectorByBin >, stir::RegisteredParsingObject< ForwardProjectorByBinParallelproj, ForwardProjectorByBin >, stir::RegisteredParsingObject< ForwardProjectorByBinUsingProjMatrixByBin, ForwardProjectorByBin >, stir::RegisteredParsingObject< ForwardProjectorByBinUsingRayTracing, ForwardProjectorByBin >, stir::RegisteredParsingObject< FourierRebinning, ProjDataRebinning, ProjDataRebinning >, stir::RegisteredParsingObject< GammaImageFilter2D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< GammaImageFilter2D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< GatedSpatialTransformation, SpatialTransformation >, stir::RegisteredParsingObject< GatedSpatialTransformation, SpatialTransformation >, stir::RegisteredParsingObject< GibbsQuadraticPenalty< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GibbsPenalty< elemT, QuadraticPotential< elemT > > >, stir::RegisteredParsingObject< GibbsQuadraticPenalty< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GibbsPenalty< elemT, QuadraticPotential< elemT > > >, stir::RegisteredParsingObject< GibbsRelativeDifferencePenalty< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GibbsPenalty< elemT, RelativeDifferencePotential< elemT > > >, stir::RegisteredParsingObject< GibbsRelativeDifferencePenalty< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GibbsPenalty< elemT, RelativeDifferencePotential< elemT > > >, stir::RegisteredParsingObject< GRD2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< GRD2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< HUToMuImageProcessor< TargetT >, DataProcessor< TargetT >, DataProcessor< TargetT > >, stir::RegisteredParsingObject< HUToMuImageProcessor< TargetT >, DataProcessor< TargetT >, DataProcessor< TargetT > >, stir::RegisteredParsingObject< InputStreamFromROOTFileForCylindricalPET, InputStreamFromROOTFile, InputStreamFromROOTFile >, stir::RegisteredParsingObject< InputStreamFromROOTFileForCylindricalPET, InputStreamFromROOTFile, InputStreamFromROOTFile >, stir::RegisteredParsingObject< InputStreamFromROOTFileForECATPET, InputStreamFromROOTFile, InputStreamFromROOTFile >, stir::RegisteredParsingObject< InputStreamFromROOTFileForECATPET, InputStreamFromROOTFile, InputStreamFromROOTFile >, stir::RegisteredParsingObject< InputStreamWithRecordsFromUPENNbin, InputStreamWithRecordsFromUPENN, InputStreamWithRecordsFromUPENN >, stir::RegisteredParsingObject< InputStreamWithRecordsFromUPENNbin, InputStreamWithRecordsFromUPENN, InputStreamWithRecordsFromUPENN >, stir::RegisteredParsingObject< InputStreamWithRecordsFromUPENNtxt, InputStreamWithRecordsFromUPENN, InputStreamWithRecordsFromUPENN >, stir::RegisteredParsingObject< InputStreamWithRecordsFromUPENNtxt, InputStreamWithRecordsFromUPENN, InputStreamWithRecordsFromUPENN >, stir::RegisteredParsingObject< InterfileDynamicDiscretisedDensityOutputFileFormat, OutputFileFormat< DynamicDiscretisedDensity >, OutputFileFormat< DynamicDiscretisedDensity > >, stir::RegisteredParsingObject< InterfileDynamicDiscretisedDensityOutputFileFormat, OutputFileFormat< DynamicDiscretisedDensity >, OutputFileFormat< DynamicDiscretisedDensity > >, stir::RegisteredParsingObject< InterfileOutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< InterfileOutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< InterfileParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > > >, stir::RegisteredParsingObject< InterfileParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > > >, stir::RegisteredParsingObject< ITKOutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< ITKOutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< KOSMAPOSLReconstruction< TargetT >, Reconstruction< TargetT >, OSMAPOSLReconstruction< TargetT > >, stir::RegisteredParsingObject< KOSMAPOSLReconstruction< TargetT >, Reconstruction< TargetT >, OSMAPOSLReconstruction< TargetT > >, stir::RegisteredParsingObject< LogcoshPrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, PriorWithParabolicSurrogate< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< LogcoshPrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, PriorWithParabolicSurrogate< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< MaximalImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< MaximalImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< MedianImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< MedianImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< MinimalImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< MinimalImageFilter3D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< ModifiedInverseAveragingImageFilterAll< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< ModifiedInverseAveragingImageFilterAll< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< ModifiedInverseAverigingImageFilter< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< ModifiedInverseAverigingImageFilter< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< MultiDynamicDiscretisedDensityOutputFileFormat, OutputFileFormat< DynamicDiscretisedDensity >, OutputFileFormat< DynamicDiscretisedDensity > >, stir::RegisteredParsingObject< MultiDynamicDiscretisedDensityOutputFileFormat, OutputFileFormat< DynamicDiscretisedDensity >, OutputFileFormat< DynamicDiscretisedDensity > >, stir::RegisteredParsingObject< MultiParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > > >, stir::RegisteredParsingObject< MultiParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > >, OutputFileFormat< ParametricDiscretisedDensity< DiscDensityT > > >, stir::RegisteredParsingObject< multiply_plane_scale_factorsImageProcessor< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< multiply_plane_scale_factorsImageProcessor< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< NonRigidObjectTransformationUsingBSplines< num_dimensions, elemT >, ObjectTransformation< num_dimensions, elemT >, ObjectTransformation< num_dimensions, elemT > >, stir::RegisteredParsingObject< NonseparableConvolutionUsingRealDFTImageFilter< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< NonseparableConvolutionUsingRealDFTImageFilter< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< NonseparableSpatiallyVaryingFilters3D< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< NonseparableSpatiallyVaryingFilters3D< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< NonseparableSpatiallyVaryingFilters< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< NonseparableSpatiallyVaryingFilters< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< OSMAPOSLReconstruction< TargetT >, Reconstruction< TargetT >, IterativeReconstruction< TargetT > >, stir::RegisteredParsingObject< OSMAPOSLReconstruction< TargetT >, Reconstruction< TargetT >, IterativeReconstruction< TargetT > >, stir::RegisteredParsingObject< OSSPSReconstruction< TargetT >, Reconstruction< TargetT >, IterativeReconstruction< TargetT > >, stir::RegisteredParsingObject< OSSPSReconstruction< TargetT >, Reconstruction< TargetT >, IterativeReconstruction< TargetT > >, stir::RegisteredParsingObject< ParametricQuadraticPrior< TargetT >, GeneralisedPrior< TargetT >, PriorWithParabolicSurrogate< TargetT > >, stir::RegisteredParsingObject< ParametricQuadraticPrior< TargetT >, GeneralisedPrior< TargetT >, PriorWithParabolicSurrogate< TargetT > >, stir::RegisteredParsingObject< PatlakPlot, KineticModel >, stir::RegisteredParsingObject< PatlakPlot, KineticModel >, stir::RegisteredParsingObject< PLSPrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GeneralisedPrior< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< PLSPrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GeneralisedPrior< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, GeneralisedObjectiveFunction< TargetT >, SumOfGeneralisedObjectiveFunctions< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, TargetT, PoissonLogLikelihoodWithLinearModelForMean< TargetT > > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, GeneralisedObjectiveFunction< TargetT >, SumOfGeneralisedObjectiveFunctions< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, TargetT, PoissonLogLikelihoodWithLinearModelForMean< TargetT > > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, GeneralisedObjectiveFunction< stir::DiscretisedDensity< 3, float > >, PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >, GeneralisedObjectiveFunction< stir::DiscretisedDensity< 3, float > >, PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, GeneralisedObjectiveFunction< TargetT >, PoissonLogLikelihoodWithLinearModelForMean< TargetT > >, stir::RegisteredParsingObject< PostsmoothingBackProjectorByBin, BackProjectorByBin >, stir::RegisteredParsingObject< PostsmoothingForwardProjectorByBin, ForwardProjectorByBin >, stir::RegisteredParsingObject< PresmoothingForwardProjectorByBin, ForwardProjectorByBin >, stir::RegisteredParsingObject< ProjectorByBinPairUsingNiftyPET, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingNiftyPET, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingParallelproj, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingParallelproj, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingProjMatrixByBin, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingProjMatrixByBin, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingSeparateProjectors, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjectorByBinPairUsingSeparateProjectors, ProjectorByBinPair, ProjectorByBinPair >, stir::RegisteredParsingObject< ProjMatrixByBinFromFile, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinPinholeSPECTUB, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinSinglePhoton, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinSPECTUB, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinUsingInterpolation, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinUsingRayTracing, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinUsingSolidAngle, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByBinWithPositronRange, ProjMatrixByBin, ProjMatrixByBin >, stir::RegisteredParsingObject< ProjMatrixByDenselUsingRayTracing, ProjMatrixByDenselOnCartesianGridUsingElement >, stir::RegisteredParsingObject< QuadraticPrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, PriorWithParabolicSurrogate< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< QuadraticPrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, PriorWithParabolicSurrogate< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< QuadraticPrior< float >, GeneralisedPrior< DiscretisedDensity< 3, float > >, PriorWithParabolicSurrogate< DiscretisedDensity< 3, float > > >, stir::RegisteredParsingObject< RelativeDifferencePrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GeneralisedPrior< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< RelativeDifferencePrior< elemT >, GeneralisedPrior< DiscretisedDensity< 3, elemT > >, GeneralisedPrior< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< RigidObject3DMotionFromPolaris, RigidObject3DMotion, RigidObject3DMotion >, stir::RegisteredParsingObject< RigidObject3DTransformation, ObjectTransformation< 3, float >, ObjectTransformation< 3, float > >, stir::RegisteredParsingObject< SeparableCartesianMetzImageFilter< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< SeparableCartesianMetzImageFilter< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< SeparableConvolutionImageFilter< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< SeparableConvolutionImageFilter< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< SeparableGaussianImageFilter< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< SeparableGaussianImageFilter< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< SeparableLowPassImageFilter< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< SeparableLowPassImageFilter< elemT >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > >, DataProcessor< DiscretisedDensity< num_dimensions, elemT > > >, stir::RegisteredParsingObject< SingleScatterSimulation, ScatterSimulation, ScatterSimulation >, stir::RegisteredParsingObject< SingleScatterSimulation, ScatterSimulation, ScatterSimulation >, stir::RegisteredParsingObject< SinglesRatesFromECAT7, SinglesRates, SinglesRatesForTimeFrames >, stir::RegisteredParsingObject< SinglesRatesFromGEHDF5, SinglesRates, SinglesRatesForTimeSlices >, stir::RegisteredParsingObject< SinglesRatesFromSglFile, SinglesRates, SinglesRatesForTimeSlices >, stir::RegisteredParsingObject< SRT2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< SRT2DReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< SRT2DSPECTReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< SRT2DSPECTReconstruction, Reconstruction< DiscretisedDensity< 3, float > >, AnalyticReconstruction >, stir::RegisteredParsingObject< ThresholdMinToSmallPositiveValueDataProcessor< DataT >, DataProcessor< DataT >, DataProcessor< DataT > >, stir::RegisteredParsingObject< ThresholdMinToSmallPositiveValueDataProcessor< DataT >, DataProcessor< DataT >, DataProcessor< DataT > >, stir::RegisteredParsingObject< Transform3DObjectImageProcessor< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< TrivialBinNormalisation, BinNormalisation >, stir::RegisteredParsingObject< TruncateToCylindricalFOVImageProcessor< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< TruncateToCylindricalFOVImageProcessor< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, stir::RegisteredParsingObject< WienerImageFilter2D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >, and stir::RegisteredParsingObject< WienerImageFilter2D< elemT >, DataProcessor< DiscretisedDensity< 3, elemT > >, DataProcessor< DiscretisedDensity< 3, elemT > > >.
set_defaults()
void stir::ParsingObject::set_defaults () protected virtual
Set defaults before parsing.
Reimplemented in stir::AnalyticReconstruction, stir::BackProjectorByBin, stir::BackProjectorByBinParallelproj, stir::BinNormalisation, stir::BinNormalisationPETFromComponents, stir::BinNormalisationWithCalibration, stir::CreateTailMaskFromACFs, stir::CudaRelativeDifferencePrior< elemT >, stir::ecat::ecat6::ECAT6OutputFileFormat, stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityOutputFileFormat, stir::ecat::ecat7::ECAT7OutputFileFormat, stir::ecat::ecat7::ECAT7ParametricDensityOutputFileFormat< DiscretisedDensityT >, stir::Ellipsoid, stir::EllipsoidalCylinder, stir::FindMCNormFactors, stir::ForwardProjectorByBin, stir::ForwardProjectorByBinParallelproj, stir::FourierRebinning, stir::GatedSpatialTransformation, stir::GeneralisedObjectiveFunction< TargetT >, stir::GeneralisedObjectiveFunction< stir::DiscretisedDensity< 3, float > >, stir::GeneralisedPrior< DataT >, stir::GeneralisedPrior< DiscretisedDensity< 3, elemT > >, stir::GeneralisedPrior< DiscretisedDensity< 3, elemT > >, stir::GeneralisedPrior< DiscretisedDensity< 3, float > >, stir::GeneralisedPrior< stir::DiscretisedDensity< 3, float > >, stir::GeneralisedPrior< TargetT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::HUToMuImageProcessor< TargetT >, stir::InputStreamFromROOTFile, stir::InputStreamFromROOTFileForCylindricalPET, stir::InputStreamFromROOTFileForECATPET, stir::InputStreamWithRecordsFromUPENN, stir::InputStreamWithRecordsFromUPENNbin, stir::InputStreamWithRecordsFromUPENNtxt, stir::InterfileDynamicDiscretisedDensityOutputFileFormat, stir::InterfileOutputFileFormat, stir::InterfileParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, stir::IterativeReconstruction< TargetT >, stir::ITKOutputFileFormat, stir::KOSMAPOSLReconstruction< TargetT >, stir::LmToProjData, stir::LmToProjDataWithMC, stir::LogcoshPrior< elemT >, stir::MatchTrackerAndScanner, stir::MoveImage, stir::MoveProjData, stir::MultiDynamicDiscretisedDensityOutputFileFormat, stir::MultiParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, stir::MyApp, stir::NonRigidObjectTransformationUsingBSplines< num_dimensions, elemT >, stir::OSMAPOSLReconstruction< TargetT >, stir::OSSPSReconstruction< TargetT >, stir::OutputFileFormat< DataT >, stir::OutputFileFormat< A >, stir::OutputFileFormat< DiscretisedDensity< 3, float > >, stir::OutputFileFormat< DiscretisedDensityType >, stir::OutputFileFormat< DynamicDiscretisedDensity >, stir::OutputFileFormat< ParametricVoxelsOnCartesianGrid >, stir::OutputFileFormat< stir::DiscretisedDensity< 3, float > >, stir::OutputFileFormat< TargetT >, stir::ParametricQuadraticPrior< TargetT >, stir::PatlakPlot, stir::PLSPrior< elemT >, stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >, stir::ProjDataRebinning, stir::ProjMatrixByBin, stir::QuadraticPrior< elemT >, stir::QuadraticPrior< float >, stir::Reconstruction< TargetT >, stir::Reconstruction< DiscretisedDensity< 3, float > >, stir::Reconstruction< stir::DiscretisedDensity< 3, float > >, stir::RelativeDifferencePrior< elemT >, stir::ReportMovement, stir::RigidObject3DMotion, stir::RigidObject3DMotionFromPolaris, stir::SAFIRCListmodeInputFileFormat< EventDataType >, stir::ScatterEstimation, stir::ScatterSimulation, stir::SeparableGaussianImageFilter< elemT >, stir::Shape3D, stir::Shape3DWithOrientation, stir::SingleScatterSimulation, stir::SqrtHessianRowSum< TargetT >, and stir::TimeFrameMotion.
References set_defaults().
Referenced by stir::ecat::ecat6::ECAT6OutputFileFormat::set_defaults(), stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityOutputFileFormat::set_defaults(), stir::ecat::ecat7::ECAT7OutputFileFormat::set_defaults(), stir::GatedSpatialTransformation::set_defaults(), stir::HUToMuImageProcessor< TargetT >::set_defaults(), stir::InterfileDynamicDiscretisedDensityOutputFileFormat::set_defaults(), stir::InterfileOutputFileFormat::set_defaults(), stir::ITKOutputFileFormat::set_defaults(), stir::LogcoshPrior< elemT >::set_defaults(), stir::MultiDynamicDiscretisedDensityOutputFileFormat::set_defaults(), stir::OSMAPOSLReconstruction< TargetT >::set_defaults(), stir::OSSPSReconstruction< TargetT >::set_defaults(), stir::ParametricQuadraticPrior< TargetT >::set_defaults(), set_defaults(), stir::PatlakPlot::set_defaults(), stir::PLSPrior< elemT >::set_defaults(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >::set_defaults(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >::set_defaults(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >::set_defaults(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::set_defaults(), stir::RelativeDifferencePrior< elemT >::set_defaults(), stir::SAFIRCListmodeInputFileFormat< EventDataType >::set_defaults(), stir::SeparableGaussianImageFilter< elemT >::set_defaults(), stir::SingleScatterSimulation::set_defaults(), and stir::QuadraticPrior< float >::set_weights().
initialise_keymap()
void stir::ParsingObject::initialise_keymap () protected virtual
Initialise all keywords.
Reimplemented in stir::AnalyticReconstruction, stir::BackProjectorByBin, stir::BackProjectorByBinNiftyPET, stir::BackProjectorByBinParallelproj, stir::BinNormalisationWithCalibration, stir::CreateTailMaskFromACFs, stir::ecat::ecat6::ECAT6OutputFileFormat, stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityOutputFileFormat, stir::ecat::ecat7::ECAT7OutputFileFormat, stir::ecat::ecat7::ECAT7ParametricDensityOutputFileFormat< DiscretisedDensityT >, stir::Ellipsoid, stir::EllipsoidalCylinder, stir::FindMCNormFactors, stir::ForwardProjectorByBin, stir::ForwardProjectorByBinNiftyPET, stir::ForwardProjectorByBinParallelproj, stir::FourierRebinning, stir::GeneralisedObjectiveFunction< TargetT >, stir::GeneralisedObjectiveFunction< stir::DiscretisedDensity< 3, float > >, stir::GeneralisedPrior< DataT >, stir::GeneralisedPrior< DiscretisedDensity< 3, elemT > >, stir::GeneralisedPrior< DiscretisedDensity< 3, elemT > >, stir::GeneralisedPrior< DiscretisedDensity< 3, float > >, stir::GeneralisedPrior< stir::DiscretisedDensity< 3, float > >, stir::GeneralisedPrior< TargetT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::HUToMuImageProcessor< TargetT >, stir::InputStreamFromROOTFile, stir::InputStreamFromROOTFileForCylindricalPET, stir::InputStreamFromROOTFileForECATPET, stir::InputStreamWithRecordsFromUPENN, stir::InputStreamWithRecordsFromUPENNbin, stir::InputStreamWithRecordsFromUPENNtxt, stir::InterfileDynamicDiscretisedDensityOutputFileFormat, stir::InterfileOutputFileFormat, stir::InterfileParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, stir::IterativeReconstruction< TargetT >, stir::ITKOutputFileFormat, stir::KOSMAPOSLReconstruction< TargetT >, stir::LmToProjData, stir::LmToProjDataWithMC, stir::LogcoshPrior< elemT >, stir::MatchTrackerAndScanner, stir::MoveImage, stir::MoveProjData, stir::MultiDynamicDiscretisedDensityOutputFileFormat, stir::MultiParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, stir::MyApp, stir::NonRigidObjectTransformationUsingBSplines< num_dimensions, elemT >, stir::OSMAPOSLReconstruction< TargetT >, stir::OSSPSReconstruction< TargetT >, stir::OutputFileFormat< DataT >, stir::OutputFileFormat< A >, stir::OutputFileFormat< DiscretisedDensity< 3, float > >, stir::OutputFileFormat< DiscretisedDensityType >, stir::OutputFileFormat< DynamicDiscretisedDensity >, stir::OutputFileFormat< ParametricVoxelsOnCartesianGrid >, stir::OutputFileFormat< stir::DiscretisedDensity< 3, float > >, stir::OutputFileFormat< TargetT >, stir::ParametricQuadraticPrior< TargetT >, stir::PLSPrior< elemT >, stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >, stir::ProjDataRebinning, stir::ProjMatrixByBin, stir::QuadraticPrior< elemT >, stir::QuadraticPrior< float >, stir::Reconstruction< TargetT >, stir::Reconstruction< DiscretisedDensity< 3, float > >, stir::Reconstruction< stir::DiscretisedDensity< 3, float > >, stir::RelativeDifferencePrior< elemT >, stir::ReportMovement, stir::RigidObject3DMotion, stir::RigidObject3DMotionFromPolaris, stir::SAFIRCListmodeInputFileFormat< EventDataType >, stir::ScatterEstimation, stir::ScatterSimulation, stir::SeparableGaussianImageFilter< elemT >, stir::Shape3D, stir::Shape3DWithOrientation, stir::SingleScatterSimulation, and stir::TimeFrameMotion.
References initialise_keymap().
Referenced by stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >::construct_target_ptr(), stir::BinNormalisationWithCalibration::initialise_keymap(), stir::ecat::ecat6::ECAT6OutputFileFormat::initialise_keymap(), stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityOutputFileFormat::initialise_keymap(), stir::ecat::ecat7::ECAT7OutputFileFormat::initialise_keymap(), stir::HUToMuImageProcessor< TargetT >::initialise_keymap(), stir::InterfileDynamicDiscretisedDensityOutputFileFormat::initialise_keymap(), stir::InterfileOutputFileFormat::initialise_keymap(), stir::ITKOutputFileFormat::initialise_keymap(), stir::LogcoshPrior< elemT >::initialise_keymap(), stir::MultiDynamicDiscretisedDensityOutputFileFormat::initialise_keymap(), stir::OSMAPOSLReconstruction< TargetT >::initialise_keymap(), stir::OSSPSReconstruction< TargetT >::initialise_keymap(), stir::ParametricQuadraticPrior< TargetT >::initialise_keymap(), initialise_keymap(), stir::PLSPrior< elemT >::initialise_keymap(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >::initialise_keymap(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >::initialise_keymap(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::initialise_keymap(), stir::QuadraticPrior< elemT >::initialise_keymap(), stir::RelativeDifferencePrior< elemT >::initialise_keymap(), stir::SAFIRCListmodeInputFileFormat< EventDataType >::initialise_keymap(), stir::SeparableGaussianImageFilter< elemT >::initialise_keymap(), and stir::SingleScatterSimulation::initialise_keymap().
post_processing()
bool stir::ParsingObject::post_processing () protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented in stir::AnalyticReconstruction, stir::BinNormalisationWithCalibration, stir::CreateTailMaskFromACFs, stir::ecat::ecat6::ECAT6OutputFileFormat, stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityOutputFileFormat, stir::ecat::ecat7::ECAT7OutputFileFormat, stir::ecat::ecat7::ECAT7ParametricDensityOutputFileFormat< DiscretisedDensityT >, stir::Ellipsoid, stir::EllipsoidalCylinder, stir::FindMCNormFactors, stir::FourierRebinning, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::HUToMuImageProcessor< TargetT >, stir::InputStreamFromROOTFile, stir::InputStreamFromROOTFileForCylindricalPET, stir::InputStreamFromROOTFileForECATPET, stir::InputStreamWithRecordsFromUPENN, stir::InputStreamWithRecordsFromUPENNbin, stir::InputStreamWithRecordsFromUPENNtxt, stir::InterfileDynamicDiscretisedDensityOutputFileFormat, stir::InterfileOutputFileFormat, stir::InterfileParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, stir::IterativeReconstruction< TargetT >, stir::ITKOutputFileFormat, stir::KOSMAPOSLReconstruction< TargetT >, stir::LmToProjData, stir::LmToProjDataWithMC, stir::LogcoshPrior< elemT >, stir::MatchTrackerAndScanner, stir::MoveImage, stir::MoveProjData, stir::MultiDynamicDiscretisedDensityOutputFileFormat, stir::MultiParametricDiscretisedDensityOutputFileFormat< DiscDensityT >, stir::MyApp, stir::NonRigidObjectTransformationUsingBSplines< num_dimensions, elemT >, stir::OSMAPOSLReconstruction< TargetT >, stir::OSSPSReconstruction< TargetT >, stir::OutputFileFormat< DataT >, stir::OutputFileFormat< A >, stir::OutputFileFormat< DiscretisedDensity< 3, float > >, stir::OutputFileFormat< DiscretisedDensityType >, stir::OutputFileFormat< DynamicDiscretisedDensity >, stir::OutputFileFormat< ParametricVoxelsOnCartesianGrid >, stir::OutputFileFormat< stir::DiscretisedDensity< 3, float > >, stir::OutputFileFormat< TargetT >, stir::ParametricQuadraticPrior< TargetT >, stir::PLSPrior< elemT >, stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >, stir::ProjDataRebinning, stir::ProjMatrixByBin, stir::QuadraticPrior< elemT >, stir::QuadraticPrior< float >, stir::Reconstruction< TargetT >, stir::Reconstruction< DiscretisedDensity< 3, float > >, stir::Reconstruction< stir::DiscretisedDensity< 3, float > >, stir::RelativeDifferencePrior< elemT >, stir::ReportMovement, stir::RigidObject3DMotion, stir::RigidObject3DMotionFromPolaris, stir::SAFIRCListmodeInputFileFormat< EventDataType >, stir::ScatterEstimation, stir::ScatterSimulation, stir::Shape3DWithOrientation, stir::SingleScatterSimulation, and stir::TimeFrameMotion.
References post_processing().
Referenced by stir::BinNormalisationWithCalibration::post_processing(), stir::ecat::ecat6::ECAT6OutputFileFormat::post_processing(), stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityOutputFileFormat::post_processing(), stir::ecat::ecat7::ECAT7OutputFileFormat::post_processing(), stir::GibbsPenalty< elemT, potentialT >::post_processing(), stir::HUToMuImageProcessor< TargetT >::post_processing(), stir::InterfileDynamicDiscretisedDensityOutputFileFormat::post_processing(), stir::InterfileOutputFileFormat::post_processing(), stir::ITKOutputFileFormat::post_processing(), stir::LogcoshPrior< elemT >::post_processing(), stir::MultiDynamicDiscretisedDensityOutputFileFormat::post_processing(), stir::MyApp::post_processing(), stir::OSMAPOSLReconstruction< TargetT >::post_processing(), stir::OSSPSReconstruction< TargetT >::post_processing(), stir::ParametricQuadraticPrior< TargetT >::post_processing(), post_processing(), stir::PLSPrior< elemT >::post_processing(), stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::post_processing(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >::post_processing(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >::post_processing(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >::post_processing(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::post_processing(), stir::QuadraticPrior< elemT >::post_processing(), stir::RelativeDifferencePrior< elemT >::post_processing(), stir::Shape3DWithOrientation::post_processing(), and stir::SingleScatterSimulation::post_processing().
set_key_values()
void stir::ParsingObject::set_key_values () protected virtual
This will be called before parsing or parameter_info is called.
This virtual function should be overloaded when the values for the keywords depend on other variables in the derived class that can be set independently of the parsing.
Example:
A derived class has a public member angle_in_radians, while a keyword sets a private member angle_in_degrees.
Reimplemented in stir::NonRigidObjectTransformationUsingBSplines< num_dimensions, elemT >, stir::OutputFileFormat< DataT >, stir::OutputFileFormat< A >, stir::OutputFileFormat< DiscretisedDensity< 3, float > >, stir::OutputFileFormat< DiscretisedDensityType >, stir::OutputFileFormat< DynamicDiscretisedDensity >, stir::OutputFileFormat< ParametricVoxelsOnCartesianGrid >, stir::OutputFileFormat< stir::DiscretisedDensity< 3, float > >, stir::OutputFileFormat< TargetT >, and stir::Shape3DWithOrientation.
References set_key_values().
Referenced by set_key_values(), and stir::Shape3DWithOrientation::set_key_values().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/ParsingObject.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/ParsingObject.cxx