STIR: stir::PlasmaSample Class Reference
stir::PlasmaSample Class Reference
STIR » STIR library » Kinetic modelling building blocks
#include "stir/modelling/PlasmaSample.h"
Public Member Functions
PlasmaSample ()
default constructor
PlasmaSample (const double sample_time, const float plasma_sample_counts, const float blood_sample_counts)
constructor, time in s
~PlasmaSample ()
default destructor
Functions to get parameters
double get_time_in_s () const
get the time of the sample
float get_blood_counts_in_kBq () const
get the blood counts of the sample
float get_plasma_counts_in_kBq () const
get the plasma counts of the sample
Functions to set parameters
void set_time_in_s (const double time)
set the time of the sample
void set_blood_counts_in_kBq (const float blood_counts)
set the blood counts of the sample
void set_plasma_counts_in_kBq (const float plasma_counts)
set the plasma counts of the sample
Detailed Description
A class for storing radiotracer concentration in a blood sample. Concentrations in plasma and the (overall) blood-concentration are stored.
Todo
This currently assumes sampling, while in practice we often have data accumulated over time, but this can currently not be encoded.
Constructor & Destructor Documentation
PlasmaSample()
stir::PlasmaSample::PlasmaSample (const double sample_time, const float plasma_sample_counts, const float blood_sample_counts) inline
constructor, time in s
A constructor : constructs a PlasmaSample object
Parameters
sample_time is the time in seconds relativily to the start of the scan.
plasma_sample_counts is the activity of plasma at the sample_time (assumed to be in kBq/ml)
blood_sample_counts is the activity of blood at the sample_time (assumed to be in kBq/ml)
References PlasmaSample(), set_blood_counts_in_kBq(), set_plasma_counts_in_kBq(), and set_time_in_s().
Member Function Documentation
set_plasma_counts_in_kBq()
void stir::PlasmaSample::set_plasma_counts_in_kBq (const float plasma_counts) inline
set the plasma counts of the sample
get the plasma counts of the sample
References set_plasma_counts_in_kBq().
Referenced by PlasmaSample(), and set_plasma_counts_in_kBq().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/modelling/PlasmaSample.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/modelling/PlasmaSample.inl