STIR: stir::CListEventCylindricalScannerWithDiscreteDetectors Class Reference
stir::CListEventCylindricalScannerWithDiscreteDetectors Class Reference abstract
STIR » STIR library » Support classes for reading list mode data
Class for storing and using a coincidence event from a list mode file for a cylindrical single layer scanner.
#include "stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.h"
Public Member Functions
CListEventCylindricalScannerWithDiscreteDetectors (const shared_ptr< Scanner > &scanner_sptr)
const Scanner * get_scanner_ptr () const
virtual void get_detection_position (DetectionPositionPair<> &) const =0
This routine returns the corresponding detector pair.
virtual void set_detection_position (const DetectionPositionPair<> &)=0
This routine sets in a coincidence event from detector "indices".
virtual LORAs2Points< float > get_LOR () const
find LOR between detector pairs
virtual void get_bin (Bin &bin, const ProjDataInfo &proj_data_info) const
find bin for this event
virtual bool is_valid_template (const ProjDataInfo &) const
This method checks if the template is valid for LmToProjData.
Public Member Functions inherited from stir::CListEvent
virtual Succeeded set_prompt (const bool prompt=true)
Changes the event from prompt to delayed or vice versa.
Public Member Functions inherited from stir::ListEvent
virtual bool is_prompt () const =0
Protected Member Functions
shared_ptr< const ProjDataInfoCylindricalNoArcCorr > get_uncompressed_proj_data_info_sptr () const
Protected Attributes
shared_ptr< Scanner > scanner_sptr
Detailed Description
Class for storing and using a coincidence event from a list mode file for a cylindrical single layer scanner.
For scanners with discrete detectors, the list mode events usually store detector indices in some way. This class provides access mechanisms to those detection positions, and also provides more efficient implementations of some virtual members of CListEvent.
Member Function Documentation
get_LOR()
LORAs2Points< float > stir::CListEventCylindricalScannerWithDiscreteDetectors::get_LOR () const inline virtual
find LOR between detector pairs
Overrides the default implementation to use get_detection_position() which should be faster.
Implements stir::ListEvent.
References get_bin(), and get_detection_position().
get_bin()
void stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin (Bin & bin, const ProjDataInfo & proj_data_info) const inline virtual
find bin for this event
Overrides the default implementation to use get_detection_position() which should be faster.
Warning
This implementation is only valid for proj_data_info of type ProjDataInfoCylindricalNoArcCorr. However, because of efficiency reasons this is only checked in debug mode (NDEBUG not defined).
Reimplemented from stir::ListEvent.
Reimplemented in stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< Derived >, stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< CListRecordECAT962 >, and stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< CListEventECAT966 >.
References get_detection_position().
Referenced by get_LOR().
is_valid_template()
bool stir::CListEventCylindricalScannerWithDiscreteDetectors::is_valid_template (const ProjDataInfo & proj_data_info) const inline virtual
This method checks if the template is valid for LmToProjData.
Used before the actual processing of the data (see issue #61), before calling get_bin() Most scanners have listmode data that correspond to non arc-corrected data and this check avoids a crash when an unsupported template is used as input.
Implements stir::ListEvent.
Reimplemented in stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< Derived >, stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< CListRecordECAT962 >, and stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< CListEventECAT966 >.
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.h
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.inl