STIR: stir::CListEventPENN Class Reference
stir::CListEventPENN Class Reference
STIR » STIR library » Support classes for reading list mode data
Class for handling PENNPet Explorer events.
#include "stir/listmode/CListRecordPENN.h"
Public Member Functions
CListEventPENN (const shared_ptr< Scanner > &scanner_sptr)
virtual void get_detection_position (DetectionPositionPair<> &) const
This routine returns the corresponding detector pair.
virtual void set_detection_position (const DetectionPositionPair<> &)
This routine sets in a coincidence event from detector "indices".
void init_from_data (bool d, int dt, int xa, int xb, int za, int zb, int ea, int eb)
bool is_prompt () const
Succeeded set_prompt (const bool _prompt=true)
Changes the event from prompt to delayed or vice versa.
Public Member Functions inherited from stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >
CListEventScannerWithDiscreteDetectors (const shared_ptr< const ProjDataInfo > &proj_data_info)
const Scanner * get_scanner_ptr () const
LORAs2Points< float > get_LOR () const override
find LOR between detector pairs
void get_bin (Bin &bin, const ProjDataInfo &proj_data_info) const override
find bin for this event
bool is_valid_template (const ProjDataInfo &) const override
This method checks if the template is valid for LmToProjData.
CListEventScannerWithDiscreteDetectors (const shared_ptr< const ProjDataInfo > &proj_data_info)
const Scanner * get_scanner_ptr () const
LORAs2Points< float > get_LOR () const override
find LOR between detector pairs
void get_bin (Bin &bin, const ProjDataInfo &proj_data_info) const override
find bin for this event
bool is_valid_template (const ProjDataInfo &) const override
This method checks if the template is valid for LmToProjData.
Additional Inherited Members
Protected Member Functions inherited from stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >
shared_ptr< const ProjDataInfoCylindricalNoArcCorr > get_uncompressed_proj_data_info_sptr () const
shared_ptr< const ProjDataInfoCylindricalNoArcCorr > get_uncompressed_proj_data_info_sptr () const
Detailed Description
Class for handling PENNPet Explorer events.
Todo
Fix the rotation
Member Function Documentation
get_detection_position()
void stir::CListEventPENN::get_detection_position (DetectionPositionPair<> & det_pos) const virtual
This routine returns the corresponding detector pair.
Implements stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >.
References get_detection_position().
Referenced by get_detection_position().
set_detection_position()
void stir::CListEventPENN::set_detection_position (const DetectionPositionPair<> &) virtual
This routine sets in a coincidence event from detector "indices".
Implements stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >.
References stir::error(), and set_detection_position().
Referenced by set_detection_position().
is_prompt()
bool stir::CListEventPENN::is_prompt () const inline virtual
Implements stir::ListEvent.
set_prompt()
Succeeded stir::CListEventPENN::set_prompt (const bool prompt = true) inline virtual
Changes the event from prompt to delayed or vice versa.
Default implementation just returns Succeeded::no.
Reimplemented from stir::CListEvent.
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/CListRecordPENN.h
/home/kris/devel/STIRdistrib/STIR/src/listmode_buildblock/CListRecordPENN.cxx