STIR: stir::ecat::CListModeDataECAT8_32bit Class Reference
stir::ecat::CListModeDataECAT8_32bit Class Reference
STIR » STIR library » Support classes for reading list mode data
A class that reads the listmode data for Siemens scanners.
#include "stir/listmode/CListModeDataECAT8_32bit.h"
Public Member Functions
CListModeDataECAT8_32bit (const std::string &listmode_filename_prefix)
Construct fron the filename of the Interfile header.
virtual std::string get_name () const
Returns the name of the list mode data.
virtual shared_ptr< CListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (CListRecord &record) const
Gets the next record in the listmode sequence.
virtual Succeeded reset ()
Call this function if you want to re-start reading at the beginning.
virtual SavedPosition save_get_position ()
Save the current reading position.
virtual Succeeded set_get_position (const SavedPosition &)
Set the position for reading to a previously saved point.
virtual bool has_delayeds () const
returns true, as ECAT listmode data stores delayed events (and prompts)
Public Member Functions inherited from stir::ListModeData
ListModeData ()
Default constructor.
shared_ptr< ListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (ListRecord &event) const
Gets the next record in the listmode sequence.
virtual const Scanner * get_scanner_ptr () const
Get scanner pointer.
virtual unsigned long int get_total_number_of_events () const
Returns the total number of events in the listmode file.
virtual shared_ptr< ProjDataInfo > get_proj_data_info_sptr () const
const ProjDataInfo * get_proj_data_info_ptr () const
Public Member Functions inherited from stir::ExamData
ExamData ()
ExamData.
ExamData (const shared_ptr< ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual const ExamInfo * get_exam_info_ptr () const
Get pointer to exam info.
virtual shared_ptr< ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
Additional Inherited Members
Public Types inherited from stir::ListModeData
typedef unsigned int SavedPosition
Use this typedef for save/set_get_position.
Protected Member Functions inherited from stir::CListModeData
virtual shared_ptr< ListRecord > get_empty_record_helper_sptr () const
virtual Succeeded get_next (ListRecord &event) const
Protected Member Functions inherited from stir::ListModeData
virtual void set_proj_data_info_sptr (shared_ptr< ProjDataInfo >)
Protected Attributes inherited from stir::ListModeData
shared_ptr< ProjDataInfo > proj_data_info_sptr
Has to be set by the derived class.
Protected Attributes inherited from stir::ExamData
shared_ptr< ExamInfo > exam_info_sptr
Detailed Description
A class that reads the listmode data for Siemens scanners.
This file format is currently used by the Siemens Biograph PET/CT and mMR scanners. There's an Interfile-like header and a binary file with the actual list mode data. The name of the binary file is given by the value of the "name of data file" keyword in the header.
Currently, the class only supports the 32bit version of the list mode format, see http://usa.healthcare.siemens.com/siemens_hwem-hwem_ssxa_websites-context-root/wcm/idc/groups/public/@us/@imaging/@molecular/documents/download/mdax/mjky/~edisp/petlink_guideline_j1-00672485.pdf
Member Function Documentation
get_name()
std::string stir::ecat::CListModeDataECAT8_32bit::get_name () const virtual
Returns the name of the list mode data.
This name is not necessarily unique, and might be empty. However, it is expected (but not guaranteed) that ListModeData::read_from_file(lm_data_ptr->get_name()) would read the same list mode data.
The reason this cannot be guaranteed is largely in case the list mode data is not really on disk, but the object corresponds for instance to a Monte Carlo simulator.
Implements stir::ListModeData.
References get_empty_record_sptr().
Referenced by CListModeDataECAT8_32bit().
get_empty_record_sptr()
shared_ptr< CListRecord > stir::ecat::CListModeDataECAT8_32bit::get_empty_record_sptr () const virtual
Get a pointer to an empty record.
This is mainly/only useful to get a record of the correct type, that can then be passed to get_next_record().
Implements stir::CListModeData.
References stir::get_directory_name(), stir::ByteOrder::get_native_order(), get_next_record(), stir::info(), stir::ByteOrder::little_endian, stir::max_filename_length, stir::prepend_directory_name(), and stir::warning().
Referenced by get_name().
save_get_position()
CListModeData::SavedPosition stir::ecat::CListModeDataECAT8_32bit::save_get_position () virtual
Save the current reading position.
Note that the return value is not related to the number of events already read. In particular, you cannot do any arithmetic on it to skip a few events. This is different from e.g. std::streampos.
Warning
There is a maximum number of times this function can be called. This is determined by the SavedPosition type. Once you save more positions, the first positions will be overwritten. There is currently no way of finding out after how many times this will happen (but it's a large number...).
These saved positions are only valid for the lifetime of the ListModeData object.
A derived class might disable this facility. It will/should then always return Succeeded::no when calling set_get_position().
Implements stir::ListModeData.
References set_get_position().
Referenced by reset().
has_delayeds()
virtual bool stir::ecat::CListModeDataECAT8_32bit::has_delayeds () const inline virtual
returns true, as ECAT listmode data stores delayed events (and prompts)
Todo:
this might depend on the acquisition parameters
Implements stir::CListModeData.
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/listmode/CListModeDataECAT8_32bit.h
/home/sirfuser/devel/STIRdistrib/STIR/src/listmode_buildblock/CListModeDataECAT8_32bit.cxx