STIR: stir::ecat::CListEventECAT8_32bit Class Reference
stir::ecat::CListEventECAT8_32bit Class Reference
Class for storing and using a coincidence event from a listmode file from Siemens scanners using the ECAT 8_32bit format.
#include "stir/listmode/CListRecordECAT8_32bit.h"
Public Types
typedef CListEventDataECAT8_32bit DataType
Public Member Functions
DataType get_data () const
CListEventECAT8_32bit (const shared_ptr< const ProjDataInfo > &proj_data_info_sptr)
void get_detection_position (DetectionPositionPair<> &) const override
This routine returns the corresponding detector pair.
void set_detection_position (const DetectionPositionPair<> &) override
This routine sets in a coincidence event from detector "indices".
Succeeded init_from_data_ptr (const void *const ptr)
bool is_prompt () const override
Succeeded set_prompt (const bool prompt=true) override
Changes the event from prompt to delayed or vice versa.
Public Member Functions inherited from stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >
CListEventScannerWithDiscreteDetectors (const shared_ptr< const ProjDataInfo > &proj_data_info)
const Scanner * get_scanner_ptr () const
LORAs2Points< float > get_LOR () const override
find LOR between detector pairs
void get_bin (Bin &bin, const ProjDataInfo &proj_data_info) const override
find bin for this event
bool is_valid_template (const ProjDataInfo &) const override
This method checks if the template is valid for LmToProjData.
CListEventScannerWithDiscreteDetectors (const shared_ptr< const ProjDataInfo > &proj_data_info)
const Scanner * get_scanner_ptr () const
LORAs2Points< float > get_LOR () const override
find LOR between detector pairs
void get_bin (Bin &bin, const ProjDataInfo &proj_data_info) const override
find bin for this event
bool is_valid_template (const ProjDataInfo &) const override
This method checks if the template is valid for LmToProjData.
Additional Inherited Members
Protected Member Functions inherited from stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >
shared_ptr< const ProjDataInfoCylindricalNoArcCorr > get_uncompressed_proj_data_info_sptr () const
shared_ptr< const ProjDataInfoCylindricalNoArcCorr > get_uncompressed_proj_data_info_sptr () const
Detailed Description
Class for storing and using a coincidence event from a listmode file from Siemens scanners using the ECAT 8_32bit format.
Todo
This implementation only works if the list-mode data is stored without axial compression.
If the target sinogram has the same characteristics as the sinogram encoding used in the list file (via the offset), the code could be sped-up dramatically by using the information. At present, we go a huge round-about (offset->sinogram->detectors->sinogram->offset)
Member Function Documentation
get_detection_position()
void stir::ecat::CListEventECAT8_32bit::get_detection_position (DetectionPositionPair<> & det_pos) const override virtual
This routine returns the corresponding detector pair.
Implements stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >.
References get_detection_position().
Referenced by get_detection_position().
set_detection_position()
void stir::ecat::CListEventECAT8_32bit::set_detection_position (const DetectionPositionPair<> &) override virtual
This routine sets in a coincidence event from detector "indices".
Implements stir::CListEventScannerWithDiscreteDetectors< ProjDataInfoCylindricalNoArcCorr >.
References stir::error(), and set_detection_position().
Referenced by set_detection_position().
is_prompt()
bool stir::ecat::CListEventECAT8_32bit::is_prompt () const inline override virtual
Implements stir::ListEvent.
set_prompt()
Succeeded stir::ecat::CListEventECAT8_32bit::set_prompt (const bool prompt = true) inline override virtual
Changes the event from prompt to delayed or vice versa.
Default implementation just returns Succeeded::no.
Reimplemented from stir::CListEvent.
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/CListRecordECAT8_32bit.h
/home/kris/devel/STIRdistrib/STIR/src/listmode_buildblock/CListRecordECAT8_32bit.cxx