STIR: stir::MoveProjData Class Reference
stir::MoveProjData Class Reference
STIR » STIR library » Items relating to motion and motion correction
A class for moving projection data according to average motion in the frame.
Public Member Functions
MoveProjData (const char *const par_filename)
virtual Succeeded process_data ()
Public Member Functions inherited from stir::TimeFrameMotion
void move_to_reference (const bool)
void set_frame_num_to_process (const int)
int get_frame_num_to_process () const
const RigidObject3DTransformation & get_current_rigid_object_transformation () const
get transformation from (or to) reference for current frame
const RigidObject3DTransformation & get_rigid_object_transformation_to_reference () const
Get the transformation to the reference as returned by the RigidObject3DMotion object.
const TimeFrameDefinitions & get_time_frame_defs () const
double get_frame_start_time (unsigned frame_num) const
double get_frame_end_time (unsigned frame_num) const
const RigidObject3DMotion & get_motion () const
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
Protected Member Functions
virtual void set_defaults ()
parsing functions
virtual void initialise_keymap ()
Initialise all keywords.
virtual bool post_processing ()
This will be called at the end of the parsing.
Protected Member Functions inherited from stir::TimeFrameMotion
void set_defaults () override
parsing functions
void initialise_keymap () override
Initialise all keywords.
bool post_processing () override
This will be called at the end of the parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Protected Attributes
string input_filename
parsing variables
string output_filename_prefix
string output_template_filename
int max_in_segment_num_to_process
int max_out_segment_num_to_process
KeyParser parser
Detailed Description
A class for moving projection data according to average motion in the frame.
Output is currently always in interfile format
See also
transform_3d_object(ProjData& out_proj_data, const ProjData& in_proj_data, const RigidObject3DTransformation& rigid_object_transformation)
Example par file
See also
TimeFrameMotion for other parameters
  MoveProjData Parameters:=
  input file:= input_filename
  ; output name
  ; filenames will be constructed by appending _f#g1d0b0 (and the extension)
  ; where # is the frame number
  output filename prefix:= output
  ;; next defaults to input file
  ;output template filename:=
  ; alternative way to reduce number of segments (defaults to: use all)
  ;max_out_segment_num_to_process:=-1
  END :=
Member Function Documentation
process_data()
Succeeded stir::MoveProjData::process_data () virtual
Implements stir::TimeFrameMotion.
set_defaults()
void stir::MoveProjData::set_defaults () protected virtual
parsing functions
Reimplemented from stir::ParsingObject.
References stir::TimeFrameMotion::set_defaults().
initialise_keymap()
void stir::MoveProjData::initialise_keymap () protected virtual
Initialise all keywords.
Reimplemented from stir::ParsingObject.
References stir::TimeFrameMotion::initialise_keymap(), and input_filename.
post_processing()
bool stir::MoveProjData::post_processing () protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented from stir::ParsingObject.
References input_filename, stir::TimeFrameMotion::post_processing(), stir::ProjData::read_from_file(), and stir::warning().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/experimental/motion_utilities/move_projdata.cxx