STIR: stir::ExamData Class Reference
stir::ExamData Class Reference
STIR » STIR library » Basic building blocks
base class for data objects such as ProjData etcProvides an ExamInfo member.
#include "stir/ExamData.h"
Public Member Functions
ExamData ()
ExamData.
ExamData (const shared_ptr< ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual const ExamInfo * get_exam_info_ptr () const
Get pointer to exam info.
virtual shared_ptr< ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
Protected Attributes
shared_ptr< ExamInfo > exam_info_sptr
Detailed Description
base class for data objects such as ProjData etc
Provides an ExamInfo member.
Constructor & Destructor Documentation
ExamData()
stir::ExamData::ExamData ()
ExamData.
Default constructor
Member Function Documentation
get_exam_info_sptr()
shared_ptr< ExamInfo > stir::ExamData::get_exam_info_sptr () const virtual
Get shared pointer to exam info.
Warning
Use with care. If you modify the object in a shared ptr, everything using the same shared pointer will be affected.
Referenced by stir::VoxelsOnCartesianGrid< elemT >::clone(), stir::ScatterSimulation::downsample_density_image_for_scatter_points(), stir::VoxelsOnCartesianGrid< elemT >::get_empty_voxels_on_cartesian_grid(), stir::SSRB(), stir::ScatterEstimation::upsample_and_fit_scatter_estimate(), and stir::ProjData::write_to_file().
set_exam_info()
void stir::ExamData::set_exam_info (ExamInfo const & new_exam_info) virtual
change exam info
This will allocate a new ExamInfo object and copy the data in there.
Referenced by stir::VoxelsOnCartesianGrid< elemT >::clone(), and stir::zoom_image().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/ExamData.h
/home/sirfuser/devel/STIRdistrib/STIR/src/buildblock/ExamData.cxx