STIR: stir::ecat::ecat7::SinglesRatesFromECAT7 Class Reference
stir::ecat::ecat7::SinglesRatesFromECAT7 Class Reference
STIR » STIR library » Acquisition data building blocks » Singles rates etc
A class that extracts singles info from an ECAT7 sinogram file.
#include "stir/data/SinglesRatesFromECAT7.h"
Public Member Functions
SinglesRatesFromECAT7 ()
Default constructor.
int read_singles_from_file (const std::string &ECAT7_filename, const std::ios::openmode open_mode=std::ios::in)
The function that reads singles from ECAT7 file.
Public Member Functions inherited from stir::RegisteredParsingObject< SinglesRatesFromECAT7, SinglesRates, SinglesRatesForTimeFrames >
std::string get_registered_name () const
Returns Derived::registered_name.
std::string parameter_info ()
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::SinglesRatesForTimeFrames
SinglesRatesForTimeFrames ()
Default constructor.
float get_singles (int singles_bin_index, unsigned int frame_number) const
get the singles for a particular singles unit and frame number.
float get_singles (const int singles_bin_index, const double start_time, const double end_time) const
get the singles for a particular singles unit and a frame with the specified start and end times.
FrameSinglesRates STIR_DEPRECATED get_rates_for_frame (double start_time, double end_time) const
Generate a FramesSinglesRate - containing the average rates.
void set_singles (const int singles_bin_index, const unsigned time_frame_num, const float new_singles)
Set a singles rate by singles bin index and time frame number.
unsigned int get_num_frames () const
Get the number of frames for which singles rates are recorded.
const TimeFrameDefinitions & get_time_frame_definitions () const
Get the time frame definitions.
Public Member Functions inherited from stir::SinglesRates
virtual float get_singles_rate (const int singles_bin_index, const double start_time, const double end_time) const
Get the (average) singles rate for a particular singles unit and a frame with the specified start and end times.
virtual float get_singles_rate (const DetectionPosition<> &det_pos, const double start_time, const double end_time) const
Virtual function that returns the average singles rate given the detection positions and time-interval of detection.
virtual float get_singles (const DetectionPosition<> &det_pos, const double start_time, const double end_time) const
Virtual function that returns the number of singles given the detection positions and time-interval of detection.
const Scanner * get_scanner_ptr () const
Get the scanner pointer.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
void ask_parameters ()
bool parse (std::istream &f)
bool parse (const char *const filename)
Static Public Attributes
static const char *const registered_name = "Singles From ECAT7"
Name which will be used when parsing a SinglesRatesFromECAT7 object.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< SinglesRatesFromECAT7, SinglesRates, SinglesRatesForTimeFrames >
static SinglesRates * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< SinglesRates >
static SinglesRates * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static SinglesRates * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< SinglesRates >
typedef SinglesRates *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Protected Member Functions inherited from stir::ParsingObject
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< SinglesRates >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::SinglesRatesForTimeFrames
Array< 2, float > _singles
TimeFrameDefinitions _time_frame_defs
Protected Attributes inherited from stir::SinglesRates
shared_ptr< Scanner > scanner_sptr
Generate a FramesSinglesRate - containing the average rates.
Protected Attributes inherited from stir::ParsingObject
KeyParser parser
Detailed Description
A class that extracts singles info from an ECAT7 sinogram file.
Member Function Documentation
read_singles_from_file()
int stir::ecat::ecat7::SinglesRatesFromECAT7::read_singles_from_file (const std::string & ECAT7_filename, const std::ios::openmode open_mode = std::ios::in)
The function that reads singles from ECAT7 file.
Returns
The number of frames found. 0 if failed.
References stir::error(), stir::ecat::find_scanner_from_ECAT_system_type(), and stir::warning().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/data/SinglesRatesFromECAT7.h
/home/sirfuser/devel/STIRdistrib/STIR/src/data_buildblock/SinglesRatesFromECAT7.cxx