STIR: stir::DistributedWorker< TargetT > Class Template Reference
stir::DistributedWorker< TargetT > Class Template Reference
STIR » STIR library » Reconstruction building blocks » distributable building blocks
This implements the Worker for the stir::distributable_computation() function.
#include "stir/recon_buildblock/DistributedWorker.h"
Public Member Functions
void start ()
Infinite loop waiting for tasks from the master.
Public Member Functions inherited from stir::TimedObject
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers (bool do_reset=false) const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the CPU timer (since first use or last reset)
double get_wall_clock_timer_value () const
get current value of the wall-clock timer (since first use or last reset)
Protected Member Functions
void set_defaults ()
sets defaults for this object
void setup_distributable_computation ()
Get basic information from the master.
void distributable_computation (RPC_process_related_viewgrams_type *RPC_process_related_viewgrams)
this does the actual computation corresponding to distributable_computation()
Detailed Description
template<class TargetT>
class stir::DistributedWorker< TargetT >
This implements the Worker for the stir::distributable_computation() function.
The start() method is an infinite loop waiting for a task from the master. Very few tasks are implemented at the moment: set_up, compute, stop.
The distributable_computation() function does the actual work. It is the slave-part of stir::distributable_computation() which runs on the master. It is a loop receiving the related viewgrams and calling an RPC_process_related_viewgrams_type function with the received values. When an end_iteration_notification is received, it calls the reduction of the output_image.
In each inner loop the worker first receives the vs_num and the information whether this is a new viewgram or a previously received viewgram. The latter case only emerges if distributed caching is enabled. If so, the worker does not have to receive the related viewgrams, but just gets it from its saved viewgrams.
Todo
The log_likelihood_ptr argument to the RPC function is currently always NULL.
Currently the only computation that is supported corresponds to the gradient computation. It would be trivial to add others.
Member Function Documentation
setup_distributable_computation()
template<typename TargetT> void stir::DistributedWorker< TargetT >::setup_distributable_computation () protected
Get basic information from the master.
It sets up all needed objects by communicating with the master.
The following objects are set up:
bool zero_seg0_end_planes
target_image_sptr
ProjDataInfo pointer
ProjectorByBinPair pointer
ProjDataInMemory to save the received related viewgrams
Additionally some values for testing are set up.
References distributed::min_threshold, distributed::receive_and_construct_exam_and_proj_data_info_ptr(), distributed::receive_and_initialize_projectors(), distributed::receive_and_set_image_parameters(), distributed::receive_bool_value(), distributed::receive_double_values(), distributed::receive_image_values_and_fill_image_ptr(), distributed::receive_int_values(), distributed::test, and distributed::test_send_receive_times.
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/DistributedWorker.h
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/DistributedWorker.cxx