STIR: stir::ProjMatrixByBin Class Reference
stir::ProjMatrixByBin Class Reference abstract
STIR » STIR library » Reconstruction building blocks » Projection building blocks
This is the (abstract) base class for all projection matrices which are organised by 'bin'.
#include "stir/recon_buildblock/ProjMatrixByBin.h"
Public Member Functions
virtual void set_up (const shared_ptr< const ProjDataInfo > &proj_data_info_ptr, const shared_ptr< const DiscretisedDensity< 3, float > > &density_info_ptr)=0
To be called before any calculation is performed.
virtual ProjMatrixByBin * clone () const =0
const DataSymmetriesForBins * get_symmetries_ptr () const
get a pointer to an object encoding all symmetries that are used by this ProjMatrixByBin
const shared_ptr< DataSymmetriesForBins > get_symmetries_sptr () const
get a shared_ptr to an object encoding all symmetries that are used by this ProjMatrixByBin
void get_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin &, const Bin &) const
The main method for getting a row of the matrix.
void enable_cache (const bool v=true)
void store_only_basic_bins_in_cache (const bool v=true)
bool is_cache_enabled () const
bool does_cache_store_only_basic_bins () const
void clear_cache () const
Remove all elements from the cache.
Public Member Functions inherited from stir::RegisteredObjectBase
virtual std::string get_registered_name () const =0
Returns the name of the type of the object.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
Public Member Functions inherited from stir::TimedObject
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers (bool do_reset=false) const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the CPU timer (since first use or last reset)
double get_wall_clock_timer_value () const
get current value of the wall-clock timer (since first use or last reset)
Protected Member Functions
ProjMatrixByBin ()
default ctor (calls set_defaults())
virtual void calculate_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin &) const =0
This method needs to be implemented in the derived class.
void set_defaults () override
sets value for caching configuration (enables caching, but for 'basic' bins only)
void initialise_keymap () override
sets keys for caching configuration
bool post_processing () override
Checks if parameters have sensible values.
Succeeded get_cached_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin &) const
The method that tries to get data from the cache.
void cache_proj_matrix_elems_for_one_bin (const ProjMatrixElemsForOneBin &) const
The method to store data in the cache.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Protected Attributes
shared_ptr< DataSymmetriesForBins > symmetries_sptr
bool cache_disabled
bool cache_stores_only_basic_bins
bool tof_enabled
If activated TOF reconstruction will be performed.
shared_ptr< const VoxelsOnCartesianGrid< float > > image_info_sptr
We need a local copy of the discretised density in order to find the cartesian coordinates of each voxel.
shared_ptr< const ProjDataInfo > proj_data_info_sptr
We need a local copy of the proj_data_info to get the integration boundaries and RayTracing.
KeyParser parser
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredObject< ProjMatrixByBin >
static ProjMatrixByBin * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static ProjMatrixByBin * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< ProjMatrixByBin >
typedef ProjMatrixByBin *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Static Protected Member Functions inherited from stir::RegisteredObject< ProjMatrixByBin >
static RegistryType & registry ()
Static function returning the registry.
Detailed Description
This is the (abstract) base class for all projection matrices which are organised by 'bin'.
This class provides essentially only 2 public members: a method to get a 'row' of the matrix, and a method to get information on the symmetries.
Currently, the class provides for some (basic) caching. This functionality will probably be moved to a new class ProjMatrixByBinWithCache. (TODO)
Parsing parameters
The following parameters can be set (default values are indicated):
  disable caching := false
  store only basic bins in cache := true
The 2nd option allows to cache the whole matrix. This results in the fastest behaviour IF your system does not start swapping. The default choice caches only the 'basic' bins, and computes symmetry related bins from the 'basic' ones.
Constructor & Destructor Documentation
ProjMatrixByBin()
stir::ProjMatrixByBin::ProjMatrixByBin () protected
default ctor (calls set_defaults())
Note that due to the C++ definition (and some good reasons), ProjMatrixByBin::set_defaults() is called, even though this is a virtual function.
References ProjMatrixByBin(), and set_defaults().
Referenced by ProjMatrixByBin().
Member Function Documentation
set_up()
void stir::ProjMatrixByBin::set_up (const shared_ptr< const ProjDataInfo > & proj_data_info_ptr, const shared_ptr< const DiscretisedDensity< 3, float > > & density_info_ptr) pure virtual
To be called before any calculation is performed.
Note that get_proj_matrix_elems_for_one_bin() will expect objects of compatible sizes and other info.
Warning
: Any implementation of set_up in a derived class has to call ProjMatrixByBin::set_up first.
Implemented in stir::ProjMatrixByBinFromFile, stir::ProjMatrixByBinPinholeSPECTUB, stir::ProjMatrixByBinSinglePhoton, stir::ProjMatrixByBinSPECTUB, stir::ProjMatrixByBinUsingInterpolation, stir::ProjMatrixByBinUsingRayTracing, stir::ProjMatrixByBinUsingSolidAngle, and stir::ProjMatrixByBinWithPositronRange.
References stir::error(), image_info_sptr, proj_data_info_sptr, set_up(), and tof_enabled.
Referenced by set_up(), stir::ProjMatrixByBinFromFile::set_up(), stir::ProjMatrixByBinPinholeSPECTUB::set_up(), stir::ProjMatrixByBinSPECTUB::set_up(), stir::ProjMatrixByBinUsingInterpolation::set_up(), and stir::ProjMatrixByBinUsingRayTracing::set_up().
get_proj_matrix_elems_for_one_bin()
void stir::ProjMatrixByBin::get_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin & probabilities, const Bin & bin) const inline
The main method for getting a row of the matrix.
The ProjMatrixElemsForOneBin argument will be overwritten (i.e. data is NOT appended).
The implementation is inline as it just gets it in terms of the cached_proj_matrix_elems_for_one_bin or calculate_proj_matrix_elems_for_one_bin.
References cache_proj_matrix_elems_for_one_bin(), calculate_proj_matrix_elems_for_one_bin(), stir::ProjMatrixElemsForOneBin::check_state(), stir::ProjMatrixElemsForOneBin::erase(), get_cached_proj_matrix_elems_for_one_bin(), get_proj_matrix_elems_for_one_bin(), proj_data_info_sptr, and stir::ProjMatrixElemsForOneBin::set_bin().
Referenced by get_proj_matrix_elems_for_one_bin(), and stir::ProjMatrixByBinFromFile::write_to_file().
calculate_proj_matrix_elems_for_one_bin()
virtual void stir::ProjMatrixByBin::calculate_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin &) const protected pure virtual
This method needs to be implemented in the derived class.
bin-coordinates are obtained via the ProjMatrixElemsForOneBin::get_bin() method.
Note that 'calculate' could just as well mean 'get from file'
References initialise_keymap(), post_processing(), and set_defaults().
Referenced by get_proj_matrix_elems_for_one_bin().
set_defaults()
void stir::ProjMatrixByBin::set_defaults () override protected virtual
sets value for caching configuration (enables caching, but for 'basic' bins only)
Has to be called by set_defaults in the leaf-class
Reimplemented from stir::ParsingObject.
References set_defaults().
Referenced by calculate_proj_matrix_elems_for_one_bin(), ProjMatrixByBin(), and set_defaults().
initialise_keymap()
void stir::ProjMatrixByBin::initialise_keymap () override protected virtual
sets keys for caching configuration
Has to be called by initialise_keymap in the leaf-class
Reimplemented from stir::ParsingObject.
References initialise_keymap().
Referenced by calculate_proj_matrix_elems_for_one_bin(), and initialise_keymap().
post_processing()
bool stir::ProjMatrixByBin::post_processing () override protected virtual
Checks if parameters have sensible values.
Has to be called by post_processing in the leaf-class
Reimplemented from stir::ParsingObject.
References post_processing().
Referenced by calculate_proj_matrix_elems_for_one_bin(), and post_processing().
get_cached_proj_matrix_elems_for_one_bin()
Succeeded stir::ProjMatrixByBin::get_cached_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin & probabilities) const protected
The method that tries to get data from the cache.
If it succeeds, it overwrites the ProjMatrixElemsForOneBin parameter and returns Succeeded::yes, otherwise it does not touch the ProjMatrixElemsForOneBin and returns Succeeded::false.
References stir::ProjMatrixElemsForOneBin::get_bin(), get_cached_proj_matrix_elems_for_one_bin(), stir::SegmentIndices::segment_num(), and stir::ViewgramIndices::view_num().
Referenced by get_cached_proj_matrix_elems_for_one_bin(), and get_proj_matrix_elems_for_one_bin().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/ProjMatrixByBin.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/ProjMatrixByBin.inl
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/ProjMatrixByBin.cxx