STIR: stir::ListModeData_dummy Class Reference
stir::ListModeData_dummy Class Reference
STIR » STIR library » Support classes for reading list mode data
A class to trick the Objective function that we have list mode data, when we only have cache.
#include "stir/listmode/ListModeData_dummy.h"
Public Member Functions
ListModeData_dummy (shared_ptr< const ExamInfo > exam_info_sptr, shared_ptr< const ProjDataInfo > proj_data_info_sptr)
std::string get_name () const override
Returns the name of the list mode data.
Succeeded reset () override
Call this function if you want to re-start reading at the beginning.
SavedPosition save_get_position () override
Save the current reading position.
Succeeded set_get_position (const SavedPosition &) override
Set the position for reading to a previously saved point.
bool has_delayeds () const override
Return if the file stores delayed events as well (as opposed to prompts)
Public Member Functions inherited from stir::ListModeData
ListModeData ()
Default constructor.
ListModeData (shared_ptr< const ExamInfo > exam_info_sptr, shared_ptr< const ProjDataInfo > proj_data_info_sptr)
shared_ptr< ListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (ListRecord &event) const
Gets the next record in the listmode sequence.
const Scanner & get_scanner () const
Get reference to scanner.
virtual unsigned long int get_total_number_of_events () const
Returns the total number of events in the listmode file.
Public Member Functions inherited from stir::ExamData
ExamData ()
ExamData.
ExamData (const shared_ptr< const ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual shared_ptr< const ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
void set_exam_info_sptr (shared_ptr< const ExamInfo > new_exam_info_sptr)
Public Member Functions inherited from stir::DataWithProjDataInfo
DataWithProjDataInfo ()
Default constructor sets internal member to 0.
DataWithProjDataInfo (const shared_ptr< const ProjDataInfo > &proj_data_info_sptr_v)
virtual const ProjDataInfo & get_proj_data_info () const
virtual shared_ptr< const ProjDataInfo > get_proj_data_info_sptr () const
Get shared pointer to ProjData info.
int get_num_segments () const
Get number of segments.
int get_num_axial_poss (const int segment_num) const
Get number of axial positions per segment.
int get_num_views () const
Get number of views.
int get_num_tangential_poss () const
Get number of tangential positions.
int get_num_tof_poss () const
Get number of TOF positions.
int get_min_tof_pos_num () const
Get the index of the first timing position.
int get_max_tof_pos_num () const
Get the index of the last timing position.
int get_tof_mash_factor () const
Get TOG mash factor.
int get_min_segment_num () const
Get minimum segment number.
int get_max_segment_num () const
Get maximum segment number.
int get_min_axial_pos_num (const int segment_num) const
Get mininum axial position per segmnet.
int get_max_axial_pos_num (const int segment_num) const
Get maximum axial position per segment.
int get_min_view_num () const
Get minimum view number.
int get_max_view_num () const
Get maximum view number.
int get_min_tangential_pos_num () const
Get minimum tangential position number.
int get_max_tangential_pos_num () const
Get maximum tangential position number.
Protected Member Functions
shared_ptr< ListRecord > get_empty_record_helper_sptr () const override
Succeeded get_next (ListRecord &event) const override
Protected Member Functions inherited from stir::ListModeData
virtual void set_proj_data_info_sptr (shared_ptr< const ProjDataInfo >)
Additional Inherited Members
Public Types inherited from stir::ListModeData
typedef ListModeData hierarchy_base_type
typedef used by read_from_file
typedef unsigned int SavedPosition
Use this typedef for save/set_get_position.
Protected Attributes inherited from stir::ExamData
shared_ptr< const ExamInfo > exam_info_sptr
Protected Attributes inherited from stir::DataWithProjDataInfo
shared_ptr< const ProjDataInfo > proj_data_info_sptr
Detailed Description
A class to trick the Objective function that we have list mode data, when we only have cache.
Author
Nikos Efthimiou
This class was created only to hold an ExamInfo and be returned by ListModeData& get_input_data() during set_up() when calling STIR from SIRF.
This can happen when a private (not open-source) IO is required to read the listmode files. However, the owner of that library shared a cache (see PoissonLogLikelihoodWithLinearModelForMeanAndListModeData) listmode file with a third party.
Todo
Currently, it can only be used in combination with SIRF.
A possibility is to complete this as a class for cache files.
!
Member Function Documentation
get_name()
std::string stir::ListModeData_dummy::get_name () const inline override virtual
Returns the name of the list mode data.
This name is not necessarily unique, and might be empty. However, it is expected (but not guaranteed) that ListModeData::read_from_file(lm_data_ptr->get_name()) would read the same list mode data.
The reason this cannot be guaranteed is largely in case the list mode data is not really on disk, but the object corresponds for instance to a Monte Carlo simulator.
Implements stir::ListModeData.
reset()
Succeeded stir::ListModeData_dummy::reset () inline override virtual
Call this function if you want to re-start reading at the beginning.
Implements stir::ListModeData.
References stir::error().
save_get_position()
SavedPosition stir::ListModeData_dummy::save_get_position () inline override virtual
Save the current reading position.
Note that the return value is not related to the number of events already read. In particular, you cannot do any arithmetic on it to skip a few events. This is different from e.g. std::streampos.
Warning
There is a maximum number of times this function can be called. This is determined by the SavedPosition type. Once you save more positions, the first positions will be overwritten. There is currently no way of finding out after how many times this will happen (but it's a large number...).
These saved positions are only valid for the lifetime of the ListModeData object.
A derived class might disable this facility. It will/should then always return Succeeded::no when calling set_get_position().
Implements stir::ListModeData.
References stir::error().
set_get_position()
Succeeded stir::ListModeData_dummy::set_get_position (const SavedPosition &) inline override virtual
Set the position for reading to a previously saved point.
Implements stir::ListModeData.
References stir::error().
has_delayeds()
bool stir::ListModeData_dummy::has_delayeds () const inline override virtual
Return if the file stores delayed events as well (as opposed to prompts)
Implements stir::ListModeData.
References stir::error().
get_empty_record_helper_sptr()
shared_ptr< ListRecord > stir::ListModeData_dummy::get_empty_record_helper_sptr () const inline override protected virtual
Implements stir::ListModeData.
get_next()
Succeeded stir::ListModeData_dummy::get_next (ListRecord & event) const inline override protected virtual
Implements stir::ListModeData.
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/ListModeData_dummy.h