STIR: stir::FrameSinglesRates Class Reference
stir::FrameSinglesRates Class Reference
STIR » STIR library » Acquisition data building blocks » Singles rates etc
A single frame of singles information.
#include "stir/data/SinglesRates.h"
Public Types
typedef std::vector< float >::iterator iterator
typedef std::vector< float >::const_iterator const_iterator
Public Member Functions
FrameSinglesRates (std::vector< float > &avg_singles_rates, double start_time, double end_time, shared_ptr< Scanner > scanner)
Constructor taking all arguments.
FrameSinglesRates (double start_time, double end_time, shared_ptr< Scanner > scanner)
Constructor without singles rates.
float get_singles_rate (int singles_bin_index) const
Get singles rate for a particular singles bin index.
float get_singles_rate (const DetectionPosition<> &det_pos) const
Get singles rate for a detection position.
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
double get_start_time () const
Get the start time of the frame whose rates are recorded.
double get_end_time () const
Get the end time of the frame whose rates are recorded.
const Scanner * get_scanner_ptr () const
Get the scanner information.
Detailed Description
A single frame of singles information.
Todo
This class does not store rates, but totals! Naming is all wrong.
Deprecated
Constructor & Destructor Documentation
FrameSinglesRates() [1/2]
stir::FrameSinglesRates::FrameSinglesRates (std::vector< float > & avg_singles_rates, double start_time, double end_time, shared_ptr< Scanner > scanner)
Constructor taking all arguments.
Warning
only checks sizes with an assert.
References FrameSinglesRates().
Referenced by FrameSinglesRates().
FrameSinglesRates() [2/2]
stir::FrameSinglesRates::FrameSinglesRates (double start_time, double end_time, shared_ptr< Scanner > scanner)
Constructor without singles rates.
Initialises the size of the internal object that stores the singles rates but does not initialise its values.
References get_singles_rate().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/data/SinglesRates.h
/home/kris/devel/STIRdistrib/STIR/src/data_buildblock/SinglesRates.cxx
/home/kris/devel/STIRdistrib/STIR/src/include/stir/data/SinglesRates.inl