STIR: stir::ForwardProjectorByBinUsingProjMatrixByBin Class Reference
stir::ForwardProjectorByBinUsingProjMatrixByBin Class Reference
STIR » STIR library » Reconstruction building blocks » Projection building blocks
This implements the ForwardProjectorByBin interface, given any ProjMatrixByBin object.
#include "stir/recon_buildblock/ForwardProjectorByBinUsingProjMatrixByBin.h"
Public Member Functions
ForwardProjectorByBinUsingProjMatrixByBin (const shared_ptr< ProjMatrixByBin > &proj_matrix_ptr)
void set_up (const shared_ptr< const ProjDataInfo > &proj_data_info_ptr, const shared_ptr< const DiscretisedDensity< 3, float > > &density_info_ptr) override
Stores all necessary geometric info.
const DataSymmetriesForViewSegmentNumbers * get_symmetries_used () const override
Informs on which symmetries the projector handles.
Public Member Functions inherited from stir::RegisteredParsingObject< ForwardProjectorByBinUsingProjMatrixByBin, ForwardProjectorByBin >
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::ForwardProjectorByBin
ForwardProjectorByBin ()
Default constructor calls reset_timers()
void forward_project (ProjData &, const DiscretisedDensity< 3, float > &, int subset_num=0, int num_subsets=1, bool zero=true)
project the volume into the whole or a subset of proj_data, optionally zeroing the rest
virtual void forward_project (ProjData &, int subset_num=0, int num_subsets=1, bool zero=true)
project the volume into the whole proj_data
void forward_project (RelatedViewgrams< float > &)
project the volume into the viewgrams
void forward_project (RelatedViewgrams< float > &, const int min_axial_pos_num, const int max_axial_pos_num)
void forward_project (RelatedViewgrams< float > &, const int min_axial_pos_num, const int max_axial_pos_num, const int min_tangential_pos_num, const int max_tangential_pos_num)
virtual void set_input (const DiscretisedDensity< 3, float > &)
Set input.
void set_pre_data_processor (shared_ptr< DataProcessor< DiscretisedDensity< 3, float > > > pre_data_processor_sptr)
Set data processor to use before forward projection. MUST BE CALLED BEFORE SET_INPUT.
Public Member Functions inherited from stir::TimedObject
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers (bool do_reset=false) const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the CPU timer (since first use or last reset)
double get_wall_clock_timer_value () const
get current value of the wall-clock timer (since first use or last reset)
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
Static Public Attributes
static const char *const registered_name = "Matrix"
Name which will be used when parsing a ForwardProjectorByBin object.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< ForwardProjectorByBinUsingProjMatrixByBin, ForwardProjectorByBin >
static ForwardProjectorByBin * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< ForwardProjectorByBin >
static ForwardProjectorByBin * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static ForwardProjectorByBin * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< ForwardProjectorByBin >
typedef ForwardProjectorByBin *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Protected Member Functions inherited from stir::ForwardProjectorByBin
virtual void actual_forward_project (RelatedViewgrams< float > &viewgrams, const int min_axial_pos_num, const int max_axial_pos_num, const int min_tangential_pos_num, const int max_tangential_pos_num)
virtual void check (const ProjDataInfo &proj_data_info) const
check if the argument is the same as what was used for set_up()
virtual void check (const ProjDataInfo &proj_data_info, const DiscretisedDensity< 3, float > &density_info) const
check if the arguments are the same as what was used for set_up()
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< ForwardProjectorByBin >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::ForwardProjectorByBin
bool _already_set_up
shared_ptr< DiscretisedDensity< 3, float > > _density_sptr
The density ptr set with set_up()
shared_ptr< DataProcessor< DiscretisedDensity< 3, float > > > _pre_data_processor_sptr
shared_ptr< const ProjDataInfo > _proj_data_info_sptr
ProjDataInfo set by set_up()
KeyParser parser
Detailed Description
This implements the ForwardProjectorByBin interface, given any ProjMatrixByBin object.
It stores a shared_ptr to a ProjMatrixByBin object, which will be used to get the relevant elements of the projection matrix.
Member Function Documentation
set_up()
void stir::ForwardProjectorByBinUsingProjMatrixByBin::set_up (const shared_ptr< const ProjDataInfo > & proj_data_info_ptr, const shared_ptr< const DiscretisedDensity< 3, float > > & density_info_ptr) override virtual
Stores all necessary geometric info.
Note that the density_info_ptr is not stored in this object. It's only used to get some info on sizes etc.
Implements stir::ForwardProjectorByBin.
References stir::ForwardProjectorByBin::set_up(), and set_up().
Referenced by set_up().
get_symmetries_used()
const DataSymmetriesForViewSegmentNumbers * stir::ForwardProjectorByBinUsingProjMatrixByBin::get_symmetries_used () const override virtual
Informs on which symmetries the projector handles.
It should get data related by at least those symmetries. Otherwise, a run-time error will occur (unless the derived class has other behaviour).
Implements stir::ForwardProjectorByBin.
References stir::error(), and get_symmetries_used().
Referenced by get_symmetries_used().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/ForwardProjectorByBinUsingProjMatrixByBin.h
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/ForwardProjectorByBinUsingProjMatrixByBin.cxx