STIR: stir::BinNormalisationWithCalibration Class Reference
stir::BinNormalisationWithCalibration Class Reference abstract
STIR » STIR library » Reconstruction building blocks » Normalisation building blocks
#include "stir/recon_buildblock/BinNormalisationWithCalibration.h"
Public Member Functions
Succeeded set_up (const shared_ptr< const ExamInfo > &exam_info_sptr, const shared_ptr< const ProjDataInfo > &) override
initialises the object and checks if it can handle such projection data
float get_calib_decay_branching_ratio_factor (const Bin &) const
product of calibration factor etc
float get_calibration_factor () const override
float get_branching_ratio () const
void set_calibration_factor (const float)
void set_radionuclide (const Radionuclide &)
virtual float get_uncalibrated_bin_efficiency (const Bin &) const =0
float get_bin_efficiency (const Bin &bin) const final
return efficiency for 1 bin
Public Member Functions inherited from stir::BinNormalisation
virtual bool is_trivial () const
check if we would be multiplying with 1 (i.e. do nothing)
virtual bool is_TOF_only_norm () const
returns if the object can only handle TOF data
virtual void apply (RelatedViewgrams< float > &) const
normalise some data
virtual void undo (RelatedViewgrams< float > &) const
undo the normalisation of some data
void apply (ProjData &, shared_ptr< DataSymmetriesForViewSegmentNumbers >=shared_ptr< DataSymmetriesForViewSegmentNumbers >()) const
normalise some data
void undo (ProjData &, shared_ptr< DataSymmetriesForViewSegmentNumbers >=shared_ptr< DataSymmetriesForViewSegmentNumbers >()) const
undo the normalisation of some data
void set_exam_info_sptr (const shared_ptr< const ExamInfo > _exam_info_sptr)
shared_ptr< const ExamInfo > get_exam_info_sptr () const
Public Member Functions inherited from stir::RegisteredObjectBase
virtual std::string get_registered_name () const =0
Returns the name of the type of the object.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
Protected Member Functions
void set_defaults () override
void initialise_keymap () override
Initialise all keywords.
bool post_processing () override
This will be called at the end of the parsing.
Protected Member Functions inherited from stir::BinNormalisation
virtual void check (const ProjDataInfo &proj_data_info) const
check if the argument is the same as what was used for set_up()
virtual void check (const ExamInfo &exam_info) const
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredObject< BinNormalisation >
static BinNormalisation * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static BinNormalisation * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< BinNormalisation >
typedef BinNormalisation *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Static Protected Member Functions inherited from stir::RegisteredObject< BinNormalisation >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::BinNormalisation
bool _already_set_up
shared_ptr< const ProjDataInfo > proj_data_info_sptr
KeyParser parser
Detailed Description
This class provides the facility to use a calibration factor and (isotope) branching ratio when normalising data. Therefore, if they are set correctly, the reconstructed image will be calibrated as well.
Note that it is the responsibility of the derived classes to set the calibration factor. The branching ratio is obtained from the radionuclide set in ExamInfo (passed by set_up()).
Member Function Documentation
set_up()
Succeeded stir::BinNormalisationWithCalibration::set_up (const shared_ptr< const ExamInfo > & exam_info_sptr, const shared_ptr< const ProjDataInfo > & proj_data_info_sptr) override virtual
initialises the object and checks if it can handle such projection data
Computes internal numbers related to calibration etc.
Reimplemented from stir::BinNormalisation.
References stir::BinNormalisation::set_up(), set_up(), and stir::warning().
Referenced by set_up(), stir::ecat::BinNormalisationFromECAT8::set_up(), stir::ecat::ecat7::BinNormalisationFromECAT7::set_up(), and stir::GE::RDF_HDF5::BinNormalisationFromGEHDF5::set_up().
get_calibration_factor()
float stir::BinNormalisationWithCalibration::get_calibration_factor () const override virtual
Reimplemented from stir::BinNormalisation.
get_bin_efficiency()
float stir::BinNormalisationWithCalibration::get_bin_efficiency (const Bin & bin) const inline final virtual
return efficiency for 1 bin
returns get_uncalibrated_bin_efficiency(bin)/get_calib_decay_branching_ratio_factor(bin)
Implements stir::BinNormalisation.
set_defaults()
void stir::BinNormalisationWithCalibration::set_defaults () override protected virtual
sets _already_setup to false
Reimplemented from stir::BinNormalisation.
References stir::BinNormalisation::set_defaults(), and set_defaults().
Referenced by set_defaults().
initialise_keymap()
void stir::BinNormalisationWithCalibration::initialise_keymap () override protected virtual
Initialise all keywords.
Reimplemented from stir::ParsingObject.
References initialise_keymap(), and stir::ParsingObject::initialise_keymap().
Referenced by initialise_keymap().
post_processing()
bool stir::BinNormalisationWithCalibration::post_processing () override protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented from stir::ParsingObject.
References post_processing(), and stir::ParsingObject::post_processing().
Referenced by post_processing().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/BinNormalisationWithCalibration.h
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/BinNormalisationWithCalibration.cxx