STIR: stir::MultiParametricDiscretisedDensityInputFileFormat Class Reference
stir::MultiParametricDiscretisedDensityInputFileFormat Class Reference
STIR » STIR library » Input/Output Library
Class for reading images in Multi file-format.
#include "stir/IO/MultiParametricDiscretisedDensityInputFileFormat.h"
Public Member Functions
const std::string get_name () const override
Public Member Functions inherited from stir::InputFileFormat< ParametricVoxelsOnCartesianGrid >
virtual bool can_read (const FileSignature &signature, std::istream &input) const
virtual bool can_read (const FileSignature &signature, const std::string &filename) const
Protected Member Functions
bool actual_can_read (const FileSignature &signature, std::istream &) const override
unique_ptr< data_type > read_from_file (std::istream &) const override
read data from a stream
unique_ptr< data_type > read_from_file (const std::string &filename) const override
read data from a filename
Additional Inherited Members
Public Types inherited from stir::InputFileFormat< ParametricVoxelsOnCartesianGrid >
typedef ParametricVoxelsOnCartesianGrid data_type
Detailed Description
Class for reading images in Multi file-format.
Member Function Documentation
get_name()
const std::string stir::MultiParametricDiscretisedDensityInputFileFormat::get_name () const inline override virtual
Implements stir::InputFileFormat< ParametricVoxelsOnCartesianGrid >.
actual_can_read()
bool stir::MultiParametricDiscretisedDensityInputFileFormat::actual_can_read (const FileSignature & signature, std::istream &) const inline override protected virtual
Implements stir::InputFileFormat< ParametricVoxelsOnCartesianGrid >.
read_from_file() [1/2]
unique_ptr< data_type > stir::MultiParametricDiscretisedDensityInputFileFormat::read_from_file (std::istream & input) const inline override protected virtual
read data from a stream
This function should throw an exception if the read fails.
Warning
This member throws for most implementations. Use a filename instead.
Implements stir::InputFileFormat< ParametricVoxelsOnCartesianGrid >.
References stir::error().
read_from_file() [2/2]
unique_ptr< data_type > stir::MultiParametricDiscretisedDensityInputFileFormat::read_from_file (const std::string & filename) const inline override protected virtual
read data from a filename
This function should throw an exception if the read fails.
Default implementation used open_read_binary and read_from_file(std::istream&).
Reimplemented from stir::InputFileFormat< ParametricVoxelsOnCartesianGrid >.
References stir::error(), stir::ParametricDiscretisedDensity< ParametricVoxelsOnCartesianGridBaseType >::get_num_params(), stir::KeyParser::parse(), and stir::read_from_file().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/MultiParametricDiscretisedDensityInputFileFormat.h