STIR: stir::GatedDiscretisedDensity Class Reference
stir::GatedDiscretisedDensity Class Reference
STIR » STIR library » Acquisition data building blocks
Class of multiple image gates.
#include "stir/GatedDiscretisedDensity.h"
Public Member Functions
GatedDiscretisedDensity (const GatedDiscretisedDensity &argument)
GatedDiscretisedDensity (const std::string &filename)
GatedDiscretisedDensity (const TimeGateDefinitions &time_gate_definitions)
GatedDiscretisedDensity (const shared_ptr< DiscretisedDensity< 3, float > > &density_sptr, const unsigned int num_gates)
GatedDiscretisedDensity (const TimeGateDefinitions &time_gate_definitions, const shared_ptr< DiscretisedDensity< 3, float > > &density_sptr)
Construct an empty GatedDiscretisedDensity based on a shared_ptr<DiscretisedDensity<3,float> >
GatedDiscretisedDensity & operator= (const GatedDiscretisedDensity &argument)
Static Public Member Functions
static GatedDiscretisedDensity * read_from_file (const std::string &filename)
static GatedDiscretisedDensity * read_from_files (const std::string &filename)
static GatedDiscretisedDensity * read_from_files (const std::string &filename, const std::string &suffix)
get/set the densities
Warning
The gate_num starts from 1
void set_density_sptr (const shared_ptr< DiscretisedDensity< 3, float > > &density_sptr, const unsigned int gate_num)
void resize_densities (const TimeGateDefinitions &time_gate_definitions)
const std::vector< shared_ptr< DiscretisedDensity< 3, float > > > & get_densities () const
const DiscretisedDensity< 3, float > & get_density (const unsigned int gate_num) const
const DiscretisedDensity< 3, float > & operator[] (const unsigned int gate_num) const
DiscretisedDensity< 3, float > & get_density (const unsigned int gate_num)
DiscretisedDensity< 3, float > & operator[] (const unsigned int gate_num)
void set_time_gate_definitions (TimeGateDefinitions time_gate_definitions)
const TimeGateDefinitions & get_time_gate_definitions () const
unsigned get_num_gates () const
void fill_with_zero ()
Succeeded write_to_files (const std::string &filename) const
write data to file Currently only in format.
Succeeded write_to_files (const std::string &filename, const std::string &suffix) const
Detailed Description
Class of multiple image gates.
Member Function Documentation
set_density_sptr()
void stir::GatedDiscretisedDensity::set_density_sptr (const shared_ptr< DiscretisedDensity< 3, float > > & density_sptr, const unsigned int gate_num)
Warning
This function is likely to disappear later, and is dangerous to use.
References set_density_sptr().
Referenced by stir::warp_imageTests::run_tests(), and set_density_sptr().
write_to_files()
Succeeded stir::GatedDiscretisedDensity::write_to_files (const std::string & filename) const
write data to file Currently only in format.
Warning
write_time_gate_definitions() is not yet implemented, so time information is missing.
References stir::write_to_file(), and write_to_files().
Referenced by write_to_files().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/GatedDiscretisedDensity.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/GatedDiscretisedDensity.cxx