STIR: stir::ProjectorByBinPairUsingParallelproj Class Reference
stir::ProjectorByBinPairUsingParallelproj Class Reference
STIR » STIR library » Reconstruction building blocks » Wrapped Parallelproj functionality in STIR
A projector pair based on Parallelproj projectors.
#include "stir/recon_buildblock/Parallelproj_projector/ProjectorByBinPairUsingParallelproj.h"
Public Member Functions
ProjectorByBinPairUsingParallelproj ()
Default constructor.
Succeeded set_up (const shared_ptr< const ProjDataInfo > &, const shared_ptr< const DiscretisedDensity< 3, float > > &) override
Stores all necessary geometric info.
void set_verbosity (const bool verbosity)
Set verbosity.
bool get_restrict_to_cylindrical_FOV () const
void set_restrict_to_cylindrical_FOV (bool val)
void set_num_gpu_chunks (const int num_gpu_chunks)
Set number of GPU chunks used by the forward and back projectors.
Public Member Functions inherited from stir::RegisteredParsingObject< ProjectorByBinPairUsingParallelproj, ProjectorByBinPair, ProjectorByBinPair >
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::ProjectorByBinPair
ProjectorByBinPair ()
Default constructor.
const shared_ptr< ForwardProjectorByBin > get_forward_projector_sptr () const
const shared_ptr< BackProjectorByBin > get_back_projector_sptr () const
const DataSymmetriesForViewSegmentNumbers * get_symmetries_used () const
Provide access to the (minimal) symmetries used by the projectors.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
Static Public Attributes
static const char *const registered_name = "Parallelproj"
Name which will be used when parsing a ProjectorByBinPair object.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< ProjectorByBinPairUsingParallelproj, ProjectorByBinPair, ProjectorByBinPair >
static ProjectorByBinPair * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
static ProjectorByBinPair * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< ProjectorByBinPair >
static ProjectorByBinPair * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static ProjectorByBinPair * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< ProjectorByBinPair >
typedef ProjectorByBinPair *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Protected Member Functions inherited from stir::ProjectorByBinPair
virtual void check (const ProjDataInfo &proj_data_info, const DiscretisedDensity< 3, float > &density_info) const
check if the argument is the same as what was used for set_up()
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< ProjectorByBinPair >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::ProjectorByBinPair
shared_ptr< ForwardProjectorByBin > forward_projector_sptr
shared_ptr< BackProjectorByBin > back_projector_sptr
bool _already_set_up
KeyParser parser
Detailed Description
A projector pair based on Parallelproj projectors.
Member Function Documentation
set_up()
Succeeded stir::ProjectorByBinPairUsingParallelproj::set_up (const shared_ptr< const ProjDataInfo > & proj_data_info_sptr, const shared_ptr< const DiscretisedDensity< 3, float > > & image_info_sptr) override virtual
Stores all necessary geometric info.
If necessary, set_up() can be called more than once.
Derived classes can assume that the projectors will be called with input corresponding to the arguments of the last call to set_up().
Warning
Derived classes have to call set_up from the base class.
Reimplemented from stir::ProjectorByBinPair.
References stir::error(), stir::ProjectorByBinPair::set_up(), and set_up().
Referenced by set_up().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/Parallelproj_projector/ProjectorByBinPairUsingParallelproj.h
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/Parallelproj_projector/ProjectorByBinPairUsingParallelproj.cxx