STIR: stir::GeneralisedPrior< DataT > Class Template Reference
stir::GeneralisedPrior< DataT > Class Template Reference abstract
STIR » STIR library » Reconstruction building blocks » Objective functions for iterative estimation of variables » Priors and penalties for MAP
A base class for 'generalised' priors, i.e. priors for which at least a 'gradient' is defined.
#include "stir/recon_buildblock/GeneralisedPrior.h"
Public Member Functions
virtual double compute_value (const DataT &current_estimate)=0
compute the value of the function
virtual void compute_gradient (DataT &prior_gradient, const DataT &current_estimate)=0
This should compute the gradient of the log of the prior function at the current_estimate.
virtual double compute_gradient_times_input (const DataT &input, const DataT &current_estimate)
compute the dot product of the gradient of the log of the prior function at the current_estimate with input
virtual void compute_Hessian (DataT &prior_Hessian_for_single_densel, const BasicCoordinate< 3, int > &coords, const DataT &current_image_estimate) const
This computes a single row of the Hessian.
virtual void compute_Hessian_diagonal (DataT &Hessian_diagonal, const DataT &current_estimate) const
This computes the diagonal of the Hessian of the log of the prior function at the current_estimate and stores it in Hessian_diagonal.
virtual void add_multiplication_with_approximate_Hessian (DataT &output, const DataT &input) const
This should compute the multiplication of the Hessian with a vector and add it to output.
virtual void accumulate_Hessian_times_input (DataT &output, const DataT &current_estimate, const DataT &input) const
This should compute the multiplication of the Hessian with a vector and add it to output.
float get_penalisation_factor () const
void set_penalisation_factor (float new_penalisation_factor)
virtual Succeeded set_up (shared_ptr< const DataT > const &target_sptr)
Has to be called before using this object.
virtual bool is_convex () const =0
Indicates if the prior is a smooth convex function.
Public Member Functions inherited from stir::RegisteredObjectBase
virtual std::string get_registered_name () const =0
Returns the name of the type of the object.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
Protected Member Functions
void set_defaults () override
sets value for penalisation factor
void initialise_keymap () override
sets key for penalisation factor
virtual void check (DataT const &current_estimate) const
Check that the prior is ready to be used.
virtual bool post_processing ()
This will be called at the end of the parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Protected Attributes
float penalisation_factor
bool _already_set_up
KeyParser parser
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredObject< GeneralisedPrior< DataT > >
static GeneralisedPrior< DataT > * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static GeneralisedPrior< DataT > * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< GeneralisedPrior< DataT > >
typedef GeneralisedPrior< DataT > *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Static Protected Member Functions inherited from stir::RegisteredObject< GeneralisedPrior< DataT > >
static RegistryType & registry ()
Static function returning the registry.
Detailed Description
template<typename DataT>
class stir::GeneralisedPrior< DataT >
A base class for 'generalised' priors, i.e. priors for which at least a 'gradient' is defined.
This class exists to accomodate FilterRootPrior. Otherwise we could just live with Prior as a base class.
Member Function Documentation
compute_value()
template<typename DataT> virtual double stir::GeneralisedPrior< DataT >::compute_value (const DataT & current_estimate) pure virtual
compute the value of the function
For derived classes where this doesn't make sense, it's recommended to return 0.
Implemented in stir::CudaGibbsPenalty< elemT, PotentialT >, stir::CudaRelativeDifferencePrior< elemT >, stir::FilterRootPrior< DataT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::ParametricQuadraticPrior< TargetT >, stir::PLSPrior< elemT >, stir::QuadraticPrior< float >, and stir::RelativeDifferencePrior< elemT >.
compute_gradient()
template<typename DataT> virtual void stir::GeneralisedPrior< DataT >::compute_gradient (DataT & prior_gradient, const DataT & current_estimate) pure virtual
This should compute the gradient of the log of the prior function at the current_estimate.
The gradient is already multiplied with the penalisation_factor.
Warning
The derived class should overwrite any data in prior_gradient.
Implemented in stir::CudaGibbsPenalty< elemT, PotentialT >, stir::CudaRelativeDifferencePrior< elemT >, stir::FilterRootPrior< DataT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::ParametricQuadraticPrior< TargetT >, stir::PLSPrior< elemT >, stir::QuadraticPrior< float >, and stir::RelativeDifferencePrior< elemT >.
Referenced by stir::GeneralisedPriorTests::test_Hessian_against_numerical().
compute_gradient_times_input()
template<typename DataT> double stir::GeneralisedPrior< TargetT >::compute_gradient_times_input (const DataT & input, const DataT & current_estimate) virtual
compute the dot product of the gradient of the log of the prior function at the current_estimate with input
Default implementation just call error(). This function needs to be overridden by the derived class. The gradient is already multiplied with the penalisation_factor.
Warning
The derived class should return the dot product of the gradient with input. This function is expected to be more efficient than computing the gradient and then taking the dot product.
Reimplemented in stir::CudaGibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, and stir::GibbsPenalty< elemT, PotentialT >.
References compute_gradient_times_input(), and stir::error().
Referenced by compute_gradient_times_input().
compute_Hessian()
template<typename DataT> void stir::GeneralisedPrior< TargetT >::compute_Hessian (DataT & prior_Hessian_for_single_densel, const BasicCoordinate< 3, int > & coords, const DataT & current_image_estimate) const virtual
This computes a single row of the Hessian.
Default implementation just call error(). This function needs to be overridden by the derived class.
The method computes a row (i.e. at a densel/voxel, indicated by coords) of the Hessian at current_estimate. Note that a row corresponds to an object of DataT. The method (as implemented in derived classes) should store the result in prior_Hessian_for_single_densel.
Reimplemented in stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, and stir::RelativeDifferencePrior< elemT >.
References compute_Hessian(), stir::error(), and is_convex().
Referenced by compute_Hessian(), and stir::GeneralisedPriorTests::test_Hessian_against_numerical().
compute_Hessian_diagonal()
template<typename DataT> void stir::GeneralisedPrior< TargetT >::compute_Hessian_diagonal (DataT & Hessian_diagonal, const DataT & current_estimate) const virtual
This computes the diagonal of the Hessian of the log of the prior function at the current_estimate and stores it in Hessian_diagonal.
The Hessian diagonal is already multiplied with the penalisation_factor. Default implementation just call error(). This function needs to be overridden by the derived class.
Warning
The derived class should overwrite any data in Hessian_diagonal.
Reimplemented in stir::CudaGibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, and stir::GibbsPenalty< elemT, PotentialT >.
References compute_Hessian_diagonal(), and stir::error().
Referenced by compute_Hessian_diagonal().
add_multiplication_with_approximate_Hessian()
template<typename DataT> void stir::GeneralisedPrior< TargetT >::add_multiplication_with_approximate_Hessian (DataT & output, const DataT & input) const virtual
This should compute the multiplication of the Hessian with a vector and add it to output.
Default implementation just call error(). This function needs to be overridden by the derived class. This method assumes that the hessian of the prior is 1 and hence the function quadratic. Instead, accumulate_Hessian_times_input() should be used. This method remains for backwards comparability.
Warning
The derived class should accumulate in output.
Reimplemented in stir::RelativeDifferencePrior< elemT >.
References add_multiplication_with_approximate_Hessian(), and stir::error().
Referenced by add_multiplication_with_approximate_Hessian().
accumulate_Hessian_times_input()
template<typename DataT> void stir::GeneralisedPrior< TargetT >::accumulate_Hessian_times_input (DataT & output, const DataT & current_estimate, const DataT & input) const virtual
This should compute the multiplication of the Hessian with a vector and add it to output.
Default implementation just call error(). This function needs to be overridden by the derived class.
Warning
The derived class should accumulate in output.
Reimplemented in stir::CudaGibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, and stir::RelativeDifferencePrior< elemT >.
References accumulate_Hessian_times_input().
Referenced by accumulate_Hessian_times_input(), and stir::GeneralisedPriorTests::test_Hessian_convexity_configuration().
set_penalisation_factor()
template<typename elemT> void stir::GeneralisedPrior< elemT >::set_penalisation_factor (float new_penalisation_factor) inline
Warning
Currently we allow the penalisation factor to be set after calling set_up().
References set_penalisation_factor().
Referenced by set_penalisation_factor(), stir::GeneralisedPriorTests::test_Hessian_convexity(), and stir::GeneralisedPriorTests::test_Hessian_convexity_configuration().
set_up()
template<typename DataT> Succeeded stir::GeneralisedPrior< TargetT >::set_up (shared_ptr< const DataT > const & target_sptr) virtual
Has to be called before using this object.
Reimplemented in stir::CudaGibbsPenalty< elemT, PotentialT >, stir::CudaRelativeDifferencePrior< elemT >, stir::FilterRootPrior< DataT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::PLSPrior< elemT >, and stir::RelativeDifferencePrior< elemT >.
References set_up().
Referenced by stir::GeneralisedPriorTests::run_tests_for_objective_function(), stir::FilterRootPrior< DataT >::set_up(), and set_up().
is_convex()
template<typename DataT> virtual bool stir::GeneralisedPrior< DataT >::is_convex () const pure virtual
Indicates if the prior is a smooth convex function.
If true, the prior is expected to have 0th, 1st and 2nd order behaviour implemented.
Implemented in stir::FilterRootPrior< DataT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::LogcoshPrior< elemT >, stir::PLSPrior< elemT >, stir::QuadraticPrior< elemT >, stir::QuadraticPrior< float >, and stir::RelativeDifferencePrior< elemT >.
Referenced by compute_Hessian(), stir::GeneralisedPriorTests::test_Hessian_against_numerical(), and stir::GeneralisedPriorTests::test_Hessian_convexity().
set_defaults()
template<typename TargetT> void stir::GeneralisedPrior< TargetT >::set_defaults () override protected virtual
sets value for penalisation factor
Has to be called by set_defaults in the leaf-class
Reimplemented from stir::ParsingObject.
Reimplemented in stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::LogcoshPrior< elemT >, stir::ParametricQuadraticPrior< TargetT >, stir::PLSPrior< elemT >, stir::QuadraticPrior< elemT >, stir::QuadraticPrior< float >, and stir::RelativeDifferencePrior< elemT >.
References set_defaults().
Referenced by set_defaults().
initialise_keymap()
template<typename TargetT> void stir::GeneralisedPrior< TargetT >::initialise_keymap () override protected virtual
sets key for penalisation factor
Has to be called by initialise_keymap in the leaf-class
Reimplemented from stir::ParsingObject.
Reimplemented in stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::LogcoshPrior< elemT >, stir::ParametricQuadraticPrior< TargetT >, stir::PLSPrior< elemT >, stir::QuadraticPrior< elemT >, stir::QuadraticPrior< float >, and stir::RelativeDifferencePrior< elemT >.
References initialise_keymap().
Referenced by initialise_keymap().
check()
template<typename DataT> void stir::GeneralisedPrior< TargetT >::check (DataT const & current_estimate) const protected virtual
Check that the prior is ready to be used.
Reimplemented in stir::FilterRootPrior< DataT >, stir::GibbsPenalty< elemT, potentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::GibbsPenalty< elemT, PotentialT >, stir::PLSPrior< elemT >, and stir::RelativeDifferencePrior< elemT >.
References check().
Referenced by stir::FilterRootPrior< DataT >::check(), and check().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/GeneralisedPrior.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/GeneralisedPrior.inl