STIR: stir::TrivialDataSymmetriesForViewSegmentNumbers Class Reference
stir::TrivialDataSymmetriesForViewSegmentNumbers Class Reference
A class for encoding/finding NO symmetries. Works only on ViewSegmentNumbers (instead of Bin).
#include "stir/TrivialDataSymmetriesForViewSegmentNumbers.h"
Public Member Functions
DataSymmetriesForViewSegmentNumbers * clone () const override
void get_related_view_segment_numbers (std::vector< ViewSegmentNumbers > &, const ViewSegmentNumbers &v_s) const override
fills in a vector with all the view/segments that are related to 'v_s' (including itself)
int num_related_view_segment_numbers (const ViewSegmentNumbers &v_s) const override
returns the number of view_segment_numbers related to 'v_s'
bool find_basic_view_segment_numbers (ViewSegmentNumbers &v_s) const override
given an arbitrary view/segment, find the basic view/segment
Public Member Functions inherited from stir::DataSymmetriesForViewSegmentNumbers
bool operator== (const DataSymmetriesForViewSegmentNumbers &) const
Check equality.
bool operator!= (const DataSymmetriesForViewSegmentNumbers &) const
Check inequality.
std::size_t num_related_viewgram_indices (const ViewgramIndices &ind) const
virtual bool is_basic (const ViewSegmentNumbers &v_s) const
test if a view/segment is 'basic'
Additional Inherited Members
Protected Types inherited from stir::DataSymmetriesForViewSegmentNumbers
typedef DataSymmetriesForViewSegmentNumbers root_type
Detailed Description
A class for encoding/finding NO symmetries. Works only on ViewSegmentNumbers (instead of Bin).
This class is mainly useful if you need a DataSymmetriesForViewSegmentNumbers object (e.g. for RelatedViewgrams), but do not need/have projectors.
Member Function Documentation
clone()
DataSymmetriesForViewSegmentNumbers * stir::TrivialDataSymmetriesForViewSegmentNumbers::clone () const inline override virtual
Implements stir::DataSymmetriesForViewSegmentNumbers.
get_related_view_segment_numbers()
void stir::TrivialDataSymmetriesForViewSegmentNumbers::get_related_view_segment_numbers (std::vector< ViewSegmentNumbers > & , const ViewSegmentNumbers & v_s) const inline override virtual
fills in a vector with all the view/segments that are related to 'v_s' (including itself)
Implements stir::DataSymmetriesForViewSegmentNumbers.
References get_related_view_segment_numbers().
Referenced by get_related_view_segment_numbers().
num_related_view_segment_numbers()
int stir::TrivialDataSymmetriesForViewSegmentNumbers::num_related_view_segment_numbers (const ViewSegmentNumbers & v_s) const inline override virtual
returns the number of view_segment_numbers related to 'v_s'
The default implementation is in terms of get_related_view_segment_numbers, which will be slow of course
Reimplemented from stir::DataSymmetriesForViewSegmentNumbers.
References num_related_view_segment_numbers().
Referenced by num_related_view_segment_numbers().
find_basic_view_segment_numbers()
bool stir::TrivialDataSymmetriesForViewSegmentNumbers::find_basic_view_segment_numbers (ViewSegmentNumbers & v_s) const inline override virtual
given an arbitrary view/segment, find the basic view/segment
in this class, v_s is unchanged, and the return value is always false. 'v_s' is changed (i.e. it was NOT a basic view/segment).
Implements stir::DataSymmetriesForViewSegmentNumbers.
References find_basic_view_segment_numbers().
Referenced by find_basic_view_segment_numbers().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/TrivialDataSymmetriesForViewSegmentNumbers.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/TrivialDataSymmetriesForViewSegmentNumbers.inl