STIR: stir::GeneralisedObjectiveFunction< TargetT > Class Template Reference
stir::GeneralisedObjectiveFunction< TargetT > Class Template Reference abstract
STIR » STIR library » Reconstruction building blocks » Objective functions for iterative estimation of variables
A base class for 'generalised' objective functions, i.e. objective functions for which at least a 'gradient' is defined.
#include "stir/recon_buildblock/GeneralisedObjectiveFunction.h"
Public Member Functions
virtual TargetT * construct_target_ptr () const =0
Creates a suitable target as determined by the parameters.
virtual Succeeded set_up (shared_ptr< TargetT > const &target_sptr)
Has to be called before using this object.
virtual void compute_sub_gradient (TargetT &gradient, const TargetT &current_estimate, const int subset_num)
Compute the subset-gradient of the objective function at current_estimate.
virtual void compute_sub_gradient_without_penalty (TargetT &gradient, const TargetT &current_estimate, const int subset_num)=0
This should compute the subset-gradient of the unregularised objective function at current_estimate.
virtual void compute_gradient (TargetT &gradient, const TargetT &current_estimate)
Compute the gradient of the objective function at the current_estimate.
virtual void compute_gradient_without_penalty (TargetT &gradient, const TargetT &current_estimate)
Compute the gradient of the unregularised objective function at the current_estimate.
virtual double compute_objective_function_without_penalty (const TargetT &current_estimate, const int subset_num)
Compute the value of the unregularised sub-objective function at the current_estimate.
virtual double compute_objective_function_without_penalty (const TargetT &current_estimate)
Compute the value of the unregularised objective function at the current_estimate.
double compute_penalty (const TargetT &current_estimate, const int subset_num)
Compute the value of the sub-penalty at the current_estimate.
double compute_penalty (const TargetT &current_estimate)
Compute the value of the penalty at the current_estimate.
double compute_objective_function (const TargetT &current_estimate, const int subset_num)
Compute the value of the sub-objective function at the current_estimate.
double compute_objective_function (const TargetT &current_estimate)
Compute the value of the objective function at the current_estimate.
double compute_value (const TargetT &current_estimate)
Alias for compute_objective_function(const TargetT&)
virtual void fill_nonidentifiable_target_parameters (TargetT &target, const float value) const
Fill any elements that we cannot estimate with a fixed value.
multiplication with approximate (sub)Hessian
Succeeded add_multiplication_with_approximate_sub_Hessian_without_penalty (TargetT &output, const TargetT &input, const int subset_num) const
Functions that multiply the approximate (sub)Hessian with a \'vector\'.
Succeeded add_multiplication_with_approximate_sub_Hessian (TargetT &output, const TargetT &input, const int subset_num) const
Succeeded add_multiplication_with_approximate_Hessian_without_penalty (TargetT &output, const TargetT &input) const
Succeeded add_multiplication_with_approximate_Hessian (TargetT &output, const TargetT &input) const
Public Member Functions inherited from stir::RegisteredObjectBase
virtual std::string get_registered_name () const =0
Returns the name of the type of the object.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
multiplication (sub)Hessian times input
int num_subsets
bool already_set_up
shared_ptr< GeneralisedPrior< TargetT > > prior_sptr
Succeeded accumulate_Hessian_times_input (TargetT &output, const TargetT &current_image_estimate, const TargetT &input) const
Functions that multiply the True (sub)Hessian with a \'vector\'.
Succeeded accumulate_Hessian_times_input_without_penalty (TargetT &output, const TargetT &current_image_estimate, const TargetT &input) const
Succeeded accumulate_sub_Hessian_times_input (TargetT &output, const TargetT &current_image_estimate, const TargetT &input, const int subset_num) const
Succeeded accumulate_sub_Hessian_times_input_without_penalty (TargetT &output, const TargetT &current_image_estimate, const TargetT &input, const int subset_num) const
std::string get_objective_function_values_report (const TargetT &current_estimate)
Construct a string with info on the value of objective function with and without penalty.
int get_num_subsets () const
Return the number of subsets in-use.
virtual std::unique_ptr< ExamInfo > get_exam_info_uptr_for_target () const
virtual int set_num_subsets (const int num_subsets)=0
Attempts to change the number of subsets.
bool subsets_are_approximately_balanced () const
Checks of the current subset scheme is approximately balanced.
bool subsets_are_approximately_balanced (std::string &warning_message) const
Checks of the current subset scheme is approximately balanced and constructs a warning message.
bool prior_is_zero () const
check if the prior is set (or the penalisation factor is 0)
GeneralisedPrior< TargetT > *const get_prior_ptr () const
Read-only access to the prior.
shared_ptr< GeneralisedPrior< TargetT > > get_prior_sptr ()
void set_prior_sptr (const shared_ptr< GeneralisedPrior< TargetT > > &)
Change the prior.
virtual void set_input_data (const shared_ptr< ExamData > &)=0
set_input_data
virtual const ExamData & get_input_data () const =0
get input data
virtual void set_additive_proj_data_sptr (const shared_ptr< ExamData > &)=0
set_additive_proj_data_sptr
virtual void set_normalisation_sptr (const shared_ptr< BinNormalisation > &)=0
set_normalisation_sptr
void set_defaults () override
sets any default values
void initialise_keymap () override
sets parsing keys
virtual bool actual_subsets_are_approximately_balanced (std::string &warning_message) const =0
Implementation of function that checks subset balancing.
virtual double actual_compute_objective_function_without_penalty (const TargetT &current_estimate, const int subset_num)=0
Implementation of function that computes the objective function for the current subset.
virtual Succeeded actual_add_multiplication_with_approximate_sub_Hessian_without_penalty (TargetT &output, const TargetT &input, const int subset_num) const
Implementation of the function that multiplies the approximate sub-Hessian with a vector.
virtual Succeeded actual_accumulate_sub_Hessian_times_input_without_penalty (TargetT &output, const TargetT &current_image_estimate, const TargetT &input, const int subset_num) const
Implementation of the function computes the sub-Hessian and multiplies by a vector.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredObject< GeneralisedObjectiveFunction< TargetT > >
static GeneralisedObjectiveFunction< TargetT > * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static GeneralisedObjectiveFunction< TargetT > * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< GeneralisedObjectiveFunction< TargetT > >
typedef GeneralisedObjectiveFunction< TargetT > *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
virtual bool post_processing ()
This will be called at the end of the parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< GeneralisedObjectiveFunction< TargetT > >
static RegistryType & registry ()
Static function returning the registry.
KeyParser parser
Detailed Description
template<typename TargetT>
class stir::GeneralisedObjectiveFunction< TargetT >
A base class for 'generalised' objective functions, i.e. objective functions for which at least a 'gradient' is defined.
Some iterative algorithms use an 'objective function' only in a loose sense. They might for instance allow generalisations which no longer optimise a function. For example in the case of PoissonLogLikelihoodWithLinearModelForMeanAndProjData with non-matching forward and back projectors, the 'gradient' that is computed is generally not the gradient of the log-likelihood that corresponds to the forward projector. However, one hopes that it still points towards the optimum.
Often, one includes a penalty (or prior) in the objective function. This class uses a GeneralisedPrior object for this. Note that we use the convention that the objective function is maximised. The penalty is expected to be a function that increases with higher penalty, so it will be subtracted from the unregularised case.
In tomography, we often use subsets, where the objective function is written as a sum of sub-objective functions. This class has some subset functionality. When using subsets, the penalty will be distributed evenly over all subsets. While this increases the computational cost, it makes the subsets more 'balanced' which is best for most algorithms.
See also
IterativeReconstruction
Todo
Currently, there is subset code in both IterativeReconstruction and here. This is confusing and leads to repetition. It probably should all be moved here.
Parameters for parsing
; specify prior, see GeneralisedObjectiveFunction<TargetT> hierarchy for possible values
prior type :=
Member Function Documentation
construct_target_ptr()
template<typename TargetT> virtual TargetT * stir::GeneralisedObjectiveFunction< TargetT >::construct_target_ptr () const pure virtual
Creates a suitable target as determined by the parameters.
Warning
This should not check already_set_up (unfortunately), as it is currently called in Reconstruction::reconstruct() before calling set_up().
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
References compute_sub_gradient(), and set_up().
set_up()
template<typename TargetT> Succeeded stir::GeneralisedObjectiveFunction< TargetT >::set_up (shared_ptr< TargetT > const & target_sptr) virtual
Has to be called before using this object.
Reimplemented in stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, and stir::SumOfGeneralisedObjectiveFunctions< ObjFuncT, TargetT, ParentT >.
References stir::error(), set_up(), and stir::warning().
Referenced by construct_target_ptr(), set_up(), and stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::set_up().
compute_sub_gradient()
template<typename TargetT> void stir::GeneralisedObjectiveFunction< TargetT >::compute_sub_gradient (TargetT & gradient, const TargetT & current_estimate, const int subset_num) virtual
Compute the subset-gradient of the objective function at current_estimate.
The subset-gradient is the gradient of the objective function restricted to the subset specified. What this means depends on how this function is implemented later on in the hierarchy.
Computed as the difference of compute_sub_gradient_without_penalty and get_prior_ptr()->compute_gradient()/num_subsets.
Warning
Any data in gradient will be overwritten.
References compute_sub_gradient().
Referenced by compute_sub_gradient(), and construct_target_ptr().
compute_sub_gradient_without_penalty()
template<typename TargetT> virtual void stir::GeneralisedObjectiveFunction< TargetT >::compute_sub_gradient_without_penalty (TargetT & gradient, const TargetT & current_estimate, const int subset_num) pure virtual
This should compute the subset-gradient of the unregularised objective function at current_estimate.
Warning
The derived class should overwrite any data in gradient.
Implemented in stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, and stir::SumOfGeneralisedObjectiveFunctions< ObjFuncT, TargetT, ParentT >.
References compute_gradient(), compute_gradient_without_penalty(), compute_objective_function(), compute_objective_function_without_penalty(), and compute_penalty().
Referenced by compute_gradient_without_penalty().
compute_gradient()
template<typename TargetT> void stir::GeneralisedObjectiveFunction< TargetT >::compute_gradient (TargetT & gradient, const TargetT & current_estimate) virtual
Compute the gradient of the objective function at the current_estimate.
Computed as the difference of compute_gradient_without_penalty and get_prior_ptr()->compute_gradient().
Warning
Any data in gradient will be overwritten.
References compute_gradient(), compute_gradient_without_penalty(), and prior_is_zero().
Referenced by compute_gradient(), and compute_sub_gradient_without_penalty().
compute_gradient_without_penalty()
template<typename TargetT> void stir::GeneralisedObjectiveFunction< TargetT >::compute_gradient_without_penalty (TargetT & gradient, const TargetT & current_estimate) virtual
Compute the gradient of the unregularised objective function at the current_estimate.
Computed by summing subset-gradients.
Warning
Any data in gradient will be overwritten.
References compute_gradient_without_penalty(), compute_sub_gradient_without_penalty(), and get_num_subsets().
Referenced by compute_gradient(), compute_gradient_without_penalty(), and compute_sub_gradient_without_penalty().
compute_objective_function_without_penalty() [1/2]
template<typename TargetT> double stir::GeneralisedObjectiveFunction< TargetT >::compute_objective_function_without_penalty (const TargetT & current_estimate, const int subset_num) virtual
Compute the value of the unregularised sub-objective function at the current_estimate.
Implemented in terms of actual_compute_objective_function_without_penalty.
References actual_compute_objective_function_without_penalty(), compute_objective_function_without_penalty(), stir::error(), and get_num_subsets().
Referenced by compute_objective_function(), compute_objective_function(), compute_objective_function_without_penalty(), compute_objective_function_without_penalty(), compute_sub_gradient_without_penalty(), and get_objective_function_values_report().
compute_objective_function_without_penalty() [2/2]
template<typename TargetT> double stir::GeneralisedObjectiveFunction< TargetT >::compute_objective_function_without_penalty (const TargetT & current_estimate) virtual
Compute the value of the unregularised objective function at the current_estimate.
Computed by summing over all subsets.
References compute_objective_function_without_penalty(), and get_num_subsets().
compute_penalty() [1/2]
template<typename TargetT> double stir::GeneralisedObjectiveFunction< TargetT >::compute_penalty (const TargetT & current_estimate, const int subset_num)
Compute the value of the sub-penalty at the current_estimate.
As each subset contains the same penalty, this function returns the same as
compute_penalty(current_estimate)/num_subsets
Implemented in terms of GeneralisedPrior::compute_value.
See also
compute_objective_function(const TargetT&) for sign conventions.
References compute_penalty(), and get_num_subsets().
Referenced by compute_objective_function(), compute_penalty(), compute_penalty(), compute_sub_gradient_without_penalty(), and get_objective_function_values_report().
compute_penalty() [2/2]
template<typename TargetT> double stir::GeneralisedObjectiveFunction< TargetT >::compute_penalty (const TargetT & current_estimate)
Compute the value of the penalty at the current_estimate.
Implemented in terms of GeneralisedPrior::compute_value.
References compute_penalty(), and prior_is_zero().
compute_objective_function() [1/2]
template<typename TargetT> double stir::GeneralisedObjectiveFunction< TargetT >::compute_objective_function (const TargetT & current_estimate, const int subset_num)
Compute the value of the sub-objective function at the current_estimate.
Computed as the difference of compute_objective_function_without_penalty and compute_penalty.
References compute_objective_function(), and compute_objective_function_without_penalty().
Referenced by compute_objective_function(), compute_objective_function(), compute_sub_gradient_without_penalty(), and compute_value().
compute_objective_function() [2/2]
template<typename TargetT> double stir::GeneralisedObjectiveFunction< TargetT >::compute_objective_function (const TargetT & current_estimate)
Compute the value of the objective function at the current_estimate.
Computed as the difference of compute_objective_function_without_penalty and compute_penalty.
References compute_objective_function(), compute_objective_function_without_penalty(), and compute_penalty().
fill_nonidentifiable_target_parameters()
template<typename TargetT> virtual void stir::GeneralisedObjectiveFunction< TargetT >::fill_nonidentifiable_target_parameters (TargetT & target, const float value) const inline virtual
Fill any elements that we cannot estimate with a fixed value.
In many cases, it is easier to use a larger target than what we can actually estimate. For instance, using a rectangular image while we estimate only a circular region.
For some algorithms, it is important that the parameters that cannot be estimate are set to 0 (or some other value). For example, if the outer voxels contribute to the forward projection of an image, but not to a backprojection.
This function allows you to do that. Its default implementation is to do nothing. It is up to the derived class to implement this sensible.
Todo
The type of the value should really be derived from e.g. TargetT::full_iterator.
Reimplemented in stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >.
add_multiplication_with_approximate_sub_Hessian_without_penalty()
template<typename TargetT> Succeeded stir::GeneralisedObjectiveFunction< TargetT >::add_multiplication_with_approximate_sub_Hessian_without_penalty (TargetT & output, const TargetT & input, const int subset_num) const
Functions that multiply the approximate (sub)Hessian with a \'vector\'.
All these functions add their result to any existing data in output.
They all call actual_add_multiplication_with_approximate_sub_Hessian_without_penalty.
References add_multiplication_with_approximate_sub_Hessian_without_penalty(), stir::error(), and get_num_subsets().
Referenced by add_multiplication_with_approximate_sub_Hessian_without_penalty().
accumulate_Hessian_times_input()
template<typename TargetT> Succeeded stir::GeneralisedObjectiveFunction< TargetT >::accumulate_Hessian_times_input (TargetT & output, const TargetT & current_image_estimate, const TargetT & input) const
Functions that multiply the True (sub)Hessian with a \'vector\'.
All these functions add their result to any existing data in output.
They all call actual_accumulate_sub_Hessian_times_input_without_penalty.
References accumulate_Hessian_times_input(), and prior_is_zero().
Referenced by accumulate_Hessian_times_input().
set_num_subsets()
template<typename TargetT> virtual int stir::GeneralisedObjectiveFunction< TargetT >::set_num_subsets (const int num_subsets) pure virtual
Attempts to change the number of subsets.
Returns
The number of subsets that will be used later, which is not guaranteed to be what you asked for.
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >, and stir::SumOfGeneralisedObjectiveFunctions< ObjFuncT, TargetT, ParentT >.
References get_prior_ptr(), prior_is_zero(), set_prior_sptr(), and subsets_are_approximately_balanced().
subsets_are_approximately_balanced() [1/2]
template<typename TargetT> bool stir::GeneralisedObjectiveFunction< TargetT >::subsets_are_approximately_balanced () const
Checks of the current subset scheme is approximately balanced.
Balanced subsets means that the sub-gradients point all roughly in the same direction (at least when far from the optimum).
This function tests if this is approximately true, such that a reconstruction algorithm can either adapt or abort.
Implemented in terms of actual_subsets_are_approximately_balanced(std::string&).
References actual_subsets_are_approximately_balanced(), and subsets_are_approximately_balanced().
Referenced by stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::compute_sensitivities(), set_num_subsets(), subsets_are_approximately_balanced(), and subsets_are_approximately_balanced().
subsets_are_approximately_balanced() [2/2]
template<typename TargetT> bool stir::GeneralisedObjectiveFunction< TargetT >::subsets_are_approximately_balanced (std::string & warning_message) const
Checks of the current subset scheme is approximately balanced and constructs a warning message.
See also
subsets_are_approximately_balanced()
Parameters
warning_message A string variable. If the subsets are not (approx.) balanced, this function will append a warning message explaining why.
References actual_subsets_are_approximately_balanced(), stir::error(), and subsets_are_approximately_balanced().
get_prior_ptr()
template<typename TargetT> GeneralisedPrior< TargetT > *const stir::GeneralisedObjectiveFunction< TargetT >::get_prior_ptr () const
Read-only access to the prior.
Todo
It would be nicer to not return a pointer.
References get_prior_ptr().
Referenced by get_prior_ptr(), and set_num_subsets().
set_prior_sptr()
template<typename TargetT> void stir::GeneralisedObjectiveFunction< TargetT >::set_prior_sptr (const shared_ptr< GeneralisedPrior< TargetT > > & arg)
Change the prior.
Warning
You should call set_up() again after using this function.
References set_prior_sptr().
Referenced by stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests::run_tests(), set_num_subsets(), and set_prior_sptr().
set_input_data()
template<typename TargetT> virtual void stir::GeneralisedObjectiveFunction< TargetT >::set_input_data (const shared_ptr< ExamData > &) pure virtual
set_input_data
Author
Nikos Efthimiou
It can be used to set the data to be reconstructed within some other code, as opposed to via parsing.
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
get_input_data()
template<typename TargetT> virtual const ExamData & stir::GeneralisedObjectiveFunction< TargetT >::get_input_data () const pure virtual
get input data
Will throw an exception if it wasn't set first
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
set_additive_proj_data_sptr()
template<typename TargetT> virtual void stir::GeneralisedObjectiveFunction< TargetT >::set_additive_proj_data_sptr (const shared_ptr< ExamData > &) pure virtual
set_additive_proj_data_sptr
Author
Nikos Efthimiou
In the case the reconstruction process is called from another piece of code, the user should be able to set any additive sinogram
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
set_normalisation_sptr()
template<typename TargetT> virtual void stir::GeneralisedObjectiveFunction< TargetT >::set_normalisation_sptr (const shared_ptr< BinNormalisation > &) pure virtual
set_normalisation_sptr
Author
Nikos Efthimiou
In the case the reconstruction process is called from another piece of code, the user should be able to set any additive sinogram
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
References initialise_keymap(), and set_defaults().
set_defaults()
template<typename TargetT> void stir::GeneralisedObjectiveFunction< TargetT >::set_defaults () override protected virtual
sets any default values
Has to be called by set_defaults in the leaf-class
Reimplemented from stir::ParsingObject.
Reimplemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
References set_defaults().
Referenced by set_defaults(), stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::set_defaults(), and set_normalisation_sptr().
initialise_keymap()
template<typename TargetT> void stir::GeneralisedObjectiveFunction< TargetT >::initialise_keymap () override protected virtual
sets parsing keys
Has to be called by initialise_keymap in the leaf-class
Reimplemented from stir::ParsingObject.
Reimplemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMean< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeData< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
References initialise_keymap().
Referenced by initialise_keymap(), stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::initialise_keymap(), and set_normalisation_sptr().
actual_subsets_are_approximately_balanced()
template<typename TargetT> virtual bool stir::GeneralisedObjectiveFunction< TargetT >::actual_subsets_are_approximately_balanced (std::string & warning_message) const protected pure virtual
Implementation of function that checks subset balancing.
See also
subsets_are_approximately_balanced(std::string&)
Developer\'s note
The reason we have this function is that overloading subsets_are_approximately_balanced(std::string&) in a derived class would hide subsets_are_approximately_balanced().
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >, and stir::SumOfGeneralisedObjectiveFunctions< ObjFuncT, TargetT, ParentT >.
Referenced by subsets_are_approximately_balanced(), and subsets_are_approximately_balanced().
actual_compute_objective_function_without_penalty()
template<typename TargetT> virtual double stir::GeneralisedObjectiveFunction< TargetT >::actual_compute_objective_function_without_penalty (const TargetT & current_estimate, const int subset_num) protected pure virtual
Implementation of function that computes the objective function for the current subset.
See also
compute_objective_function_without_penalty(const Target&,const int)
Developer\'s note
The reason we have this function is that overloading a function in a derived class, hides all functions of the same name.
Implemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::SumOfGeneralisedObjectiveFunctions< ObjFuncT, TargetT, ParentT >.
References actual_accumulate_sub_Hessian_times_input_without_penalty(), and actual_add_multiplication_with_approximate_sub_Hessian_without_penalty().
Referenced by compute_objective_function_without_penalty().
actual_add_multiplication_with_approximate_sub_Hessian_without_penalty()
template<typename TargetT> Succeeded stir::GeneralisedObjectiveFunction< TargetT >::actual_add_multiplication_with_approximate_sub_Hessian_without_penalty (TargetT & output, const TargetT & input, const int subset_num) const protected virtual
Implementation of the function that multiplies the approximate sub-Hessian with a vector.
See also
multiplication_with_approximate_sub_Hessian_without_penalty(TargetT&,const TargetT&, const int).
Warning
The default implementation just calls error(). This behaviour has to be overloaded by the derived classes.
Developer\'s note
The reason we have this function is that overloading a function in a derived class, hides all functions of the same name.
Reimplemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
References actual_add_multiplication_with_approximate_sub_Hessian_without_penalty(), and stir::error().
Referenced by actual_add_multiplication_with_approximate_sub_Hessian_without_penalty(), and actual_compute_objective_function_without_penalty().
actual_accumulate_sub_Hessian_times_input_without_penalty()
template<typename TargetT> Succeeded stir::GeneralisedObjectiveFunction< TargetT >::actual_accumulate_sub_Hessian_times_input_without_penalty (TargetT & output, const TargetT & current_image_estimate, const TargetT & input, const int subset_num) const protected virtual
Implementation of the function computes the sub-Hessian and multiplies by a vector.
See also
accumulate_sub_Hessian_times_input_without_penalty(TargetT&,const TargetT&, TargetT&, const int).
Warning
The default implementation just calls error(). This behaviour has to be overloaded by the derived classes.
Developer\'s note
The reason we have this function is that overloading a function in a derived class, hides all functions of the same name.
Reimplemented in stir::PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< stir::DiscretisedDensity< 3, float > >, stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >, and stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< stir::DiscretisedDensity< 3, float > >.
References actual_accumulate_sub_Hessian_times_input_without_penalty(), and stir::error().
Referenced by actual_accumulate_sub_Hessian_times_input_without_penalty(), and actual_compute_objective_function_without_penalty().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/GeneralisedObjectiveFunction.h
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/GeneralisedObjectiveFunction.cxx