STIR: stir::AbsTimeIntervalFromECAT7ACF Class Reference
stir::AbsTimeIntervalFromECAT7ACF Class Reference
STIR » STIR library » Basic building blocks
class for specifying a time interval via an ECAT7 .a file
#include "stir_experimental/AbsTimeIntervalFromECAT7ACF.h"
Public Member Functions
AbsTimeIntervalFromECAT7ACF ()
default constructor sets duration to -1 (i.e. ill-defined)
AbsTimeIntervalFromECAT7ACF (const std::string &filename, const double duration_in_secs)
read info from ECAT7 file
Public Member Functions inherited from stir::RegisteredParsingObject< AbsTimeIntervalFromECAT7ACF, AbsTimeInterval, AbsTimeInterval >
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::AbsTimeInterval
AbsTimeInterval (double start_time_in_secs_since_1970, double end_time_in_secs_since_1970)
double get_start_time_in_secs_since_1970 () const
double get_end_time_in_secs_since_1970 () const
double get_duration_in_secs () const
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
void ask_parameters ()
bool parse (std::istream &f)
bool parse (const char *const filename)
Static Public Attributes
static const char *const registered_name = "from ECAT7 ACF"
Name which will be used when parsing a AbsTimeInterval object.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< AbsTimeIntervalFromECAT7ACF, AbsTimeInterval, AbsTimeInterval >
static AbsTimeInterval * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< AbsTimeInterval >
static AbsTimeInterval * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static AbsTimeInterval * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< AbsTimeInterval >
typedef AbsTimeInterval *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Protected Member Functions inherited from stir::ParsingObject
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< AbsTimeInterval >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::AbsTimeInterval
double _start_time_in_secs_since_1970
double _end_time_in_secs_since_1970
Protected Attributes inherited from stir::ParsingObject
KeyParser parser
Detailed Description
class for specifying a time interval via an ECAT7 .a file
The ECAT7 header for a .a file does not record the scan duration, but only the start time of the transmission scan. So, we have to explicitly ask for the duration.
Constructor & Destructor Documentation
AbsTimeIntervalFromECAT7ACF()
stir::AbsTimeIntervalFromECAT7ACF::AbsTimeIntervalFromECAT7ACF (const std::string & filename, const double duration_in_secs)
read info from ECAT7 file
will call error() if something goes wrong
References stir::KeyParser::add_key(), stir::KeyParser::add_start_key(), stir::KeyParser::add_stop_key(), stir::error(), and stir::warning().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir_experimental/AbsTimeIntervalFromECAT7ACF.h
/home/sirfuser/devel/STIRdistrib/STIR/src/experimental/buildblock/AbsTimeIntervalFromECAT7ACF.cxx