STIR: stir::HighResWallClockTimer Class Reference
stir::HighResWallClockTimer Class Reference
High-resolution timer.
#include "stir/HighResWallClockTimer.h"
Public Member Functions
HighResWallClockTimer (void)
Create a timer.
virtual ~HighResWallClockTimer (void)
Destroy a timer.
void start (bool bReset=false)
Start a timer.
void stop (void)
Stop a running timer.
void reset (void)
Reset a timer.
bool is_running (void)
Check if a timer is running.
int get_sec (void)
Returns the number of whole seconds elapsed.
int get_nanosec (void)
Returns the number of nanoseconds that elapsed on top of whatever get_sec() returned.
double value (void)
Returns the elapsed time (in seconds)
Static Public Member Functions
static int get_resolution_in_nanosecs (void)
Attempts to guess the timer resolution.
Detailed Description
High-resolution timer.
This timer measures wall-clock time. Implementation is OS specific to try to use high-resolution timers. It is not derived from stir::Timer to avoid the overhead of calling a virtual function.
Typical usage:
HighResWallClockTimer t;
t.start();
do_something();
t.stop();
cout << "do_something took " << t.value() << " seconds" << endl;
t.start();
do_something_else();
t.stop();
cout << "total wall-clock time: " << t.value() << " seconds" << endl;
You have to call stop() before getting the value. You have to call reset() if you wish to use the same timer to measure several separate time intervals, otherwise the time will be accumulated.
Constructor & Destructor Documentation
HighResWallClockTimer()
stir::HighResWallClockTimer::HighResWallClockTimer (void) inline
Create a timer.
The timer is not started, and elapsed time is set to zero.
References reset().
~HighResWallClockTimer()
stir::HighResWallClockTimer::~HighResWallClockTimer (void) inline virtual
Destroy a timer.
The timer must not be running.
Member Function Documentation
start()
void stir::HighResWallClockTimer::start (bool bReset = false) inline
Start a timer.
Parameters
bReset indicates whether the elapsed time should be reset before the timer is started. The timer must not be running.
References reset().
Referenced by stir::LM_distributable_computation(), distributed::receive_and_construct_exam_and_proj_data_info_ptr(), distributed::receive_and_construct_viewgram(), distributed::receive_and_initialize_projectors(), distributed::receive_and_set_image_parameters(), distributed::receive_bool_value(), distributed::receive_double_values(), distributed::receive_image_values_and_fill_image_ptr(), distributed::receive_int_value(), distributed::receive_int_values(), distributed::receive_string(), distributed::reduce_output_image(), distributed::reduce_received_output_image(), stir::BlocksTests::run_tests(), distributed::send_bool_value(), distributed::send_double_values(), distributed::send_exam_and_proj_data_info(), distributed::send_image_estimate(), distributed::send_image_parameters(), distributed::send_int_value(), distributed::send_int_values(), distributed::send_string(), distributed::send_viewgram(), and stir::ScatterSimulation::set_use_cache().
stop()
void stir::HighResWallClockTimer::stop (void) inline
Stop a running timer.
When a timer is stopped (=not running), get_sec(), get_nanosec(), and value() can be used to obtain elapsed time.
References get_resolution_in_nanosecs().
Referenced by distributed::receive_and_construct_exam_and_proj_data_info_ptr(), distributed::receive_and_construct_viewgram(), distributed::receive_and_initialize_projectors(), distributed::receive_and_set_image_parameters(), distributed::receive_bool_value(), distributed::receive_double_values(), distributed::receive_image_values_and_fill_image_ptr(), distributed::receive_int_value(), distributed::receive_int_values(), distributed::receive_string(), distributed::reduce_output_image(), distributed::reduce_received_output_image(), stir::BlocksTests::run_tests(), distributed::send_bool_value(), distributed::send_double_values(), distributed::send_exam_and_proj_data_info(), distributed::send_image_estimate(), distributed::send_image_parameters(), distributed::send_int_value(), distributed::send_int_values(), distributed::send_string(), distributed::send_viewgram(), and stir::ScatterSimulation::set_use_cache().
reset()
void stir::HighResWallClockTimer::reset (void) inline
Reset a timer.
Sets the elapsed time to zero. The timer must not be running.
Referenced by HighResWallClockTimer(), distributed::receive_and_construct_exam_and_proj_data_info_ptr(), distributed::receive_and_construct_viewgram(), distributed::receive_and_initialize_projectors(), distributed::receive_and_set_image_parameters(), distributed::receive_bool_value(), distributed::receive_double_values(), distributed::receive_image_values_and_fill_image_ptr(), distributed::receive_int_value(), distributed::receive_int_values(), distributed::receive_string(), distributed::reduce_output_image(), distributed::reduce_received_output_image(), stir::BlocksTests::run_tests(), distributed::send_bool_value(), distributed::send_double_values(), distributed::send_exam_and_proj_data_info(), distributed::send_image_estimate(), distributed::send_image_parameters(), distributed::send_int_value(), distributed::send_int_values(), distributed::send_string(), distributed::send_viewgram(), and start().
is_running()
bool stir::HighResWallClockTimer::is_running (void) inline
Check if a timer is running.
Returns true if the timer is running, or false otherwise
get_sec()
int stir::HighResWallClockTimer::get_sec (void) inline
Returns the number of whole seconds elapsed.
The timer must not be running
Referenced by value().
get_nanosec()
int stir::HighResWallClockTimer::get_nanosec (void) inline
Returns the number of nanoseconds that elapsed on top of whatever get_sec() returned.
The timer must not be running
Referenced by value().
value()
double stir::HighResWallClockTimer::value (void) inline
Returns the elapsed time (in seconds)
The timer must not be running
References get_nanosec(), and get_sec().
Referenced by distributed::receive_and_construct_exam_and_proj_data_info_ptr(), distributed::receive_and_construct_viewgram(), distributed::receive_and_initialize_projectors(), distributed::receive_and_set_image_parameters(), distributed::receive_bool_value(), distributed::receive_double_values(), distributed::receive_image_values_and_fill_image_ptr(), distributed::receive_int_value(), distributed::receive_int_values(), distributed::receive_string(), distributed::reduce_output_image(), distributed::reduce_received_output_image(), stir::BlocksTests::run_tests(), distributed::send_bool_value(), distributed::send_double_values(), distributed::send_exam_and_proj_data_info(), distributed::send_image_estimate(), distributed::send_image_parameters(), distributed::send_int_value(), distributed::send_int_values(), distributed::send_string(), distributed::send_viewgram(), and stir::ScatterSimulation::set_use_cache().
get_resolution_in_nanosecs()
int stir::HighResWallClockTimer::get_resolution_in_nanosecs (void) inline static
Attempts to guess the timer resolution.
get_resolution_in_nanosecs() is by no means accurate. The only thing that is guranteed is that timer resolution is not less than the value returned by get_resolution_in_nanosecs().
On Win32, returns more or less precise resolution (can be slightly rounded if the actual resolution can't be expressed as an integer number of nanoseconds)
Returns
Estimated timer resolution (in nanoseconds)
Referenced by stop().
The documentation for this class was generated from the following file:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/HighResWallClockTimer.h