STIR: stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests Class Reference
stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests Class Reference
STIR » Test code for STIR » Tests of the basic building blocks
Test class for PoissonLogLikelihoodWithLinearModelForMeanAndProjData.
Public Member Functions
PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests (char const *const proj_data_filename=0, char const *const density_filename=0)
Constructor that can take some input data to run the test with.
void construct_input_data (shared_ptr< target_type > &density_sptr, const bool TOF_or_not)
void run_tests () override
Function (to be overloaded) which does the actual tests.
Public Member Functions inherited from stir::ObjectiveFunctionTests< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > >, DiscretisedDensity< 3, float > >
virtual Succeeded test_gradient (const std::string &test_name, PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > > &objective_function, DiscretisedDensity< 3, float > &target, const float eps, const bool full_gradient=true)
Test the gradient of the objective function by comparing to the numerical gradient via perturbation.
virtual Succeeded test_Hessian (const std::string &test_name, PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > > &objective_function, const DiscretisedDensity< 3, float > &target, const float eps)
Test the accumulate_Hessian_times_input of the objective function by comparing to the numerical result via perturbation.
virtual Succeeded test_Hessian_concavity (const std::string &test_name, PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > > &objective_function, const DiscretisedDensity< 3, float > &target, const float mult_factor=1.F)
Test the Hessian of the objective function by testing the (mult_factor * x^T Hx > 0) condition.
Public Member Functions inherited from stir::RunTests
RunTests (const double tolerance=1E-4)
Default constructor.
virtual ~RunTests ()
Destructor, outputs a diagnostic message.
bool is_everything_ok () const
Returns if all checks were fine upto now.
int main_return_value () const
Handy return value for a main() function.
void set_tolerance (const double tolerance)
Set value used in floating point comparisons (see check_* functions)
double get_tolerance () const
Get value used in floating point comparisons (see check_* functions)
bool check (const bool, const std::string &str="")
Tests if true, str can be used to tell what you are testing.
template<class T1 , class T2 >
bool check_if_less (T1 a, T2 b, const std::string &str="")
check if a<b
bool check_if_equal (const std::string &a, const std::string &b, const std::string &str="")
bool check_if_equal (const double a, const double b, const std::string &str="")
bool check_if_equal (const short a, const short b, const std::string &str="")
bool check_if_equal (const unsigned short a, const unsigned short b, const std::string &str="")
bool check_if_equal (const int a, const int b, const std::string &str="")
bool check_if_equal (const unsigned int a, const unsigned int b, const std::string &str="")
bool check_if_equal (const long a, const long b, const std::string &str="")
bool check_if_equal (const unsigned long a, const unsigned long b, const std::string &str="")
bool check_if_equal (const Bin &a, const Bin &b, const std::string &str="")
template<class T >
bool check_if_equal (const DetectionPosition< T > &a, const DetectionPosition< T > &b, const std::string &str="")
template<class T >
bool check_if_equal (const std::complex< T > a, const std::complex< T > b, const std::string &str="")
check equality by calling check_if_equal on real and imaginary parts
template<class T >
bool check_if_equal (const VectorWithOffset< T > &t1, const VectorWithOffset< T > &t2, const std::string &str="")
check equality by comparing ranges and calling check_if_equal on all elements
template<class T >
bool check_if_equal (const std::vector< T > &t1, const std::vector< T > &t2, const std::string &str="")
check equality by comparing size and calling check_if_equal on all elements
bool check_if_equal (const ProjDataInMemory &t1, const ProjDataInMemory &t2, const std::string &str="")
template<int n>
bool check_if_equal (const IndexRange< n > &t1, const IndexRange< n > &t2, const std::string &str="")
template<int num_dimensions, class coordT >
bool check_if_equal (const BasicCoordinate< num_dimensions, coordT > &a, const BasicCoordinate< num_dimensions, coordT > &b, const std::string &str="")
check equality by comparing norm(a-b) with tolerance
bool check_if_zero (const double a, const std::string &str="")
bool check_if_zero (const short a, const std::string &str="")
bool check_if_zero (const unsigned short a, const std::string &str="")
bool check_if_zero (const int a, const std::string &str="")
bool check_if_zero (const unsigned int a, const std::string &str="")
bool check_if_zero (const long a, const std::string &str="")
bool check_if_zero (const unsigned long a, const std::string &str="")
template<class T >
bool check_if_zero (const VectorWithOffset< T > &t, const std::string &str="")
use check_if_zero on all elements
template<int num_dimensions, class coordT >
bool check_if_zero (const BasicCoordinate< num_dimensions, coordT > &a, const std::string &str="")
compare norm with tolerance
Protected Member Functions
void run_tests_for_objective_function (objective_function_type &objective_function, target_type &target)
run the test
void test_approximate_Hessian_concavity (objective_function_type &objective_function, target_type &target)
Test the approximate Hessian of the objective function by testing the (x^T Hx > 0) condition.
Protected Member Functions inherited from stir::ObjectiveFunctionTests< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > >, DiscretisedDensity< 3, float > >
virtual shared_ptr< const DiscretisedDensity< 3, float > > construct_increment (const DiscretisedDensity< 3, float > &target, const float eps) const
Construct small increment for target.
Protected Member Functions inherited from stir::RunTests
template<class T >
bool check_if_equal_generic (const T &a, const T &b, const std::string &str)
function that is called by some check_if_equal implementations. It just uses operator!=
template<class T >
bool check_if_zero_generic (T a, const std::string &str)
function that is called by some check_if_zero implementations. It just uses operator!=
Protected Attributes
char const * proj_data_filename
char const * density_filename
shared_ptr< ProjData > proj_data_sptr
shared_ptr< ProjData > mult_proj_data_sptr
shared_ptr< ProjData > add_proj_data_sptr
shared_ptr< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< target_type > > objective_function_sptr
Protected Attributes inherited from stir::RunTests
double tolerance
tolerance for comparisons with real values
bool everything_ok
variable storing current status
Additional Inherited Members
Public Types inherited from stir::ObjectiveFunctionTests< PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > >, DiscretisedDensity< 3, float > >
typedef PoissonLogLikelihoodWithLinearModelForMeanAndProjData< DiscretisedDensity< 3, float > > objective_function_type
typedef DiscretisedDensity< 3, float > target_type
Detailed Description
Test class for PoissonLogLikelihoodWithLinearModelForMeanAndProjData.
This is a somewhat preliminary implementation of a test that compares the result of GeneralisedObjectiveFunction::compute_gradient with a numerical gradient computed by using the GeneralisedObjectiveFunction::compute_objective_function() function.
The trouble with this is that compute the gradient voxel by voxel is obviously terribly slow. A solution (for the test) would be to compute it only in a subset of voxels or so. We'll leave this for later.
Note that the test only works if the objective function is well-defined. For example, if certain projections are non-zero, while the model estimates them to be zero, the Poisson objective function is in theory infinite. PoissonLogLikelihoodWithLinearModelForMeanAndProjData uses some thresholds to try to avoid overflow, but if there are too many of these bins, the total objective function will become infinite. The numerical gradient then becomes ill-defined (even in voxels that do not contribute to these bins).
Constructor & Destructor Documentation
PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests()
stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests (char const *const proj_data_filename = 0, char const *const density_filename = 0)
Constructor that can take some input data to run the test with.
This makes it possible to run the test with your own data. However, beware that it is very easy to set up a very long computation. See also the note about non-zero measured bins.
Todo:
it would be better to parse an objective function. That would allow us to set all parameters from the command line.
Member Function Documentation
run_tests()
void stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests::run_tests () override virtual
Function (to be overloaded) which does the actual tests.
This function is expected to do a series of calls to check(), check_if_equal() etc.
Implements stir::RunTests.
References stir::RunTests::check(), stir::IterativeReconstruction< TargetT >::get_initial_data_ptr(), and run_tests_for_objective_function().
test_approximate_Hessian_concavity()
void stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests::test_approximate_Hessian_concavity (objective_function_type & objective_function, target_type & target) protected
Test the approximate Hessian of the objective function by testing the (x^T Hx > 0) condition.
setup images
Compute H x
Compute dot(x,(H x))
References stir::Array< num_dimensions, elemT >::begin_all(), stir::Array< 3, elemT >::begin_all(), stir::RunTests::check(), stir::RunTests::check_if_less(), stir::ProjDataInfo::construct_proj_data_info(), stir::Array< num_dimensions, elemT >::end_all(), stir::Array< 3, elemT >::end_all(), stir::Array< num_dimensions, elemT >::find_max(), stir::Array< 3, elemT >::find_max(), stir::Array< num_dimensions, elemT >::find_min(), stir::DiscretisedDensity< num_dimensions, elemT >::get_empty_copy(), stir::info(), stir::inner_product(), stir::ProjDataInfo::ProjDataInfoCTI(), stir::ProjData::read_from_file(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::set_additive_proj_data_sptr(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::set_normalisation_sptr(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::set_num_subsets(), stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::set_up(), and stir::PoissonLogLikelihoodWithLinearModelForMean< TargetT >::set_use_subset_sensitivities().
Referenced by run_tests_for_objective_function().
The documentation for this class was generated from the following file:
/home/sirfuser/devel/STIRdistrib/STIR/src/recon_test/test_PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx