STIR: stir::Ellipsoid Class Reference
stir::Ellipsoid Class Reference
STIR » STIR library » Classes for describing geometric shapes such as cylinders etc.
Three-dimensional ellipsoid.
#include "stir/Shape/Ellipsoid.h"
Public Member Functions
Ellipsoid (const CartesianCoordinate3D< float > &radii, const CartesianCoordinate3D< float > &centre, const Array< 2, float > &direction_vectors=diagonal_matrix(3, 1.F))
float get_geometric_volume () const
get volume
bool is_inside_shape (const CartesianCoordinate3D< float > &coord) const
determine if a point is inside the shape or not (up to floating point errors)
Shape3D * clone () const
Allocate a new Shape3D object which is a copy of the current one.
bool operator== (const Ellipsoid &) const
Compare cylinders.
virtual bool operator== (const Shape3D &shape) const
Compare shapes.
float get_radius_x () const
float get_radius_y () const
float get_radius_z () const
CartesianCoordinate3D< float > get_radii () const
void set_radii (const CartesianCoordinate3D< float > &new_radii)
Public Member Functions inherited from stir::RegisteredParsingObject< Ellipsoid, Shape3D, Shape3DWithOrientation >
std::string get_registered_name () const
Returns Derived::registered_name.
std::string parameter_info ()
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::Shape3DWithOrientation
bool operator== (const Shape3DWithOrientation &s) const
virtual void scale (const CartesianCoordinate3D< float > &scale3D)
scale the whole shape
const Array< 2, float > & get_direction_vectors () const
get direction vectors currently in use
Succeeded set_direction_vectors (const Array< 2, float > &)
set direction vectors
Public Member Functions inherited from stir::Shape3D
bool operator!= (const Shape3D &) const
Compare shapes.
virtual float get_voxel_weight (const CartesianCoordinate3D< float > &voxel_centre, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< int > &num_samples) const
Determine (approximately) the intersection volume of a voxel with the shape.
virtual void translate (const CartesianCoordinate3D< float > &direction)
translate the whole shape by shifting its origin
void scale_around_origin (const CartesianCoordinate3D< float > &scale3D)
scale the whole shape, keeping the centre at the same place
virtual void construct_volume (VoxelsOnCartesianGrid< float > &image, const CartesianCoordinate3D< int > &num_samples) const
construct an image representation the shape in a discretised manner
CartesianCoordinate3D< float > get_origin () const
get the origin of the shape-coordinate system
virtual void set_origin (const CartesianCoordinate3D< float > &)
set the origin of the shape-coordinate system
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
void ask_parameters ()
bool parse (std::istream &f)
bool parse (const char *const filename)
Static Public Attributes
static const char *const registered_name = "Ellipsoid"
Name which will be used when parsing a Shape3D object.
Protected Member Functions
virtual void set_defaults ()
set defaults before parsing
virtual void initialise_keymap ()
Initialise all keywords.
virtual bool post_processing ()
This will be called at the end of the parsing.
Protected Member Functions inherited from stir::Shape3DWithOrientation
Shape3DWithOrientation ()
default constructor (NO initialisation of values)
Shape3DWithOrientation (const CartesianCoordinate3D< float > &origin, const Array< 2, float > &directions=diagonal_matrix(3, 1.F))
float get_volume_of_unit_cell () const
gets the volume of the cell spanned by the direction vectors
CartesianCoordinate3D< float > transform_to_shape_coords (const CartesianCoordinate3D< float > &) const
Transform a 'real-world' coordinate to the coordinate system used by the shape.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Protected Member Functions inherited from stir::Shape3D
Shape3D (const CartesianCoordinate3D< float > &origin)
Protected Attributes
CartesianCoordinate3D< float > radii
Radii in 3 directions (before using the direction vectors)
Protected Attributes inherited from stir::ParsingObject
KeyParser parser
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< Ellipsoid, Shape3D, Shape3DWithOrientation >
static Shape3D * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< Shape3D >
static Shape3D * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static Shape3D * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< Shape3D >
typedef Shape3D *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Static Protected Member Functions inherited from stir::RegisteredObject< Shape3D >
static RegistryType & registry ()
Static function returning the registry.
Detailed Description
Three-dimensional ellipsoid.
Description
A point with coordinates coord is inside the shape if for :
where are described in the documentation for class stir::Shape3DWithOrientation.
Parameters
    Ellipsoid Parameters:=
   radius-x (in mm):= <float>
   radius-y (in mm):= <float>
   radius-z (in mm):= <float>
   ; any parameters of Shape3DWithOrientation
   End:=
Member Function Documentation
is_inside_shape()
bool stir::Ellipsoid::is_inside_shape (const CartesianCoordinate3D< float > & coord) const virtual
determine if a point is inside the shape or not (up to floating point errors)
Parameters
coord is a cartesian coordinate in 'absolute' coordinates, i.e. in mm and not relative to the origin member.
This is really only well defined for shapes with sharp boundaries.
See also
DiscretisedShape3D::is_inside_shape for some discussion.
Todo:
replace by floating point return value?
Implements stir::Shape3D.
References stir::norm_squared().
operator==() [1/2]
bool stir::Ellipsoid::operator== (const Ellipsoid & cylinder) const
Compare cylinders.
Uses a tolerance determined by the smallest dimension of the object divided by 1000.
References radii.
operator==() [2/2]
bool stir::Ellipsoid::operator== (const Shape3D & s) const virtual
Compare shapes.
Implementation note
This virtual function has to be implemented in each final class of the hierarchy. However, Shape3D::operator== has an implementation that checks equality of the origin (up-to a tolerance of .001). Derived classes can call this implementation.
Implements stir::Shape3D.
set_defaults()
void stir::Ellipsoid::set_defaults () protected virtual
set defaults before parsing
sets radii to 0 and calls Shape3DWithOrientation::set_defaults()
Reimplemented from stir::Shape3DWithOrientation.
post_processing()
bool stir::Ellipsoid::post_processing () protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented from stir::Shape3DWithOrientation.
References stir::error(), and stir::warning().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/Shape/Ellipsoid.h
/home/sirfuser/devel/STIRdistrib/STIR/src/Shape_buildblock/Ellipsoid.cxx