STIR: stir::ecat::ecat7::CListEventDataECAT966 Class Reference
stir::ecat::ecat7::CListEventDataECAT966 Class Reference
STIR » STIR library » Support classes for reading list mode data
Class for decoding storing and using a raw coincidence event from a listmode file from the ECAT 966 scanner.
#include "stir/listmode/CListRecordECAT966.h"
Public Member Functions
void get_sinogram_and_ring_coordinates (int &view, int &tangential_pos_num, unsigned int &ring_a, unsigned int &ring_b) const
void set_sinogram_and_ring_coordinates (const int view_num, const int tangential_pos_num, const int ring_a, const int ring_b)
Public Attributes
unsigned view: 9
unsigned bin: 9
unsigned delayed: 1
unsigned block_A_detector: 3
unsigned block_B_detector: 3
unsigned block_A_ring: 3
unsigned block_B_ring: 3
unsigned type: 1
Detailed Description
Class for decoding storing and using a raw coincidence event from a listmode file from the ECAT 966 scanner.
This class just provides the bit-field definitions. You should normally use CListEventECAT966.
For the 966 the event word is 32 bit. To save 1 bit in size, a 2d sinogram encoding is used (as opposed to a detector number on the ring for both events). Both bin and view use 9 bits, so their maximum range is 512 values, which is fine for the 966 (which needs only 288).
Member Function Documentation
get_sinogram_and_ring_coordinates()
void stir::ecat::ecat7::CListEventDataECAT966::get_sinogram_and_ring_coordinates (int & view, int & tangential_pos_num, unsigned int & ring_a, unsigned int & ring_b) const
This routine returns the corresponding tangential_pos_num,view_num,ring_a and ring_b
References get_sinogram_and_ring_coordinates().
Referenced by get_sinogram_and_ring_coordinates().
set_sinogram_and_ring_coordinates()
void stir::ecat::ecat7::CListEventDataECAT966::set_sinogram_and_ring_coordinates (const int view_num, const int tangential_pos_num, const int ring_a, const int ring_b)
This routine constructs a coincidence event
References set_sinogram_and_ring_coordinates().
Referenced by set_sinogram_and_ring_coordinates().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/CListRecordECAT966.h
/home/kris/devel/STIRdistrib/STIR/src/listmode_buildblock/CListRecordECAT966.cxx