STIR: stir::DynamicProjData Class Reference
stir::DynamicProjData Class Reference
STIR » STIR library » Basic building blocks
Dynamic projection data.
#include "stir/DynamicProjData.h"
Public Member Functions
DynamicProjData (const MultipleProjData &m)
DynamicProjData (const shared_ptr< const ExamInfo > &exam_info_sptr)
DynamicProjData (const shared_ptr< const ExamInfo > &exam_info_sptr, const int num_gates)
const double get_start_time_in_secs_since_1970 () const
Return time of start of scan.
void set_start_time_in_secs_since_1970 (const double start_time)
set start of scan
unsigned int get_num_frames () const
Succeeded write_to_ecat7 (const std::string &filename) const
void set_time_frame_definitions (const TimeFrameDefinitions &time_frame_definitions)
const TimeFrameDefinitions & get_time_frame_definitions () const
void calibrate_frames (const float cal_factor)
multiply data with a constant factor
void divide_with_duration ()
divide data with the corresponding frame duration
Static Public Member Functions
static unique_ptr< DynamicProjData > read_from_file (const std::string &filename)
Detailed Description
Dynamic projection data.
Somewhat preliminary
Todo
Move read_from_file, write_to_ecat7 to usual registry methods
Interfile support currently doesn't set start_time_in_secs_since_1970
Member Function Documentation
get_start_time_in_secs_since_1970()
const double stir::DynamicProjData::get_start_time_in_secs_since_1970 () const
Return time of start of scan.
Returns
the time in seconds since 1 Jan 1970 00:00 UTC, i.e. independent of your local time zone.
Note that the return type is a double. This allows for enough accuracy for a long time to come. It also means that the start time can have fractional seconds.
The time frame definitions should be relative to this time.
References get_start_time_in_secs_since_1970().
Referenced by get_start_time_in_secs_since_1970().
set_start_time_in_secs_since_1970()
void stir::DynamicProjData::set_start_time_in_secs_since_1970 (const double start_time)
set start of scan
See also
get_start_time_in_secs_since_1970()
References set_start_time_in_secs_since_1970().
Referenced by set_start_time_in_secs_since_1970().
calibrate_frames()
void stir::DynamicProjData::calibrate_frames (const float cal_factor) inline
multiply data with a constant factor
Warning
for most types of data, this will modify the data on disk
References stir::error(), and stir::TimeFrameDefinitions::get_num_frames().
divide_with_duration()
void stir::DynamicProjData::divide_with_duration () inline
divide data with the corresponding frame duration
Warning
for most types of data, this will modify the data on disk
References stir::error(), and stir::TimeFrameDefinitions::get_num_frames().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/DynamicProjData.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/DynamicProjData.cxx