STIR: stir::InvertAxis Class Reference
stir::InvertAxis Class Reference
STIR » STIR library » Motion fields etc
a utility class to "invert" an axis
#include "stir/spatial_transformation/InvertAxis.h"
Public Member Functions
void invert_axis (DiscretisedDensity< 3, float > &inverted_image, const DiscretisedDensity< 3, float > &input_image, const std::string &axis_name)
transform the image
int invert_axis_index (const int input_index, const int size, const std::string &axis_name)
Detailed Description
a utility class to "invert" an axis
Warning
this will reorder the voxel values without adjusting the geometric information.
Member Function Documentation
invert_axis()
void stir::InvertAxis::invert_axis (DiscretisedDensity< 3, float > & inverted_image, const DiscretisedDensity< 3, float > & input_image, const std::string & axis_name)
transform the image
axis_name has to be x, y, z. Otherwise error() will be called.
References stir::VectorWithOffset< T >::get_max_index(), stir::VectorWithOffset< T >::get_min_index(), and invert_axis().
Referenced by invert_axis().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/spatial_transformation/InvertAxis.h
/home/kris/devel/STIRdistrib/STIR/src/spatial_transformation_buildblock/InvertAxis.cxx