STIR: stir::GeneralisedPriorTests Class Reference
stir::GeneralisedPriorTests Class Reference
STIR » Test code for STIR » Tests of the basic building blocks
Test class for QuadraticPrior, RelativeDifferencePrior, and LogcoshPrior.
Public Types
typedef DiscretisedDensity< 3, float > target_type
Public Member Functions
GeneralisedPriorTests (char const *const density_filename=0)
Constructor that can take some input data to run the test with.
void construct_input_data (shared_ptr< target_type > &density_sptr)
void run_tests ()
Function (to be overloaded) which does the actual tests.
Public Member Functions inherited from stir::RunTests
RunTests (const double tolerance=1E-4)
Default constructor.
virtual ~RunTests ()
Destructor, outputs a diagnostic message.
bool is_everything_ok () const
Returns if all checks were fine upto now.
int main_return_value () const
Handy return value for a main() function.
void set_tolerance (const double tolerance)
Set value used in floating point comparisons (see check_* functions)
double get_tolerance () const
Get value used in floating point comparisons (see check_* functions)
bool check (const bool, const std::string &str="")
Tests if true, str can be used to tell what you are testing.
template<class T1 , class T2 >
bool check_if_less (T1 a, T2 b, const std::string &str="")
check if a<b
bool check_if_equal (const double a, const double b, const std::string &str="")
bool check_if_equal (const short a, const short b, const std::string &str="")
bool check_if_equal (const unsigned short a, const unsigned short b, const std::string &str="")
bool check_if_equal (const int a, const int b, const std::string &str="")
bool check_if_equal (const unsigned int a, const unsigned int b, const std::string &str="")
bool check_if_equal (const long a, const long b, const std::string &str="")
bool check_if_equal (const unsigned long a, const unsigned long b, const std::string &str="")
template<class T >
bool check_if_equal (const std::complex< T > a, const std::complex< T > b, const std::string &str="")
check equality by calling check_if_equal on real and imaginary parts
template<class T >
bool check_if_equal (const VectorWithOffset< T > &t1, const VectorWithOffset< T > &t2, const std::string &str="")
check equality by comparing ranges and calling check_if_equal on all elements
template<class T >
bool check_if_equal (const std::vector< T > &t1, const std::vector< T > &t2, const std::string &str="")
check equality by comparing size and calling check_if_equal on all elements
template<int n>
bool check_if_equal (const IndexRange< n > &t1, const IndexRange< n > &t2, const std::string &str="")
template<int num_dimensions, class coordT >
bool check_if_equal (const BasicCoordinate< num_dimensions, coordT > &a, const BasicCoordinate< num_dimensions, coordT > &b, const std::string &str="")
check equality by comparing norm(a-b) with tolerance
bool check_if_zero (const double a, const std::string &str="")
bool check_if_zero (const short a, const std::string &str="")
bool check_if_zero (const unsigned short a, const std::string &str="")
bool check_if_zero (const int a, const std::string &str="")
bool check_if_zero (const unsigned int a, const std::string &str="")
bool check_if_zero (const long a, const std::string &str="")
bool check_if_zero (const unsigned long a, const std::string &str="")
template<class T >
bool check_if_zero (const VectorWithOffset< T > &t, const std::string &str="")
use check_if_zero on all elements
template<int num_dimensions, class coordT >
bool check_if_zero (const BasicCoordinate< num_dimensions, coordT > &a, const std::string &str="")
compare norm with tolerance
Protected Member Functions
void run_tests_for_objective_function (const std::string &test_name, GeneralisedPrior< target_type > &objective_function, shared_ptr< target_type > target_sptr)
run the test
Protected Member Functions inherited from stir::RunTests
template<class T >
bool check_if_equal_generic (const T &a, const T &b, const std::string &str)
function that is called by some check_if_equal implementations. It just uses operator!=
template<class T >
bool check_if_zero_generic (T a, const std::string &str)
function that is called by some check_if_zero implementations. It just uses operator!=
Protected Attributes
char const * density_filename
shared_ptr< GeneralisedPrior< target_type > > objective_function_sptr
Protected Attributes inherited from stir::RunTests
double tolerance
tolerance for comparisons with real values
bool everything_ok
variable storing current status
Detailed Description
Test class for QuadraticPrior, RelativeDifferencePrior, and LogcoshPrior.
This test compares the result of GeneralisedPrior::compute_gradient() with a numerical gradient computed by using the GeneralisedPrior::compute_value() function.
Constructor & Destructor Documentation
GeneralisedPriorTests()
stir::GeneralisedPriorTests::GeneralisedPriorTests (char const *const density_filename = 0)
Constructor that can take some input data to run the test with.
This makes it possible to run the test with your own data. However, beware that it is very easy to set up a very long computation.
Todo:
it would be better to parse an objective function. That would allow us to set all parameters from the command line.
References run_tests_for_objective_function().
Member Function Documentation
run_tests()
void stir::GeneralisedPriorTests::run_tests () virtual
Function (to be overloaded) which does the actual tests.
This function is expected to do a series of calls to check(), check_if_equal() etc.
Implements stir::RunTests.
References run_tests_for_objective_function().
Referenced by run_tests_for_objective_function().
run_tests_for_objective_function()
void stir::GeneralisedPriorTests::run_tests_for_objective_function (const std::string & test_name, GeneralisedPrior< target_type > & objective_function, shared_ptr< target_type > target_sptr) protected
run the test
Note that this function is not specific to a particular prior
References stir::Array< num_dimensions, elemT >::begin_all(), stir::RunTests::check(), stir::RunTests::check_if_equal(), stir::GeneralisedPrior< DataT >::compute_gradient(), stir::GeneralisedPrior< DataT >::compute_value(), stir::Array< num_dimensions, elemT >::end_all(), stir::DiscretisedDensity< num_dimensions, elemT >::get_empty_copy(), stir::info(), run_tests(), stir::RunTests::set_tolerance(), stir::GeneralisedPrior< DataT >::set_up(), and stir::write_to_file().
Referenced by GeneralisedPriorTests(), and run_tests().
The documentation for this class was generated from the following file:
/home/sirfuser/devel/STIRdistrib/STIR/src/recon_test/test_priors.cxx