STIR: stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat Class Reference
stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat Class Reference
STIR » STIR library » Input/Output Library » ECAT6 ... ECAT8 support in the IO library
Class for reading images in ECAT7 file-format.
#include "stir/IO/ECAT7DynamicDiscretisedDensityInputFileFormat.h"
Public Member Functions
virtual const std::string get_name () const
Public Member Functions inherited from stir::InputFileFormat< DynamicDiscretisedDensity >
virtual bool can_read (const FileSignature &signature, std::istream &input) const
virtual bool can_read (const FileSignature &signature, const std::string &filename) const
Protected Member Functions
virtual bool actual_can_read (const FileSignature &signature, std::istream &input) const
Class for reading images in ECAT7 file-format.
virtual unique_ptr< data_type > read_from_file (std::istream &input) const
This always fails.
virtual unique_ptr< data_type > read_from_file (const std::string &filename) const
read data given a filename
Additional Inherited Members
Public Types inherited from stir::InputFileFormat< DynamicDiscretisedDensity >
typedef DynamicDiscretisedDensity data_type
Detailed Description
Class for reading images in ECAT7 file-format.
Preliminary
Member Function Documentation
get_name()
virtual const std::string stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat::get_name () const inline virtual
Implements stir::InputFileFormat< DynamicDiscretisedDensity >.
read_from_file() [1/2]
unique_ptr< ECAT7DynamicDiscretisedDensityInputFileFormat::data_type > stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat::read_from_file (std::istream & input) const protected virtual
This always fails.
Implements stir::InputFileFormat< DynamicDiscretisedDensity >.
References stir::error(), and read_from_file().
Referenced by read_from_file(), and read_from_file().
read_from_file() [2/2]
unique_ptr< ECAT7DynamicDiscretisedDensityInputFileFormat::data_type > stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat::read_from_file (const std::string & filename) const protected virtual
read data given a filename
Reimplemented from stir::InputFileFormat< DynamicDiscretisedDensity >.
References stir::error(), stir::ecat::find_scanner_from_ECAT_system_type(), stir::ecat::ecat7::is_ECAT7_image_file(), stir::ecat::ecat7::read_ECAT7_main_header(), and read_from_file().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/ECAT7DynamicDiscretisedDensityInputFileFormat.h
/home/kris/devel/STIRdistrib/STIR/src/IO/ECAT7DynamicDiscretisedDensityInputFileFormat.cxx