STIR: stir::Radionuclide Class Reference
stir::Radionuclide Class Reference
STIR » STIR library » Basic building blocks » Items related to ancillary information such as radionuclide, patient info etc
A class for storing radionuclide information.
#include "stir/Radionuclide.h"
Public Member Functions
Radionuclide ()
default constructor
Radionuclide (const std::string &name, float energy, float branching_ratio, float half_life, ImagingModality modality)
A constructor : constructs a radionuclide with all its information.
std::string get_name () const
get name (normally in DICOM format)
float get_energy (bool check=true) const
get energy (in keV)
float get_branching_ratio (bool check=true) const
get branching_ratio
float get_half_life (bool check=true) const
get half_life (in seconds)
ImagingModality get_modality (bool check=true) const
get modality
std::string parameter_info () const
Return a string with info on parameters.
bool operator== (const Radionuclide &r) const
comparison operators
Detailed Description
A class for storing radionuclide information.
See also
RadionuclideDB
Constructor & Destructor Documentation
Radionuclide()
stir::Radionuclide::Radionuclide ()
default constructor
Set name to "Unknown" and other values to invalid numbers (e.g. -1)
References Radionuclide().
Referenced by operator==(), and Radionuclide().
Member Function Documentation
get_energy()
float stir::Radionuclide::get_energy (bool check = true) const
get energy (in keV)
if check=true, calls error() if value not set (i.e. is negative)
References stir::error().
get_branching_ratio()
float stir::Radionuclide::get_branching_ratio (bool check = true) const
get branching_ratio
if check=true, calls error() if value not set (i.e. is negative)
References stir::error().
get_half_life()
float stir::Radionuclide::get_half_life (bool check = true) const
get half_life (in seconds)
if check=true, calls error() if value not set (i.e. is negative)
References stir::error().
Referenced by stir::randoms_from_singles(), and stir::RadionuclideTest::run_tests().
get_modality()
ImagingModality stir::Radionuclide::get_modality (bool check = true) const
get modality
if check=true, calls error() if value not set (i.e. is unknown)
References stir::error().
parameter_info()
std::string stir::Radionuclide::parameter_info () const
Return a string with info on parameters.
the returned string is not intended for parsing.
References parameter_info().
Referenced by parameter_info(), and stir::RadionuclideTest::run_tests().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/Radionuclide.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/Radionuclide.cxx