STIR: stir::TimedObject Class Reference
stir::TimedObject Class Reference
STIR » STIR library » Basic building blocks
base class for all objects which need timers. At the moment, there's only a CPU timer.
#include "stir/TimedObject.h"
Public Member Functions
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers () const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the timer (since first use or last reset)
Detailed Description
base class for all objects which need timers. At the moment, there's only a CPU timer.
It is the responsibility of the derived class to start and stop the timer.
Member Function Documentation
stop_timers()
void stir::TimedObject::stop_timers () const inline
stop all timers kept by this object
Note: function is const such that it can be called in a function of a derived class that is const.
Referenced by stir::DataProcessor< DiscretisedDensity< 3, elemT > >::apply(), stir::BackProjectorByBin::back_project(), stir::ForwardProjectorByBin::forward_project(), stir::DataProcessor< DiscretisedDensity< 3, elemT > >::set_up(), stir::ColsherFilter::set_up(), and stir::BackProjectorByBinUsingInterpolation::use_piecewise_linear_interpolation().
start_timers()
void stir::TimedObject::start_timers () const inline
start all timers kept by this object
Note: function is const such that it can be called in a function of a derived class that is const.
Referenced by stir::DataProcessor< DiscretisedDensity< 3, elemT > >::apply(), stir::BackProjectorByBin::back_project(), stir::ForwardProjectorByBin::forward_project(), stir::DataProcessor< DiscretisedDensity< 3, elemT > >::set_up(), stir::ColsherFilter::set_up(), and stir::BackProjectorByBinUsingInterpolation::use_piecewise_linear_interpolation().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/TimedObject.h
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/TimedObject.inl