STIR: stir::ecat::ecat7::ECAT7OutputFileFormat Class Reference
stir::ecat::ecat7::ECAT7OutputFileFormat Class Reference
STIR » STIR library » Input/Output Library » ECAT6 ... ECAT8 support in the IO library
Implementation of OutputFileFormat paradigm for the ECAT7 format.
#include "stir/IO/ECAT7OutputFileFormat.h"
Public Member Functions
ECAT7OutputFileFormat (const NumericType &=NumericType::SHORT, const ByteOrder &=ByteOrder::native)
virtual NumericType set_type_of_numbers (const NumericType &, const bool warn=false)
Set type of numbers to be used for output.
virtual ByteOrder set_byte_order (const ByteOrder &, const bool warn=false)
Set byte order to be used for output.
Public Member Functions inherited from stir::RegisteredParsingObject< ECAT7OutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::OutputFileFormat< DiscretisedDensity< 3, float > >
OutputFileFormat (const NumericType &=NumericType::FLOAT, const ByteOrder &=ByteOrder::native)
Succeeded write_to_file (std::string &filename, const DiscretisedDensity< 3, float > &data) const
Write a single image to file.
Succeeded write_to_file (const std::string &filename, const DiscretisedDensity< 3, float > &density) const
write a single image to file
NumericType get_type_of_numbers () const
get type used for outputting numbers
ByteOrder get_byte_order ()
get byte order used for output
float get_scale_to_write_data () const
get scale to write the data
virtual void set_byte_order_and_type_of_numbers (ByteOrder &, NumericType &, const bool warn=false)
set byte order and data type used for output
virtual float set_scale_to_write_data (const float new_scale_to_write_data, const bool warn=false)
set scale outputting numbers
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
Public Attributes
std::string default_scanner_name
Static Public Attributes
static const char *const registered_name = "ECAT7"
Name which will be used when parsing an OutputFileFormat object.
Protected Member Functions
virtual Succeeded actual_write_to_file (std::string &output_filename, const DiscretisedDensity< 3, float > &density) const
virtual function called by write_to_file()
virtual void set_defaults ()
Set defaults before parsing.
virtual void initialise_keymap ()
Initialise all keywords.
virtual bool post_processing ()
This will be called at the end of the parsing.
Protected Member Functions inherited from stir::OutputFileFormat< DiscretisedDensity< 3, float > >
void set_defaults () override
sets value for output data type
void initialise_keymap () override
sets keys for output data type for parsing
bool post_processing () override
Checks if parameters have sensible values after parsing.
void set_key_values () override
overloaded member for ParsingObject::set_key_values()
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< ECAT7OutputFileFormat, OutputFileFormat< DiscretisedDensity< 3, float > >, OutputFileFormat< DiscretisedDensity< 3, float > > >
static OutputFileFormat< DiscretisedDensity< 3, float > > * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
static OutputFileFormat< DiscretisedDensity< 3, float > > * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::OutputFileFormat< DiscretisedDensity< 3, float > >
static shared_ptr< OutputFileFormat< DiscretisedDensity< 3, float > > > default_sptr ()
A function to return a default output file format.
Static Public Member Functions inherited from stir::RegisteredObject< OutputFileFormat< DiscretisedDensity< 3, float > > >
static OutputFileFormat< DiscretisedDensity< 3, float > > * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static OutputFileFormat< DiscretisedDensity< 3, float > > * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< OutputFileFormat< DiscretisedDensity< 3, float > > >
typedef OutputFileFormat< DiscretisedDensity< 3, float > > *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Static Protected Member Functions inherited from stir::RegisteredObject< OutputFileFormat< DiscretisedDensity< 3, float > > >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::OutputFileFormat< DiscretisedDensity< 3, float > >
NumericType type_of_numbers
type used for outputting numbers
ByteOrder file_byte_order
byte order used for output
float scale_to_write_data
scale to write the data
KeyParser parser
Detailed Description
Implementation of OutputFileFormat paradigm for the ECAT7 format.
Warning
Currently output always uses 2-byte signed integers in big-endian byte order.
Member Function Documentation
set_type_of_numbers()
NumericType stir::ecat::ecat7::ECAT7OutputFileFormat::set_type_of_numbers (const NumericType & new_type, const bool warn = false) virtual
Set type of numbers to be used for output.
Currently the return value will always be NumericType::SHORT
Reimplemented from stir::OutputFileFormat< DiscretisedDensity< 3, float > >.
References set_type_of_numbers(), stir::OutputFileFormat< DiscretisedDensity< 3, float > >::type_of_numbers, and stir::warning().
Referenced by set_type_of_numbers().
set_byte_order()
ByteOrder stir::ecat::ecat7::ECAT7OutputFileFormat::set_byte_order (const ByteOrder & new_byte_order, const bool warn = false) virtual
Set byte order to be used for output.
Currently the return value will always be ByteOrder::BIGENDIAN
Reimplemented from stir::OutputFileFormat< DiscretisedDensity< 3, float > >.
References stir::ByteOrder::big_endian, stir::OutputFileFormat< DiscretisedDensity< 3, float > >::file_byte_order, set_byte_order(), and stir::warning().
Referenced by set_byte_order().
actual_write_to_file()
Succeeded stir::ecat::ecat7::ECAT7OutputFileFormat::actual_write_to_file (std::string & filename, const DiscretisedDensity< 3, float > & density) const protected virtual
virtual function called by write_to_file()
This function has to be overloaded by the derived class.
The reason we do not simply make write_to_file() virtual is that we have 2 versions of write_to_file. C++ rules are such that overloading the virtual function in a derived class means that the other version gets hidden. Having the non-virtual write_to_file() call the virtual actual_write_to_file() solves this problem.
Implements stir::OutputFileFormat< DiscretisedDensity< 3, float > >.
References actual_write_to_file(), stir::add_extension(), stir::ecat::ecat7::DiscretisedDensity_to_ECAT7(), stir::Scanner::get_scanner_from_name(), stir::ecat::ecat7::make_ECAT7_main_header(), and stir::warning().
Referenced by actual_write_to_file().
set_defaults()
void stir::ecat::ecat7::ECAT7OutputFileFormat::set_defaults () protected virtual
Set defaults before parsing.
Reimplemented from stir::ParsingObject.
References stir::ByteOrder::big_endian, stir::OutputFileFormat< DiscretisedDensity< 3, float > >::file_byte_order, set_defaults(), stir::ParsingObject::set_defaults(), stir::OutputFileFormat< DiscretisedDensity< 3, float > >::set_key_values(), and stir::OutputFileFormat< DiscretisedDensity< 3, float > >::type_of_numbers.
Referenced by set_defaults().
initialise_keymap()
void stir::ecat::ecat7::ECAT7OutputFileFormat::initialise_keymap () protected virtual
Initialise all keywords.
Reimplemented from stir::ParsingObject.
References initialise_keymap(), and stir::ParsingObject::initialise_keymap().
Referenced by initialise_keymap().
post_processing()
bool stir::ecat::ecat7::ECAT7OutputFileFormat::post_processing () protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented from stir::ParsingObject.
References stir::ecat::find_ECAT_system_type(), stir::Scanner::get_scanner_from_name(), post_processing(), stir::ParsingObject::post_processing(), and stir::warning().
Referenced by post_processing().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/ECAT7OutputFileFormat.h
/home/kris/devel/STIRdistrib/STIR/src/IO/ECAT7OutputFileFormat.cxx