STIR: stir::ProjDataInfoCylindrical Class Reference
stir::ProjDataInfoCylindrical Class Reference abstract
STIR » STIR library » Basic building blocks » Items related to projection data
projection data info for data corresponding to a 'cylindrical' sampling.
#include "stir/ProjDataInfoCylindrical.h"
Public Types
typedef std::vector< std::pair< int, int > > RingNumPairs
Type used by get_all_ring_pairs_for_segment_axial_pos_num()
Public Member Functions
ProjDataInfoCylindrical ()
Constructors.
ProjDataInfoCylindrical (const shared_ptr< Scanner > &scanner_ptr, const VectorWithOffset< int > &num_axial_poss_per_segment, const VectorWithOffset< int > &min_ring_diff, const VectorWithOffset< int > &max_ring_diff, const int num_views, const int num_tangential_poss)
Constructor given all the necessary information.
float get_tantheta (const Bin &) const override
Get tangent of the co-polar angle of the normal to the projection plane.
float get_phi (const Bin &) const override
Get azimuthal angle phi of the normal to the projection plane.
float get_t (const Bin &) const override
Get value of the (roughly) axial coordinate in the projection plane (in mm)
float get_m (const Bin &) const override
Return z-coordinate of the middle of the LOR.
void get_LOR (LORInAxialAndNoArcCorrSinogramCoordinates< float > &lor, const Bin &bin) const override
Get LOR corresponding to a given bin.
virtual void set_azimuthal_angle_offset (const float angle)
Set azimuthal angle offset (in radians)
virtual void set_azimuthal_angle_sampling (const float angle)
Set the azimuthal sampling (in radians)
void set_num_views (const int new_num_views) override
set new number of views, covering the same azimuthal angle range
void set_tof_mash_factor (const int new_num) override
The tof mashing factor (for TOF scanners).
virtual float get_azimuthal_angle_offset () const
Get azimuthal angle offset (in radians)
virtual float get_azimuthal_angle_sampling () const
Get the azimuthal sampling (in radians)
float get_sampling_in_t (const Bin &) const override
Get sampling distance in the t coordinate.
float get_sampling_in_m (const Bin &) const override
Get sampling distance in the m coordinate.
virtual float get_axial_sampling (int segment_num) const
Get the axial sampling (e.g in z_direction)
virtual bool axial_sampling_is_uniform () const
Return if axial sampling makes sense.
float get_average_ring_difference (int segment_num) const
Get average ring difference for the given segment.
int get_min_ring_difference (int segment_num) const
Get minimum ring difference for the given segment.
int get_max_ring_difference (int segment_num) const
Get maximum ring difference for the given segment.
void set_min_ring_difference (int min_ring_diff_v, int segment_num)
Set minimum ring difference.
void set_max_ring_difference (int max_ring_diff_v, int segment_num)
Set maximum ring difference.
void set_num_axial_poss_per_segment (const VectorWithOffset< int > &num_axial_poss_per_segment) override
Set number of axial positions per segment.
void set_min_axial_pos_num (const int min_ax_pos_num, const int segment_num) override
Set minimum axial position number for 1 segment.
void set_max_axial_pos_num (const int max_ax_pos_num, const int segment_num) override
Set maximum axial position number for 1 segment.
void reduce_segment_range (const int min_segment_num, const int max_segment_num) override
Set a new range of segment numbers.
virtual void set_ring_radii_for_all_views (const VectorWithOffset< float > &new_ring_radius)
Set detector ring radius for all views.
virtual VectorWithOffset< float > get_ring_radii_for_all_views () const
Get detector ring radius for all views.
virtual float get_ring_radius () const
Get detector ring radius.
virtual float get_ring_radius (const int view_num) const
virtual float get_ring_spacing () const
Get detector ring spacing.
virtual void set_ring_spacing (float ring_spacing_v)
Set detector ring spacing.
virtual int get_view_mashing_factor () const
Get the mashing factor, i.e. how many 'original' views are combined.
Succeeded get_segment_num_for_ring_difference (int &segment_num, const int ring_diff) const
Find which segment a particular ring difference belongs to.
Succeeded get_segment_axial_pos_num_for_ring_pair (int &segment_num, int &axial_pos_num, const int ring1, const int ring2) const
Find to which segment and axial position a ring pair contributes.
const RingNumPairs & get_all_ring_pairs_for_segment_axial_pos_num (const int segment_num, const int axial_pos_num) const
Find all ring pairs that contribute to a segment and axial position.
unsigned get_num_ring_pairs_for_segment_axial_pos_num (const int segment_num, const int axial_pos_num) const
Find the number of ring pairs that contribute to a segment and axial position.
void get_ring_pair_for_segment_axial_pos_num (int &ring1, int &ring2, const int segment_num, const int axial_pos_num) const
Find a ring pair that contributes to a segment and axial position.
std::string parameter_info () const override
Return a string describing the object.
Public Member Functions inherited from stir::ProjDataInfo
ProjDataInfo ()
Construct an empty object.
ProjDataInfo (const shared_ptr< Scanner > &scanner_ptr, const VectorWithOffset< int > &num_axial_pos_per_segment, const int num_views, const int num_tangential_poss)
Constructor setting all relevant info for a ProjDataInfo.
ProjDataInfo (const shared_ptr< Scanner > &scanner_ptr, const VectorWithOffset< int > &num_axial_pos_per_segment, const int num_views, const int num_tangential_poss, const int tof_mash_factor)
Overloaded Contructor with TOF initialisation.
virtual ProjDataInfo * clone () const =0
Standard trick for a 'virtual copy-constructor'.
shared_ptr< ProjDataInfo > create_shared_clone () const
Like clone() but return a shared_ptr.
shared_ptr< ProjDataInfo > create_non_tof_clone () const
Similar to create_shared_clone() but returns a non-tof version of ProjDataInfo setting tof mashing factor = 0.
virtual ~ProjDataInfo ()
Destructor.
virtual void set_num_tangential_poss (const int num_tang_poss)
Set number of tangential positions.
virtual void set_min_tangential_pos_num (const int min_tang_poss)
Set minimum tangential position number.
virtual void set_max_tangential_pos_num (const int max_tang_poss)
Set maximum tangential position number.
int get_num_segments () const
Get number of segments.
int get_num_axial_poss (const int segment_num) const
Get number of axial positions per segment.
int get_num_views () const
Get number of views.
int get_num_tangential_poss () const
Get number of tangential positions.
int get_tof_bin (const double delta) const
Get number of tof bin for a given time difference.
int get_num_tof_poss () const
Get number of TOF bins.
int get_min_segment_num () const
Get minimum segment number.
int get_max_segment_num () const
Get maximum segment number.
int get_min_axial_pos_num (const int segment_num) const
Get minimum axial position per segmnet.
int get_max_axial_pos_num (const int segment_num) const
Get maximum axial position per segment.
int get_min_view_num () const
Get minimum view number.
int get_max_view_num () const
Get maximum view number.
int get_min_tangential_pos_num () const
Get minimum tangential position number.
int get_max_tangential_pos_num () const
Get maximum tangential position number.
int get_tof_mash_factor () const
Get TOF mash factor.
int get_min_tof_pos_num () const
Get the index of the first TOF position.
int get_max_tof_pos_num () const
Get the index of the last timgin position.
int get_num_sinograms () const
Get the total number of sinograms.
int get_num_non_tof_sinograms () const
Get the number of non-tof sinograms.
std::size_t size_all () const
Get the total size of the data.
bool is_tof_data () const
Determine if TOF data from tof_mash_factor and num_tof_bins.
virtual std::vector< int > get_original_view_nums () const
Return a list of view numbers in the "original" data if subsets are used.
float get_costheta (const Bin &) const
Get cosine of the co-polar angle of the normal to the projection plane.
virtual float get_s (const Bin &) const =0
Get value of the tangential coordinate in the projection plane (in mm)
float get_k (const Bin &) const
Get value of the TOF location along the LOR (in mm) k is a line segment connecting the centers of the two detectors.
double get_tof_delta_time (const Bin &) const
Get the value of the TOF timing difference (in ps)
virtual float get_sampling_in_s (const Bin &) const
Get sampling distance in the s coordinate.
float get_sampling_in_k (const Bin &) const
Get sampling distance in the k coordinate.
virtual Bin get_bin (const LOR< float > &, const double delta_time=0.0) const =0
Find the bin in the projection data that 'contains' an LOR.
bool operator== (const ProjDataInfo &proj) const
check equality
bool operator!= (const ProjDataInfo &proj) const
virtual bool operator>= (const ProjDataInfo &proj) const
Check if *this contains proj.
Viewgram< float > get_empty_viewgram (const ViewgramIndices &) const
Get empty viewgram.
Sinogram< float > get_empty_sinogram (const SinogramIndices &) const
Get empty_sinogram.
SegmentByView< float > get_empty_segment_by_view (const SegmentIndices &) const
Get empty segment sino.
SegmentBySinogram< float > get_empty_segment_by_sinogram (const SegmentIndices &) const
Get empty segment view.
Viewgram< float > get_empty_viewgram (const int view_num, const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty viewgram.
Sinogram< float > get_empty_sinogram (const int ax_pos_num, const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty_sinogram.
SegmentByView< float > get_empty_segment_by_view (const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty segment sino.
SegmentBySinogram< float > get_empty_segment_by_sinogram (const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty segment view.
RelatedViewgrams< float > get_empty_related_viewgrams (const ViewgramIndices &, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty related viewgrams, where the symmetries_ptr specifies the symmetries to use.
const Scanner * get_scanner_ptr () const
Get scanner pointer.
shared_ptr< Scanner > get_scanner_sptr () const
Get scanner shared pointer.
void set_bed_position_horizontal (const float bed_position_horizontal_arg)
Vector which holds the lower and higher boundary for each TOF position, without the application of TOF mashing, in mm, for faster access.
float get_bed_position_horizontal () const
Get horizontal bed position.
void set_bed_position_vertical (const float bed_position_vertical_arg)
Set vertical bed position.
float get_bed_position_vertical () const
Get vertical bed position.
bool has_energy_information () const
Protected Member Functions
bool blindly_equals (const root_type *const) const override=0
Protected Attributes
bool sampling_corresponds_to_physical_rings
a variable that is set if the data corresponds to physical rings in the scanner
Additional Inherited Members
Static Public Member Functions inherited from stir::ProjDataInfo
static ProjDataInfo * ask_parameters ()
Ask for the details and return a ProjDataInfo pointer.
static ProjDataInfo * ProjDataInfoGE (const shared_ptr< Scanner > &scanner_ptr, const int max_delta, const int num_views, const int num_tangential_poss, const bool arc_corrected=true, const int tof_mash_factor=0)
Construct a ProjDataInfo with span=3 for segment 0, but span=1 for others.
static ProjDataInfo * ProjDataInfoCTI (const shared_ptr< Scanner > &scanner_ptr, const int span, const int max_delta, const int num_views, const int num_tangential_poss, const bool arc_corrected=true, const int tof_mash_factor=0)
Old name for construct_proj_data_info()
static unique_ptr< ProjDataInfo > construct_proj_data_info (const shared_ptr< Scanner > &scanner_sptr, const int span, const int max_delta, const int num_views, const int num_tangential_poss, const bool arc_corrected=true, const int tof_mash_factor=0)
Construct a ProjDataInfo suitable with a given span.
VectorWithOffset< Float1Float2 > tof_bin_boundaries_mm
Vector which holds the lower and higher boundary for each TOF position in mm, for faster access.
VectorWithOffset< Float1Float2 > tof_bin_boundaries_ps
Vector which holds the lower and higher boundary for each TOF position in ps`, for faster access.
Protected Types inherited from stir::ProjDataInfo
typedef ProjDataInfo root_type
Detailed Description
projection data info for data corresponding to a 'cylindrical' sampling.
These data are organised by ring differences (allowing for merging of some ring differences into 1 segment). The class is general enough to have both the CTI 'spanned' format, and the GE Advance format.
Constructor & Destructor Documentation
ProjDataInfoCylindrical()
stir::ProjDataInfoCylindrical::ProjDataInfoCylindrical (const shared_ptr< Scanner > & scanner_ptr, const VectorWithOffset< int > & num_axial_poss_per_segment, const VectorWithOffset< int > & min_ring_diff, const VectorWithOffset< int > & max_ring_diff, const int num_views, const int num_tangential_poss)
Constructor given all the necessary information.
The min and max ring difference in each segment are passed as VectorWithOffsets. All three vectors have to have index ranges from min_segment_num to max_segment_num.
Warning
Most of this library assumes that segment 0 corresponds to an average ring difference of 0.
References _PI, stir::Scanner::get_effective_ring_radius(), stir::VectorWithOffset< T >::get_length(), stir::ProjDataInfo::get_max_segment_num(), stir::ProjDataInfo::get_min_segment_num(), stir::Scanner::get_ring_spacing(), stir::ProjDataInfo::get_scanner_ptr(), get_view_mashing_factor(), stir::info(), stir::ProjDataInfo::ProjDataInfo(), ProjDataInfoCylindrical(), sampling_corresponds_to_physical_rings, and stir::warning().
Member Function Documentation
get_tantheta()
float stir::ProjDataInfoCylindrical::get_tantheta (const Bin &) const inline override virtual
Get tangent of the co-polar angle of the normal to the projection plane.
theta=0 for 'direct' planes (i.e. projection planes parallel to the scanner axis)
Implements stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_average_ring_difference(), get_ring_radius(), stir::ProjDataInfo::get_s(), get_tantheta(), stir::SegmentIndices::segment_num(), stir::square(), and stir::ViewgramIndices::view_num().
Referenced by get_LOR(), get_tantheta(), and stir::ProjDataInfoCylindricalArcCorrTests::run_tests().
get_phi()
float stir::ProjDataInfoCylindrical::get_phi (const Bin &) const inline override virtual
Get azimuthal angle phi of the normal to the projection plane.
phi=0 when the normal vector has no component along the horizontal axis
Implements stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_phi(), and stir::ViewgramIndices::view_num().
Referenced by get_LOR(), get_phi(), stir::ProjDataInfoTests::run_coordinate_test(), and stir::ProjDataInfoCylindricalArcCorrTests::run_tests().
get_t()
float stir::ProjDataInfoCylindrical::get_t (const Bin &) const inline override virtual
Get value of the (roughly) axial coordinate in the projection plane (in mm)
t-axis is defined to be orthogonal to the s-axis (and to the vector normal to the projection plane
Implements stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References stir::ProjDataInfo::get_costheta(), get_m(), and get_t().
Referenced by get_t(), and stir::ProjDataInfoCylindricalArcCorrTests::run_tests().
get_m()
float stir::ProjDataInfoCylindrical::get_m (const Bin & bin) const inline override virtual
Return z-coordinate of the middle of the LOR.
The 0 of the z-axis is chosen in the middle of the scanner.
Warning
Current implementation assumes that the axial positions are always 'centred', i.e. get_m(Bin(..., min_axial_pos_num,...)) == - get_m(Bin(..., max_axial_pos_num,...))
Reimplemented from stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References stir::Bin::axial_pos_num(), get_axial_sampling(), get_m(), and stir::SegmentIndices::segment_num().
Referenced by stir::ProjDataInfoCylindricalArcCorr::get_bin(), stir::ProjDataInfoCylindricalNoArcCorr::get_bin(), get_LOR(), get_m(), get_t(), stir::ProjDataInfoTests::run_coordinate_test(), stir::ProjDataInfoTests::run_coordinate_test_for_realistic_scanner(), and stir::SSRB().
get_LOR()
void stir::ProjDataInfoCylindrical::get_LOR (LORInAxialAndNoArcCorrSinogramCoordinates< float > & , const Bin &) const override virtual
Get LOR corresponding to a given bin.
See also
get_bin()
Warning
This function might get a different type of arguments in the next release.
Implements stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_m(), get_phi(), get_ring_radius(), stir::ProjDataInfo::get_s(), get_tantheta(), and stir::square().
Referenced by stir::ProjDataInfoTests::run_coordinate_test(), stir::ProjDataInfoTests::run_coordinate_test_for_realistic_scanner(), and stir::ProjDataInfoTests::run_lor_get_s_test().
set_azimuthal_angle_offset()
void stir::ProjDataInfoCylindrical::set_azimuthal_angle_offset (const float angle) virtual
Set azimuthal angle offset (in radians)
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
Referenced by stir::SSRB().
set_azimuthal_angle_sampling()
void stir::ProjDataInfoCylindrical::set_azimuthal_angle_sampling (const float angle) virtual
Set the azimuthal sampling (in radians)
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
Referenced by stir::InterfilePDFSHeaderSPECT::post_processing().
set_num_views()
void stir::ProjDataInfoCylindrical::set_num_views (const int new_num_views) override virtual
set new number of views, covering the same azimuthal angle range
calls ProjDataInfo::set_num_views(), but makes sure that we cover the same range of angles as before (usually, but not necessarily, 180 degrees) by adjusting azimuthal_angle_sampling.
Warning
This function does not change the azimutal_angle_offset, such that the first view returns the same get_phi. Depending on what you want, you might have to call set_azimuthal_angle_offset() as well.
Reimplemented from stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_azimuthal_angle_sampling(), stir::ProjDataInfo::get_num_views(), and stir::ProjDataInfo::set_num_views().
Referenced by stir::SSRB().
set_tof_mash_factor()
void stir::ProjDataInfoCylindrical::set_tof_mash_factor (const int new_num) override virtual
The tof mashing factor (for TOF scanners).
Set to 0 for non-TOF
Min and Max timing position will be recalculated.
Todo
N.E: This function is very ugly and unnessesary complicated. Could be much better.
Todo
N.E. Would be nice to have all the points of the scanner in cache.
Reimplemented from stir::ProjDataInfo.
References stir::ProjDataInfo::set_tof_mash_factor().
Referenced by stir::ProjDataInfoCylindricalNoArcCorr::ProjDataInfoCylindricalNoArcCorr(), and stir::SSRB().
get_sampling_in_t()
float stir::ProjDataInfoCylindrical::get_sampling_in_t (const Bin & bin) const inline override virtual
Get sampling distance in the t coordinate.
For some coordinate systems, this might depend on the Bin. The default implementation computes it as
1/2(get_t(..., ax_pos+1,...)-get_t(..., ax_pos-1,...)))
Reimplemented from stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_axial_sampling(), stir::ProjDataInfo::get_costheta(), get_sampling_in_t(), and stir::SegmentIndices::segment_num().
Referenced by get_sampling_in_t().
get_sampling_in_m()
float stir::ProjDataInfoCylindrical::get_sampling_in_m (const Bin & bin) const inline override virtual
Get sampling distance in the m coordinate.
For some coordinate systems, this might depend on the Bin. The default implementation computes it as
1/2(get_m(..., ax_pos+1,...)-get_m(..., ax_pos-1,...)))
Reimplemented from stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_axial_sampling(), get_sampling_in_m(), and stir::SegmentIndices::segment_num().
Referenced by get_sampling_in_m().
get_axial_sampling()
float stir::ProjDataInfoCylindrical::get_axial_sampling (int segment_num) const inline virtual
Get the axial sampling (e.g in z_direction)
Warning
The implementation of this function currently assumes that the axial sampling is equal to the ring spacing for non-spanned data (i.e. no axial compression), while it is half the ring spacing for spanned data.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_axial_sampling().
Referenced by get_axial_sampling(), stir::ProjDataInfoCylindricalArcCorr::get_bin(), stir::ProjDataInfoCylindricalNoArcCorr::get_bin(), get_m(), get_sampling_in_m(), get_sampling_in_t(), stir::ProjDataInfoCylindricalArcCorrTests::run_tests(), stir::ProjMatrixByBinPinholeSPECTUB::set_up(), and stir::SSRB().
axial_sampling_is_uniform()
virtual bool stir::ProjDataInfoCylindrical::axial_sampling_is_uniform () const inline virtual
Return if axial sampling makes sense.
could be false for block/generic cases
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
set_num_axial_poss_per_segment()
void stir::ProjDataInfoCylindrical::set_num_axial_poss_per_segment (const VectorWithOffset< int > & num_axial_poss_per_segment) override virtual
Set number of axial positions per segment.
Parameters
num_axial_poss_per_segment is a vector with the new numbers, where the index into the vector is the segment_num (i.e. it is not related to the storage order of the segments or so).
This function is virtual in case a derived class needs to know the number of axial positions changed.
Sets min_axial_pos_per_seg to 0
Reimplemented from stir::ProjDataInfo.
References stir::ProjDataInfo::set_num_axial_poss_per_segment().
set_min_axial_pos_num()
void stir::ProjDataInfoCylindrical::set_min_axial_pos_num (const int min_ax_pos_num, const int segment_num) override virtual
Set minimum axial position number for 1 segment.
This function is virtual in case a derived class needs to know the number changed.
No checks are done on validity of the min_ax_pos_num argument
Reimplemented from stir::ProjDataInfo.
References stir::ProjDataInfo::set_min_axial_pos_num().
Referenced by stir::SSRB().
set_max_axial_pos_num()
void stir::ProjDataInfoCylindrical::set_max_axial_pos_num (const int max_ax_pos_num, const int segment_num) override virtual
Set maximum axial position number for 1 segment.
This function is virtual in case a derived class needs to know the number changed.
No checks are done on validity of the max_ax_pos_num argument
Reimplemented from stir::ProjDataInfo.
References stir::ProjDataInfo::set_max_axial_pos_num().
Referenced by stir::SSRB().
reduce_segment_range()
void stir::ProjDataInfoCylindrical::reduce_segment_range (const int min_segment_num, const int max_segment_num) override virtual
Set a new range of segment numbers.
This function is virtual in case a derived class needs to know the segment range changed.
Warning
the new range has to be 'smaller' than the old one.
Reimplemented from stir::ProjDataInfo.
References stir::ProjDataInfo::reduce_segment_range().
Referenced by stir::SSRB().
set_ring_radii_for_all_views()
void stir::ProjDataInfoCylindrical::set_ring_radii_for_all_views (const VectorWithOffset< float > & new_ring_radius) inline virtual
Set detector ring radius for all views.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References stir::error(), stir::VectorWithOffset< T >::get_max_index(), stir::VectorWithOffset< T >::get_min_index(), and set_ring_radii_for_all_views().
Referenced by stir::InterfilePDFSHeaderSPECT::post_processing(), and set_ring_radii_for_all_views().
get_ring_spacing()
float stir::ProjDataInfoCylindrical::get_ring_spacing () const inline virtual
Get detector ring spacing.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
References get_ring_spacing().
Referenced by stir::ProjDataInfoCylindricalArcCorr::get_bin(), stir::ProjDataInfoCylindricalNoArcCorr::get_bin(), and get_ring_spacing().
set_ring_spacing()
void stir::ProjDataInfoCylindrical::set_ring_spacing (float ring_spacing_v) virtual
Set detector ring spacing.
Reimplemented in stir::ProjDataInfoGenericNoArcCorr.
get_view_mashing_factor()
int stir::ProjDataInfoCylindrical::get_view_mashing_factor () const inline virtual
Get the mashing factor, i.e. how many 'original' views are combined.
This gets the result by comparing the number of detectors in the scanner_ptr with the actual number of views.
Warning
In the debug version, it is checked with an assert() that the number of detectors is an even multiple of the number of views. This is not checked in the normal version though.
References stir::ProjDataInfo::get_num_views(), stir::ProjDataInfo::get_scanner_ptr(), and get_view_mashing_factor().
Referenced by stir::ProjDataInfoCylindricalNoArcCorr::get_all_det_pos_pairs_for_bin(), stir::LmToProjData::get_compression_count(), stir::ProjDataInfoCylindricalNoArcCorr::get_det_num_pair_for_view_tangential_pos_num(), stir::ProjDataInfoCylindricalNoArcCorr::get_num_det_pos_pairs_for_bin(), get_view_mashing_factor(), stir::ProjDataInfoCylindricalNoArcCorr::get_view_tangential_pos_num_for_det_num_pair(), ProjDataInfoCylindrical(), and stir::ProjMatrixByBinUsingRayTracing::set_up().
get_segment_num_for_ring_difference()
Succeeded stir::ProjDataInfoCylindrical::get_segment_num_for_ring_difference (int & segment_num, const int ring_diff) const inline
Find which segment a particular ring difference belongs to.
Returns
Succeeded::yes when a corresponding segment was found.
References get_max_ring_difference(), stir::ProjDataInfo::get_max_segment_num(), get_min_ring_difference(), stir::ProjDataInfo::get_min_segment_num(), get_segment_num_for_ring_difference(), and sampling_corresponds_to_physical_rings.
Referenced by get_segment_axial_pos_num_for_ring_pair(), and get_segment_num_for_ring_difference().
get_segment_axial_pos_num_for_ring_pair()
Succeeded stir::ProjDataInfoCylindrical::get_segment_axial_pos_num_for_ring_pair (int & segment_num, int & axial_pos_num, const int ring1, const int ring2) const inline
Find to which segment and axial position a ring pair contributes.
ring1, ring2 have to between 0 and scanner.get_num_rings()-1.
Returns
Succeeded::yes when a corresponding segment was found.
Warning
axial_pos_num returned might be outside the actual range in the proj_data_info.
For CTI data with span, this essentially implements a 'michelogram'.
Warning
Current implementation assumes that the axial positions start from 0 for the first ring-pair in the segment.
The implementation of this function currently assumes that the axial sampling is equal to the ring spacing for non-spanned data (i.e. no axial compression), while it is half the ring spacing for spanned data.
References stir::ProjDataInfo::get_scanner_ptr(), get_segment_axial_pos_num_for_ring_pair(), and get_segment_num_for_ring_difference().
Referenced by stir::CListEventCylindricalScannerWithViewTangRingRingEncoding< CListEventECAT966 >::get_bin(), stir::ProjDataInfoCylindricalArcCorr::get_bin(), stir::ProjDataInfoCylindricalNoArcCorr::get_bin(), and get_segment_axial_pos_num_for_ring_pair().
get_all_ring_pairs_for_segment_axial_pos_num()
const ProjDataInfoCylindrical::RingNumPairs & stir::ProjDataInfoCylindrical::get_all_ring_pairs_for_segment_axial_pos_num (const int segment_num, const int axial_pos_num) const inline
Find all ring pairs that contribute to a segment and axial position.
ring1, ring2 will be between 0 and scanner.get_num_rings()-1.
Warning
The implementation of this function currently assumes that the axial sampling is equal to the ring spacing for non-spanned data (i.e. no axial compression), while it is half the ring spacing for spanned data.
References get_all_ring_pairs_for_segment_axial_pos_num().
Referenced by stir::ProjDataInfoCylindricalNoArcCorr::get_all_det_pos_pairs_for_bin(), get_all_ring_pairs_for_segment_axial_pos_num(), and get_num_ring_pairs_for_segment_axial_pos_num().
get_num_ring_pairs_for_segment_axial_pos_num()
unsigned stir::ProjDataInfoCylindrical::get_num_ring_pairs_for_segment_axial_pos_num (const int segment_num, const int axial_pos_num) const inline
Find the number of ring pairs that contribute to a segment and axial position.
Warning
The implementation of this function currently assumes that the axial sampling is equal to the ring spacing for non-spanned data (i.e. no axial compression), while it is half the ring spacing for spanned data.
References get_all_ring_pairs_for_segment_axial_pos_num(), and get_num_ring_pairs_for_segment_axial_pos_num().
Referenced by stir::LmToProjData::get_compression_count(), stir::ProjDataInfoCylindricalNoArcCorr::get_num_det_pos_pairs_for_bin(), and get_num_ring_pairs_for_segment_axial_pos_num().
get_ring_pair_for_segment_axial_pos_num()
void stir::ProjDataInfoCylindrical::get_ring_pair_for_segment_axial_pos_num (int & ring1, int & ring2, const int segment_num, const int axial_pos_num) const
Find a ring pair that contributes to a segment and axial position.
ring1, ring2 will be between 0 and scanner.get_num_rings()-1.
Warning
Currently only works when no axial compression is used for the segment (i.e. min_ring_diff = max_ring_diff). Otherwise, a error() will be called.
The implementation of this function currently assumes that the axial sampling is equal to the ring spacing for non-spanned data (i.e. no axial compression), while it is half the ring spacing for spanned data.
References stir::error(), get_max_ring_difference(), get_min_ring_difference(), and sampling_corresponds_to_physical_rings.
Referenced by stir::ProjDataInfoCylindricalNoArcCorr::get_det_pair_for_bin(), and stir::DataSymmetriesForBins_PET_CartesianGrid::num_related_bins().
parameter_info()
string stir::ProjDataInfoCylindrical::parameter_info () const override virtual
Return a string describing the object.
Reimplemented from stir::ProjDataInfo.
Reimplemented in stir::ProjDataInfoCylindricalArcCorr, stir::ProjDataInfoCylindricalNoArcCorr, and stir::ProjDataInfoGenericNoArcCorr.
References _PI, get_azimuthal_angle_sampling(), stir::ProjDataInfo::get_max_segment_num(), stir::ProjDataInfo::get_min_segment_num(), stir::ProjDataInfo::get_num_views(), and stir::ProjDataInfo::parameter_info().
Referenced by stir::ProjDataInfoCylindricalArcCorr::parameter_info(), and stir::ProjDataInfoCylindricalNoArcCorr::parameter_info().
blindly_equals()
bool stir::ProjDataInfoCylindrical::blindly_equals (const root_type * const that) const override protected pure virtual
Default implementation checks common variables. Needs to be overloaded.
Implements stir::ProjDataInfo.
Implemented in stir::ProjDataInfoCylindricalNoArcCorr, and stir::ProjDataInfoGenericNoArcCorr.
References stir::ProjDataInfo::blindly_equals(), stir::norm(), and sampling_corresponds_to_physical_rings.
Member Data Documentation
sampling_corresponds_to_physical_rings
bool stir::ProjDataInfoCylindrical::sampling_corresponds_to_physical_rings protected
a variable that is set if the data corresponds to physical rings in the scanner
This is (only) used to prevent get_segment_axial_pos_num_for_ring_pair() et al to go wild. Indeed, for cases where there's cylindrical sampling, but not really any physical rings associated to the sampling, those functions will return invalid information.
The prime case where this is used is for data corresponding to (nearly) continuous detectors, such as DHCI systems, or the HiDAC.
Ideally, this would be done by having a separate class for such systems which does not contain the ring-difference et al information. This seems to make the hierarchy too complicated though.
Bug
The value of this variable is currently set by checking if the scanner is a HiDAC scanner. This needs to be changed.
Referenced by blindly_equals(), get_ring_pair_for_segment_axial_pos_num(), get_segment_num_for_ring_difference(), and ProjDataInfoCylindrical().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/ProjDataInfoCylindrical.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/ProjDataInfoCylindrical.cxx
/home/kris/devel/STIRdistrib/STIR/src/include/stir/ProjDataInfoCylindrical.inl