STIR: stir::ecat::ecat7::ECAT7ImageInputFileFormat Class Reference
stir::ecat::ecat7::ECAT7ImageInputFileFormat Class Reference
STIR » STIR library » Input/Output Library » ECAT6 ... ECAT8 support in the IO library
Class for reading images in ECAT7 file-format.
#include "stir/IO/ECAT7ImageInputFileFormat.h"
Public Member Functions
virtual const std::string get_name () const
Public Member Functions inherited from stir::InputFileFormat< DiscretisedDensity< 3, float > >
virtual bool can_read (const FileSignature &signature, std::istream &input) const
virtual bool can_read (const FileSignature &signature, const std::string &filename) const
Protected Member Functions
virtual bool actual_can_read (const FileSignature &signature, std::istream &input) const
virtual unique_ptr< data_type > read_from_file (std::istream &input) const
read data from a stream
virtual unique_ptr< data_type > read_from_file (const std::string &filename) const
read data from a filename
Additional Inherited Members
Public Types inherited from stir::InputFileFormat< DiscretisedDensity< 3, float > >
typedef DiscretisedDensity< 3, float > data_type
Detailed Description
Class for reading images in ECAT7 file-format.
Preliminary
Member Function Documentation
get_name()
virtual const std::string stir::ecat::ecat7::ECAT7ImageInputFileFormat::get_name () const inline virtual
Implements stir::InputFileFormat< DiscretisedDensity< 3, float > >.
actual_can_read()
virtual bool stir::ecat::ecat7::ECAT7ImageInputFileFormat::actual_can_read (const FileSignature & signature, std::istream & input) const inline protected virtual
Implements stir::InputFileFormat< DiscretisedDensity< 3, float > >.
read_from_file() [1/2]
virtual unique_ptr< data_type > stir::ecat::ecat7::ECAT7ImageInputFileFormat::read_from_file (std::istream & input) const inline protected virtual
read data from a stream
This function should throw an exception if the read fails.
Warning
This member throws for most implementations. Use a filename instead.
Implements stir::InputFileFormat< DiscretisedDensity< 3, float > >.
References stir::error().
read_from_file() [2/2]
virtual unique_ptr< data_type > stir::ecat::ecat7::ECAT7ImageInputFileFormat::read_from_file (const std::string & filename) const inline protected virtual
read data from a filename
This function should throw an exception if the read fails.
Default implementation used open_read_binary and read_from_file(std::istream&).
Reimplemented from stir::InputFileFormat< DiscretisedDensity< 3, float > >.
References stir::error(), stir::ecat::ecat7::is_ECAT7_image_file(), and stir::warning().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/ECAT7ImageInputFileFormat.h