STIR: stir::InterfileImageInputFileFormat Class Reference
stir::InterfileImageInputFileFormat Class Reference
STIR » STIR library » Input/Output Library
Class for reading images in Interfile file-format.
#include "stir/IO/InterfileImageInputFileFormat.h"
Public Member Functions
const std::string get_name () const override
Public Member Functions inherited from stir::InputFileFormat< DiscretisedDensity< 3, float > >
virtual bool can_read (const FileSignature &signature, std::istream &input) const
virtual bool can_read (const FileSignature &signature, const std::string &filename) const
Protected Member Functions
bool actual_can_read (const FileSignature &signature, std::istream &input) const override
unique_ptr< data_type > read_from_file (std::istream &input) const override
read data from a stream
unique_ptr< data_type > read_from_file (const std::string &filename) const override
read data from a filename
Additional Inherited Members
Public Types inherited from stir::InputFileFormat< DiscretisedDensity< 3, float > >
typedef DiscretisedDensity< 3, float > data_type
Detailed Description
Class for reading images in Interfile file-format.
Member Function Documentation
get_name()
const std::string stir::InterfileImageInputFileFormat::get_name () const inline override virtual
Implements stir::InputFileFormat< DiscretisedDensity< 3, float > >.
actual_can_read()
bool stir::InterfileImageInputFileFormat::actual_can_read (const FileSignature & signature, std::istream & input) const inline override protected virtual
Implements stir::InputFileFormat< DiscretisedDensity< 3, float > >.
read_from_file() [1/2]
unique_ptr< data_type > stir::InterfileImageInputFileFormat::read_from_file (std::istream & input) const inline override protected virtual
read data from a stream
This function should throw an exception if the read fails.
Warning
This member throws for most implementations. Use a filename instead.
Implements stir::InputFileFormat< DiscretisedDensity< 3, float > >.
References stir::error(), and stir::read_interfile_image().
read_from_file() [2/2]
unique_ptr< data_type > stir::InterfileImageInputFileFormat::read_from_file (const std::string & filename) const inline override protected virtual
read data from a filename
This function should throw an exception if the read fails.
Default implementation used open_read_binary and read_from_file(std::istream&).
Reimplemented from stir::InputFileFormat< DiscretisedDensity< 3, float > >.
References stir::error(), and stir::read_interfile_image().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/InterfileImageInputFileFormat.h