STIR: stir::ProjDataInfoCylindricalArcCorr Class Reference
stir::ProjDataInfoCylindricalArcCorr Class Reference
STIR » STIR library » Basic building blocks » Items related to projection data
Projection data info for arc-corrected data.
#include "stir/ProjDataInfoCylindricalArcCorr.h"
Public Member Functions
ProjDataInfoCylindricalArcCorr ()
Constructors.
ProjDataInfoCylindricalArcCorr (const shared_ptr< Scanner > scanner_ptr, float bin_size, const VectorWithOffset< int > &num_axial_pos_per_segment, const VectorWithOffset< int > &min_ring_diff_v, const VectorWithOffset< int > &max_ring_diff_v, const int num_views, const int num_tangential_poss, const int tof_mash_factor=0)
self_type * clone () const override
Standard trick for a 'virtual copy-constructor'.
bool operator== (const self_type &) const
float get_s (const Bin &) const override
Get value of the tangential coordinate in the projection plane (in mm)
void set_tangential_sampling (const float bin_size)
Set tangential sampling.
float get_tangential_sampling () const
Get tangential sampling.
float get_sampling_in_s (const Bin &) const override
Get sampling distance in the s coordinate.
Bin get_bin (const LOR< float > &, const double delta_time=0.0) const override
Find the bin in the projection data that 'contains' an LOR.
std::string parameter_info () const override
Return a string describing the object.
Public Member Functions inherited from stir::ProjDataInfoCylindrical
ProjDataInfoCylindrical ()
Constructors.
ProjDataInfoCylindrical (const shared_ptr< Scanner > &scanner_ptr, const VectorWithOffset< int > &num_axial_poss_per_segment, const VectorWithOffset< int > &min_ring_diff, const VectorWithOffset< int > &max_ring_diff, const int num_views, const int num_tangential_poss)
Constructor given all the necessary information.
float get_tantheta (const Bin &) const override
Get tangent of the co-polar angle of the normal to the projection plane.
float get_phi (const Bin &) const override
Get azimuthal angle phi of the normal to the projection plane.
float get_t (const Bin &) const override
Get value of the (roughly) axial coordinate in the projection plane (in mm)
float get_m (const Bin &) const override
Return z-coordinate of the middle of the LOR.
void get_LOR (LORInAxialAndNoArcCorrSinogramCoordinates< float > &lor, const Bin &bin) const override
Get LOR corresponding to a given bin.
virtual void set_azimuthal_angle_offset (const float angle)
Set azimuthal angle offset (in radians)
virtual void set_azimuthal_angle_sampling (const float angle)
Set the azimuthal sampling (in radians)
void set_num_views (const int new_num_views) override
set new number of views, covering the same azimuthal angle range
void set_tof_mash_factor (const int new_num) override
The tof mashing factor (for TOF scanners).
virtual float get_azimuthal_angle_offset () const
Get azimuthal angle offset (in radians)
virtual float get_azimuthal_angle_sampling () const
Get the azimuthal sampling (in radians)
float get_sampling_in_t (const Bin &) const override
Get sampling distance in the t coordinate.
float get_sampling_in_m (const Bin &) const override
Get sampling distance in the m coordinate.
virtual float get_axial_sampling (int segment_num) const
Get the axial sampling (e.g in z_direction)
virtual bool axial_sampling_is_uniform () const
Return if axial sampling makes sense.
float get_average_ring_difference (int segment_num) const
Get average ring difference for the given segment.
int get_min_ring_difference (int segment_num) const
Get minimum ring difference for the given segment.
int get_max_ring_difference (int segment_num) const
Get maximum ring difference for the given segment.
void set_min_ring_difference (int min_ring_diff_v, int segment_num)
Set minimum ring difference.
void set_max_ring_difference (int max_ring_diff_v, int segment_num)
Set maximum ring difference.
void set_num_axial_poss_per_segment (const VectorWithOffset< int > &num_axial_poss_per_segment) override
Set number of axial positions per segment.
void set_min_axial_pos_num (const int min_ax_pos_num, const int segment_num) override
Set minimum axial position number for 1 segment.
void set_max_axial_pos_num (const int max_ax_pos_num, const int segment_num) override
Set maximum axial position number for 1 segment.
void reduce_segment_range (const int min_segment_num, const int max_segment_num) override
Set a new range of segment numbers.
virtual void set_ring_radii_for_all_views (const VectorWithOffset< float > &new_ring_radius)
Set detector ring radius for all views.
virtual VectorWithOffset< float > get_ring_radii_for_all_views () const
Get detector ring radius for all views.
virtual float get_ring_radius () const
Get detector ring radius.
virtual float get_ring_radius (const int view_num) const
virtual float get_ring_spacing () const
Get detector ring spacing.
virtual void set_ring_spacing (float ring_spacing_v)
Set detector ring spacing.
virtual int get_view_mashing_factor () const
Get the mashing factor, i.e. how many 'original' views are combined.
Succeeded get_segment_num_for_ring_difference (int &segment_num, const int ring_diff) const
Find which segment a particular ring difference belongs to.
Succeeded get_segment_axial_pos_num_for_ring_pair (int &segment_num, int &axial_pos_num, const int ring1, const int ring2) const
Find to which segment and axial position a ring pair contributes.
const RingNumPairs & get_all_ring_pairs_for_segment_axial_pos_num (const int segment_num, const int axial_pos_num) const
Find all ring pairs that contribute to a segment and axial position.
unsigned get_num_ring_pairs_for_segment_axial_pos_num (const int segment_num, const int axial_pos_num) const
Find the number of ring pairs that contribute to a segment and axial position.
void get_ring_pair_for_segment_axial_pos_num (int &ring1, int &ring2, const int segment_num, const int axial_pos_num) const
Find a ring pair that contributes to a segment and axial position.
Public Member Functions inherited from stir::ProjDataInfo
ProjDataInfo ()
Construct an empty object.
ProjDataInfo (const shared_ptr< Scanner > &scanner_ptr, const VectorWithOffset< int > &num_axial_pos_per_segment, const int num_views, const int num_tangential_poss)
Constructor setting all relevant info for a ProjDataInfo.
ProjDataInfo (const shared_ptr< Scanner > &scanner_ptr, const VectorWithOffset< int > &num_axial_pos_per_segment, const int num_views, const int num_tangential_poss, const int tof_mash_factor)
Overloaded Contructor with TOF initialisation.
shared_ptr< ProjDataInfo > create_shared_clone () const
Like clone() but return a shared_ptr.
shared_ptr< ProjDataInfo > create_non_tof_clone () const
Similar to create_shared_clone() but returns a non-tof version of ProjDataInfo setting tof mashing factor = 0.
virtual ~ProjDataInfo ()
Destructor.
virtual void set_num_tangential_poss (const int num_tang_poss)
Set number of tangential positions.
virtual void set_min_tangential_pos_num (const int min_tang_poss)
Set minimum tangential position number.
virtual void set_max_tangential_pos_num (const int max_tang_poss)
Set maximum tangential position number.
int get_num_segments () const
Get number of segments.
int get_num_axial_poss (const int segment_num) const
Get number of axial positions per segment.
int get_num_views () const
Get number of views.
int get_num_tangential_poss () const
Get number of tangential positions.
int get_tof_bin (const double delta) const
Get number of tof bin for a given time difference.
int get_num_tof_poss () const
Get number of TOF bins.
int get_min_segment_num () const
Get minimum segment number.
int get_max_segment_num () const
Get maximum segment number.
int get_min_axial_pos_num (const int segment_num) const
Get minimum axial position per segmnet.
int get_max_axial_pos_num (const int segment_num) const
Get maximum axial position per segment.
int get_min_view_num () const
Get minimum view number.
int get_max_view_num () const
Get maximum view number.
int get_min_tangential_pos_num () const
Get minimum tangential position number.
int get_max_tangential_pos_num () const
Get maximum tangential position number.
int get_tof_mash_factor () const
Get TOF mash factor.
int get_min_tof_pos_num () const
Get the index of the first TOF position.
int get_max_tof_pos_num () const
Get the index of the last timgin position.
int get_num_sinograms () const
Get the total number of sinograms.
int get_num_non_tof_sinograms () const
Get the number of non-tof sinograms.
std::size_t size_all () const
Get the total size of the data.
bool is_tof_data () const
Determine if TOF data from tof_mash_factor and num_tof_bins.
virtual std::vector< int > get_original_view_nums () const
Return a list of view numbers in the "original" data if subsets are used.
float get_costheta (const Bin &) const
Get cosine of the co-polar angle of the normal to the projection plane.
float get_k (const Bin &) const
Get value of the TOF location along the LOR (in mm) k is a line segment connecting the centers of the two detectors.
double get_tof_delta_time (const Bin &) const
Get the value of the TOF timing difference (in ps)
float get_sampling_in_k (const Bin &) const
Get sampling distance in the k coordinate.
bool operator== (const ProjDataInfo &proj) const
check equality
bool operator!= (const ProjDataInfo &proj) const
virtual bool operator>= (const ProjDataInfo &proj) const
Check if *this contains proj.
Viewgram< float > get_empty_viewgram (const ViewgramIndices &) const
Get empty viewgram.
Sinogram< float > get_empty_sinogram (const SinogramIndices &) const
Get empty_sinogram.
SegmentByView< float > get_empty_segment_by_view (const SegmentIndices &) const
Get empty segment sino.
SegmentBySinogram< float > get_empty_segment_by_sinogram (const SegmentIndices &) const
Get empty segment view.
Viewgram< float > get_empty_viewgram (const int view_num, const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty viewgram.
Sinogram< float > get_empty_sinogram (const int ax_pos_num, const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty_sinogram.
SegmentByView< float > get_empty_segment_by_view (const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty segment sino.
SegmentBySinogram< float > get_empty_segment_by_sinogram (const int segment_num, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty segment view.
RelatedViewgrams< float > get_empty_related_viewgrams (const ViewgramIndices &, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &, const bool make_num_tangential_poss_odd=false, const int timing_pos_num=0) const
Get empty related viewgrams, where the symmetries_ptr specifies the symmetries to use.
const Scanner * get_scanner_ptr () const
Get scanner pointer.
shared_ptr< Scanner > get_scanner_sptr () const
Get scanner shared pointer.
void set_bed_position_horizontal (const float bed_position_horizontal_arg)
Vector which holds the lower and higher boundary for each TOF position, without the application of TOF mashing, in mm, for faster access.
float get_bed_position_horizontal () const
Get horizontal bed position.
void set_bed_position_vertical (const float bed_position_vertical_arg)
Set vertical bed position.
float get_bed_position_vertical () const
Get vertical bed position.
bool has_energy_information () const
Additional Inherited Members
Public Types inherited from stir::ProjDataInfoCylindrical
typedef std::vector< std::pair< int, int > > RingNumPairs
Type used by get_all_ring_pairs_for_segment_axial_pos_num()
Static Public Member Functions inherited from stir::ProjDataInfo
static ProjDataInfo * ask_parameters ()
Ask for the details and return a ProjDataInfo pointer.
static ProjDataInfo * ProjDataInfoGE (const shared_ptr< Scanner > &scanner_ptr, const int max_delta, const int num_views, const int num_tangential_poss, const bool arc_corrected=true, const int tof_mash_factor=0)
Construct a ProjDataInfo with span=3 for segment 0, but span=1 for others.
static ProjDataInfo * ProjDataInfoCTI (const shared_ptr< Scanner > &scanner_ptr, const int span, const int max_delta, const int num_views, const int num_tangential_poss, const bool arc_corrected=true, const int tof_mash_factor=0)
Old name for construct_proj_data_info()
static unique_ptr< ProjDataInfo > construct_proj_data_info (const shared_ptr< Scanner > &scanner_sptr, const int span, const int max_delta, const int num_views, const int num_tangential_poss, const bool arc_corrected=true, const int tof_mash_factor=0)
Construct a ProjDataInfo suitable with a given span.
VectorWithOffset< Float1Float2 > tof_bin_boundaries_mm
Vector which holds the lower and higher boundary for each TOF position in mm, for faster access.
VectorWithOffset< Float1Float2 > tof_bin_boundaries_ps
Vector which holds the lower and higher boundary for each TOF position in ps`, for faster access.
Protected Types inherited from stir::ProjDataInfo
typedef ProjDataInfo root_type
Protected Attributes inherited from stir::ProjDataInfoCylindrical
bool sampling_corresponds_to_physical_rings
a variable that is set if the data corresponds to physical rings in the scanner
Detailed Description
Projection data info for arc-corrected data.
This means that 'tangential_pos_num' actually indexes a linear coordinate with a particular sampling distance (usually called the 'bin_size').
Member Function Documentation
clone()
ProjDataInfoCylindricalArcCorr * stir::ProjDataInfoCylindricalArcCorr::clone () const override virtual
Standard trick for a 'virtual copy-constructor'.
Implements stir::ProjDataInfo.
get_s()
float stir::ProjDataInfoCylindricalArcCorr::get_s (const Bin &) const inline override virtual
Get value of the tangential coordinate in the projection plane (in mm)
s-axis is defined to be orthogonal to the scanner axis (and to the vector normal to the projection plane
Implements stir::ProjDataInfo.
References get_s(), and stir::Bin::tangential_pos_num().
Referenced by get_s(), and stir::ProjDataInfoCylindricalArcCorrTests::run_tests().
get_sampling_in_s()
float stir::ProjDataInfoCylindricalArcCorr::get_sampling_in_s (const Bin & bin) const inline override virtual
Get sampling distance in the s coordinate.
For some coordinate systems, this might depend on the Bin. The default implementation computes it as
1/2(get_s(..., tang_pos+1)-get_s(..., tang_pos_pos-1)))
Reimplemented from stir::ProjDataInfo.
get_bin()
Bin stir::ProjDataInfoCylindricalArcCorr::get_bin (const LOR< float > & , const double delta_time = 0.0) const override virtual
Find the bin in the projection data that 'contains' an LOR.
Projection data corresponds to lines, so most Lines Of Response (LORs) there is a bin in the projection data. Usually this will be the bin which has a central LOR that is 'closest' to the LOR that is passed as an argument.
If there is no such bin (e.g. the LOR does not intersect the detectors, Bin::get_bin_value() will be less than 0, otherwise it will be 1.
Warning
This function might get a different type of arguments in the next release.
See also
get_LOR()
Implements stir::ProjDataInfo.
References stir::Bin::axial_pos_num(), stir::error(), stir::ProjDataInfoCylindrical::get_axial_sampling(), stir::ProjDataInfoCylindrical::get_azimuthal_angle_offset(), stir::ProjDataInfoCylindrical::get_azimuthal_angle_sampling(), stir::ProjDataInfoCylindrical::get_m(), stir::ProjDataInfo::get_max_axial_pos_num(), stir::ProjDataInfoCylindrical::get_max_ring_difference(), stir::ProjDataInfo::get_max_segment_num(), stir::ProjDataInfo::get_max_tangential_pos_num(), stir::ProjDataInfo::get_max_view_num(), stir::ProjDataInfo::get_min_axial_pos_num(), stir::ProjDataInfoCylindrical::get_min_ring_difference(), stir::ProjDataInfo::get_min_segment_num(), stir::ProjDataInfo::get_min_tangential_pos_num(), stir::Scanner::get_num_rings(), stir::ProjDataInfo::get_num_views(), stir::ProjDataInfoCylindrical::get_ring_radius(), stir::ProjDataInfoCylindrical::get_ring_spacing(), stir::ProjDataInfo::get_scanner_ptr(), stir::ProjDataInfoCylindrical::get_segment_axial_pos_num_for_ring_pair(), get_tangential_sampling(), stir::round(), stir::SegmentIndices::segment_num(), stir::Bin::set_bin_value(), stir::Bin::tangential_pos_num(), stir::to_0_2pi(), and stir::ViewgramIndices::view_num().
parameter_info()
string stir::ProjDataInfoCylindricalArcCorr::parameter_info () const override virtual
Return a string describing the object.
Reimplemented from stir::ProjDataInfoCylindrical.
References get_tangential_sampling(), and stir::ProjDataInfoCylindrical::parameter_info().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/ProjDataInfoCylindricalArcCorr.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/ProjDataInfoCylindricalArcCorr.cxx
/home/kris/devel/STIRdistrib/STIR/src/include/stir/ProjDataInfoCylindricalArcCorr.inl