STIR: stir::CListModeDataSAFIR< CListRecordT > Class Template Reference
stir::CListModeDataSAFIR< CListRecordT > Class Template Reference
STIR » STIR library » Support classes for reading list mode data
Class for reading SAFIR listmode data with variable geometry.
#include "stir/listmode/CListModeDataSAFIR.h"
Public Member Functions
CListModeDataSAFIR (const std::string &listmode_filename, const std::string &crystal_map_filename, const std::string &template_proj_data_filename, const double lor_randomization_sigma=0.0)
CListModeDataSAFIR (const std::string &listmode_filename, const shared_ptr< const ProjDataInfo > &proj_data_info_sptr)
virtual std::string get_name () const
Returns the name of the list mode data.
virtual shared_ptr< CListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (CListRecord &record_of_general_type) const
Gets the next record in the listmode sequence.
virtual Succeeded reset ()
Call this function if you want to re-start reading at the beginning.
virtual SavedPosition save_get_position ()
virtual Succeeded set_get_position (const SavedPosition &pos)
Set the position for reading to a previously saved point.
virtual bool has_delayeds () const
Public Member Functions inherited from stir::ListModeData
ListModeData ()
Default constructor.
shared_ptr< ListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (ListRecord &event) const
Gets the next record in the listmode sequence.
virtual const Scanner * get_scanner_ptr () const
Get scanner pointer.
virtual unsigned long int get_total_number_of_events () const
Returns the total number of events in the listmode file.
virtual shared_ptr< const ProjDataInfo > get_proj_data_info_sptr () const
Public Member Functions inherited from stir::ExamData
ExamData ()
ExamData.
ExamData (const shared_ptr< const ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual shared_ptr< const ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
void set_exam_info_sptr (shared_ptr< const ExamInfo > new_exam_info_sptr)
Additional Inherited Members
Public Types inherited from stir::ListModeData
typedef ListModeData hierarchy_base_type
typedef used by read_from_file
typedef unsigned int SavedPosition
Use this typedef for save/set_get_position.
Protected Member Functions inherited from stir::CListModeData
virtual shared_ptr< ListRecord > get_empty_record_helper_sptr () const
virtual Succeeded get_next (ListRecord &event) const
Protected Member Functions inherited from stir::ListModeData
virtual void set_proj_data_info_sptr (shared_ptr< const ProjDataInfo >)
Protected Attributes inherited from stir::ListModeData
shared_ptr< const ProjDataInfo > proj_data_info_sptr
Has to be set by the derived class.
Protected Attributes inherited from stir::ExamData
shared_ptr< const ExamInfo > exam_info_sptr
Detailed Description
template<class CListRecordT>
class stir::CListModeDataSAFIR< CListRecordT >
Class for reading SAFIR listmode data with variable geometry.
By providing crystal map and template projection data files, the coordinates are read from files and used defining the LOR coordinates.
Constructor & Destructor Documentation
CListModeDataSAFIR()
template<class CListRecordT > stir::CListModeDataSAFIR< CListRecordT >::CListModeDataSAFIR (const std::string & listmode_filename, const std::string & crystal_map_filename, const std::string & template_proj_data_filename, const double lor_randomization_sigma = 0.0)
Constructor
Takes as arguments the filenames of the coicidence listmode file, the crystal map (text) file, and the template projection data file
References stir::error(), stir::CListModeDataSAFIR< CListRecordT >::get_name(), stir::ListModeData::proj_data_info_sptr, and stir::ProjData::read_from_file().
Member Function Documentation
get_name()
template<class CListRecordT > std::string stir::CListModeDataSAFIR< CListRecordT >::get_name () const virtual
Returns the name of the list mode data.
This name is not necessarily unique, and might be empty. However, it is expected (but not guaranteed) that ListModeData::read_from_file(lm_data_ptr->get_name()) would read the same list mode data.
The reason this cannot be guaranteed is largely in case the list mode data is not really on disk, but the object corresponds for instance to a Monte Carlo simulator.
Implements stir::ListModeData.
References stir::CListModeDataSAFIR< CListRecordT >::get_empty_record_sptr().
Referenced by stir::CListModeDataSAFIR< CListRecordT >::CListModeDataSAFIR().
get_empty_record_sptr()
template<class CListRecordT > shared_ptr< CListRecord > stir::CListModeDataSAFIR< CListRecordT >::get_empty_record_sptr () const virtual
Get a pointer to an empty record.
This is mainly/only useful to get a record of the correct type, that can then be passed to get_next_record().
Implements stir::CListModeData.
References stir::CListModeDataSAFIR< CListRecordT >::get_next_record().
Referenced by stir::CListModeDataSAFIR< CListRecordT >::get_name().
save_get_position()
template<class CListRecordT > virtual SavedPosition stir::CListModeDataSAFIR< CListRecordT >::save_get_position () inline virtual
This function should save the position in input file. This is not implemented but disabled. Returns 0 in the moement.
Todo:
Maybe provide real implementation?
Implements stir::ListModeData.
has_delayeds()
template<class CListRecordT > virtual bool stir::CListModeDataSAFIR< CListRecordT >::has_delayeds () const inline virtual
Returns just false in the moment.
Todo:
Implement this properly to check for delayed events in LM files.
Implements stir::CListModeData.
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/listmode/CListModeDataSAFIR.h
/home/sirfuser/devel/STIRdistrib/STIR/src/listmode_buildblock/CListModeDataSAFIR.cxx