STIR: stir::InputFileFormat< DataT > Class Template Reference
stir::InputFileFormat< DataT > Class Template Reference abstract
STIR » STIR library » Input/Output Library
Base-class for file-formats for reading.
#include "stir/IO/InputFileFormat.h"
Public Types
typedef DataT data_type
Public Member Functions
virtual bool can_read (const FileSignature &signature, std::istream &input) const
virtual bool can_read (const FileSignature &signature, const std::string &filename) const
virtual unique_ptr< DataT > read_from_file (std::istream &input) const =0
read data from a stream
virtual unique_ptr< DataT > read_from_file (const std::string &filename) const
read data from a filename
virtual const std::string get_name () const =0
Protected Member Functions
virtual bool actual_can_read (const FileSignature &signature, std::istream &input) const =0
Detailed Description
template<class DataT>
class stir::InputFileFormat< DataT >
Base-class for file-formats for reading.
Preliminary
Todo
should be able to open for input-output maybe
there is overlap between function having filenames or istreams. This is a bit of a mess. Also, some file formats we might only have an API for using C-style FILE.
Member Function Documentation
can_read() [1/2]
template<class DataT> virtual bool stir::InputFileFormat< DataT >::can_read (const FileSignature & signature, std::istream & input) const inline virtual
Reimplemented in stir::ecat::ecat7::ECAT966ListmodeInputFileFormat, stir::ITKImageInputFileFormat< STIRImageType >, and stir::SAFIRCListmodeInputFileFormat< EventDataType >.
can_read() [2/2]
template<class DataT> virtual bool stir::InputFileFormat< DataT >::can_read (const FileSignature & signature, const std::string & filename) const inline virtual
Reimplemented in stir::ecat::ecat7::ECAT966ListmodeInputFileFormat, stir::ITKImageInputFileFormat< STIRImageType >, and stir::SAFIRCListmodeInputFileFormat< EventDataType >.
read_from_file() [1/2]
template<class DataT> virtual unique_ptr< DataT > stir::InputFileFormat< DataT >::read_from_file (std::istream & input) const pure virtual
read data from a stream
This function should throw an exception if the read fails.
Warning
This member throws for most implementations. Use a filename instead.
Implemented in stir::ecat::ecat6::ECAT6ImageInputFileFormat, stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat, stir::ecat::ecat7::ECAT7ImageInputFileFormat, stir::ecat::ecat7::ECAT962ListmodeInputFileFormat, stir::ecat::ecat7::ECAT966ListmodeInputFileFormat, stir::ecat::ECAT8_32bitListmodeInputFileFormat, stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat, stir::InterfileDynamicDiscretisedDensityInputFileFormat, stir::InterfileImageInputFileFormat, stir::InterfileParametricDiscretisedDensityInputFileFormat, stir::ITKImageInputFileFormat< STIRImageType >, stir::MultiDynamicDiscretisedDensityInputFileFormat, stir::MultiParametricDiscretisedDensityInputFileFormat, stir::PENNListmodeInputFileFormat, stir::ROOTListmodeInputFileFormat, and stir::SAFIRCListmodeInputFileFormat< EventDataType >.
Referenced by read_from_file(), and stir::read_from_file().
read_from_file() [2/2]
template<class DataT> virtual unique_ptr< DataT > stir::InputFileFormat< DataT >::read_from_file (const std::string & filename) const inline virtual
read data from a filename
This function should throw an exception if the read fails.
Default implementation used open_read_binary and read_from_file(std::istream&).
Reimplemented in stir::ecat::ecat6::ECAT6ImageInputFileFormat, stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat, stir::ecat::ecat7::ECAT7ImageInputFileFormat, stir::ecat::ecat7::ECAT962ListmodeInputFileFormat, stir::ecat::ecat7::ECAT966ListmodeInputFileFormat, stir::ecat::ECAT8_32bitListmodeInputFileFormat, stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat, stir::InterfileDynamicDiscretisedDensityInputFileFormat, stir::InterfileImageInputFileFormat, stir::InterfileParametricDiscretisedDensityInputFileFormat, stir::ITKImageInputFileFormat< STIRImageType >, stir::MultiDynamicDiscretisedDensityInputFileFormat, stir::MultiParametricDiscretisedDensityInputFileFormat, stir::PENNListmodeInputFileFormat, stir::ROOTListmodeInputFileFormat, and stir::SAFIRCListmodeInputFileFormat< EventDataType >.
References stir::open_read_binary(), and read_from_file().
actual_can_read()
template<class DataT> virtual bool stir::InputFileFormat< DataT >::actual_can_read (const FileSignature & signature, std::istream & input) const protected pure virtual
Implemented in stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat, and stir::ecat::ecat7::ECAT966ListmodeInputFileFormat.
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/InputFileFormat.h