STIR: stir::CListModeDataLMF Class Reference
stir::CListModeDataLMF Class Reference
A class that reads the listmode data from an LMF file.
#include "stir_experimental/listmode/CListModeDataLMF.h"
Public Member Functions
CListModeDataLMF (const std::string &listmode_filename)
Constructor taking a filename.
virtual std::time_t get_scan_start_time_in_secs_since_1970 () const
virtual shared_ptr< CListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual bool has_delayeds () const
LMF listmode data stores delayed events as well (as opposed to prompts)
virtual Succeeded get_next_record (CListRecord &event) const
Gets the next record in the listmode sequence.
virtual Succeeded reset ()
Call this function if you want to re-start reading at the beginning.
virtual SavedPosition save_get_position ()
Save the current reading position.
virtual Succeeded set_get_position (const SavedPosition &)
Set the position for reading to a previously saved point.
Public Member Functions inherited from stir::ListModeData
ListModeData ()
Default constructor.
virtual std::string get_name () const =0
Returns the name of the list mode data.
shared_ptr< ListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (ListRecord &event) const
Gets the next record in the listmode sequence.
virtual const Scanner * get_scanner_ptr () const
Get scanner pointer.
virtual unsigned long int get_total_number_of_events () const
Returns the total number of events in the listmode file.
virtual shared_ptr< const ProjDataInfo > get_proj_data_info_sptr () const
Public Member Functions inherited from stir::ExamData
ExamData ()
ExamData.
ExamData (const shared_ptr< const ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual shared_ptr< const ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
void set_exam_info_sptr (shared_ptr< const ExamInfo > new_exam_info_sptr)
Additional Inherited Members
Public Types inherited from stir::ListModeData
typedef ListModeData hierarchy_base_type
typedef used by read_from_file
typedef unsigned int SavedPosition
Use this typedef for save/set_get_position.
Protected Member Functions inherited from stir::CListModeData
virtual shared_ptr< ListRecord > get_empty_record_helper_sptr () const
virtual Succeeded get_next (ListRecord &event) const
Protected Member Functions inherited from stir::ListModeData
virtual void set_proj_data_info_sptr (shared_ptr< const ProjDataInfo >)
Protected Attributes inherited from stir::ListModeData
shared_ptr< const ProjDataInfo > proj_data_info_sptr
Has to be set by the derived class.
Protected Attributes inherited from stir::ExamData
shared_ptr< const ExamInfo > exam_info_sptr
Detailed Description
A class that reads the listmode data from an LMF file.
Member Function Documentation
get_empty_record_sptr()
shared_ptr< CListRecord > stir::CListModeDataLMF::get_empty_record_sptr () const virtual
Get a pointer to an empty record.
This is mainly/only useful to get a record of the correct type, that can then be passed to get_next_record().
Implements stir::CListModeData.
References get_next_record().
Referenced by CListModeDataLMF().
save_get_position()
CListModeData::SavedPosition stir::CListModeDataLMF::save_get_position () virtual
Save the current reading position.
Note that the return value is not related to the number of events already read. In particular, you cannot do any arithmetic on it to skip a few events. This is different from e.g. std::streampos.
Warning
There is a maximum number of times this function can be called. This is determined by the SavedPosition type. Once you save more positions, the first positions will be overwritten. There is currently no way of finding out after how many times this will happen (but it's a large number...).
These saved positions are only valid for the lifetime of the ListModeData object.
A derived class might disable this facility. It will/should then always return Succeeded::no when calling set_get_position().
Implements stir::ListModeData.
References set_get_position().
Referenced by reset().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir_experimental/listmode/CListModeDataLMF.h
/home/sirfuser/devel/STIRdistrib/STIR/src/experimental/listmode/CListModeDataLMF.cxx