STIR: stir::Filter1D< T > Class Template Reference
stir::Filter1D< T > Class Template Reference abstract
Preliminary class for 1D filtering using FFTs.
#include "stir_experimental/Filter.h"
Public Member Functions
Filter1D (const int length_v)
Filter1D (const Array< 1, T > &filter)
void apply (Array< 1, T > &data)
Filters data (which has to be in the 'spatial' domain.
void apply (Array< 2, T > &data)
Applies the filter on each 1D subarray.
void apply (Array< 3, T > &data)
Applies the filter on each 1D subarray.
virtual std::string parameter_info () const =0
Public Member Functions inherited from stir::TimedObject
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers (bool do_reset=false) const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the CPU timer (since first use or last reset)
double get_wall_clock_timer_value () const
get current value of the wall-clock timer (since first use or last reset)
Public Attributes
Array< 1, float > filter
Stores the filter in frequency space (will be private sometime)
Detailed Description
template<class T>
class stir::Filter1D< T >
Preliminary class for 1D filtering using FFTs.
Warning
The filtering will be performed using the convlvC() function. See warnings in its documentation.
Todo
apply() members can't be const as they call TimedObject::start_timers()
Member Function Documentation
apply()
template<class T> void stir::Filter1D< T >::apply (Array< 1, T > & data) inline
Filters data (which has to be in the 'spatial' domain.
data will be padded with zeroes to the same length as the stored filter before filtering. This is done on a local copy of the data, such that the index range of data is not modified.
References apply(), stir::convlvC(), filter, stir::VectorWithOffset< T >::get_max_index(), stir::VectorWithOffset< T >::get_min_index(), stir::Array< num_dimensions, elemT >::grow(), stir::VectorWithOffset< T >::set_offset(), stir::TimedObject::start_timers(), and stir::TimedObject::stop_timers().
Referenced by apply(), apply(), and apply().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir_experimental/Filter.h