STIR: stir::Timer Class Reference
stir::Timer Class Reference abstract
STIR » STIR library » Basic building blocks
A general base class for timers. Interface is like a stop watch.
#include "stir/Timer.h"
Public Member Functions
void start (bool do_reset=false)
start stopwatch, optionally resetting first
void stop ()
stop stopwatch
void reset ()
reset stopwatch
double value () const
return value is undefined when start() is not called first.
Protected Member Functions
virtual double get_current_value () const =0
Protected Attributes
bool running
double previous_value
double previous_total_value
Detailed Description
A general base class for timers. Interface is like a stop watch.
Example of usage:
DerivedFromTimer t;
t.start();
// do things
cerr << t.value();
// do things
t.stop();
// do things
t.reset()
// etc
Derived classes simply have to implement the virtual function double get_current_value()
Member Function Documentation
start()
void stir::Timer::start (bool do_reset = false) inline
start stopwatch, optionally resetting first
the stopwatch should not be running already if asking to reset
References stir::error(), reset(), and start().
Referenced by stir::distributable_computation(), stir::distributable_computation_cache_enabled(), stir::OSSPSReconstruction< TargetT >::precompute_denominator_of_conditioner_without_penalty(), stir::LmToProjData::process_data(), stir::FourierRebinning::rebin(), stir::ProjDataInfoTests::run_Blocks_DOI_test(), stir::ProjDataInfoTests::run_coordinate_test(), stir::ProjDataInfoTests::run_coordinate_test_for_realistic_scanner(), stir::RigidObject3DTransformationTests::run_tests(), stir::ProjMatrixByBinPinholeSPECTUB::set_up(), stir::ProjMatrixByBinSPECTUB::set_up(), and start().
reset()
void stir::Timer::reset () inline
reset stopwatch
the stopwatch should not be running
References reset().
Referenced by stir::OSSPSReconstruction< TargetT >::precompute_denominator_of_conditioner_without_penalty(), reset(), stir::ProjDataInfoTests::run_Blocks_DOI_test(), stir::ProjDataInfoTests::run_coordinate_test(), stir::ProjDataInfoTests::run_coordinate_test_for_realistic_scanner(), stir::RigidObject3DTransformationTests::run_tests(), and start().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/Timer.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/Timer.inl