STIR: stir::MultiDynamicDiscretisedDensityInputFileFormat Class Reference
stir::MultiDynamicDiscretisedDensityInputFileFormat Class Reference
STIR » STIR library » Input/Output Library
Class for reading images in Multi file-format.
#include "stir/IO/MultiDynamicDiscretisedDensityInputFileFormat.h"
Public Member Functions
const std::string get_name () const override
Public Member Functions inherited from stir::InputFileFormat< DynamicDiscretisedDensity >
virtual bool can_read (const FileSignature &signature, std::istream &input) const
virtual bool can_read (const FileSignature &signature, const std::string &filename) const
Protected Member Functions
bool actual_can_read (const FileSignature &signature, std::istream &) const override
std::unique_ptr< data_type > read_from_file (std::istream &) const override
always throws via error()
std::unique_ptr< data_type > read_from_file (const std::string &filename) const override
read data from a filename
Additional Inherited Members
Public Types inherited from stir::InputFileFormat< DynamicDiscretisedDensity >
typedef DynamicDiscretisedDensity data_type
Detailed Description
Class for reading images in Multi file-format.
Member Function Documentation
get_name()
const std::string stir::MultiDynamicDiscretisedDensityInputFileFormat::get_name () const inline override virtual
Implements stir::InputFileFormat< DynamicDiscretisedDensity >.
actual_can_read()
bool stir::MultiDynamicDiscretisedDensityInputFileFormat::actual_can_read (const FileSignature & signature, std::istream &) const override protected virtual
Implements stir::InputFileFormat< DynamicDiscretisedDensity >.
read_from_file() [1/2]
std::unique_ptr< MultiDynamicDiscretisedDensityInputFileFormat::data_type > stir::MultiDynamicDiscretisedDensityInputFileFormat::read_from_file (std::istream &) const override protected virtual
always throws via error()
Implements stir::InputFileFormat< DynamicDiscretisedDensity >.
References stir::error(), and read_from_file().
Referenced by read_from_file(), and read_from_file().
read_from_file() [2/2]
std::unique_ptr< MultiDynamicDiscretisedDensityInputFileFormat::data_type > stir::MultiDynamicDiscretisedDensityInputFileFormat::read_from_file (const std::string & filename) const override protected virtual
read data from a filename
This function should throw an exception if the read fails.
Default implementation used open_read_binary and read_from_file(std::istream&).
Reimplemented from stir::InputFileFormat< DynamicDiscretisedDensity >.
References stir::error(), stir::Scanner::get_scanner_from_name(), stir::KeyParser::parse(), stir::DiscretisedDensity< num_dimensions, elemT >::read_from_file(), read_from_file(), stir::DynamicDiscretisedDensity::set_density(), stir::ExamData::set_exam_info(), stir::TimeFrameDefinitions::set_num_time_frames(), and stir::TimeFrameDefinitions::set_time_frame().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/MultiDynamicDiscretisedDensityInputFileFormat.h
/home/kris/devel/STIRdistrib/STIR/src/IO/MultiDynamicDiscretisedDensityInputFileFormat.cxx