STIR: stir::CListModeDataPENN Class Reference
stir::CListModeDataPENN Class Reference
Base class for listmode data for PENNPET Explorer scanner.
#include "stir/listmode/CListModeDataPENN.h"
Public Member Functions
CListModeDataPENN (const std::string &listmode_filename_prefix)
Construct fron the filename of the Interfile header.
virtual std::string get_name () const
Returns the name of the list mode data.
virtual shared_ptr< CListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (CListRecord &record) const
Gets the next record in the listmode sequence.
virtual Succeeded reset ()
Call this function if you want to re-start reading at the beginning.
virtual SavedPosition save_get_position ()
Save the current reading position.
virtual Succeeded set_get_position (const SavedPosition &)
Set the position for reading to a previously saved point.
virtual unsigned long int get_total_number_of_events () const
The safest way to get the total number of events is to count them.
virtual bool has_delayeds () const
Return if the file stores delayed events as well (as opposed to prompts)
void set_output_filename (const std::string ofname)
void set_event ()
void set_event (const bool &is_delay, const short int &_dt, const unsigned short int &_xa, const unsigned short int &_xb, const unsigned short int &_za, const unsigned short int &_zb, const unsigned short int &_ea, const unsigned short int &_eb)
Public Member Functions inherited from stir::ListModeData
ListModeData ()
Default constructor.
shared_ptr< ListRecord > get_empty_record_sptr () const
Get a pointer to an empty record.
virtual Succeeded get_next_record (ListRecord &event) const
Gets the next record in the listmode sequence.
virtual const Scanner * get_scanner_ptr () const
Get scanner pointer.
virtual shared_ptr< const ProjDataInfo > get_proj_data_info_sptr () const
Public Member Functions inherited from stir::ExamData
ExamData ()
ExamData.
ExamData (const shared_ptr< const ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual shared_ptr< const ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
void set_exam_info_sptr (shared_ptr< const ExamInfo > new_exam_info_sptr)
Additional Inherited Members
Public Types inherited from stir::ListModeData
typedef ListModeData hierarchy_base_type
typedef used by read_from_file
typedef unsigned int SavedPosition
Use this typedef for save/set_get_position.
Protected Member Functions inherited from stir::CListModeData
virtual shared_ptr< ListRecord > get_empty_record_helper_sptr () const
virtual Succeeded get_next (ListRecord &event) const
Protected Member Functions inherited from stir::ListModeData
virtual void set_proj_data_info_sptr (shared_ptr< const ProjDataInfo >)
Protected Attributes inherited from stir::ListModeData
shared_ptr< const ProjDataInfo > proj_data_info_sptr
Has to be set by the derived class.
Protected Attributes inherited from stir::ExamData
shared_ptr< const ExamInfo > exam_info_sptr
Detailed Description
Base class for listmode data for PENNPET Explorer scanner.
Member Function Documentation
get_name()
std::string stir::CListModeDataPENN::get_name () const virtual
Returns the name of the list mode data.
This name is not necessarily unique, and might be empty. However, it is expected (but not guaranteed) that ListModeData::read_from_file(lm_data_ptr->get_name()) would read the same list mode data.
The reason this cannot be guaranteed is largely in case the list mode data is not really on disk, but the object corresponds for instance to a Monte Carlo simulator.
Implements stir::ListModeData.
References get_empty_record_sptr().
Referenced by CListModeDataPENN().
get_empty_record_sptr()
shared_ptr< CListRecord > stir::CListModeDataPENN::get_empty_record_sptr () const virtual
Get a pointer to an empty record.
This is mainly/only useful to get a record of the correct type, that can then be passed to get_next_record().
Implements stir::CListModeData.
References get_next_record().
Referenced by get_name().
save_get_position()
CListModeData::SavedPosition stir::CListModeDataPENN::save_get_position () virtual
Save the current reading position.
Note that the return value is not related to the number of events already read. In particular, you cannot do any arithmetic on it to skip a few events. This is different from e.g. std::streampos.
Warning
There is a maximum number of times this function can be called. This is determined by the SavedPosition type. Once you save more positions, the first positions will be overwritten. There is currently no way of finding out after how many times this will happen (but it's a large number...).
These saved positions are only valid for the lifetime of the ListModeData object.
A derived class might disable this facility. It will/should then always return Succeeded::no when calling set_get_position().
Implements stir::ListModeData.
References set_get_position().
Referenced by reset().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/listmode/CListModeDataPENN.h
/home/sirfuser/devel/STIRdistrib/STIR/src/listmode_buildblock/CListModeDataPENN.cxx