STIR: stir::CListRecordROOT Class Reference
stir::CListRecordROOT Class Reference
A class for a general element of a listmode file for a Siemens scanner using the ROOT files.
#include "stir/listmode/CListRecordROOT.h"
Public Member Functions
bool is_time () const override
Returns always true.
bool is_event () const override
Returns always true.
CListEventROOT & event () override
const CListEventROOT & event () const override
CListTimeROOT & time () override
const CListTimeROOT & time () const override
bool operator== (const CListRecord &e2) const
CListRecordROOT (const shared_ptr< const ProjDataInfo > &proj_data_info_sptr)
virtual Succeeded init_from_data (const int &ring1, const int &ring2, const int &crystal1, const int &crystal2, const double &time1, const double &delta_time, const int &event1, const int &event2)
Detailed Description
A class for a general element of a listmode file for a Siemens scanner using the ROOT files.
Member Function Documentation
is_time()
bool stir::CListRecordROOT::is_time () const inline override virtual
Returns always true.
Implements stir::ListRecord.
References is_time().
Referenced by is_time().
is_event()
bool stir::CListRecordROOT::is_event () const inline override virtual
Returns always true.
Implements stir::ListRecord.
References is_event().
Referenced by is_event().
event() [1/2]
CListEventROOT & stir::CListRecordROOT::event () inline override virtual
Implements stir::ListRecord.
event() [2/2]
const CListEventROOT & stir::CListRecordROOT::event () const inline override virtual
Implements stir::ListRecord.
time() [1/2]
CListTimeROOT & stir::CListRecordROOT::time () inline override virtual
Implements stir::ListRecord.
time() [2/2]
const CListTimeROOT & stir::CListRecordROOT::time () const inline override virtual
Implements stir::ListRecord.
init_from_data()
virtual Succeeded stir::CListRecordROOT::init_from_data (const int & ring1, const int & ring2, const int & crystal1, const int & crystal2, const double & time1, const double & delta_time, const int & event1, const int & event2) inline virtual
Warning
ROOT data are time and event at the same time.
Referenced by stir::InputStreamFromROOTFileForCylindricalPET::get_next_record(), and stir::InputStreamFromROOTFileForECATPET::get_next_record().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/CListRecordROOT.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/CListRecordROOT.inl