STIR: stir::ProjMatrixElemsForOneBinValue Class Reference
stir::ProjMatrixElemsForOneBinValue Class Reference
STIR » STIR library » Reconstruction building blocks » Projection building blocks
Stores voxel coordinates and the value of the matrix element.
#include "stir/recon_buildblock/ProjMatrixElemsForOneBinValue.h"
Public Member Functions
ProjMatrixElemsForOneBinValue (const BasicCoordinate< 3, int > &coords, const float ivalue=0)
BasicCoordinate< 3, int > get_coords () const
get the coordinates
int coord1 () const
In effect the same as get_coords()[1] (but faster)
int coord2 () const
In effect the same as get_coords()[2] (but faster)
int coord3 () const
In effect the same as get_coords()[3] (but faster)
float get_value () const
Get the value of the matrix element.
ProjMatrixElemsForOneBinValue & operator+= (const ProjMatrixElemsForOneBinValue &el2)
Adds el2.get_value() to the value of the current object.
ProjMatrixElemsForOneBinValue & operator*= (const float d)
Multiplies the value of with a float.
ProjMatrixElemsForOneBinValue & operator+= (const float d)
Adds a float to the value.
ProjMatrixElemsForOneBinValue & operator/= (const float d)
Divides the value of with a float.
Static Public Member Functions
static bool coordinates_equal (const ProjMatrixElemsForOneBinValue &el1, const ProjMatrixElemsForOneBinValue &el2)
Checks if the coordinates are equal.
static bool coordinates_less (const ProjMatrixElemsForOneBinValue &el1, const ProjMatrixElemsForOneBinValue &el2)
Checks lexicographical order of the coordinates.
Friends
bool operator== (const ProjMatrixElemsForOneBinValue &el1, const ProjMatrixElemsForOneBinValue &el2)
Checks coordinates and value are equal.
bool operator< (const ProjMatrixElemsForOneBinValue &el1, const ProjMatrixElemsForOneBinValue &el2)
Checks lexicographical order of the coordinates and the value.
Detailed Description
Stores voxel coordinates and the value of the matrix element.
(Probably) only useful in class ProjMatrixElemsForOneBin.
Warning
It is recommended never to use this class name directly, but always use the typedef ProjMatrixElemsForOneBin::value_type.
Voxel coordinates are currently stored as shorts for saving memory.
Member Function Documentation
coordinates_equal()
bool stir::ProjMatrixElemsForOneBinValue::coordinates_equal (const ProjMatrixElemsForOneBinValue & el1, const ProjMatrixElemsForOneBinValue & el2) inline static
Checks if the coordinates are equal.
This function and the next one below are implemented as static members, such that you can pass them (as functoon objects) to std::sort.
References coordinates_less().
Referenced by stir::ProjMatrixElemsForOneBin::check_state(), stir::ProjMatrixElemsForOneBin::merge(), and operator/=().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/ProjMatrixElemsForOneBinValue.h
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/ProjMatrixElemsForOneBinValue.inl