STIR: stir::Utah_phantom Class Reference
stir::Utah_phantom Class Reference
A class that represents a Utah phantom.
#include "stir_experimental/phantoms/Utah.h"
Public Member Functions
Utah_phantom ()
Construct a Utah phantom.
const shared_ptr< Shape3D > & get_A_ptr () const
const shared_ptr< Shape3D > & get_B_ptr () const
const shared_ptr< Shape3D > & get_full_B_ptr () const
get B without holes
const shared_ptr< Shape3D > & get_C_ptr () const
const shared_ptr< Shape3D > & get_full_C_ptr () const
get C without hole
const shared_ptr< Shape3D > & get_D_ptr () const
const shared_ptr< Shape3D > & get_E_ptr () const
shared_ptr< Shape3D > make_inside_B_ptr (const float fraction) const
make a region inside B when fraction<1.
shared_ptr< Shape3D > make_inside_C_ptr (const float fraction) const
make a region inside C when fraction<1.
void translate (const CartesianCoordinate3D< float > &direction)
void scale (const CartesianCoordinate3D< float > &scale3D)
Detailed Description
A class that represents a Utah phantom.
Todo
dims here are wrong A: cylinder, 20cm diam, 10cm height B: cylinder, 18cm diam, 15cm height C: outer annulus, 20cm extern.diam, 2cm thick, 15cm height D: cylinder in B, 4.5cm diam, 18cm??? height E: shorter cylinder in B, 4.5cm diam, 5.5cm height
Constructor & Destructor Documentation
Utah_phantom()
stir::Utah_phantom::Utah_phantom () inline
Construct a Utah phantom.
It is oriented along z, with edge between A and B at z=0.
References Utah_phantom().
Referenced by Utah_phantom().
Member Function Documentation
make_inside_B_ptr()
shared_ptr< Shape3D > stir::Utah_phantom::make_inside_B_ptr (const float fraction) const inline
make a region inside B when fraction<1.
The region has a smaller outer cylinder (scaled with fraction) and larger inner cylinders (scaled with 1/fraction).
References get_full_B_ptr(), and make_inside_B_ptr().
Referenced by make_inside_B_ptr().
make_inside_C_ptr()
shared_ptr< Shape3D > stir::Utah_phantom::make_inside_C_ptr (const float fraction) const inline
make a region inside C when fraction<1.
The region has a smaller outer cylinder (scaled with fraction) and larger inner cylinder (scaled with 1/fraction).
References get_full_B_ptr(), get_full_C_ptr(), and make_inside_C_ptr().
Referenced by make_inside_C_ptr().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir_experimental/phantoms/Utah.h