STIR: stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat Class Reference
stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat Class Reference
STIR » STIR library » Support classes for reading list mode data | STIR » STIR library » Input/Output Library | STIR » STIR library » Input/Output Library » support for GE data
Class for being able to read list mode data from the GE Signa PET/MR scanner via the listmode-data registry.
#include "stir/IO/GEHDF5ListmodeInputFileFormat.h"
Public Member Functions
const std::string get_name () const override
unique_ptr< data_type > read_from_file (std::istream &input) const override
read data from a stream
unique_ptr< data_type > read_from_file (const std::string &filename) const override
read data from a filename
Public Member Functions inherited from stir::InputFileFormat< ListModeData >
virtual bool can_read (const FileSignature &signature, std::istream &input) const
Protected Member Functions
bool actual_can_read (const FileSignature &signature, std::istream &input) const override
bool can_read (const FileSignature &signature, const std::string &filename) const override
Additional Inherited Members
Public Types inherited from stir::InputFileFormat< ListModeData >
typedef ListModeData data_type
Detailed Description
Class for being able to read list mode data from the GE Signa PET/MR scanner via the listmode-data registry.
Member Function Documentation
get_name()
const std::string stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat::get_name () const inline override virtual
Implements stir::InputFileFormat< ListModeData >.
actual_can_read()
bool stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat::actual_can_read (const FileSignature & signature, std::istream & input) const override protected virtual
Implements stir::InputFileFormat< ListModeData >.
can_read()
bool stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat::can_read (const FileSignature & signature, const std::string & filename) const override protected virtual
Reimplemented from stir::InputFileFormat< ListModeData >.
read_from_file() [1/2]
std::unique_ptr< ListModeData > stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat::read_from_file (std::istream & input) const override virtual
read data from a stream
This function should throw an exception if the read fails.
Warning
This member throws for most implementations. Use a filename instead.
Implements stir::InputFileFormat< ListModeData >.
References read_from_file(), and stir::warning().
Referenced by read_from_file(), and read_from_file().
read_from_file() [2/2]
std::unique_ptr< ListModeData > stir::GE::RDF_HDF5::GEHDF5ListmodeInputFileFormat::read_from_file (const std::string & filename) const override virtual
read data from a filename
This function should throw an exception if the read fails.
Default implementation used open_read_binary and read_from_file(std::istream&).
Reimplemented from stir::InputFileFormat< ListModeData >.
References read_from_file().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/GEHDF5ListmodeInputFileFormat.h
/home/kris/devel/STIRdistrib/STIR/src/IO/GEHDF5ListmodeInputFileFormat.cxx