STIR: stir::BloodFrameData Class Reference
stir::BloodFrameData Class Reference
STIR » STIR library » Kinetic modelling building blocks
A class for storing plasma samples of a single study.
#include "stir_experimental/modelling/BloodFrameData.h"
Public Types
typedef plot_type::const_iterator const_iterator
Public Member Functions
void read_blood_frame_data (const std::string input_string)
Implementation to read the input function from ONLY a 2-columns frame data (FrameNumber-InputFunctionRadioactivity).
void set_plot (const std::vector< BloodFrame > &blood_plot)
void shift_time (const float time_shift)
Implementation to set the input units not currently used. Always, it assumed to use kBq, seconds, ml.
float get_time_shift ()
Function to get the time data.
void set_isotope_halflife (const float isotope_halflife)
Function to set the isotope halflife.
void set_if_decay_corrected (const bool is_decay_corrected)
Function to set _is_decay_corrected boolean true ar false.
bool get_if_decay_corrected ()
Function to set _is_decay_corrected boolean true ar false.
void decay_correct_BloodFrameData ()
Function to decay correct the data.
BloodFrameData ()
default constructor
BloodFrameData (const std::vector< BloodFrame > &blood_plot)
constructor giving a vector
~BloodFrameData ()
default constructor
const_iterator begin () const
void begin() and end() iterators for the plasma curve ;
const_iterator end () const
unsigned int size () const
Detailed Description
A class for storing plasma samples of a single study.
Constructor & Destructor Documentation
~BloodFrameData()
stir::BloodFrameData::~BloodFrameData () inline
default constructor
default destructor
References ~BloodFrameData().
Referenced by ~BloodFrameData().
Member Function Documentation
shift_time()
void stir::BloodFrameData::shift_time (const float time_shift) inline
Implementation to set the input units not currently used. Always, it assumed to use kBq, seconds, ml.
Implementation to set the input units not currently used.
Function to shift the time data
References shift_time().
Referenced by shift_time().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir_experimental/modelling/BloodFrameData.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir_experimental/modelling/BloodFrameData.inl