STIR: stir::ProjMatrixByBinSinglePhoton Class Reference
stir::ProjMatrixByBinSinglePhoton Class Reference
STIR » STIR library » Reconstruction building blocks
a 'projection matrix' to implement a model for a single photon acquisition in terms of the detector efficiencies.
#include "stir_experimental/recon_buildblock/ProjMatrixByBinSinglePhoton.h"
Public Member Functions
ProjMatrixByBinSinglePhoton ()
Default constructor (calls set_defaults())
virtual void set_up (const shared_ptr< ProjDataInfo > &proj_data_info_ptr, const shared_ptr< DiscretisedDensity< 3, float > > &density_info_ptr)
Stores all necessary geometric info.
Public Member Functions inherited from stir::RegisteredParsingObject< ProjMatrixByBinSinglePhoton, ProjMatrixByBin, ProjMatrixByBin >
std::string get_registered_name () const
Returns Derived::registered_name.
std::string parameter_info ()
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::ProjMatrixByBin
const DataSymmetriesForBins * get_symmetries_ptr () const
get a pointer to an object encoding all symmetries that are used by this ProjMatrixByBin
const shared_ptr< DataSymmetriesForBins > get_symmetries_sptr () const
get a shared_ptr to an object encoding all symmetries that are used by this ProjMatrixByBin
void get_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin &, const Bin &) STIR_MUTABLE_CONST
The main method for getting a row of the matrix.
void enable_cache (const bool v=true)
void store_only_basic_bins_in_cache (const bool v=true)
bool is_cache_enabled () const
bool does_cache_store_only_basic_bins () const
void clear_cache () STIR_MUTABLE_CONST
Remove all elements from the cache.
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
void ask_parameters ()
bool parse (std::istream &f)
bool parse (const char *const filename)
Public Member Functions inherited from stir::TimedObject
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers () const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the timer (since first use or last reset)
Static Public Attributes
static const char *const registered_name
Name which will be used when parsing a ProjMatrixByBin object.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< ProjMatrixByBinSinglePhoton, ProjMatrixByBin, ProjMatrixByBin >
static ProjMatrixByBin * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< ProjMatrixByBin >
static ProjMatrixByBin * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static ProjMatrixByBin * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< ProjMatrixByBin >
typedef ProjMatrixByBin *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Protected Member Functions inherited from stir::ProjMatrixByBin
ProjMatrixByBin ()
default ctor (calls set_defaults())
virtual bool post_processing ()
Checks if parameters have sensible values.
Succeeded get_cached_proj_matrix_elems_for_one_bin (ProjMatrixElemsForOneBin &) const
The method that tries to get data from the cache.
void cache_proj_matrix_elems_for_one_bin (const ProjMatrixElemsForOneBin &) STIR_MUTABLE_CONST
The method to store data in the cache.
Protected Member Functions inherited from stir::ParsingObject
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< ProjMatrixByBin >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::ProjMatrixByBin
shared_ptr< DataSymmetriesForBins > symmetries_sptr
bool cache_disabled
bool cache_stores_only_basic_bins
Protected Attributes inherited from stir::ParsingObject
KeyParser parser
Detailed Description
a 'projection matrix' to implement a model for a single photon acquisition in terms of the detector efficiencies.
Todo:
This is a horrible work-around for the fact that STIR currently insists on working on a density.
Member Function Documentation
set_up()
void stir::ProjMatrixByBinSinglePhoton::set_up (const shared_ptr< ProjDataInfo > & proj_data_info_ptr, const shared_ptr< DiscretisedDensity< 3, float > > & density_info_ptr) virtual
Stores all necessary geometric info.
Note that the density_info_ptr is not stored in this object. It's only used to get some info on sizes etc.
Implements stir::ProjMatrixByBin.
References stir::error(), stir::ProjMatrixElemsForOneBin::get_bin(), stir::Array< num_dimensions, elemT >::get_regular_range(), stir::ProjMatrixElemsForOneBin::push_back(), and stir::ProjMatrixElemsForOneBin::size().
Member Data Documentation
registered_name
const char *const stir::ProjMatrixByBinSinglePhoton::registered_name static
Initial value:
=
  "Single Photon"
Name which will be used when parsing a ProjMatrixByBin object.
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir_experimental/recon_buildblock/ProjMatrixByBinSinglePhoton.h
/home/sirfuser/devel/STIRdistrib/STIR/src/experimental/recon_buildblock/ProjMatrixByBinSinglePhoton.cxx