STIR: stir::AbsTimeIntervalFromDynamicData Class Reference
stir::AbsTimeIntervalFromDynamicData Class Reference
STIR » STIR library » Basic building blocks
class for specifying a time interval via a dynamic scan
#include "stir_experimental/AbsTimeIntervalFromDynamicData.h"
Public Member Functions
AbsTimeIntervalFromDynamicData ()
default constructor gives ill-defined values
AbsTimeIntervalFromDynamicData (const std::string &filename, const unsigned int start_time_frame_num, const unsigned int end_time_frame_num)
read info from file
Public Member Functions inherited from stir::RegisteredParsingObject< AbsTimeIntervalFromDynamicData, AbsTimeInterval, AbsTimeInterval >
std::string get_registered_name () const
Returns Derived::registered_name.
std::string parameter_info ()
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::AbsTimeInterval
AbsTimeInterval (double start_time_in_secs_since_1970, double end_time_in_secs_since_1970)
double get_start_time_in_secs_since_1970 () const
double get_end_time_in_secs_since_1970 () const
double get_duration_in_secs () const
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
void ask_parameters ()
bool parse (std::istream &f)
bool parse (const char *const filename)
Static Public Attributes
static const char *const registered_name = "from Dynamic Data"
Name which will be used when parsing a AbsTimeInterval object.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< AbsTimeIntervalFromDynamicData, AbsTimeInterval, AbsTimeInterval >
static AbsTimeInterval * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< AbsTimeInterval >
static AbsTimeInterval * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static AbsTimeInterval * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< AbsTimeInterval >
typedef AbsTimeInterval *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Protected Member Functions inherited from stir::ParsingObject
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Static Protected Member Functions inherited from stir::RegisteredObject< AbsTimeInterval >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::AbsTimeInterval
double _start_time_in_secs_since_1970
double _end_time_in_secs_since_1970
Protected Attributes inherited from stir::ParsingObject
KeyParser parser
Detailed Description
class for specifying a time interval via a dynamic scan
The dynamic scan can be either a sinogram of an image. It is read via DynamicProjData or DynamicDiscretisedDensity.
Example .par file
  ; example keyword in some .par file
   time interval type:= from dynamic data
     Absolute Time Interval from dynamic data :=
       filename:=scandata.S
       start time frame:=1
       end time frame:=1
     end Absolute Time Interval from dynamic data :=
Constructor & Destructor Documentation
AbsTimeIntervalFromDynamicData()
stir::AbsTimeIntervalFromDynamicData::AbsTimeIntervalFromDynamicData (const std::string & filename, const unsigned int start_time_frame_num, const unsigned int end_time_frame_num)
read info from file
will call error() if something goes wrong
References stir::KeyParser::add_key(), stir::KeyParser::add_start_key(), stir::KeyParser::add_stop_key(), stir::error(), stir::info(), and stir::warning().
The documentation for this class was generated from the following files:
/home/sirfuser/devel/STIRdistrib/STIR/src/include/stir_experimental/AbsTimeIntervalFromDynamicData.h
/home/sirfuser/devel/STIRdistrib/STIR/src/experimental/buildblock/AbsTimeIntervalFromDynamicData.cxx