STIR: stir::LmToProjDataBootstrap< LmToProjDataT > Class Template Reference
stir::LmToProjDataBootstrap< LmToProjDataT > Class Template Reference
STIR » STIR library » Support classes for reading list mode data
Class for binning list mode data into projection data using the bootstrap procedure.
#include "stir/listmode/LmToProjDataBootstrap.h"
Public Member Functions
LmToProjDataBootstrap (const char *const par_filename)
Constructor that parses from a file.
LmToProjDataBootstrap (const char *const par_filename, const unsigned int seed)
Constructor that parses from a file but with explicit seed.
Succeeded set_up () override
Protected Member Functions
void start_new_time_frame (const unsigned int new_frame_num) override
will be called when a new time frame starts
void get_bin_from_event (Bin &bin, const ListEvent &) const override
Protected Attributes
unsigned int seed
used to seed the pseudo-random number generator
Detailed Description
template<typename LmToProjDataT>
class stir::LmToProjDataBootstrap< LmToProjDataT >
Class for binning list mode data into projection data using the bootstrap procedure.
The bootstrap method allows estimating the variance of an estimator based on a single data-set (magic!). This class can be used to generate multiple equivalent projdata, which can then be reconstructed. The sample variance computed on these images will be an estimate of the variance on the reconstructions.
For list mode data, bootstrapping works by selecting random events from the list mode file with replication (i.e. some events will occur more than once, other events will not occur at all).
There are various papers on the bootstrap method. For PET data, it was for example applied by I. Buvat. (TODO add references)
The pseudo-random number generator used is boost::mt19937 which should be good enough for most purposes. However, it can be easily replaced by any generator that follows the boost conventions.
Parsing
This class implements just one keyword in addition to those made available by its base type.
; an unsigned int (but not 0) to seed the pseudo-random number generator
seed := 42 ; default value
Notes for developers
This class is templated in terms of a LmToProjDataT to allow it to be used with different derived classes of LmToProjData. After all, the bootstrapping mechanism does not depend on how LmToProjData actually works.
Constructor & Destructor Documentation
LmToProjDataBootstrap()
template<typename LmToProjDataT> stir::LmToProjDataBootstrap< LmToProjDataT >::LmToProjDataBootstrap (const char *const par_filename, const unsigned int seed)
Constructor that parses from a file but with explicit seed.
The seed argument will override any value found in the par file
References LmToProjDataBootstrap(), seed, and stir::warning().
Member Function Documentation
start_new_time_frame()
template<typename LmToProjDataT> void stir::LmToProjDataBootstrap< LmToProjDataT >::start_new_time_frame (const unsigned int new_frame_num) override protected
will be called when a new time frame starts
Initialises a vector with the number of times each event has to be replicated
References stir::Bin::axial_pos_num(), stir::Bin::get_bin_value(), stir::info(), seed, stir::SegmentIndices::segment_num(), stir::Bin::set_bin_value(), start_new_time_frame(), stir::Bin::tangential_pos_num(), stir::ViewgramIndices::view_num(), and stir::warning().
Referenced by start_new_time_frame().
Member Data Documentation
seed
template<typename LmToProjDataT> unsigned int stir::LmToProjDataBootstrap< LmToProjDataT >::seed protected
used to seed the pseudo-random number generator
should be non-zero
Referenced by LmToProjDataBootstrap(), and start_new_time_frame().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/listmode/LmToProjDataBootstrap.h
/home/kris/devel/STIRdistrib/STIR/src/listmode_buildblock/LmToProjDataBootstrap.cxx