STIR: stir::CreateTailMaskFromACFs Class Reference
stir::CreateTailMaskFromACFs Class Reference
The CreateTailMaskFromACFs class.
#include "stir/scatter/CreateTailMaskFromACFs.h"
Public Member Functions
virtual Succeeded process_data ()
void set_input_projdata_sptr (shared_ptr< ProjData > &)
void set_input_projdata (std::string &)
void set_output_projdata_sptr (shared_ptr< ProjData > &)
void set_output_projdata (std::string &)
shared_ptr< ProjData > get_output_projdata_sptr ()
get_output_projdata
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
virtual std::string parameter_info ()
Public Attributes
float ACF_threshold
ACF_threshold.
int safety_margin
safety_margin
Protected Member Functions
void initialise_keymap () override
Initialise all keywords.
bool post_processing () override
This will be called at the end of the parsing.
void set_defaults () override
Set defaults before parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Additional Inherited Members
KeyParser parser
Detailed Description
The CreateTailMaskFromACFs class.
Author
Nikos Efthimiou
This class implements the functionality of the executable. It was nessesary in order to be able to perform this calculations from the ScatterEstimationByBin.
Member Function Documentation
get_output_projdata_sptr()
shared_ptr< ProjData > stir::CreateTailMaskFromACFs::get_output_projdata_sptr ()
get_output_projdata
Returns
Use this function to return the output projdata.
References get_output_projdata_sptr().
Referenced by get_output_projdata_sptr().
initialise_keymap()
void stir::CreateTailMaskFromACFs::initialise_keymap () override protected virtual
Initialise all keywords.
Reimplemented from stir::ParsingObject.
References ACF_threshold, initialise_keymap(), and safety_margin.
Referenced by initialise_keymap().
post_processing()
bool stir::CreateTailMaskFromACFs::post_processing () override protected virtual
This will be called at the end of the parsing.
Returns
false if everything OK, true if not
Reimplemented from stir::ParsingObject.
References ACF_threshold, stir::error(), and post_processing().
Referenced by post_processing().
set_defaults()
void stir::CreateTailMaskFromACFs::set_defaults () override protected virtual
Set defaults before parsing.
Reimplemented from stir::ParsingObject.
References ACF_threshold, safety_margin, and set_defaults().
Referenced by set_defaults().
Member Data Documentation
ACF_threshold
float stir::CreateTailMaskFromACFs::ACF_threshold
ACF_threshold.
Warning
ACF-threshold defaults to 1.1 (should be larger than 1)
Referenced by initialise_keymap(), post_processing(), and set_defaults().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/scatter/CreateTailMaskFromACFs.h
/home/kris/devel/STIRdistrib/STIR/src/scatter_buildblock/CreateTailMaskFromACFs.cxx