STIR: stir::BackProjectorByBinNiftyPET Class Reference
stir::BackProjectorByBinNiftyPET Class Reference
STIR » STIR library » Reconstruction building blocks » Projection building blocks
Class for NiftyPET's GPU back projector.
#include "stir/recon_buildblock/NiftyPET_projector/BackProjectorByBinNiftyPET.h"
Public Member Functions
BackProjectorByBinNiftyPET ()
Default constructor calls reset_timers()
virtual void initialise_keymap ()
Keymap.
virtual void set_up (const shared_ptr< const ProjDataInfo > &proj_data_info_ptr, const shared_ptr< const DiscretisedDensity< 3, float > > &density_info_sptr)
Stores all necessary geometric info.
virtual const DataSymmetriesForViewSegmentNumbers * get_symmetries_used () const
Symmetries not used, so returns TrivialDataSymmetriesForBins.
void back_project (const ProjData &, int subset_num=0, int num_subsets=1)
Back project.
virtual void get_output (DiscretisedDensity< 3, float > &) const
Get output.
virtual void start_accumulating_in_new_target ()
tell the back projector to start accumulating into a new target. This function has to be called before any back-projection is initiated.
void set_verbosity (const bool verbosity)
Set verbosity.
void set_use_truncation (const bool use_truncation)
Set use truncation - truncate before forward projection and after back projection.
Public Member Functions inherited from stir::RegisteredParsingObject< BackProjectorByBinNiftyPET, BackProjectorByBin >
std::string get_registered_name () const override
Returns Derived::registered_name.
std::string parameter_info () override
Returns a string with all parameters and their values, in a form suitable for parsing again.
Public Member Functions inherited from stir::BackProjectorByBin
BackProjectorByBin ()
Default constructor calls reset_timers()
void back_project (DiscretisedDensity< 3, float > &, const ProjData &, int subset_num=0, int num_subsets=1)
project whole proj_data into the volume
void back_project (const RelatedViewgrams< float > &)
projects the viewgrams into the volume it adds to the data backprojected since start_accumulating_in_new_target() was last called.
void back_project (const RelatedViewgrams< float > &, const int min_axial_pos_num, const int max_axial_pos_num)
projects the specified range of the viewgrams and axial positions into the volume it adds to the data backprojected since start_accumulating_in_new_target() was last called.
void back_project (const RelatedViewgrams< float > &, const int min_axial_pos_num, const int max_axial_pos_num, const int min_tangential_pos_num, const int max_tangential_pos_num)
projects the specified range of the viewgrams, axial positions and tangential positions into the volume it adds to the data backprojected since start_accumulating_in_new_target() was last called.
void set_post_data_processor (shared_ptr< DataProcessor< DiscretisedDensity< 3, float > > > post_data_processor_sptr)
Set data processor to use after back projection.
virtual BackProjectorByBin * clone () const =0
Public Member Functions inherited from stir::TimedObject
void reset_timers ()
reset all timers kept by this object
void stop_timers () const
stop all timers kept by this object
void start_timers (bool do_reset=false) const
start all timers kept by this object
double get_CPU_timer_value () const
get current value of the CPU timer (since first use or last reset)
double get_wall_clock_timer_value () const
get current value of the wall-clock timer (since first use or last reset)
Public Member Functions inherited from stir::ParsingObject
ParsingObject (const ParsingObject &)
ParsingObject & operator= (const ParsingObject &)
bool parse (std::istream &f)
bool parse (const char *const filename)
void ask_parameters ()
Static Public Attributes
static const char *const registered_name = "NiftyPET"
Name which will be used when parsing a BackProjectorByBin object.
Protected Member Functions
virtual void actual_back_project (const RelatedViewgrams< float > &, const int min_axial_pos_num, const int max_axial_pos_num, const int min_tangential_pos_num, const int max_tangential_pos_num)
This actually does the back projection. There are two versions of this code to enable backwards compatibility.
Protected Member Functions inherited from stir::BackProjectorByBin
virtual void actual_back_project (DiscretisedDensity< 3, float > &, const RelatedViewgrams< float > &, const int min_axial_pos_num, const int max_axial_pos_num, const int min_tangential_pos_num, const int max_tangential_pos_num)
This actually does the back projection. There are two versions of this code to enable backwards compatibility.
virtual void check (const ProjDataInfo &proj_data_info) const
check if the argument is the same as what was used for set_up()
virtual void check (const ProjDataInfo &proj_data_info, const DiscretisedDensity< 3, float > &density_info) const
check if the arguments are the same as what was used for set_up()
void set_defaults () override
Set defaults before parsing.
virtual bool post_processing ()
This will be called at the end of the parsing.
virtual void set_key_values ()
This will be called before parsing or parameter_info is called.
Additional Inherited Members
Static Public Member Functions inherited from stir::RegisteredParsingObject< BackProjectorByBinNiftyPET, BackProjectorByBin >
static BackProjectorByBin * read_from_stream (std::istream *)
Construct a new object (of type Derived) by parsing the istream.
Static Public Member Functions inherited from stir::RegisteredObject< BackProjectorByBin >
static BackProjectorByBin * read_registered_object (std::istream *in, const std::string &registered_name)
Construct a new object (of a type derived from Root, its actual type determined by the registered_name parameter) by parsing the istream.
static BackProjectorByBin * ask_type_and_parameters ()
ask the user for the type, and then calls read_registered_object(0, type)
static void list_registered_names (std::ostream &stream)
List all possible registered names to the stream.
Protected Types inherited from stir::RegisteredObject< BackProjectorByBin >
typedef BackProjectorByBin *(* RootFactory) (std::istream *)
The type of a root factory is a function, taking an istream* as argument, and returning a Root*.
typedef FactoryRegistry< std::string, RootFactory, interfile_less > RegistryType
The type of the registry.
Static Protected Member Functions inherited from stir::RegisteredObject< BackProjectorByBin >
static RegistryType & registry ()
Static function returning the registry.
Protected Attributes inherited from stir::BackProjectorByBin
bool _already_set_up
shared_ptr< DiscretisedDensity< 3, float > > _density_sptr
Clone of the density sptr set with set_up()
shared_ptr< DataProcessor< DiscretisedDensity< 3, float > > > _post_data_processor_sptr
shared_ptr< const ProjDataInfo > _proj_data_info_sptr
ProjDataInfo set by set_up()
KeyParser parser
Detailed Description
Class for NiftyPET's GPU back projector.
Only applicable for mMR data. Current limitations:
Projects all of the data in one go
Only debugged for span 11.
Member Function Documentation
initialise_keymap()
void stir::BackProjectorByBinNiftyPET::initialise_keymap () virtual
Keymap.
Reimplemented from stir::BackProjectorByBin.
set_up()
void stir::BackProjectorByBinNiftyPET::set_up (const shared_ptr< const ProjDataInfo > & proj_data_info_ptr, const shared_ptr< const DiscretisedDensity< 3, float > > & density_info_sptr) virtual
Stores all necessary geometric info.
If necessary, set_up() can be called more than once.
Implements stir::BackProjectorByBin.
References stir::BackProjectorByBin::_density_sptr, stir::BackProjectorByBin::check(), stir::error(), and stir::BackProjectorByBin::set_up().
get_symmetries_used()
const DataSymmetriesForViewSegmentNumbers * stir::BackProjectorByBinNiftyPET::get_symmetries_used () const virtual
Symmetries not used, so returns TrivialDataSymmetriesForBins.
Implements stir::BackProjectorByBin.
References stir::error().
back_project()
void stir::BackProjectorByBinNiftyPET::back_project (const ProjData & proj_data, int subset_num = 0, int num_subsets = 1) virtual
Back project.
Reimplemented from stir::BackProjectorByBin.
References stir::error().
get_output()
void stir::BackProjectorByBinNiftyPET::get_output (DiscretisedDensity< 3, float > & density) const virtual
Get output.
Reimplemented from stir::BackProjectorByBin.
References stir::truncate_rim().
start_accumulating_in_new_target()
void stir::BackProjectorByBinNiftyPET::start_accumulating_in_new_target () virtual
tell the back projector to start accumulating into a new target. This function has to be called before any back-projection is initiated.
Reimplemented from stir::BackProjectorByBin.
References stir::BackProjectorByBin::start_accumulating_in_new_target().
actual_back_project()
void stir::BackProjectorByBinNiftyPET::actual_back_project (const RelatedViewgrams< float > & viewgrams, const int min_axial_pos_num, const int max_axial_pos_num, const int min_tangential_pos_num, const int max_tangential_pos_num) protected virtual
This actually does the back projection. There are two versions of this code to enable backwards compatibility.
This is the newer version (in which the backprojected image is a member variable). In most cases, the new version calls the old version (in which the backprojected image is not a member variable).
If you are developing your own projector, one of these two needs to be overloaded. It doesn't matter which, but it might as well be the new one in case we one day decide to remove the old ones.
Reimplemented from stir::BackProjectorByBin.
References stir::RelatedViewgrams< elemT >::begin(), and stir::RelatedViewgrams< elemT >::end().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/recon_buildblock/NiftyPET_projector/BackProjectorByBinNiftyPET.h
/home/kris/devel/STIRdistrib/STIR/src/recon_buildblock/NiftyPET_projector/BackProjectorByBinNiftyPET.cxx