STIR: stir::DataSymmetriesForViewSegmentNumbers Class Reference
stir::DataSymmetriesForViewSegmentNumbers Class Reference abstract
STIR » STIR library » Basic building blocks » Items related to projection data
A class for encoding/finding symmetries. Works only on ViewSegmentNumbers (instead of Bin).
#include "stir/DataSymmetriesForViewSegmentNumbers.h"
Public Member Functions
virtual DataSymmetriesForViewSegmentNumbers * clone () const =0
bool operator== (const DataSymmetriesForViewSegmentNumbers &) const
Check equality.
bool operator!= (const DataSymmetriesForViewSegmentNumbers &) const
Check inequality.
virtual void get_related_view_segment_numbers (std::vector< ViewSegmentNumbers > &, const ViewSegmentNumbers &v_s) const =0
fills in a vector with all the view/segments that are related to 'v_s' (including itself)
virtual int num_related_view_segment_numbers (const ViewSegmentNumbers &v_s) const
returns the number of view_segment_numbers related to 'v_s'
std::size_t num_related_viewgram_indices (const ViewgramIndices &ind) const
virtual bool find_basic_view_segment_numbers (ViewSegmentNumbers &v_s) const =0
given an arbitrary view/segment, find the basic view/segment
virtual bool is_basic (const ViewSegmentNumbers &v_s) const
test if a view/segment is 'basic'
Protected Types
typedef DataSymmetriesForViewSegmentNumbers root_type
Protected Member Functions
virtual bool blindly_equals (const root_type *const) const =0
Detailed Description
A class for encoding/finding symmetries. Works only on ViewSegmentNumbers (instead of Bin).
This class (mainly used in RelatedViewgrams and the projectors) is useful to store and use all information on symmetries common between the image representation and the projection data.
The class mainly defines members to find basic ViewSegmentNumbers. These form a 'basis' for all ViewSegmentNumbers in the sense that all ViewSegmentNumbers can be obtained by using symmetry operations on the 'basic' ones.
Warning: This class wil be renamed/revised to work with ViewgramIndices instead.
Member Function Documentation
operator==()
bool stir::DataSymmetriesForViewSegmentNumbers::operator== (const DataSymmetriesForViewSegmentNumbers & that) const
Check equality.
Implemented in terms of blindly_equals, after checking the type
References blindly_equals(), and operator==().
Referenced by operator==().
operator!=()
bool stir::DataSymmetriesForViewSegmentNumbers::operator!= (const DataSymmetriesForViewSegmentNumbers & that) const
Check inequality.
Implemented in terms of operator==()
References operator!=().
Referenced by operator!=().
get_related_view_segment_numbers()
virtual void stir::DataSymmetriesForViewSegmentNumbers::get_related_view_segment_numbers (std::vector< ViewSegmentNumbers > & , const ViewSegmentNumbers & v_s) const pure virtual
fills in a vector with all the view/segments that are related to 'v_s' (including itself)
Implemented in stir::DataSymmetriesForBins_PET_CartesianGrid, stir::TrivialDataSymmetriesForBins, and stir::TrivialDataSymmetriesForViewSegmentNumbers.
References get_related_view_segment_numbers().
Referenced by stir::detail::find_basic_vs_nums_in_subset(), stir::DataSymmetriesForBins::get_related_bins(), get_related_view_segment_numbers(), and num_related_view_segment_numbers().
num_related_view_segment_numbers()
int stir::DataSymmetriesForViewSegmentNumbers::num_related_view_segment_numbers (const ViewSegmentNumbers & v_s) const virtual
returns the number of view_segment_numbers related to 'v_s'
The default implementation is in terms of get_related_view_segment_numbers, which will be slow of course
Reimplemented in stir::DataSymmetriesForBins_PET_CartesianGrid, stir::TrivialDataSymmetriesForBins, and stir::TrivialDataSymmetriesForViewSegmentNumbers.
References get_related_view_segment_numbers(), and num_related_view_segment_numbers().
Referenced by stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::actual_subsets_are_approximately_balanced(), and num_related_view_segment_numbers().
find_basic_view_segment_numbers()
virtual bool stir::DataSymmetriesForViewSegmentNumbers::find_basic_view_segment_numbers (ViewSegmentNumbers & v_s) const pure virtual
given an arbitrary view/segment, find the basic view/segment
sets 'v_s' to the corresponding 'basic' view/segment and returns true if 'v_s' is changed (i.e. it was NOT a basic view/segment).
Implemented in stir::DataSymmetriesForBins_PET_CartesianGrid, stir::TrivialDataSymmetriesForBins, and stir::TrivialDataSymmetriesForViewSegmentNumbers.
References blindly_equals(), and is_basic().
Referenced by stir::BackProjectorByBin::back_project(), and is_basic().
is_basic()
bool stir::DataSymmetriesForViewSegmentNumbers::is_basic (const ViewSegmentNumbers & v_s) const virtual
test if a view/segment is 'basic'
The default implementation uses find_basic_view_segment_numbers
References find_basic_view_segment_numbers(), and is_basic().
Referenced by stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjData< TargetT >::actual_subsets_are_approximately_balanced(), find_basic_view_segment_numbers(), stir::detail::find_basic_vs_nums_in_subset(), and is_basic().
blindly_equals()
bool stir::DataSymmetriesForViewSegmentNumbers::blindly_equals (const root_type * const) const protected pure virtual
Default implementation always returns true. Needs to be overloaded.
Implemented in stir::DataSymmetriesForBins.
References blindly_equals().
Referenced by stir::DataSymmetriesForBins::blindly_equals(), blindly_equals(), find_basic_view_segment_numbers(), and operator==().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/DataSymmetriesForViewSegmentNumbers.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/DataSymmetriesForViewSegmentNumbers.cxx