STIR: stir::VoxelsOnCartesianGrid< elemT > Class Template Reference
stir::VoxelsOnCartesianGrid< elemT > Class Template Reference
STIR » STIR library » Basic building blocks » Items related to image data
This class is used to represent voxelised densities on a cuboid grid (3D).
#include "stir/VoxelsOnCartesianGrid.h"
Public Member Functions
VoxelsOnCartesianGrid ()
Construct an empty VoxelsOnCartesianGrid (empty range, 0 origin, 0 grid_spacing)
VoxelsOnCartesianGrid (const Array< 3, elemT > &v, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< 3, float > &grid_spacing)
Construct a VoxelsOnCartesianGrid, initialising data from the Array<3,elemT> object.
VoxelsOnCartesianGrid (Array< 3, elemT > &&v, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< 3, float > &grid_spacing)
Construct a VoxelsOnCartesianGrid, moving data from the Array<3,elemT> object.
VoxelsOnCartesianGrid (const IndexRange< 3 > &range, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< 3, float > &grid_spacing)
Construct a VoxelsOnCartesianGrid from an index range.
VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr, const Array< 3, elemT > &v, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< 3, float > &grid_spacing)
Construct a VoxelsOnCartesianGrid, initialising data from the Array<3,elemT> object.
VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr, Array< 3, elemT > &&v, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< 3, float > &grid_spacing)
Construct a VoxelsOnCartesianGrid, moving data from the Array<3,elemT> object.
VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr, const IndexRange< 3 > &range, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< 3, float > &grid_spacing)
Construct a VoxelsOnCartesianGrid from an index range.
VoxelsOnCartesianGrid (const ProjDataInfo &proj_data_info_ptr, const float zoom=1.F, const CartesianCoordinate3D< float > &origin=CartesianCoordinate3D< float >(0.F, 0.F, 0.F), const CartesianCoordinate3D< int > &sizes=CartesianCoordinate3D< int >(-1, -1, -1))
use ProjDataInfo to obtain the size information
VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr, const ProjDataInfo &proj_data_info, const float zoom=1.F, const CartesianCoordinate3D< float > &origin=CartesianCoordinate3D< float >(0.F, 0.F, 0.F), const CartesianCoordinate3D< int > &sizes=CartesianCoordinate3D< int >(-1, -1, -1))
Constructor from exam_info and proj_data_info.
VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr_v, const ProjDataInfo &proj_data_info, const CartesianCoordinate3D< float > &zooms, const CartesianCoordinate3D< float > &origin=CartesianCoordinate3D< float >(0.F, 0.F, 0.F), const CartesianCoordinate3D< int > &sizes=CartesianCoordinate3D< int >(-1, -1, -1))
Constructor from exam_info and proj_data_info.
VoxelsOnCartesianGrid< elemT > * get_empty_copy () const override
Definition of the pure virtual defined in DiscretisedDensity.
VoxelsOnCartesianGrid< elemT > * get_empty_voxels_on_cartesian_grid () const
Alias of get_empty_copy (for backwards compatibility)
VoxelsOnCartesianGrid< elemT > * clone () const override
Allocate a new DiscretisedDensity object which is a copy of the current one.
PixelsOnCartesianGrid< elemT > get_plane (const int z) const
Extract a single plane.
void set_plane (const PixelsOnCartesianGrid< elemT > &plane, const int z)
Set a single plane.
CartesianCoordinate3D< float > get_voxel_size () const
is the same as get_grid_spacing(), but now returns CartesianCoordinate3D for convenience
void set_voxel_size (const BasicCoordinate< 3, float > &)
is the same as set_grid_spacing()
void grow_z_range (const int min_z, const int max_z)
Growing of outer dimension only.
Convenience functions for regular grids in 3D
int get_x_size () const
int get_y_size () const
int get_z_size () const
int get_min_x () const
int get_min_y () const
int get_min_z () const
int get_max_x () const
int get_max_y () const
int get_max_z () const
BasicCoordinate< 3, int > get_lengths () const
BasicCoordinate< 3, int > get_min_indices () const
BasicCoordinate< 3, int > get_max_indices () const
Public Member Functions inherited from stir::DiscretisedDensityOnCartesianGrid< 3, elemT >
DiscretisedDensityOnCartesianGrid ()
Construct an empty DiscretisedDensityOnCartesianGrid.
DiscretisedDensityOnCartesianGrid (const IndexRange< num_dimensions > &range, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< num_dimensions, float > &grid_spacing)
Constructor given range, grid spacing and origin.
DiscretisedDensityOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr, const IndexRange< num_dimensions > &range, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< num_dimensions, float > &grid_spacing)
Constructor given exam_info, range, grid spacing and origin.
const BasicCoordinate< num_dimensions, float > & get_grid_spacing () const
Return the grid_spacing.
void set_grid_spacing (const BasicCoordinate< num_dimensions, float > &grid_spacing_v)
Set the grid_spacing.
DiscretisedDensityOnCartesianGrid ()
Construct an empty DiscretisedDensityOnCartesianGrid.
DiscretisedDensityOnCartesianGrid (const IndexRange< num_dimensions > &range, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< num_dimensions, float > &grid_spacing)
Constructor given range, grid spacing and origin.
DiscretisedDensityOnCartesianGrid (const shared_ptr< const ExamInfo > &exam_info_sptr, const IndexRange< num_dimensions > &range, const CartesianCoordinate3D< float > &origin, const BasicCoordinate< num_dimensions, float > &grid_spacing)
Constructor given exam_info, range, grid spacing and origin.
const BasicCoordinate< num_dimensions, float > & get_grid_spacing () const
Return the grid_spacing.
void set_grid_spacing (const BasicCoordinate< num_dimensions, float > &grid_spacing_v)
Set the grid_spacing.
Public Member Functions inherited from stir::DiscretisedDensity< num_dimensions, elemT >
DiscretisedDensity ()
Construct an empty DiscretisedDensity.
DiscretisedDensity (const IndexRange< num_dimensions > &range, const CartesianCoordinate3D< float > &origin)
Construct DiscretisedDensity from a given range of indices & origin.
DiscretisedDensity (const shared_ptr< const ExamInfo > &exam_info_sptr, const IndexRange< num_dimensions > &range, const CartesianCoordinate3D< float > &origin)
Construct DiscretisedDensity from ExamInfo and a given range of indices & origin.
const CartesianCoordinate3D< float > & get_origin () const
Return the origin.
void set_origin (const CartesianCoordinate3D< float > &origin)
Set the origin.
CartesianCoordinate3D< float > get_physical_coordinates_for_indices (const BasicCoordinate< num_dimensions, int > &indices) const
Return the coordinates of the centre of the basis-function corresponding to indices.
CartesianCoordinate3D< float > get_physical_coordinates_for_indices (const BasicCoordinate< num_dimensions, float > &indices) const
Return the coordinates of the centre of the basis-function corresponding to non-integer coordinate in 'physical' coordinates.
CartesianCoordinate3D< float > get_relative_coordinates_for_indices (const BasicCoordinate< num_dimensions, int > &indices) const
Return the relative coordinates of the centre of the basis-function corresponding to indices.
CartesianCoordinate3D< float > get_relative_coordinates_for_indices (const BasicCoordinate< num_dimensions, float > &indices) const
Return the relative coordinates of the centre of the basis-function corresponding to the non-integer coordinates in 'index' coordinates.
BasicCoordinate< num_dimensions, int > get_indices_closest_to_physical_coordinates (const CartesianCoordinate3D< float > &coords) const
Return the indices of the basis-function closest to the given point.
BasicCoordinate< num_dimensions, int > get_indices_closest_to_relative_coordinates (const CartesianCoordinate3D< float > &coords) const
Return the indices of the basis-function closest to the given point.
BasicCoordinate< num_dimensions, float > get_index_coordinates_for_physical_coordinates (const CartesianCoordinate3D< float > &coords) const
Return the indices of the basis-function closest to the given point.
BasicCoordinate< num_dimensions, float > get_index_coordinates_for_relative_coordinates (const CartesianCoordinate3D< float > &coords) const
Return the index-coordinates of the basis-function closest to the given point.
BasicCoordinate< num_dimensions, float > get_index_coordinates_for_LPS_coordinates (const CartesianCoordinate3D< float > &coords) const
Translation from LPS coordinates to continuous indices.
CartesianCoordinate3D< float > get_LPS_coordinates_for_physical_coordinates (const CartesianCoordinate3D< float > &indices) const
Translation from physical to LPS coordinates.
CartesianCoordinate3D< float > get_LPS_coordinates_for_indices (const BasicCoordinate< num_dimensions, int > &indices) const
Translation from indices to LPS coordinates.
CartesianCoordinate3D< float > get_LPS_coordinates_for_indices (const BasicCoordinate< num_dimensions, float > &indices) const
Translation from continuous indices to LPS coordinates.
CartesianCoordinate3D< float > get_physical_coordinates_for_LPS_coordinates (const CartesianCoordinate3D< float > &coords) const
Translation from LPS coordinates to physical coordinates.
BasicCoordinate< num_dimensions, int > get_indices_closest_to_LPS_coordinates (const CartesianCoordinate3D< float > &coords) const
Translation from LPS coordinates to indices.
DiscretisedDensity< num_dimensions, elemT > * get_empty_discretised_density () const
Allocate a new DiscretisedDensity object with same characteristics as the current one.
bool has_same_characteristics (self_type const &, std::string &explanation) const
Checks if the 2 objects have the same type, index range, origin etc.
bool has_same_characteristics (self_type const &) const
Checks if the 2 objects have the same type, index range, origin etc.
bool operator== (const self_type &) const
check equality (data has to be identical)
bool operator!= (const self_type &) const
negation of operator==
Public Member Functions inherited from stir::ExamData
ExamData ()
ExamData.
ExamData (const shared_ptr< const ExamInfo > &_this_exam)
virtual const ExamInfo & get_exam_info () const
virtual shared_ptr< const ExamInfo > get_exam_info_sptr () const
Get shared pointer to exam info.
virtual void set_exam_info (ExamInfo const &)
change exam info
void set_exam_info_sptr (shared_ptr< const ExamInfo > new_exam_info_sptr)
Public Member Functions inherited from stir::Array< num_dimensions, elemT >
template<int num_dimensions, typename elemT>
Array (Array< num_dimensions, elemT > &&other) noexcept
template<typename elemT2>
void axpby (const elemT2 a, const Array &x, const elemT2 b, const Array &y)
template<class elemT>
Array (const IndexRange< 1 > &range)
template<class elemT>
Array (const int min_index, const int max_index)
template<class elemT>
Array (const IndexRange< 1 > &range, shared_ptr< elemT[]> data_sptr)
template<class elemT>
Array (const IndexRange< 1 > &range, const elemT *const data_ptr)
template<typename elemT>
Array (const Array< 1, elemT > &other)
template<typename elemT>
Array (Array< 1, elemT > &&other) noexcept
full_iterator begin_all ()
start value for iterating through all elements in the array, see full_iterator
const_full_iterator begin_all () const
start value for iterating through all elements in the (const) array, see full_iterator
const_full_iterator begin_all_const () const
start value for iterating through all elements in the array, see full_iterator
full_iterator end_all ()
end value for iterating through all elements in the array, see full_iterator
const_full_iterator end_all () const
end value for iterating through all elements in the (const) array, see full_iterator
const_full_iterator end_all_const () const
end value for iterating through all elements in the array, see full_iterator
IndexRange< num_dimensions > get_index_range () const
size_t size_all () const
return the total number of elements in this array
virtual void resize (const IndexRange< num_dimensions > &range)
change the array to a new range of indices, new elements are set to 0
virtual void grow (const IndexRange< num_dimensions > &range)
alias for resize()
elemT sum () const
return sum of all elements
elemT sum_positive () const
return sum of all positive elements
elemT find_max () const
return maximum of all the elements
elemT find_min () const
return minimum of all the elements
void fill (const elemT &n)
Fill elements with value n.
void apply_lower_threshold (const elemT &l)
Sets elements below value to the value.
void apply_upper_threshold (const elemT &u)
Sets elements above value to the value.
bool is_regular () const
checks if the index range is 'regular'
bool get_regular_range (BasicCoordinate< num_dimensions, int > &min, BasicCoordinate< num_dimensions, int > &max) const
find regular range, returns false if the range is not regular
Array< num_dimensions - 1, elemT > & operator[] (int i)
allow array-style access, read/write
const Array< num_dimensions - 1, elemT > & operator[] (int i) const
array access, read-only
elemT & operator[] (const BasicCoordinate< num_dimensions, int > &c)
allow array-style access given a BasicCoordinate to specify the indices, read/write
const elemT & operator[] (const BasicCoordinate< num_dimensions, int > &c) const
array access given a BasicCoordinate to specify the indices, read-only
Array< num_dimensions - 1, elemT > & at (int i)
const Array< num_dimensions - 1, elemT > & at (int i) const
elemT & at (const BasicCoordinate< num_dimensions, int > &c)
const elemT & at (const BasicCoordinate< num_dimensions, int > &c) const
self & operator+= (const self &x)
self & operator-= (const self &x)
self & operator*= (const self &x)
self & operator/= (const self &x)
self & operator+= (const elemT x)
self & operator-= (const elemT x)
self & operator*= (const elemT x)
self & operator/= (const elemT x)
self operator+ (const self &x) const
self operator+ (const elemT x) const
self operator- (const self &x) const
self operator- (const elemT x) const
self operator* (const self &x) const
self operator* (const elemT x) const
self operator/ (const self &x) const
self operator/ (const elemT x) const
template<typename elemT2>
STIR_DEPRECATED void axpby (const elemT2 a, const Array &x, const elemT2 b, const Array &y)
void xapyb (const Array &x, const elemT a, const Array &y, const elemT b)
set values of the array to x*a+y*b, where a and b are scalar
void xapyb (const Array &x, const Array &a, const Array &y, const Array &b)
set values of the array to x*a+y*b, where a and b are arrays
template<class T>
void sapyb (const T &a, const Array &y, const T &b)
set values of the array to self*a+y*b where a and b are scalar or arrays
Array ()
Construct an empty Array.
Array (const IndexRange< num_dimensions > &)
Construct an Array of given range of indices, elements are initialised to 0.
Array (const IndexRange< num_dimensions > &range, shared_ptr< elemT[]> data_sptr)
Construct an Array pointing to existing contiguous data.
Array (const base_type &t)
Construct an Array from an object of its base_type.
Array (const self &t)
Copy constructor.
~Array () override
virtual destructor, frees up any allocated memory
Array (Array &&other) noexcept
move constructor
Array & operator= (Array other)
assignment operator
bool is_contiguous () const
return if the array is contiguous in memory
elemT * get_full_data_ptr ()
member function for access to the data via a elemT*
const elemT * get_const_full_data_ptr () const
member function for access to the data via a const elemT*
void release_full_data_ptr ()
signal end of access to elemT*
void release_const_full_data_ptr () const
signal end of access to const elemT*
Public Member Functions inherited from stir::NumericVectorWithOffset< Array< num_dimensions - 1, elemT >, elemT >
NumericVectorWithOffset (const VectorWithOffset< Array< num_dimensions - 1, elemT > > &t)
Constructor from an object of this class' base_type.
NumericVectorWithOffset (const NumericVectorWithOffset &t)
Constructor from an object of this class' base_type.
NumericVectorWithOffset (NumericVectorWithOffset &&other) noexcept
move constructor
NumericVectorWithOffset & operator= (const NumericVectorWithOffset &other)
assignment
NumericVectorWithOffset operator+ (const NumericVectorWithOffset &v) const
adding vectors, element by element
NumericVectorWithOffset operator- (const NumericVectorWithOffset &v) const
subtracting vectors, element by element
NumericVectorWithOffset operator* (const NumericVectorWithOffset &v) const
multiplying vectors, element by element
NumericVectorWithOffset operator/ (const NumericVectorWithOffset &v) const
dividing vectors, element by element
NumericVectorWithOffset operator+ (const elemT &v) const
return a new vector with elements equal to the sum of the elements in the original and the elemT
NumericVectorWithOffset operator- (const elemT &v) const
return a new vector with elements equal to the difference of the elements in the original and the elemT
NumericVectorWithOffset operator* (const elemT &v) const
return a new vector with elements equal to the multiplication of the elements in the original and the elemT
NumericVectorWithOffset operator/ (const elemT &v) const
return a new vector with elements equal to the division of the elements in the original and the elemT
NumericVectorWithOffset & operator+= (const NumericVectorWithOffset &v)
adding elements of v to the current vector
NumericVectorWithOffset & operator-= (const NumericVectorWithOffset &v)
subtracting elements of v from the current vector
NumericVectorWithOffset & operator*= (const NumericVectorWithOffset &v)
multiplying elements of the current vector with elements of v
NumericVectorWithOffset & operator/= (const NumericVectorWithOffset &v)
dividing all elements of the current vector by elements of v
NumericVectorWithOffset & operator+= (const elemT &v)
adding an elemT to the elements of the current vector
NumericVectorWithOffset & operator-= (const elemT &v)
subtracting an elemT from the elements of the current vector
NumericVectorWithOffset & operator*= (const elemT &v)
multiplying the elements of the current vector with an elemT
NumericVectorWithOffset & operator/= (const elemT &v)
dividing the elements of the current vector by an elemT
STIR_DEPRECATED void axpby (const elemT2 a, const NumericVectorWithOffset &x, const elemT2 b, const NumericVectorWithOffset &y)
void xapyb (const NumericVectorWithOffset &x, const elemT a, const NumericVectorWithOffset &y, const elemT b)
set values of the array to x*a+y*b, where a and b are scalar
void xapyb (const NumericVectorWithOffset &x, const NumericVectorWithOffset &a, const NumericVectorWithOffset &y, const NumericVectorWithOffset &b)
set the values of the array to x*a+y*b, where a and b are vectors
void sapyb (const T2 &a, const NumericVectorWithOffset &y, const T2 &b)
set the values of the array to self*a+y*b, where a and b are scalar or vectors
void axpby (const NUMBER2 a, const NumericVectorWithOffset &x, const NUMBER2 b, const NumericVectorWithOffset &y)
NumericVectorWithOffset (const VectorWithOffset< Array< num_dimensions - 1, elemT > > &t)
Constructor from an object of this class' base_type.
NumericVectorWithOffset (const NumericVectorWithOffset &t)
Constructor from an object of this class' base_type.
NumericVectorWithOffset (NumericVectorWithOffset &&other) noexcept
move constructor
NumericVectorWithOffset & operator= (const NumericVectorWithOffset &other)
assignment
NumericVectorWithOffset operator+ (const NumericVectorWithOffset &v) const
adding vectors, element by element
NumericVectorWithOffset operator+ (const elemT &v) const
return a new vector with elements equal to the sum of the elements in the original and the elemT
NumericVectorWithOffset operator- (const NumericVectorWithOffset &v) const
subtracting vectors, element by element
NumericVectorWithOffset operator- (const elemT &v) const
return a new vector with elements equal to the difference of the elements in the original and the elemT
NumericVectorWithOffset operator* (const NumericVectorWithOffset &v) const
multiplying vectors, element by element
NumericVectorWithOffset operator* (const elemT &v) const
return a new vector with elements equal to the multiplication of the elements in the original and the elemT
NumericVectorWithOffset operator/ (const NumericVectorWithOffset &v) const
dividing vectors, element by element
NumericVectorWithOffset operator/ (const elemT &v) const
return a new vector with elements equal to the division of the elements in the original and the elemT
NumericVectorWithOffset & operator+= (const NumericVectorWithOffset &v)
adding elements of v to the current vector
NumericVectorWithOffset & operator+= (const elemT &v)
adding an elemT to the elements of the current vector
NumericVectorWithOffset & operator-= (const NumericVectorWithOffset &v)
subtracting elements of v from the current vector
NumericVectorWithOffset & operator-= (const elemT &v)
subtracting an elemT from the elements of the current vector
NumericVectorWithOffset & operator*= (const NumericVectorWithOffset &v)
multiplying elements of the current vector with elements of v
NumericVectorWithOffset & operator*= (const elemT &v)
multiplying the elements of the current vector with an elemT
NumericVectorWithOffset & operator/= (const NumericVectorWithOffset &v)
dividing all elements of the current vector by elements of v
NumericVectorWithOffset & operator/= (const elemT &v)
dividing the elements of the current vector by an elemT
STIR_DEPRECATED void axpby (const elemT2 a, const NumericVectorWithOffset &x, const elemT2 b, const NumericVectorWithOffset &y)
void axpby (const NUMBER2 a, const NumericVectorWithOffset &x, const NUMBER2 b, const NumericVectorWithOffset &y)
void xapyb (const NumericVectorWithOffset &x, const elemT a, const NumericVectorWithOffset &y, const elemT b)
set values of the array to x*a+y*b, where a and b are scalar
void xapyb (const NumericVectorWithOffset &x, const NumericVectorWithOffset &a, const NumericVectorWithOffset &y, const NumericVectorWithOffset &b)
set the values of the array to x*a+y*b, where a and b are vectors
void sapyb (const T2 &a, const NumericVectorWithOffset &y, const T2 &b)
set the values of the array to self*a+y*b, where a and b are scalar or vectors
Public Member Functions inherited from stir::VectorWithOffset< T >
int get_length () const
return number of elements in this vector
size_t size () const
return number of elements in this vector
int get_min_index () const
get value of first valid index
int get_max_index () const
get value of last valid index
void set_offset (const int min_index)
change value of starting index
void set_min_index (const int min_index)
identical to set_offset()
virtual void grow (const int min_index, const int max_index)
grow the range of the vector, new elements are set to T()
void grow (const unsigned int new_size)
grow the range of the vector from 0 to new_size-1, new elements are set to T()
virtual void resize (const int min_index, const int max_index)
change the range of the vector, new elements are set to T()
void resize (const unsigned int new_size)
change the range of the vector from 0 to new_size-1, new elements are set to T()
void reserve (const int min_index, const int max_index)
make the allocated range at least from min_index to max_index
void reserve (const unsigned int new_size)
make the allocated range at least from 0 to new_size-1
size_t capacity () const
get allocated size
bool owns_memory_for_data () const
check if this object owns the memory for the data
int get_capacity_min_index () const
get min_index within allocated range
int get_capacity_max_index () const
get max_index within allocated range
T & operator[] (int i)
allow array-style access, read/write
const T & operator[] (int i) const
array access, read-only
T & at (int i)
allow array-style access, read/write, but with range checking (throws std::out_of_range)
const T & at (int i) const
array access, read-only, but with range checking (throws std::out_of_range)
bool empty () const
checks if the vector is empty
bool operator== (const VectorWithOffset &iv) const
bool operator!= (const VectorWithOffset &iv) const
void fill (const T &n)
fill elements with value n
void apply_lower_threshold (const T &lower)
Sets elements below value to the value.
void apply_upper_threshold (const T &upper)
Sets elements above value to the value.
T * get_data_ptr ()
member function for access to the data via a T*
const T * get_const_data_ptr () const
member function for access to the data via a const T*
void release_data_ptr ()
signal end of access to T*
void release_const_data_ptr () const
signal end of access to const T*
iterator begin ()
use to initialise an iterator to the first element of the vector
const_iterator begin () const
use to initialise an iterator to the first element of the (const) vector
iterator end ()
iterator 'past' the last element of the vector
const_iterator end () const
iterator 'past' the last element of the (const) vector
reverse_iterator rbegin ()
reverse_iterator rend ()
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
VectorWithOffset & operator+= (const VectorWithOffset &v)
adding elements of v to the current vector
VectorWithOffset & operator-= (const VectorWithOffset &v)
subtracting elements of v from the current vector
VectorWithOffset & operator*= (const VectorWithOffset &v)
multiplying elements of the current vector with elements of v
VectorWithOffset & operator/= (const VectorWithOffset &v)
dividing all elements of the current vector by elements of v
VectorWithOffset ()
Default constructor: creates a vector of length 0.
VectorWithOffset (const int hsz)
Construct a VectorWithOffset of given length (initialised with T())
VectorWithOffset (const int min_index, const int max_index)
Construct a VectorWithOffset with offset min_index (initialised with T())
STIR_DEPRECATED VectorWithOffset (const int hsz, T *const data_ptr, T *const end_of_data_ptr)
Construct a VectorWithOffset of given length pointing to existing data.
STIR_DEPRECATED VectorWithOffset (const int min_index, const int max_index, T *const data_ptr, T *const end_of_data_ptr)
Construct a VectorWithOffset with offset min_index pointing to existing data.
VectorWithOffset (const int hsz, const T *const data_ptr)
Construct a VectorWithOffset of given length from a bare pointer (copying data)
VectorWithOffset (const int min_index, const int max_index, const T *const data_ptr)
Construct a VectorWithOffset with offset min_index from a bare pointer (copying data)
VectorWithOffset (const int min_index, const int max_index, shared_ptr< T[]> data_sptr)
Construct a VectorWithOffset sharing existing data.
VectorWithOffset (const int sz, shared_ptr< T[]> data_sptr)
Construct a VectorWithOffset sharing existing data.
VectorWithOffset (const VectorWithOffset &il)
copy constructor
virtual ~VectorWithOffset ()
Destructor.
VectorWithOffset (VectorWithOffset &&other) noexcept
move constructor
void recycle ()
Free all memory and make object as if default-constructed.
VectorWithOffset & operator= (const VectorWithOffset &il)
assignment operator with another vector
VectorWithOffset operator+ (const VectorWithOffset &v) const
adding vectors, element by element
VectorWithOffset operator- (const VectorWithOffset &v) const
subtracting vectors, element by element
VectorWithOffset operator* (const VectorWithOffset &v) const
multiplying vectors, element by element
VectorWithOffset operator/ (const VectorWithOffset &v) const
dividing vectors, element by element
Numerical operations
self_type & operator+= (const self_type &x)
self_type & operator-= (const self_type &x)
self_type & operator*= (const self_type &x)
self_type & operator/= (const self_type &x)
self_type & operator+= (const elemT x)
self_type & operator-= (const elemT x)
self_type & operator*= (const elemT x)
self_type & operator/= (const elemT x)
self_type operator+ (const self_type &x) const
self_type operator+ (const elemT x) const
self_type operator- (const self_type &x) const
self_type operator- (const elemT x) const
self_type operator* (const self_type &x) const
self_type operator* (const elemT x) const
self_type operator/ (const self_type &x) const
self_type operator/ (const elemT x) const
Additional Inherited Members
Public Types inherited from stir::DiscretisedDensity< num_dimensions, elemT >
typedef DiscretisedDensity< num_dimensions, elemT > hierarchy_base_type
A typedef that can be used what the base of the hierarchy is.
Public Types inherited from stir::Array< num_dimensions, elemT >
typedef base_type::value_type value_type
typedefs such that we do not need to have typename wherever we use these types defined in the base class
typedef base_type::reference reference
typedef base_type::const_reference const_reference
typedef base_type::difference_type difference_type
typedef base_type::size_type size_type
typedef base_type::iterator iterator
typedef base_type::const_iterator const_iterator
typedef elemT full_value_type
typedef full_value_type * full_pointer
typedef const full_value_type * const_full_pointer
typedef full_value_type & full_reference
typedef const full_value_type & const_full_reference
typedef FullArrayIterator< typename base_type::iterator, typename Array< num_dimensions - 1, elemT >::full_iterator, elemT, full_reference, full_pointer > full_iterator
This defines an iterator type that iterates through all elements.
typedef FullArrayIterator< typename base_type::const_iterator, typename Array< num_dimensions - 1, elemT >::const_full_iterator, elemT, const_full_reference, const_full_pointer > const_full_iterator
As full_iterator, but for const objects.
typedef T value_type
typedef value_type & reference
typedef const value_type & const_reference
typedef ptrdiff_t difference_type
typedef T * iterator
typedef T const * const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef size_t size_type
Static Public Member Functions inherited from stir::DiscretisedDensity< num_dimensions, elemT >
static DiscretisedDensity * read_from_file (const std::string &filename)
A static member to read an image from file.
Protected Member Functions inherited from stir::DiscretisedDensityOnCartesianGrid< 3, elemT >
bool actual_has_same_characteristics (DiscretisedDensity< num_dimensions, elemT > const &, std::string &explanation) const override
Implementation used by has_same_characteristics.
CartesianCoordinate3D< float > actual_get_relative_coordinates_for_indices (const BasicCoordinate< num_dimensions, float > &indices) const override
Return the relative coordinates of the centre of the basis-function corresponding to indices.
BasicCoordinate< num_dimensions, float > actual_get_index_coordinates_for_relative_coordinates (const CartesianCoordinate3D< float > &coords) const override
Return the indices of the basis-function closest to the given point.
bool actual_has_same_characteristics (DiscretisedDensity< num_dimensions, elemT > const &, std::string &explanation) const override
Implementation used by has_same_characteristics.
CartesianCoordinate3D< float > actual_get_relative_coordinates_for_indices (const BasicCoordinate< num_dimensions, float > &indices) const override
Return the relative coordinates of the centre of the basis-function corresponding to indices.
BasicCoordinate< num_dimensions, float > actual_get_index_coordinates_for_relative_coordinates (const CartesianCoordinate3D< float > &coords) const override
Return the indices of the basis-function closest to the given point.
void check_state () const
Called internally to see if all variables are consistent.
void init_with_copy (const int min_index, const int max_index, T const *const data_ptr)
change vector to the new index range and copy data from data_ptr
void init (const int min_index, const int max_index, T *const data_ptr, bool copy_data)
initialise vector to the given index range and either copy from or point to data_ptr
Protected Attributes inherited from stir::ExamData
shared_ptr< const ExamInfo > exam_info_sptr
T * num
pointer to (*this)[0] (taking get_min_index() into account that is).
Detailed Description
template<class elemT>
class stir::VoxelsOnCartesianGrid< elemT >
This class is used to represent voxelised densities on a cuboid grid (3D).
This class represents 'normal' data. Basisfunctions are just voxels.
Constructor & Destructor Documentation
VoxelsOnCartesianGrid() [1/5]
template<class elemT> stir::VoxelsOnCartesianGrid< elemT >::VoxelsOnCartesianGrid (const IndexRange< 3 > & range, const CartesianCoordinate3D< float > & origin, const BasicCoordinate< 3, float > & grid_spacing)
Construct a VoxelsOnCartesianGrid from an index range.
All elements are set 0.
VoxelsOnCartesianGrid() [2/5]
template<class elemT> stir::VoxelsOnCartesianGrid< elemT >::VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > & exam_info_sptr, const IndexRange< 3 > & range, const CartesianCoordinate3D< float > & origin, const BasicCoordinate< 3, float > & grid_spacing)
Construct a VoxelsOnCartesianGrid from an index range.
All elements are set 0.
References stir::DiscretisedDensityOnCartesianGrid< 3, elemT >::DiscretisedDensityOnCartesianGrid().
VoxelsOnCartesianGrid() [3/5]
template<class elemT> stir::VoxelsOnCartesianGrid< elemT >::VoxelsOnCartesianGrid (const ProjDataInfo & proj_data_info_ptr, const float zoom = 1.F, const CartesianCoordinate3D< float > & origin = CartesianCoordinate3D<float>(0.F, 0.F, 0.F), const CartesianCoordinate3D< int > & sizes = CartesianCoordinate3D<int>(-1, -1, -1))
use ProjDataInfo to obtain the size information
When sizes.x() is -1, a default size in x is found by taking the diameter of the FOV spanned by the projection data. Similar for sizes.y().
When sizes.z() is -1, a default size in z is found by taking the number of planes as
$N_0$ when segment 0 is axially compressed,
$2N_0-1$ when segment 0 is not axially compressed,
where $N_0$ is the number of sinograms in segment 0.
Actual index ranges start from 0 for z, but from -(x_size_used/2) for x (and similar for y).
x,y grid spacing are set to the proj_data_info_ptr->get_scanner_ptr()->get_default_bin_size()/zoom. This is to make sure that the voxel size is independent on if arc-correction is used or not. If the default bin size is 0, the sampling distance in s (for bin 0) is used.
z grid spacing is set to half the scanner ring distance.
All voxel values are set 0.
VoxelsOnCartesianGrid() [4/5]
template<class elemT> stir::VoxelsOnCartesianGrid< elemT >::VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > & exam_info_sptr, const ProjDataInfo & proj_data_info, const float zoom = 1.F, const CartesianCoordinate3D< float > & origin = CartesianCoordinate3D<float>(0.F, 0.F, 0.F), const CartesianCoordinate3D< int > & sizes = CartesianCoordinate3D<int>(-1, -1, -1))
Constructor from exam_info and proj_data_info.
See also
VoxelsOnCartesianGrid(const ProjDataInfo&, const float zoom, const CartesianCoordinate3D<float>&, const CartesianCoordinate3D<int>&);
VoxelsOnCartesianGrid() [5/5]
template<class elemT> stir::VoxelsOnCartesianGrid< elemT >::VoxelsOnCartesianGrid (const shared_ptr< const ExamInfo > & exam_info_sptr_v, const ProjDataInfo & proj_data_info, const CartesianCoordinate3D< float > & zooms, const CartesianCoordinate3D< float > & origin = CartesianCoordinate3D<float>(0.F, 0.F, 0.F), const CartesianCoordinate3D< int > & sizes = CartesianCoordinate3D<int>(-1, -1, -1))
Constructor from exam_info and proj_data_info.
See also
VoxelsOnCartesianGrid(const ProjDataInfo&, const float zoom, const CartesianCoordinate3D<float>&, const CartesianCoordinate3D<int>&);
Member Function Documentation
get_empty_copy()
template<class elemT> VoxelsOnCartesianGrid< elemT > * stir::VoxelsOnCartesianGrid< elemT >::get_empty_copy () const override virtual
Definition of the pure virtual defined in DiscretisedDensity.
Implements stir::DiscretisedDensity< num_dimensions, elemT >.
References get_empty_voxels_on_cartesian_grid().
Referenced by stir::VoxelsOnCartesianGridTests::run_tests(), and stir::warp_imageTests::run_tests().
get_empty_voxels_on_cartesian_grid()
template<class elemT> VoxelsOnCartesianGrid< elemT > * stir::VoxelsOnCartesianGrid< elemT >::get_empty_voxels_on_cartesian_grid () const
Alias of get_empty_copy (for backwards compatibility)
This member function will be unnecessary when all compilers can handle 'covariant' return types. It is a non-virtual counterpart of get_empty_voxels_on_cartesian_grid.
References stir::DiscretisedDensityOnCartesianGrid< 3, elemT >::get_grid_spacing(), stir::DiscretisedDensity< num_dimensions, elemT >::get_origin(), and VoxelsOnCartesianGrid().
Referenced by get_empty_copy(), and stir::VoxelsOnCartesianGridTests::run_tests().
clone()
template<class elemT> VoxelsOnCartesianGrid< elemT > * stir::VoxelsOnCartesianGrid< elemT >::clone () const override virtual
Allocate a new DiscretisedDensity object which is a copy of the current one.
Implements stir::DiscretisedDensity< num_dimensions, elemT >.
References stir::ExamData::set_exam_info(), and VoxelsOnCartesianGrid().
Referenced by stir::warp_imageTests::run_tests().
set_plane()
template<class elemT> void stir::VoxelsOnCartesianGrid< elemT >::set_plane (const PixelsOnCartesianGrid< elemT > & plane, const int z)
Set a single plane.
This function requires that the dimensions, origin and grid_spacings match.
References stir::DiscretisedDensity< num_dimensions, elemT >::get_origin(), stir::PixelsOnCartesianGrid< elemT >::get_pixel_size(), get_voxel_size(), and stir::Array< num_dimensions, elemT >::operator[]().
Referenced by stir::zoom_image().
get_x_size()
template<typename elemT> int stir::VoxelsOnCartesianGrid< elemT >::get_x_size () const inline
It is assumed that z is the highest dimension and x the lowest.
References stir::VectorWithOffset< T >::get_length(), and get_x_size().
Referenced by stir::ITKOutputFileFormat::actual_write_to_file(), stir::ScatterSimulation::downsample_density_image_for_scatter_points(), get_x_size(), stir::zoom_imageTests::run_tests(), stir::ProjMatrixByBinPinholeSPECTUB::set_up(), stir::ProjMatrixByBinSPECTUB::set_up(), and stir::zoom_image().
The documentation for this class was generated from the following files:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/analytic/FBP3DRP/FBP3DRPReconstruction.h
/home/kris/devel/STIRdistrib/STIR/src/include/stir/VoxelsOnCartesianGrid.h
/home/kris/devel/STIRdistrib/STIR/src/buildblock/VoxelsOnCartesianGrid.cxx
/home/kris/devel/STIRdistrib/STIR/src/include/stir/VoxelsOnCartesianGrid.inl