STIR: stir::FileSignature Class Reference
stir::FileSignature Class Reference
STIR » STIR library » Input/Output Library
A class to read/store the file signature.
#include "stir/IO/FileSignature.h"
Public Member Functions
FileSignature (std::istream &input)
read signature
FileSignature (const std::string &filename)
open file and read signature
const char * get_signature () const
get access to the signature
std::size_t size () const
return size of valid signature read from the file
Detailed Description
A class to read/store the file signature.
Most file formats have a 'magic number' at the start, which allows easy recognition. This class provides an interface to reading and storing that signature.
The current implementation reads a signature of maximum 1024 bytes. The buffer is initialised to zero before reading.
Constructor & Destructor Documentation
FileSignature()
stir::FileSignature::FileSignature (std::istream & input) inline explicit
read signature
The signature will be read from the current point in the stream. The seekg pointer will be advanced by max 1024.
Member Function Documentation
get_signature()
const char * stir::FileSignature::get_signature () const inline
get access to the signature
Data is only valid up to size() (currently max 1024)
Referenced by stir::ecat::ecat7::ECAT7DynamicDiscretisedDensityInputFileFormat::actual_can_read(), stir::ecat::ecat7::ECAT966ListmodeInputFileFormat::actual_can_read(), stir::ecat::ecat7::ECAT966ListmodeInputFileFormat::can_read(), stir::ProjData::read_from_file(), stir::InputStreamFromROOTFile::set_up(), and stir::TimeFrameDefinitions::TimeFrameDefinitions().
The documentation for this class was generated from the following file:
/home/kris/devel/STIRdistrib/STIR/src/include/stir/IO/FileSignature.h