STIR: Implementation details for functions that implement IO for Array objects
Implementation details for functions that implement IO for Array objects
STIR » STIR library » Basic building blocks » Items relating to vectors and (multi-dimensional) arrays » Functions that implement IO for Array objects
Files
file read_data_1d.h
Declaration of stir::read_data_1d() functions for reading 1D stir::Array objects from file.
file read_data_1d.inl
Implementation of stir::read_data_1d() functions.
file write_data_1d.h
Declaration of stir::write_data_1d() functions for writing 1D stir::Array objects to file.
file write_data_1d.inl
Implementation of stir::write_data_1d() functions.
Functions
template<int num_dimensions, class elemT>
Succeeded stir::detail::read_data_1d (std::istream &s, ArrayType< num_dimensions, elemT > &data, const ByteOrder byte_order)
This is an internal function called by read_data(). It does the actual reading to std::istream.
template<int num_dimensions, class elemT>
Succeeded stir::detail::write_data_1d (std::ostream &s, const Array< num_dimensions, elemT > &data, const ByteOrder byte_order, const bool can_corrupt_data)
This is an internal function called by write_data(). It does the actual writing to std::ostream.
template<int num_dimensions, class elemT>
Succeeded stir::detail::write_data_1d (FILE *&fptr_ref, const ArrayType< num_dimensions, elemT > &data, const ByteOrder byte_order, const bool can_corrupt_data)
This is an internal function called by write_data(). It does the actual writing to FILE* using stdio functions.
Detailed Description
Function Documentation
read_data_1d()
template<int num_dimensions, class elemT> Succeeded stir::detail::read_data_1d (std::istream & s, ArrayType< num_dimensions, elemT > & data, const ByteOrder byte_order) inline
This is an internal function called by read_data(). It does the actual reading to std::istream.
This function might propagate any exceptions by std::istream::read.
References stir::Array< num_dimensions, elemT >::begin_all(), stir::Array< num_dimensions, elemT >::end_all(), stir::Array< num_dimensions, elemT >::get_full_data_ptr(), stir::ByteOrder::is_native_order(), read_data_1d(), stir::Array< num_dimensions, elemT >::release_full_data_ptr(), stir::Array< num_dimensions, elemT >::size_all(), stir::ByteOrder::swap_order(), and stir::warning().
Referenced by read_data_1d().
write_data_1d() [1/2]
template<int num_dimensions, class elemT> Succeeded stir::detail::write_data_1d (std::ostream & s, const Array< num_dimensions, elemT > & data, const ByteOrder byte_order, const bool can_corrupt_data) inline
This is an internal function called by write_data(). It does the actual writing to std::ostream.
This function does not throw any exceptions. Exceptions thrown by std::ostream::write are caught.
References stir::Array< num_dimensions, elemT >::begin_all(), stir::Array< num_dimensions, elemT >::end_all(), stir::Array< num_dimensions, elemT >::get_const_full_data_ptr(), stir::ByteOrder::is_native_order(), stir::Array< num_dimensions, elemT >::release_const_full_data_ptr(), stir::Array< num_dimensions, elemT >::size_all(), stir::ByteOrder::swap_order(), stir::warning(), and write_data_1d().
Referenced by write_data_1d(), and write_data_1d().
write_data_1d() [2/2]
template<int num_dimensions, class elemT> Succeeded stir::detail::write_data_1d (FILE *& fptr_ref, const ArrayType< num_dimensions, elemT > & data, const ByteOrder byte_order, const bool can_corrupt_data) inline
This is an internal function called by write_data(). It does the actual writing to FILE* using stdio functions.
This function does not throw any exceptions.
References write_data_1d().