STIR: Items related to ancillary information such as radionuclide, patient info etc
Items related to ancillary information such as radionuclide, patient info etc
STIR » STIR library » Basic building blocks
Files
file find_STIR_config.cxx
implementation of functions to get configuration directory etc
file RadionuclideDB.cxx
Implementation of class stir::RadionuclideDB.
file find_STIR_config.h
Declaration of functions to get configuration directory etc.
file Radionuclide.h
Declaration of class stir::Radionuclide.
file RadionuclideDB.h
Declaration of class stir::RadionuclideDB.
file test_radionuclide.cxx
A simple program to test stir::RadionuclideDB and stir::Radionuclide.
Namespaces
namespace stir
Namespace for the STIR library (and some/most of its applications)
Classes
class stir::Radionuclide
A class for storing radionuclide information.
class stir::RadionuclideTest
Class with tests for stir::RadionuclideDB and stir::Radionuclide.
Functions
std::string stir::find_STIR_config_file (const std::string &filename)
find full path of a config file
std::string stir::get_STIR_config_dir ()
find string with the (full) path of the directory where looks for STIR configuration files
std::string stir::get_STIR_doc_dir ()
find string with the (full) path of the directory where the STIR documentation was installed
std::string stir::get_STIR_examples_dir ()
find string with the (full) path of the directory where the STIR examples are installed
Detailed Description
Function Documentation
find_STIR_config_file()
std::string stir::find_STIR_config_file (const std::string & filename)
find full path of a config file
Returns
calls get_STIR_config_dir() and prepends it to filename
Does a brief check if the file can be opened.
References error(), find_STIR_config_file(), and get_STIR_config_dir().
Referenced by find_STIR_config_file().
get_STIR_config_dir()
std::string stir::get_STIR_config_dir ()
find string with the (full) path of the directory where looks for STIR configuration files
Returns
path name
First checks an environment variable STIR_CONFIG_DIR. If that isn't set, it returns the value of the STIR_CONFIG_DIR CMake variable set at build time (which has a default location in the installation directory).
References get_STIR_config_dir().
Referenced by find_STIR_config_file(), and get_STIR_config_dir().
get_STIR_doc_dir()
std::string stir::get_STIR_doc_dir ()
find string with the (full) path of the directory where the STIR documentation was installed
Returns
path name
First checks an environment variable STIR_DOC_DIR. If that isn't set, it returns the value of the STIR_DOC_DIR CMake variable set at build time (which has a default location in the installation directory).
References get_STIR_doc_dir().
Referenced by get_STIR_doc_dir(), and get_STIR_examples_dir().
get_STIR_examples_dir()
std::string stir::get_STIR_examples_dir ()
find string with the (full) path of the directory where the STIR examples are installed
Returns
path name
First checks an environment variable STIR_DOC_DIR. If that isn't set, it uses the value of the STIR_DOC_DIR CMake variable set at build time (which has a default location in the installation directory). At present, this function then simply adds "/examples" .
References get_STIR_doc_dir(), and get_STIR_examples_dir().
Referenced by get_STIR_examples_dir().