STIR: Items related to Line Of Responses (preliminary)
Items related to Line Of Responses (preliminary)
STIR » STIR library » Basic building blocks » Items related to projection data
Files
file LORCoordinates.h
defines various classes for specifying a line in 3 dimensions
file LORCoordinates.inl
Implementations for LORCoordinates.h.
Classes
class stir::LOR< coordT >
A base class for specifying an LOR with geometric coordinates.
class stir::PointOnCylinder< coordT >
A class for a point on a cylinder.
class stir::LORCylindricalCoordinates_z_and_radius< coordT >
An internal class for LORs. Do not use.
class stir::LORInCylinderCoordinates< coordT >
A class for LORs.
class stir::LORAs2Points< coordT >
A class for LORs.
class stir::LORInAxialAndSinogramCoordinates< coordT >
A class for LORs.
class stir::LORInAxialAndNoArcCorrSinogramCoordinates< coordT >
A class for LORs.
Functions
Succeeded stir::LORInCylinderCoordinates< coordT >::set_radius (coordT new_radius)
Changes the radius of the LOR.
template<class coordT1, class coordT2>
Succeeded stir::find_LOR_intersections_with_cylinder (LORInCylinderCoordinates< coordT1 > &, const LORAs2Points< coordT2 > &, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class coordT1, class coordT2>
Succeeded stir::find_LOR_intersections_with_cylinder (LORAs2Points< coordT1 > &intersection_coords, const LORAs2Points< coordT2 > &coords, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class coordT1, class coordT2>
Succeeded stir::find_LOR_intersections_with_cylinder (LORInAxialAndNoArcCorrSinogramCoordinates< coordT1 > &lor, const LORAs2Points< coordT2 > &cart_coords, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class coordT1, class coordT2>
Succeeded stir::find_LOR_intersections_with_cylinder (LORInAxialAndSinogramCoordinates< coordT1 > &lor, const LORAs2Points< coordT2 > &cart_coords, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
Detailed Description
Classes for LORs.
Warning
Preliminary and likely to change in the next release
Function Documentation
set_radius()
template<class coordT> Succeeded stir::LORInCylinderCoordinates< coordT >::set_radius (coordT new_radius) inline
Changes the radius of the LOR.
Warning
This does not preserve the LOR. Instead, it scales the LOR radially.
find_LOR_intersections_with_cylinder() [1/4]
template<class coordT1, class coordT2> Succeeded stir::find_LOR_intersections_with_cylinder (LORInCylinderCoordinates< coordT1 > & cyl_coords, const LORAs2Points< coordT2 > & cart_coords, const double radius) inline
Given an LOR, find its intersection with a (infintely long) cylinder.
Warning
This is all preliminary and likely to change.
References find_LOR_intersections_with_cylinder(), and from_min_pi_plus_pi_to_0_2pi().
Referenced by find_LOR_intersections_with_cylinder(), find_LOR_intersections_with_cylinder(), find_LOR_intersections_with_cylinder(), and stir::ProjDataInfoCylindricalNoArcCorr::find_scanner_coordinates_given_cartesian_coordinates().
find_LOR_intersections_with_cylinder() [2/4]
template<class coordT1, class coordT2> Succeeded stir::find_LOR_intersections_with_cylinder (LORAs2Points< coordT1 > & intersection_coords, const LORAs2Points< coordT2 > & coords, const double radius) inline
Given an LOR, find its intersection with a (infintely long) cylinder.
Warning
This is all preliminary and likely to change.
References square().
find_LOR_intersections_with_cylinder() [3/4]
template<class coordT1, class coordT2> Succeeded stir::find_LOR_intersections_with_cylinder (LORInAxialAndNoArcCorrSinogramCoordinates< coordT1 > & lor, const LORAs2Points< coordT2 > & cart_coords, const double radius) inline
Given an LOR, find its intersection with a (infintely long) cylinder.
Warning
This is all preliminary and likely to change.
References find_LOR_intersections_with_cylinder().
find_LOR_intersections_with_cylinder() [4/4]
template<class coordT1, class coordT2> Succeeded stir::find_LOR_intersections_with_cylinder (LORInAxialAndSinogramCoordinates< coordT1 > & lor, const LORAs2Points< coordT2 > & cart_coords, const double radius) inline
Given an LOR, find its intersection with a (infintely long) cylinder.
Warning
This is all preliminary and likely to change.
References find_LOR_intersections_with_cylinder().