STIR: Items relating to coordinates
Items relating to coordinates
STIR » STIR library » Basic building blocks
Files
file BasicCoordinate.h
This file declares class stir::BasicCoordinate and some functions acting on stir::BasicCoordinate objects.
file BasicCoordinate.inl
(inline) implementations for stir::BasicCoordinate
file CartesianCoordinate2D.h
defines the stir::CartesianCoordinate2D<coordT> class
file CartesianCoordinate2D.inl
inline implementations for the stir::CartesianCoordinate2D<coordT> class
file CartesianCoordinate3D.h
defines the stir::CartesianCoordinate3D<coordT> class
file CartesianCoordinate3D.inl
inline implementations for the stir::CartesianCoordinate3D<coordT> class
file Coordinate2D.h
defines the stir::Coordinate2D<coordT> class
file Coordinate3D.h
defines the stir::Coordinate3D<coordT> class
file Coordinate3D.inl
inline implementations for the stir::Coordinate3D class
file Coordinate4D.h
defines the stir::Coordinate4D<coordT> class
file Coordinate4D.inl
inline implementations for the stir::Coordinate4D class
Classes
class stir::BasicCoordinate< num_dimensions, coordT >
class BasicCoordinate<int num_dimensions, typename coordT> defines num_dimensions -dimensional coordinates.
class stir::CartesianCoordinate2D< coordT >
a templated class for 2-dimensional coordinates.
class stir::CartesianCoordinate3D< coordT >
a templated class for 3-dimensional coordinates.
class stir::Coordinate2D< coordT >
a templated class for 2-dimensional coordinates.
class stir::Coordinate3D< coordT >
a templated class for 3-dimensional coordinates.
class stir::Coordinate4D< coordT >
a templated class for 4-dimensional coordinates.
Functions
template<int num_dimensions, typename coordT >
coordT stir::inner_product (const BasicCoordinate< num_dimensions, coordT > &p1, const BasicCoordinate< num_dimensions, coordT > &p2)
compute sum_i p1[i] * p2[i]
template<int num_dimensions, typename coordT >
double stir::norm_squared (const BasicCoordinate< num_dimensions, coordT > &p1)
compute (inner_product(p1,p1))
template<int num_dimensions, typename coordT >
double stir::norm (const BasicCoordinate< num_dimensions, coordT > &p1)
compute sqrt(inner_product(p1,p1))
template<int num_dimensions, typename coordT >
double stir::angle (const BasicCoordinate< num_dimensions, coordT > &p1, const BasicCoordinate< num_dimensions, coordT > &p2)
compute angle between 2 directions
template<int num_dimensions, typename coordT >
double stir::cos_angle (const BasicCoordinate< num_dimensions, coordT > &p1, const BasicCoordinate< num_dimensions, coordT > &p2)
compute cos of the angle between 2 directions
template<int num_dimensions, typename coordT >
BasicCoordinate< num_dimensions+1, coordT > stir::join (const coordT &a, const BasicCoordinate< num_dimensions, coordT > &c)
make a longer BasicCoordinate, by prepending c with the single coordT
template<int num_dimensions, class coordT >
BasicCoordinate< num_dimensions+1, coordT > stir::join (const BasicCoordinate< num_dimensions, coordT > &c, const coordT &a)
make a longer BasicCoordinate, by appending the coordT to c
template<int num_dimensions, class coordT >
BasicCoordinate< num_dimensions - 1, coordT > stir::cut_last_dimension (const BasicCoordinate< num_dimensions, coordT > &c)
make a shorter BasicCoordinate, by cutting the last element from c
template<int num_dimensions, typename coordT >
BasicCoordinate< num_dimensions - 1, coordT > stir::cut_first_dimension (const BasicCoordinate< num_dimensions, coordT > &c)
make a shorter BasicCoordinate, by cutting the first element from c
template<int num_dimensions>
BasicCoordinate< num_dimensions, float > stir::convert_int_to_float (const BasicCoordinate< num_dimensions, int > &cint)
converts a BasicCoordinate<int> to BasicCoordinate<float>
Detailed Description
Function Documentation
inner_product()
template<int num_dimensions, typename coordT > coordT stir::inner_product (const BasicCoordinate< num_dimensions, coordT > & p1, const BasicCoordinate< num_dimensions, coordT > & p2) inline
compute sum_i p1[i] * p2[i]
Todo:
move to a new CartesianCoordinate class
Referenced by stir::absolute_max_eigenvector_using_power_method(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin< TargetT >::actual_compute_objective_function_without_penalty(), stir::coordinate_between_2_lines(), stir::cos_angle(), stir::distance_between_line_and_point(), stir::ProjMatrixByBin::get_proj_matrix_elems_for_one_bin(), stir::norm_squared(), stir::project_point_on_a_line(), stir::coordinateTests::run_tests(), stir::PLSPrior< elemT >::set_anatomical_filename(), stir::PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests::test_approximate_Hessian_concavity(), stir::ObjectiveFunctionTests< GeneralisedPrior< DiscretisedDensity< 3, float > >, DiscretisedDensity< 3, float > >::test_gradient(), stir::ObjectiveFunctionTests< GeneralisedPrior< DiscretisedDensity< 3, float > >, DiscretisedDensity< 3, float > >::test_Hessian_concavity(), and stir::GeneralisedPriorTests::test_Hessian_convexity_configuration().
norm_squared()
template<int num_dimensions, typename coordT > double stir::norm_squared (const BasicCoordinate< num_dimensions, coordT > & p1) inline
compute (inner_product(p1,p1))
Todo:
move to a new CartesianCoordinate class
References stir::inner_product().
Referenced by stir::abs_max_element(), stir::absolute_max_eigenvector_using_power_method(), stir::cos_angle(), stir::ScatterSimulation::detection_efficiency_no_scatter(), stir::Ellipsoid::is_inside_shape(), stir::norm(), stir::norm_squared(), stir::ProjDataInMemory::norm_squared(), stir::RigidObject3DTransformation::RMSE(), and stir::SingleScatterSimulation::simulate_for_one_scatter_point().
norm()
template<int num_dimensions, typename coordT > double stir::norm (const BasicCoordinate< num_dimensions, coordT > & p1) inline
compute sqrt(inner_product(p1,p1))
Todo:
move to a new CartesianCoordinate class
References stir::norm_squared().
Referenced by stir::absolute_max_eigenvector_using_power_method(), stir::DiscretisedDensityOnCartesianGrid< 3, elemT >::actual_has_same_characteristics(), stir::DiscretisedDensity< 3, float >::actual_has_same_characteristics(), stir::ITKOutputFileFormat::actual_write_to_file(), stir::ProjDataInfoCylindrical::blindly_equals(), stir::RunTests::check_if_equal(), stir::RunTests::check_if_zero(), stir::ProjMatrixByBin::get_proj_matrix_elems_for_one_bin(), stir::RigidObject3DMotionFromPolaris::get_rel_time_of_samples(), stir::norm(), stir::ProjDataInMemory::norm(), stir::Shape3D::operator==(), stir::RigidObject3DMotionFromPolaris::post_processing(), stir::RayTraceVoxelsOnCartesianGrid(), stir::coordinateTests::run_tests(), stir::RigidObject3DTransformationTests::run_tests(), stir::RelativeDifferencePriorTests< RDP >::run_tests(), stir::Shape3D::scale_around_origin(), and stir::ArrayFilterUsingRealDFTWithPadding< 2, float >::set_kernel().
angle()
template<int num_dimensions, typename coordT > double stir::angle (const BasicCoordinate< num_dimensions, coordT > & p1, const BasicCoordinate< num_dimensions, coordT > & p2) inline
compute angle between 2 directions
Implemented in terms of acos(cos_angle(p1,p2)).
Todo:
move to a new CartesianCoordinate class
References stir::cos_angle().
cos_angle()
template<int num_dimensions, typename coordT > double stir::cos_angle (const BasicCoordinate< num_dimensions, coordT > & p1, const BasicCoordinate< num_dimensions, coordT > & p2) inline
compute cos of the angle between 2 directions
Todo:
move to a new CartesianCoordinate class
References stir::inner_product(), and stir::norm_squared().
Referenced by stir::angle(), stir::ScatterSimulation::detection_efficiency_no_scatter(), and stir::SingleScatterSimulation::simulate_for_one_scatter_point().
join() [1/2]
template<int num_dimensions, typename coordT > BasicCoordinate< num_dimensions+1, coordT > stir::join (const coordT & a, const BasicCoordinate< num_dimensions, coordT > & c) inline
make a longer BasicCoordinate, by prepending c with the single coordT
Referenced by stir::coordinateTests::run_tests().
join() [2/2]
template<int num_dimensions, class coordT > BasicCoordinate< num_dimensions+1, coordT > stir::join (const BasicCoordinate< num_dimensions, coordT > & c, const coordT & a) inline
make a longer BasicCoordinate, by appending the coordT to c
cut_last_dimension()
template<int num_dimensions, class coordT > BasicCoordinate< num_dimensions - 1, coordT > stir::cut_last_dimension (const BasicCoordinate< num_dimensions, coordT > & c) inline
make a shorter BasicCoordinate, by cutting the last element from c
Referenced by stir::coordinateTests::run_tests().
cut_first_dimension()
template<int num_dimensions, typename coordT > BasicCoordinate< num_dimensions - 1, coordT > stir::cut_first_dimension (const BasicCoordinate< num_dimensions, coordT > & c) inline
make a shorter BasicCoordinate, by cutting the first element from c
Referenced by stir::get(), stir::Array< 2, float >::operator[](), and stir::coordinateTests::run_tests().
convert_int_to_float()
template<int num_dimensions> BasicCoordinate< num_dimensions, float > stir::convert_int_to_float (const BasicCoordinate< num_dimensions, int > & cint) inline
converts a BasicCoordinate<int> to BasicCoordinate<float>
Referenced by stir::ScatterSimulation::sample_scatter_points().