STIR: stir Namespace Reference
stir Namespace Reference
STIR » STIR library » Reconstruction building blocks » distributable building blocksSTIR » Test code for STIR » | Tests of the basic building blocks
Namespace for the STIR library (and some/most of its applications)
Namespaces
BSpline
Namespace for functions and classes for B-Spline interpolation in the STIR library.
detail
Namespace for the implementation details of the STIR library.
ecat
Namespace for the ECAT IO part of the STIR library (and some/most of its applications)
Classes
class AbsTimeInterval
Base class for specifying a time interval (in absolute time)
class AbsTimeIntervalFromDynamicData
class for specifying a time interval via a dynamic scan
class AbsTimeIntervalFromECAT7ACF
class for specifying a time interval via an ECAT7 .a file
class AbsTimeIntervalWithParsing
class for specifying a time interval via parsing of explicit times
class AnalyticReconstruction
base class for all analytic reconstruction algorithmsThis class provides extra functinoality (compared to Reconstruction) as it assumes that the TargetT is really a VoxelsOnCartesianGrid.
class ArcCorrection
A class to arc-correct projection data.
class ArcCorrectionTests
Test class for ArcCorrection.
class Array
This class defines multi-dimensional (numeric) arrays.
class Array< 1, elemT >
The 1-dimensional (partial) specialisation of Array.
class ArrayFilter1DUsingConvolution
This class implements convolution of a 1D array with an arbitrary (i.e. potentially non-symmetric) kernel.
class ArrayFilter1DUsingConvolutionSymmetricKernel
This class implements convolution of a 1D array with a symmetric kernel.
class ArrayFilterTests
Tests Array functionality.
class ArrayFilterUsingRealDFTWithPadding
This class implements convolution of an array of real numbers with an arbitrary (i.e. potentially non-symmetric) kernel using DFTs.
class ArrayFunctionObject
A class for operations on n-dimensional Arrays.
class ArrayFunctionObject_1ArgumentImplementation
A convenience class for children of ArrayFunctionObject. It implements the 2 argument operator() in terms of the in-place version.
class ArrayFunctionObject_2ArgumentImplementation
A convenience class for children of ArrayFunctionObject. It implements the in-place operator() in terms of the 2 argument version.
class ArrayTests
Tests Array functionality.
class BackProjectorByBin
Abstract base class for all back projectors.
class BackProjectorByBinUsingInterpolation
does backprojection by interpolating between the bins.
class BackProjectorByBinUsingProjMatrixByBin
This implements the BackProjectorByBin interface, given any ProjMatrixByBin object.
class BackProjectorByBinUsingSquareProjMatrixByBin
This implements the BackProjectorByBin interface, given any ProjMatrixByBin object.
class BasicCoordinate
class BasicCoordinate<int num_dimensions, typename coordT> defines num_dimensions -dimensional coordinates.
class BeginEndAllFunction
Helper class for NestedIterator when the 1st level iterator refers to a stir full iterator for the 2nd level iterator.
class BeginEndFunction
Helper class for NestedIterator when the 1st level iterator refers to an ordinary iterator for the 2nd level iterator.
class Bin
A class for storing coordinates and value of a single projection bin.
class BinNormalisation
Abstract base class for implementing bin-wise normalisation of data.
class BinNormalisationFromAttenuationImage
A BinNormalisation class that gets attenuation correction factors from an attenuation image.
class BinNormalisationFromML2D
A BinNormalisation class that gets the normalisation factors from the files output by find_ML_normfactors.
class BinNormalisationFromProjData
A BinNormalisation class that gets the normalisation factors from a ProjData object.
class BinNormalisationSinogramRescaling
The BinNormalisationSinogramRescaling class gets normaliastion factors by dividing forward projection of the fitted cyl. to the precorrecred data.
class BloodFrameData
A class for storing plasma samples of a single study.
class BoundaryConditions
Preliminary class to specify boundary conditions for filters.
class Box3D
Three-dimensional cuboid box.
class ByteOrder
This class provides member functions to find out what byte-order your machine is and to swap numbers.
class ByteOrderTests
Test class for ByteOrder and the preprocessor defines from ByteOrderDefine.h.
class CartesianCoordinate2D
a templated class for 2-dimensional coordinates.
class CartesianCoordinate3D
a templated class for 3-dimensional coordinates.
class ChainedBinNormalisation
A BinNormalisation class that simply multiplies the factors given by 2 BinNormalisation objects.
class ChainedDataProcessor
A class in the DataProcessor hierarchy that calls 2 DataProcessors in sequence.
class CListEvent
Class for storing and using a coincidence event from a list mode file.
class CListEventCylindricalScannerWithDiscreteDetectors
Class for storing and using a coincidence event from a list mode file for a cylindrical single layer scanner.
class CListEventCylindricalScannerWithViewTangRingRingEncoding
Helper class for listmode events when using 2d sinograms and ring-pairs is most efficient.
class CListEventDataLMF
Class for storing and using a coincidence event from a listmode file.
class CListEventDataSAFIR
Class for record with coincidence data.
class CListEventSAFIR
class CListModeData
The base class for reading list mode data.
class CListModeDataLMF
A class that reads the listmode data from an LMF file.
class CListModeDataROOT
class that reads ROOT files, generated by GATE, as listmode data.
class CListModeDataSAFIR
Class for reading SAFIR listmode data with variable geometry.
class CListRecordLMF
A class for a general element of a listmode file.
class CListRecordROOT
A class for a general element of a listmode file for a Siemens scanner using the ROOT files.
class CListRecordSAFIR
Class for general record, containing a union of data, time and raw record and providing access to certain elements.
class CListTimeDataLMF
A class for storing and using a timing 'event' from a listmode file.
class CListTimeDataSAFIR
Class for record with time data.
class CListTimeROOT
A class for storing and using a timing 'event' from a listmode file from the ECAT 8_32bit scanner.
class ColsherFilter
This class contains the Colsher filter used for 3D-PET reconstruction.
class CombinedShape3D
A class that allows combining several shapes using logical operations.
class ConstBeginEndAllFunction
Convenience class where the 2nd level iterator is a const_full_iterator.
class ConstBeginEndFunction
Convenience class where the 2nd level iterator is a const_iterator.
class ConstPtrBeginEndAllFunction
Convenience class where the 2nd level iterator is a const_full_iterator.
class ConstPtrBeginEndFunction
Convenience class where the 2nd level iterator is a const_iterator.
class convert_array_Tests
tests convert_array functionality
class Coordinate2D
a templated class for 2-dimensional coordinates.
class Coordinate3D
a templated class for 3-dimensional coordinates.
class Coordinate4D
a templated class for 4-dimensional coordinates.
class coordinateTests
Class with tests for BasicCoordinate, Coordinate3D et al.
class CorrectProjDataApplication
class to do precorrections
class CPUTimer
A class for measuring elapsed CPU time.
class CreateTailMaskFromACFs
The CreateTailMaskFromACFs class.
class DataProcessor
Base class that defines an interface for classes that do data processing.
class DataSymmetriesForBins
A class for encoding/finding symmetries common to the geometry of the projection data and the discretised density.
class DataSymmetriesForBins_PET_CartesianGrid
Symmetries appropriate for a (cylindrical) PET scanner, and a discretised density on a Cartesian grid.
class DataSymmetriesForBins_PET_CartesianGridTests
Test class for DataSymmetriesForBins_PET_CartesianGrid.
class DataSymmetriesForDensels
A class for encoding/finding symmetries common to the geometry of the projection data and the discretised density.
class DataSymmetriesForDensels_PET_CartesianGrid
Symmetries appropriate for a (cylindrical) PET scanner, and a discretised density on a Cartesian grid.
class DataSymmetriesForViewSegmentNumbers
A class for encoding/finding symmetries. Works only on ViewSegmentNumbers (instead of Bin).
class DetectionPosition
A class for storing coordinates of a detection.
class DetectionPositionPair
A class for storing 2 coordinates-sets of a detection, as suitable for PET.
class DetectorCoordinateMapFromFile
class DiscretisedDensity
This abstract class is the basis for all image representations.
class DiscretisedDensityOnCartesianGrid
This abstract class is the basis for images on a Cartesian grid.
class DiscretisedShape3D
A class for shapes that have been discretised.
class DistributedCachingInformation
This class implements the logic needed to support caching in a distributed manner.
class DistributedWorker
This implements the Worker for the stir::distributable_computation() function.
class DynamicDiscretisedDensity
Class of multiple image frames, one for each time frame Each time frame is a DiscretisedDensity<3,float>
class DynamicProjData
Dynamic projection data.
class Ellipsoid
Three-dimensional ellipsoid.
class EllipsoidalCylinder
Three-dimensional ellipsoidal cylinder.
class erfTests
A simple class to test the erf and erfc functions.
class ExamData
base class for data objects such as ProjData etcProvides an ExamInfo member.
class ExamInfo
a class for storing information about 1 exam (or scan)
class FactoryRegistry
This class can be used to store 'factories' and their corresponding keys. It is essentially a map, but with some extra embelishments.
class FBP2DReconstruction
Reconstruction class for 2D Filtered Back Projection.
class FBP3DRPReconstruction
This class contains the implementation of the FBP3DRP algorithm.
class FilenameTests
Test class for filename functions defined in utility.h.
class FilePath
The FilePath class.
class FileSignature
A class to read/store the file signature.
class Filter1D
Preliminary class for 1D filtering using FFTs.
class Filter2D
2-dimensional filters (filtering done by FFTs)
class FilterRootPrior
A class in the GeneralisedPrior hierarchy. This implements 'generalised' priors a la the Median Root Prior (which was invented by Sakari Alenius).
class find_fwhm_in_imageTests
A simple class to test the find_fwhm_in_image function.
class FindMCNormFactors
Class to compute 'time-efficiency' factors for motino corrected projection data.
class ForwardProjectorByBin
Abstract base class for all forward projectors.
class ForwardProjectorByBinUsingProjMatrixByBin
This implements the ForwardProjectorByBin interface, given any ProjMatrixByBin objectIt stores a shared_ptr to a ProjMatrixByBin object, which will be used to get the relevant elements of the projection matrix.
class ForwardProjectorByBinUsingRayTracing
This class implements forward projection using Siddon's algorithm for ray tracing. That is, it computes length of intersection with the voxels.
class FourierRebinning
Class for Serial FORE Reconstruction.
class FourierTests
A simple class to test the erf and erfc functions.
class FrameSinglesRates
A single frame of singles information.
class FullArrayIterator
Class FullArrayIterator implements (forward) iterators that go through all elements of an Array.
class GatedDiscretisedDensity
Class of multiple image gates.
class GatedSpatialTransformation
Class for spatial transformations for gated images.
class GeneralisedObjectiveFunction
A base class for 'generalised' objective functions, i.e. objective functions for which at least a 'gradient' is defined.
class GeneralisedPoissonNoiseGenerator
Generates noise realisations according to Poisson statistics but allowing for scaling.
class GeneralisedPoissonNoiseGeneratorTests
Tests GeneralisedPoissonNoiseGenerator functionalityCurrently contains only simple tests to check mean and variance.
class GeneralisedPrior
A base class for 'generalised' priors, i.e. priors for which at least a 'gradient' is defined.
class HighResWallClockTimer
High-resolution timer.
class ImagingModality
class IndexRange
This class defines ranges which can be 'irregular'.
class IndexRange2D
a 'convenience' class for 2D index ranges.
class IndexRange3D
a 'convenience' class for 3D index ranges. Provides an easier constructor for regular ranges.
class IndexRange4D
A convenience class for 4D index ranges.
class IndexRange< 1 >
The (simple) 1 dimensional specialisation of IndexRange.
class IndexRange_Tests
Class with tests for IndexRange, IndexRange3D.
class InputFileFormat
Base-class for file-formats for reading.
class InputFileFormatRegistry
A class for registering (and finding) all input file formats.
class InputStreamFromROOTFile
A helper class to read data from a ROOT file Generated by GATE simulation toolkit.
class InputStreamFromROOTFileForCylindricalPET
Declaration of class stir::InputStreamFromROOTFileForCylindricalPET.
class InputStreamFromROOTFileForECATPET
Declaration of class stir::InputStreamFromROOTFileForECATPET.
class InputStreamWithRecords
A helper class to read data from a (presumably binary) stream.
class integrate_discrete_functionTests
A simple class to test the integrate_discrete_function function.
struct interfile_less
A function object that compares Interfile keywords.
class InterfileDynamicDiscretisedDensityInputFileFormat
Class for reading images in Interfile file-format.
class InterfileDynamicDiscretisedDensityOutputFileFormat
Implementation of OutputFileFormat paradigm for the Interfile format.
class InterfileHeader
a class for Interfile keywords (and parsing) common to all types of data
class InterfileHeaderSiemens
a class for Interfile keywords (and parsing) common to all types of data
class InterfileImageHeader
a class for Interfile keywords (and parsing) specific to images
class InterfileImageInputFileFormat
Class for reading images in Interfile file-format.
class InterfileListmodeHeaderSiemens
a class for Interfile keywords (and parsing) specific to Siemesn listmode data (in PETLINK format)
class InterfileOutputFileFormat
Implementation of OutputFileFormat paradigm for the Interfile format.
class InterfileParametricDiscretisedDensityInputFileFormat
Class for reading images in Interfile file-format.
class InterfileParametricDiscretisedDensityOutputFileFormat
Implementation of OutputFileFormat paradigm for the Interfile format.
class InterfilePDFSHeader
a class for Interfile keywords (and parsing) specific to projection data (i.e. ProjDataFromStream)
class InterfilePDFSHeaderSiemens
a class for Interfile keywords (and parsing) specific to projection data (i.e. ProjDataFromStream)
class InterfilePDFSHeaderSPECT
a class for Interfile keywords (and parsing) specific to SPECT projection data
class InterfileRawDataHeaderSiemens
a class for Interfile keywords (and parsing) specific to Siemens PET projection or list mode data
class IOTests
A simple class to test the OutputFileFormat function.
class IOTests_DiscretisedDensity
A simple class to test the OutputFileFormat function.
class IOTests_DynamicDiscretisedDensity
A simple class to test the OutputFileFormat function.
class IOTests_ParametricDiscretisedDensity
A simple class to test the OutputFileFormat function.
class IR_filterTests
A simple class to test the IIR_filter and FIR_filter function.
class IterativeReconstruction
base class for iterative reconstruction objectsThis is the base class for all iterative reconstruction methods. It provides the basic iteration mechanisms. What each iteration does has to be implemented in a derived class.
class ITKImageInputFileFormat
Class for reading images using ITK.
class ITKOutputFileFormat
Implementation of OutputFileFormat paradigm using the ITK library for writing.
class JacobianForIntBP
The next class is used in BackProjectorByBinUsingInterpolation to take geometric things into account. It also includes some normalisation. (internal use only).
class KeyArgument
A class that enumerates the possible types that can be used to store parsed values. Used (only) by KeyParser.
class KeyParser
A class to parse Interfile headers.
class KeyParserTests
Test class for KeyParser.
class KineticModel
base class for all kinetic modelsAt present very basic. It just provides the parsing mechanism.
class Line
A class used by the Interfile parser.
class linear_regressionTests
A simple class to test the linear_regression function.
class ListEvent
Class for storing and using gamma events from a list mode file.
class ListGatingInput
A class recording external input to the scanner (normally used for gating)
class ListModeData
The base class for reading list mode data.
class ListRecord
A class for a general element of a list mode file.
class ListTime
A class for storing and using a timing record from a listmode file.
class LmToProjData
This class is used to bin listmode data to projection data, i.e. (3d) sinograms.
class LmToProjDataBootstrap
Class for binning list mode data into projection data using the bootstrap procedure.
class LmToProjDataWithMC
Class for binning list mode files with motion correction.
class LmToProjDataWithRandomRejection
Class for binning list mode data into projection data using the bootstrap procedure.
class LOR
A base class for specifying an LOR with geometric coordinates.
class LORAs2Points
A class for LORs.
class LORCylindricalCoordinates_z_and_radius
An internal class for LORs. Do not use.
class LORInAxialAndNoArcCorrSinogramCoordinates
A class for LORs.
class LORInAxialAndSinogramCoordinates
A class for LORs.
class LORInCylinderCoordinates
A class for LORs.
class map_element
Class to store the Interfile keywords and their actions.
struct MaskingParameters
A struct to hold the parameters for image masking.
class MatchTrackerAndScanner
A class for finding the coordinate transformation between tracker and scanner coordinate systems.
class MatrixTests
Tests MatrixFunction.h functionality.
class MaximalArrayFilter3D
Implements erosion on 3D arrays.
class MaximalImageFilter3D
A class in the ImageProcessor hierarchy that implements maximal filtering.
class MedianArrayFilter3D
Implements median filtering on 3D arrays.
class MedianImageFilter3D
A class in the ImageProcessor hierarchy that implements median filtering.
class MinimalArrayFilter3D
Implements erosion on 3D arrays.
class MinimalImageFilter3D
A class in the ImageProcessor hierarchy that implements minimal filtering.
class MinimalInterfileHeader
a minimal class for Interfile keywords (and parsing) common to all types of data
class modellingTests
A simple class to test modelling functions.
class ModelMatrix
A helper class to store the model matrix for a linear kinetic model.
class MoveImage
A class for moving an image according to average motion in the frame.
class MoveProjData
A class for moving projection data according to average motion in the frame.
class MultiDynamicDiscretisedDensityInputFileFormat
Class for reading images in Multi file-format.
class MultiDynamicDiscretisedDensityOutputFileFormat
Implementation of OutputFileFormat paradigm for the Multi format.
class MultipleProjDataTests
Test class for MultipleProjData.
class multiply_plane_scale_factorsImageProcessor
Simply multiplies each plane in an image with a scale factor.
class MyApp
A class for moving an image according to average motion in the frame.
class NestedIterator
Class NestedIterator implements a (forward) iterator using a pair of 'nested' iterators.
class NestedIteratorTests
Tests NestedIterator functionality.
class NonRigidObjectTransformationUsingBSplines
Class to perform non-rigid object transformations in arbitrary dimensions.
class NonseparableConvolutionUsingRealDFTImageFilter
A class derived from DataProcessor for performing separable periodic convolutions with an array kernel.
struct NormSquared
A helper class that computes the square of the norm of numeric data.
class NumericInfo
class NumericInfo<NUMBER> defines properties for the type NUMBER.
class NumericInfo< double >
Basic properties of double.
class NumericInfo< float >
Basic properties of float.
class NumericInfo< signed char >
Basic properties of signed char.
class NumericInfo< signed int >
Basic properties of signed int.
class NumericInfo< signed long >
Basic properties of signed long.
class NumericInfo< signed short >
Basic properties of signed short.
class NumericInfo< unsigned char >
Basic properties of unsigned char.
class NumericInfo< unsigned int >
Basic properties of unsigned int.
class NumericInfo< unsigned long >
Basic properties of unsigned long.
class NumericInfo< unsigned short >
Basic properties of unsigned short.
class NumericType
provides names for some numeric types and methods for finding their properties.
class NumericVectorWithOffset
like VectorWithOffset, but with changes in various numeric operators
class ObjectTransformation
Base-class for performing (potentially non-rigid) object transformations.
class OSMAPOSLReconstruction
Implementation of the Ordered Subsets version of Green's MAP One Step Late algorithm.
class OSSPSReconstruction
Implementation of the relaxed Ordered Subsets Separable Paraboloidal Surrogate (OSSPS)
class OutputFileFormat
Base class for classes that create output files.
class OutputFileFormatTests
A simple class to test the OutputFileFormat function.
class overlap_interpolateTests
Test class for stir::overlap_interpolate.
struct Parametric2Single
A helper class to find the type of a 'single' image for a corresponding parametric image.
class ParametricDiscretisedDensity
Class to store parametric images.
class ParametricQuadraticPrior
A class in the GeneralisedPrior hierarchy. This implements a quadratic Gibbs prior.
class ParseAndCreateFrom
template for adding keywords to a parser and creating an object
class ParseAndCreateFrom< DiscretisedDensity< 3, elemT >, ExamDataT >
parse keywords for creating a VoxelsOnCartesianGrid from ProjData etc
class ParseAndCreateFrom< ParametricDiscretisedDensity< VoxelsOnCartesianGrid< elemT > >, ExamDataT >
parse keywords for creating a parametric VoxelsOnCartesianGrid from DynamicProjData etc
class ParseDiscretisedDensityParameters
Class for adding parameters relevant to DiscretisedDensity to a parser.
class ParsingObject
A base class for objects that want to be able to parse parameter files.
class PatientPosition
class PatlakPlot
Patlak kinetic model.
class PixelsOnCartesianGrid
This class is used to represent pixelised densities on a rectangular grid (2D).
class PlasmaData
A class for storing plasma samples of a single study.
class PointOnCylinder
A class for a point on a cylinder.
class PoissonLogLikelihoodWithLinearKineticModelAndDynamicProjectionData
a base class for LogLikelihood of independent Poisson variables where the mean values are linear combinations of the kinetic parameters.
class PoissonLogLikelihoodWithLinearModelForMean
a base class for LogLikelihood of independent Poisson variables where the mean values are linear combinations of the parameters.
class PoissonLogLikelihoodWithLinearModelForMeanAndDynamicProjData
a base class for LogLikelihood of independent Poisson variables where the mean values are linear combinations of the frames.
class PoissonLogLikelihoodWithLinearModelForMeanAndGatedProjDataWithMotion
a base class for LogLikelihood of independent Poisson variables where the mean values are linear combinations of the gated images.
class PoissonLogLikelihoodWithLinearModelForMeanAndListModeData
An objective function class appropriate for PET list mode data.
class PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin
Class for PET list mode data from static images for a scanner with discrete detectors.
class PoissonLogLikelihoodWithLinearModelForMeanAndProjData
An objective function class appropriate for PET emission data.
class PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests
Test class for PoissonLogLikelihoodWithLinearModelForMeanAndProjData.
class Polaris_MT_File
a class for parsing .mt files output by the Polaris software
class PostsmoothingBackProjectorByBin
A very preliminary class that first smooths the image, then back projects.
class PostsmoothingForwardProjectorByBin
A very preliminary class that first forward projects, and then smooths the viewgrams.
class PrepareProjData
A preliminary class to prepare files for iterative reconstruction.
class PresmoothingForwardProjectorByBin
A very preliminary class that first smooths the image, then forward projects.
class PriorWithParabolicSurrogate
this class implements priors with a parabolic surrogate curvature
class ProjData
The (abstract) base class for the projection data.
class ProjDataFromStream
A class which reads/writes projection data from/to a (binary) stream.
class ProjDataGEAdvance
A class which reads projection data from a GE Advance sinogram file.
class ProjDataInfo
An (abstract base) class that contains information on the projection data.
class ProjDataInfoCylindrical
projection data info for data corresponding to a 'cylindrical' sampling.
class ProjDataInfoCylindricalArcCorr
Projection data info for arc-corrected data.
class ProjDataInfoCylindricalArcCorrTests
Test class for ProjDataInfoCylindricalArcCorr.
class ProjDataInfoCylindricalNoArcCorr
Projection data info for data which are not arc-corrected.
class ProjDataInfoCylindricalNoArcCorrTests
Test class for ProjDataInfoCylindricalNoArcCorr.
class ProjDataInfoCylindricalTests
Test class for ProjDataInfoCylindrical.
class ProjDataInfoTests
Test class for ProjDataInfo.
class ProjDataInMemory
A class which reads/writes projection data from/to memory.
class ProjDataInMemoryTests
Test class for ProjDataInMemory.
class ProjDataInterfile
A class which reads/writes projection data from/to a (binary) stream, but creates the corresponding Interfile header.
class ProjDataRebinning
base class for all rebinning algorithms for 3D PET dataTODO describe what rebinning is and why you need it
class ProjectorByBinPair
Abstract base class for all projector pairs.
class ProjectorByBinPairUsingProjMatrixByBin
A projector pair based on a single matrix.
class ProjectorByBinPairUsingSeparateProjectors
A projector pair based on a single matrix.
class ProjMatrixByBin
This is the (abstract) base class for all projection matrices which are organised by 'bin'.
class ProjMatrixByBinFromFile
Reads/writes a projection matrix from/to file.
class ProjMatrixByBinSinglePhoton
a 'projection matrix' to implement a model for a single photon acquisition in terms of the detector efficiencies.
class ProjMatrixByBinUsingInterpolation
Computes projection matrix elements for VoxelsOnCartesianGrid images by using an interpolation model.
class ProjMatrixByBinUsingInterpolationTests
Test class for ProjMatrixByBinUsingInterpolation.
class ProjMatrixByBinUsingRayTracing
Computes projection matrix elements for VoxelsOnCartesianGrid images by using a Length of Intersection (LOI) model.
class ProjMatrixByBinUsingSolidAngle
Computes projection matrix elements for VoxelsOnCartesianGrid images by using a Solid Angle model.
class ProjMatrixByBinWithPositronRange
Computes projection matrix elements for VoxelsOnCartesianGrid images by using a Solid Angle model.
class ProjMatrixByDensel
This is the (abstract) base class for all projection matrices which are organised by 'Densel'.
class ProjMatrixByDenselOnCartesianGridUsingElement
Computes projection matrix elements for VoxelsOnCartesianGrid images by using a Length of Intersection (LOI) model.
class ProjMatrixByDenselUsingRayTracing
Computes projection matrix elements for VoxelsOnCartesianGrid images by using a Length of Intersection (LOI) model.
class ProjMatrixElemsForOneBin
This stores the non-zero projection matrix elements for every 'densel' that contributes to a given bin.
class ProjMatrixElemsForOneBinValue
Stores voxel coordinates and the value of the matrix element.
class ProjMatrixElemsForOneDensel
This stores the non-zero projection matrix elements for every 'voxel'.
class ProjMatrixElemsForOneDenselValue
Stores voxel coordinates and the value of the matrix element.
class PtrBeginEndAllFunction
Helper class for NestedIterator when the 1st level iterator refers to a pointer to a stir full iterator for the 2nd level iterator.
class PtrBeginEndFunction
Helper class for NestedIterator when the 1st level iterator refers to pointers to an ordinary iterator for the 2nd level iterator.
class PullLinearInterpolator
A function object to pull interpolated values from the input array into the grid points of the output array.
class PullNearestNeighbourInterpolator
A function object to pull interpolated values from the input array into the grid points of the output array.
class PushNearestNeighbourInterpolator
A function object to push values at the grid of the input array into the output array.
class PushTransposeLinearInterpolator
A function object to push values at the grid of the input array into the output array.
class QuadraticPrior
A class in the GeneralisedPrior hierarchy. This implements a quadratic Gibbs prior.
class QuaternionTests
Test class for Quaternion.
class RampFilter
The ramp filter used for (2D) FBP.
class Reconstruction
base class for all ReconstructionsAs there is not a lot of commonality between different reconstruction algorithms, this base class is rather basic. It essentially takes care of constructing a target image, calls the virtual reconstruct() function, and writes the result to file.
class RegisteredObject
Helper class to provide registry mechanisms to a Base classSuppose you have a hierarchy of classes with (nearly) all public functionality provided by virtual functions of the Base class. The aim is then to be able to select at run-time which of the nodes will be used.
class RegisteredObjectBase
Base class for all classes that can parse .par files (and more?)The only reason that this class exists is such that KeyParser can store different types of objects, and get some basic info from it.
class RegisteredParsingObject
Parent class for all leaves in a RegisteredObject hierarchy that do parsing of parameter files.
struct RegisterInputFileFormat
A helper class to allow automatic registration to the default InputFileFormatRegistry.
class RelatedBins
This class contains all information about a set of bins related by symmetry.
class RelatedDensels
This class contains all information about a set of densels related by symmetry.
class RelatedViewgrams
A class for storing viewgrams which are related by symmetry.
class ReportMovement
A class for reporting the movement within the frame w.r.t. to the reference position.
struct ResolutionIndex
a structure that is used to hold the output of the function find_fwhm_in_image.
class RigidObject3DMotion
Base class for 3D rigid motion.
class RigidObject3DMotionFromPolaris
A class for handling motion information from the Polaris tracker.
class RigidObject3DTransformation
Class to perform rigid object transformations in 3 dimensions.
class RigidObject3DTransformationTests
Various tests on RigidObject3DTransformation.
class ROITests
Test class for compute_ROI_values and Shape3D hierarchy.
class ROIValues
A class to store and get results of an ROI calculation.
class ROOTListmodeInputFileFormat
The ROOTListmodeInputFileFormat class.
class RunTests
A base class for making test classesWith a derived class, an application could look like.
class SAFIRCListmodeInputFileFormat
class Scanner
A class for storing some info on the scanner.
class ScannerTests
Test class for Scanner.
class ScatterEstimation
Estimate the scatter probability using a model-based approach.
class ScatterSimulation
Simulate the scatter probability using a model-based approach.
class ScatterSimulationTests
Test class for ScatterSimulation.
class Segment
An (abstract base) class for storing 3d projection dataThis stores a subset of the data accessible via a ProjData object, where the segment_num is fixed.
class SegmentBySinogram
A class for storing (3d) projection data with a fixed segment_num.
class SegmentByView
A class for storing (3d) projection data with a fixed segment_num.
class SeparableArrayFunctionObject
This class implements an n -dimensional ArrayFunctionObject whose operation is separable.
class SeparableArrayFunctionObject2
This class implements an n -dimensional ArrayFunctionObject whose operation is separable.
class SeparableCartesianMetzImageFilter
A class in the DataProcessor hierarchy that implements Metz filtering (which includes Gaussian filtering).
class SeparableConvolutionImageFilter
A class derived from DataProcessor for performing separable non-periodic convolutions.
class SeparableGaussianArrayFilter
Separable Gaussian filtering in n - dimensions.
class SeparableGaussianImageFilter
A class in the DataProcessor hierarchy that implements Gaussian filtering.
class SeparableMetzArrayFilter
Separable Metz filtering in n - dimensions.
class SeparableMetzArrayFilterTests
Tests SeparableMetzArrayFilter functionalityCurrently only very basic tests on normalisation.
class Shape3D
The base class for all 3 dimensional shapes.
class Shape3DWithOrientation
Class for shapes with orientation.
class SingleScatterSimulation
PET single scatter simulation.
class SinglesRates
The base-class for using singles info.
class SinglesRatesForTimeFrames
A class for singles rates that are recorded in time frames.
class Sinogram
A class for 2d projection data.
class SpatialTransformation
base class for any type of motion fieldsAt present very basic. It just provides the parsing mechanism.
class SPECTListEvent
Class for storing and using gamma events from a SPECT List mode file.
class SPECTListModeData
The base class for reading SPECT list mode data.This class (and SPECTListRecord) is specific to SPECT, i.e. to single gamma detection. However, the only difference with the PET part are the functions related to prompts and delayeds. SPECT is handled by calling all single photon events 'prompts'.
class SPECTListRecord
A class for a general element of a list mode file.
class stir_mathTests
Test class for the stir_math utility.
class Succeeded
a class containing an enumeration type that can be used by functions to signal successful operation or not
class SumOfGeneralisedObjectiveFunctions
A base class for sums of 'generalised' objective functions, i.e. objective functions for which at least a 'gradient' is defined.
class SymmetryOperation
Encodes symmetry operation on image coordinates and projection data coordinates.
class TestBSplineTransformation
Test class for Transformations.
class TestDataProcessorProjectors
Test class for GPU projectors.
class ThresholdMinToSmallPositiveValueDataProcessor
A class in the DataProcessor hierarchy for making sure all elements are strictly positive.
class TimedBlock< TimerT=Timer >
Helper class for measuring execution time of a block of code.It starts the timer in ctor, stops in dtor. Do not create unnamed instances of this class, as they are quite useless: you cannot predict destruction time.
class TimedObject
base class for all objects which need timers. At the moment, there's only a CPU timer.
class TimeFrameDefinitions
Class used for storing time frame durations.
class TimeFrameMotion
A class for encoding average motion in the frames.
class TimeGateDefinitions
Class used for storing time gate durations.
class Timer
A general base class for timers. Interface is like a stop watch.
class Transform3DObjectImageProcessor
A class in the ImageProcessor hierarchy that performs movement by reinterpolation.
class TrivialBinNormalisation
Trivial class which does not do any normalisation whatsoever.
class TrivialDataSymmetriesForBins
A class derived from DataSymmetriesForBins that says that there are no symmetries at all.
class TrivialDataSymmetriesForViewSegmentNumbers
A class for encoding/finding NO symmetries. Works only on ViewSegmentNumbers (instead of Bin).
class TrivialSymmetryOperation
A class implementing the trivial case where the symmetry operation does nothing at all.
class TruncateToCylindricalFOVImageProcessor
A class in the DataProcessor hierarchy that sets voxels to 0 outside a given radius.
struct TypeForNumericType
A helper class that specifies the C++ type for a particular NumericType.
class Utah_phantom
A class that represents a Utah phantom.
class VectorWithOffset
A templated class for vectors, but with indices starting not from 0.
class VectorWithOffsetTests
Test class for VectorWithOffset.
class Verbosity
This class enables the user to control the on-screen output.
class Viewgram
A class for 2d projection data.
class ViewSegmentNumbers
A very simple class to store view and segment numbers.
class VoxelsOnCartesianGrid
This class is used to represent voxelised densities on a cuboid grid (3D).
class VoxelsOnCartesianGridTests
Test class for VoxelsOnCartesianGrid and image hierarchy.
class warp_imageTests
Class with tests for warp_image functions.
class zoom_imageTests
Test class for zoom_image (and centre_of_gravity)
class ZoomOptions
This class enables the user to choose between different zooming optionsThe 3 possible values determine a global scale factor used for the end result: (i) preserve sum (locally) (ii) preserve values (like interpolation) (iii) preserve projections: using a STIR forward projector on the zoomed image will give (approximately) the same projections.
Typedefs
typedef char assert_unsigned_long_size[sizeof(unsigned long) - sizeof(unsigned char)]
typedef SegmentByView< elem_type > segment_type
typedef VectorWithOffset< shared_ptr< segment_type > > all_segments_type
typedef Array< 1, std::complex< float > > ArrayC1
typedef Array< 1, float > ArrayF1
typedef Array< 2, float > ArrayF2
typedef Array< 2, std::complex< float > > ArrayC2
typedef Array< 3, float > ArrayF3
typedef Array< 3, std::complex< float > > ArrayC3
typedef Coordinate3D< int > Densel
a typedef used for an element of a DiscretisedDensity
typedef std::vector< std::string > ASCIIlist_type
typedef Array< 2, float > GeoData
typedef Array< 2, float > BlockData
typedef Array< 2, float > DetectorEfficiencies
typedef FanProjData BlockData3D
typedef VoxelsOnCartesianGrid< KineticParameters< 2, float > > ParametricVoxelsOnCartesianGridBaseType
Convenience typedef for base-type of Cartesian Voxelised Parametric Images with just two parameters.
typedef ParametricDiscretisedDensity< ParametricVoxelsOnCartesianGridBaseType > ParametricVoxelsOnCartesianGrid
Convenience typedef for Cartesian Voxelised Parametric Images with just two parameters.
typedef Coordinate2D< int > AxTangPosNumbers
AxTangPosNumbers as a class that provides the 2 remaining coordinates for a Bin, aside from ViewSegmentNumbers.
typedef void RPC_process_related_viewgrams_type(const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, RelatedViewgrams< float > *measured_viewgrams_ptr, int &count, int &count2, double *log_likelihood_ptr, const RelatedViewgrams< float > *additive_binwise_correction_ptr, const RelatedViewgrams< float > *mult_viewgrams_ptr)
typedef for callback functions for distributable_computation()
typedef itk::Image< float, 3 > ITKImageSingle
Class for reading images in ITK file-format.
typedef itk::VectorImage< float, 3 > ITKImageMulti
typedef DiscretisedDensity< 3, float > STIRImageSingle
typedef VoxelsOnCartesianGrid< float > STIRImageSingleConcrete
typedef VoxelsOnCartesianGrid< CartesianCoordinate3D< float > > STIRImageMulti
typedef itk::MetaDataObject< std::string > MetaDataStringType
typedef VectorWithOffset< VectorWithOffset< std::complex< float > > > exparray_t
Enumerations
enum OUTPUT_CHANNEL { INFORMATION_CHANNEL, WARNING_CHANNEL, ERROR_CHANNEL }
enum options {
_quit, _display_view, _display_sino, _absdiff,
_add_sino, _subtract_sino, _mult_sino, _div_sino,
_add_scalar, _mult_scalar, _div_scalar, _stats,
_pos_ind, _trunc_neg, _trim, _zero_ends,
_restart, _menu
}
Functions
template<class T >
T find_unweighted_centre_of_gravity_1d (const VectorWithOffset< T > &row)
Compute centre of gravity of a vector but without dividing by its sum.
template<class T >
T find_unweighted_centre_of_gravity (const Array< 1, T > &)
Compute centre of gravity of a 1D Array but without dividing by its sum.
template<int num_dimensions, class T >
BasicCoordinate< num_dimensions, T > find_unweighted_centre_of_gravity (const Array< num_dimensions, T > &)
Compute centre of gravity of an Array but without dividing by its sum.
template<int num_dimensions, class T >
BasicCoordinate< num_dimensions, T > find_centre_of_gravity (const Array< num_dimensions, T > &)
Compute centre of gravity of an Array.
template<class T >
void find_centre_of_gravity_in_mm_per_plane (VectorWithOffset< CartesianCoordinate3D< float > > &allCoG, VectorWithOffset< T > &weights, const VoxelsOnCartesianGrid< T > &image)
Computes centre of gravity for each plane.
template<class T >
CartesianCoordinate3D< float > find_centre_of_gravity_in_mm (const VoxelsOnCartesianGrid< T > &image)
Computes centre of gravity of an image.
template void find_centre_of_gravity_in_mm_per_plane (VectorWithOffset< CartesianCoordinate3D< float > > &allCoG, VectorWithOffset< float > &weights, const VoxelsOnCartesianGrid< float > &image)
template CartesianCoordinate3D< float > find_centre_of_gravity_in_mm (const VoxelsOnCartesianGrid< float > &image)
void error (const char *const s,...)
Print error with format string a la printf and throw exception.
template<class elemT >
std::list< ResolutionIndex< 3, float > > find_fwhm_in_image (DiscretisedDensity< 3, elemT > &input_image, const unsigned int num_maxima, const float level, const int dimension, const bool nema)
Finds FWHM, FWTM etc (in mm) for a number of point sources or a line source.
template<class elemT >
BasicCoordinate< 3, int > maximum_location_per_slice (const Array< 3, elemT > &input_array, const int slice, const int dimension)
finds the maximum of the Input_Array in the given slice at the given dimension (z=1, y=2, x=3), and returns its location as a vector in BasicCoordinate Field (only 3D implementation).
template<class elemT >
Array< 1, elemT > interpolate_line (const Array< 3, elemT > &input_array, const BasicCoordinate< 3, int > &max_location, const BasicCoordinate< 3, bool > &do_direction, const int dimension)
extract a line from the given array after determining its locatin with a parabolic fit
template<class RandomAccessIterType >
float parabolic_3points_fit (const RandomAccessIterType &begin_iter, const RandomAccessIterType &end_iter)
template<class RandomAccessIterType >
float parabolic_3points_fit_x0 (const RandomAccessIterType &begin_iter, const RandomAccessIterType &end_iter)
template std::list< ResolutionIndex< 3, float > > find_fwhm_in_image (DiscretisedDensity< 3, float > &input_image, const unsigned int num_maxima, const float level, const int dimension, const bool nema)
string standardise_interfile_keyword (const std::string &keyword)
Put a (Interfile) keyword into a standard form.
Succeeded inverse_SSRB (ProjData &proj_data_4D, const ProjData &proj_data_3D)
Perform Inverse Single Slice Rebinning and write output to ProjData4D format.
template<>
Succeeded get_param_from_string (string &param, const string &s)
template<>
Succeeded get_vparam_from_string (vector< string > &param, const string &s)
void make_det_pair_data (DetPairData &det_pair_data, const ProjDataInfo &proj_data_info, const int segment_num, const int ax_pos_num)
Makes a DetPairData of appropriate dimensions and fills it with 0.
void make_det_pair_data (DetPairData &det_pair_data, const ProjData &proj_data, const int segment_num, const int ax_pos_num)
void set_det_pair_data (ProjData &proj_data, const DetPairData &det_pair_data, const int segment_num, const int ax_pos_num)
void apply_block_norm (DetPairData &det_pair_data, const BlockData &block_data, const bool apply)
void apply_geo_norm (DetPairData &det_pair_data, const GeoData &geo_data, const bool apply)
void apply_efficiencies (DetPairData &det_pair_data, const Array< 1, float > &efficiencies, const bool apply)
void make_fan_sum_data (Array< 1, float > &data_fan_sums, const DetPairData &det_pair_data)
void make_geo_data (GeoData &geo_data, const DetPairData &det_pair_data)
void make_block_data (BlockData &block_data, const DetPairData &det_pair_data)
void iterate_efficiencies (Array< 1, float > &efficiencies, const Array< 1, float > &data_fan_sums, const DetPairData &model)
void iterate_geo_norm (GeoData &norm_geo_data, const GeoData &measured_geo_data, const DetPairData &model)
void iterate_block_norm (BlockData &norm_block_data, const BlockData &measured_block_data, const DetPairData &model)
float KL (const DetPairData &d1, const DetPairData &d2, const float threshold)
std::ostream & operator<< (std::ostream &s, const FanProjData &fan_data)
std::istream & operator>> (std::istream &s, FanProjData &fan_data)
shared_ptr< ProjDataInfoCylindricalNoArcCorr > get_fan_info (int &num_rings, int &num_detectors_per_ring, int &max_ring_diff, int &fan_size, const ProjDataInfo &proj_data_info)
void make_fan_data (FanProjData &fan_data, const ProjData &proj_data)
void set_fan_data (ProjData &proj_data, const FanProjData &fan_data)
void apply_block_norm (FanProjData &fan_data, const BlockData3D &block_data, const bool apply)
void apply_efficiencies (FanProjData &fan_data, const DetectorEfficiencies &efficiencies, const bool apply)
void make_fan_sum_data (Array< 2, float > &data_fan_sums, const FanProjData &fan_data)
void make_fan_sum_data (Array< 2, float > &data_fan_sums, const ProjData &proj_data)
void make_fan_sum_data (Array< 2, float > &data_fan_sums, const DetectorEfficiencies &efficiencies, const int max_ring_diff, const int half_fan_size)
void make_block_data (BlockData3D &block_data, const FanProjData &fan_data)
void iterate_efficiencies (DetectorEfficiencies &efficiencies, const Array< 2, float > &data_fan_sums, const FanProjData &model)
void iterate_efficiencies (DetectorEfficiencies &efficiencies, const Array< 2, float > &data_fan_sums, const int max_ring_diff, const int half_fan_size)
void iterate_block_norm (BlockData3D &norm_block_data, const BlockData3D &measured_block_data, const FanProjData &model)
float KL (const FanProjData &d1, const FanProjData &d2, const float threshold)
int get_max_num_threads ()
Get current maximum number of threads.
void set_num_threads (const int num_threads=0)
Set current number of threads.
int get_default_num_threads ()
Get default number of threads.
void set_default_num_threads ()
set current number of threads to the default
template<typename T >
void overlap_interpolate (VectorWithOffset< T > &out_data, const VectorWithOffset< T > &in_data, const float zoom, const float offset, const bool assign_rest_with_zeroes=true)
'overlap' interpolation (i.e. count preserving) for vectors.
template void overlap_interpolate (VectorWithOffset< float > &out_data, const VectorWithOffset< float > &in_data, const float zoom, const float offset, const bool assign_rest_with_zeroes)
template void overlap_interpolate (VectorWithOffset< double > &out_data, const VectorWithOffset< double > &in_data, const float zoom, const float offset, const bool assign_rest_with_zeroes)
template void overlap_interpolate (VectorWithOffset< Array< 1, float > > &out_data, const VectorWithOffset< Array< 1, float > > &in_data, const float zoom, const float offset, const bool assign_rest_with_zeroes)
template void overlap_interpolate (VectorWithOffset< Array< 2, float > > &out_data, const VectorWithOffset< Array< 2, float > > &in_data, const float zoom, const float offset, const bool assign_rest_with_zeroes)
void truncate_rim (Viewgram< float > &viewgram, const int rim_truncation_sino)
sets the first and last rim_truncation_sino bins at the 'edges' to zero
void truncate_rim (SegmentByView< float > &seg, const int rim_truncation_sino)
sets the first and last rim_truncation_sino bins at the 'edges' to zero
void truncate_rim (SegmentBySinogram< float > &seg, const int rim_truncation_sino)
void truncate_rim (DiscretisedDensity< 3, float > &image_input, const int rim_truncation_image, const bool strictly_less_than_radius=true)
sets to zero voxels within rim_truncation_image of the FOV rim
void divide_and_truncate (Viewgram< float > &numerator, const Viewgram< float > &denominator, const int rim_truncation_sino, int &count, int &count2, double *f=NULL)
divide viewgrams and set 'edge bins' to zero, put answer in numerator
void divide_and_truncate (RelatedViewgrams< float > &numerator, const RelatedViewgrams< float > &denominator, const int rim_truncation_sino, int &count, int &count2, double *f=NULL)
divide related viewgrams and set 'edge bins' to zero, put answer in numerator
void divide_array (SegmentByView< float > &numerator, const SegmentByView< float > &denominator)
simple division of two sinograms, x/0 = 0
void divide_array (DiscretisedDensity< 3, float > &numerator, const DiscretisedDensity< 3, float > &denominator)
simple division of two images, x/0 = 0
void accumulate_loglikelihood (Viewgram< float > &projection_data, const Viewgram< float > &estimated_projections, const int rim_truncation_sino, double *accum)
compute the log term of the loglikelihood function for given part of the projection space
void multiply_and_add (DiscretisedDensity< 3, float > &image_res, const DiscretisedDensity< 3, float > &image_scaled, float scalar)
float neg_trunc (float x)
truncates negative values to zero
void truncate_end_planes (DiscretisedDensity< 3, float > &input_image, int input_num_planes=1)
sets the end planes of the image to zero
Succeeded scale_sinograms (ProjData &output_proj_data, const ProjData &input_proj_data, const Array< 2, float > scale_factors_per_sinogram)
apply a scale factor for every sinogram
Array< 2, float > get_scale_factors_per_sinogram (const ProjData &numerator_proj_data, const ProjData &denominator_proj_data, const ProjData &weights_proj_data)
find scale factors between two different sinograms
template<typename elemT >
void build_gauss (VectorWithOffset< elemT > &kernel, int res, float s2, float sampling_interval)
template<typename elemT >
void build_metz (VectorWithOffset< elemT > &kernel, float N, float fwhm, float MmPerVox, int max_kernel_size)
ProjDataInfo * SSRB (const ProjDataInfo &in_proj_data_info, const int num_segments_to_combine, const int num_views_to_combine=1, const int num_tangential_poss_to_trim=0, const int max_in_segment_num_to_process=-1)
construct new ProjDataInfo that is appropriate for rebinned data
void SSRB (const std::string &output_filename, const ProjData &in_projdata, const int num_segments_to_combine, const int num_views_to_combine=1, const int num_tangential_poss_to_trim=0, const bool do_normalisation=true, const int max_in_segment_num_to_process=-1)
Perform Single Slice Rebinning and write output to file.
void SSRB (ProjData &out_projdata, const ProjData &in_projdata, const bool do_normalisation=true)
Perform Single Slice Rebinning and write output to ProjData.
void writeText (const char *text, OUTPUT_CHANNEL channel)
template<class FSTREAM >
void ask_filename_and_open (FSTREAM &s, const string &prompt, const string &default_extension, ios::openmode mode, bool abort_if_failed)
template void ask_filename_and_open (ifstream &s, const string &prompt, const string &default_extension, ios::openmode mode, bool abort_if_failed)
template void ask_filename_and_open (ofstream &s, const string &prompt, const string &default_extension, ios::openmode mode, bool abort_if_failed)
template void ask_filename_and_open (fstream &s, const string &prompt, const string &default_extension, ios::openmode mode, bool abort_if_failed)
void * read_stream_in_memory (istream &input, streamsize &file_size)
void warning (const char *const s,...)
Print warning with format string a la printf.
template<class elemT , class SCALE , class CHARP >
void display_bitmap (const Array< 3, elemT > &plane_stack, const VectorWithOffset< SCALE > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi, const char *const title, int scale)
template<class elemT , class SCALE , class CHARP >
void display_mathlink (const Array< 3, elemT > &plane_stack, const VectorWithOffset< SCALE > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi, const char *const title, int scale)
template<class elemT , class SCALE , class CHARP >
void display_pgm (const Array< 3, elemT > &plane_stack, const VectorWithOffset< SCALE > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi, const char *const title, int scale)
template<class elemT , class SCALE , class CHARP >
void display (const Array< 3, elemT > &plane_stack, const VectorWithOffset< SCALE > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi, const char *const title, int scale)
template<class elemT >
void display (const RelatedViewgrams< elemT > &v1, double maxi=0, const char *const title=0, int zoom=0)
Convenience function to display all viewgrams in a RelatedViewgrams object.
void display (const DetPairData &det_pair_data, const char *const title)
void display (const FanProjData &fan_data, const char *const title)
template void display (const Array< 3, short > &plane_stack, const VectorWithOffset< short > &scale_factors, const VectorWithOffset< char *> &text, double maxi, const char *const title, int scale)
template void display (const Array< 3, short > &plane_stack, const VectorWithOffset< float > &scale_factors, const VectorWithOffset< char *> &text, double maxi, const char *const title, int scale)
template void display (const Array< 3, float > &plane_stack, const VectorWithOffset< float > &scale_factors, const VectorWithOffset< char *> &text, double maxi, const char *const title, int scale)
template void display (const Array< 3, short > &plane_stack, const VectorWithOffset< short > &scale_factors, const VectorWithOffset< const char *> &text, double maxi, const char *const title, int scale)
template void display (const Array< 3, short > &plane_stack, const VectorWithOffset< float > &scale_factors, const VectorWithOffset< const char *> &text, double maxi, const char *const title, int scale)
template void display (const Array< 3, float > &plane_stack, const VectorWithOffset< float > &scale_factors, const VectorWithOffset< const char *> &text, double maxi, const char *const title, int scale)
template void display (const RelatedViewgrams< float > &vs, double maxi, const char *const title, int zoom)
void find_inverse_and_bck_densels (DiscretisedDensity< 3, float > &image, VectorWithOffset< SegmentByView< float > *> &all_segments, VectorWithOffset< SegmentByView< float > *> &attenuation_segmnets, const int min_z, const int max_z, const int min_y, const int max_y, const int min_x, const int max_x, ProjMatrixByDensel &proj_matrix, bool do_attenuation, const float threshold, bool normalize_result)
void do_segments_densels_fwd (const VoxelsOnCartesianGrid< float > &image, ProjData &proj_data, VectorWithOffset< SegmentByView< float > *> &all_segments, const int min_z, const int max_z, const int min_y, const int max_y, const int min_x, const int max_x, ProjMatrixByDensel &proj_matrix)
void fwd_densels_all (VectorWithOffset< SegmentByView< float > *> &all_segments, shared_ptr< ProjMatrixByDensel > proj_matrix_ptr, shared_ptr< ProjData > proj_data_ptr, const int min_z, const int max_z, const int min_y, const int max_y, const int min_x, const int max_x, const DiscretisedDensity< 3, float > &in_density)
void divide_complex_arrays (Array< 1, float > &out_array, const Array< 1, float > &array_nom, const Array< 1, float > &array_denom)
void mulitply_complex_arrays (Array< 1, float > &out_array, const Array< 1, float > &array_nom, const Array< 1, float > &array_denom)
void mulitply_complex_arrays (Array< 1, float > &array_nom, const Array< 1, float > &array_denom)
void divide_complex_arrays (Array< 1, float > &array_nom, const Array< 1, float > &array_denom)
void create_kernel_3d (Array< 3, float > &kernel_3d, const VectorWithOffset< float > &kernel_1d)
void create_kernel_2d (Array< 2, float > &kernel_2d, const VectorWithOffset< float > &kernel_1d)
void padd_filter_coefficients_3D_and_make_them_symmetric (VectorWithOffset< VectorWithOffset< VectorWithOffset< float > > > &padded_filter_coefficients_3D, VectorWithOffset< VectorWithOffset< VectorWithOffset< float > > > &filter_coefficients)
void convert_array_3D_into_1D_array (Array< 1, float > &out_array, const Array< 3, float > &in_array)
void convert_array_1D_into_3D_array (Array< 3, float > &out_array, const Array< 1, float > &in_array)
void convert_array_2D_into_1D_array (Array< 1, float > &out_array, Array< 2, float > &in_array)
void convert_array_1D_into_2D_array (Array< 2, float > &out_array, Array< 1, float > &in_array)
void precompute_filter_coefficients_for_second_apporach (VoxelsOnCartesianGrid< float > &precomputed_coefficients, const VoxelsOnCartesianGrid< float > &input_image, VoxelsOnCartesianGrid< float > &sensitivity_image, VoxelsOnCartesianGrid< float > &normalised_bck)
void construct_scaled_filter_coefficients_3D (VectorWithOffset< VectorWithOffset< VectorWithOffset< float > > > &new_filter_coefficients_3D_array, VectorWithOffset< float > kernel_1d, const float kapa0_over_kapa1)
void construct_scaled_filter_coefficients_2D (Array< 2, float > &new_filter_coefficients_2D_array, VectorWithOffset< float > kernel_1d, const float kapa0_over_kapa1)
void construct_scaled_filter_coefficients_3D (Array< 3, float > &new_filter_coefficients_3D_array, VectorWithOffset< float > kernel_1d, const float kapa0_over_kapa1)
void construct_scaled_filter_coefficients_2D (Array< 2, float > &new_filter_coefficients_2D_array, Array< 2, float > &kernel_2d, const float kapa0_over_kapa1, int number_of_coefficients_before_padding)
void construct_scaled_filter_coefficients_3D (Array< 3, float > &new_filter_coefficients_2D_array, Array< 3, float > &kernel_3d, const float kapa0_over_kapa1)
RigidObject3DTransformation compose (const RigidObject3DTransformation &apply_last, const RigidObject3DTransformation &apply_first)
Composition of 2 transformations.
std::ostream & operator<< (std::ostream &out, const RigidObject3DTransformation &rigid_object_transformation)
Output to (text) stream.
std::istream & operator>> (std::istream &, RigidObject3DTransformation &rigid_object_transformation)
Input from (text) stream.
Succeeded transform_3d_object (DiscretisedDensity< 3, float > &out_density, const DiscretisedDensity< 3, float > &in_density, const RigidObject3DTransformation &transformation_in_to_out)
transform image data
Succeeded transpose_of_transform_3d_object (DiscretisedDensity< 3, float > &out_density, const DiscretisedDensity< 3, float > &in_density, const RigidObject3DTransformation &transformation_in_to_out)
transform image data using transposed matrix
Array< 3, BasicCoordinate< 3, float > > find_grid_coords_of_transformed_centres (const DiscretisedDensity< 3, float > &source_density, const DiscretisedDensity< 3, float > &target_density, const ObjectTransformation< 3, float > &transformation_source_to_target)
Array< 3, std::pair< BasicCoordinate< 3, float >, float > > find_grid_coords_of_transformed_centres_and_jacobian (const DiscretisedDensity< 3, float > &source_density, const DiscretisedDensity< 3, float > &target_density, const ObjectTransformation< 3, float > &transformation_source_to_target)
Succeeded transform_3d_object (ProjData &out_proj_data, const ProjData &in_proj_data, const RigidObject3DTransformation &object_transformation)
transform projection data
Succeeded transform_3d_object (ProjData &out_proj_data, const ProjData &in_proj_data, const RigidObject3DTransformation &rigid_object_transformation, const int min_in_segment_num_to_process, const int max_in_segment_num_to_process)
transform projection data
int sign (const float x)
float trapezoid_integral (const float s, const float m2, const float m3)
template<typename T >
T cube (const T x)
float convolution_2_trapezoids (const float x, const float m21, const float m31, const float m22, const float m32)
float VOI (const float s_voxel, const float half_bin_size, const float halfcosminsin, const float halfcosplussin)
float SA_rotated_voxel (const float s_voxel, const float half_voxel_size, const float m2, const float m3)
float SAapprox (const float s_voxel, const float half_voxel_size, const float m2, const float m3, const float halfcosminsin, const float halfcosplussin)
float SA (const float s_voxel, const float half_voxel_size, const float m2, const float m3, const float halfcosminsin, const float halfcosplussin)
template<typename T >
bool coordinates_less (const BasicCoordinate< 3, T > &el1, const BasicCoordinate< 3, T > &el2)
template<typename elemT >
void discrete_fourier_transform (VectorWithOffset< elemT > &data, int isign)
float rand1 ()
void do_block (vector< Bin > &list_of_bins_in_block, const int axial_block_num, const int tangential_block_num, const ProjDataInfoCylindricalNoArcCorr &proj_data_info, const int axial_num_crystals_in_block, const int tangential_num_crystals_in_block)
bool bin_coordinates_by_view_less (const Bin &b1, const Bin &b2)
void sort_and_make_unique (vector< Bin > &list_of_bins)
void find_inverse (ProjData *proj_data_ptr_out, const ProjData *proj_data_ptr_in)
void do_segments (DiscretisedDensity< 3, float > &image, ProjData &proj_data_org, const int start_segment_num, const int end_segment_num, const int start_view, const int end_view, BackProjectorByBin &back_projector, bool fill_with_1)
void find_inverse (ProjData &proj_data_out, const ProjData &proj_data_in, const int min_segment_num, const int max_segment_num)
template<class elemT >
Array< 1, elemT > & in_place_log (Array< 1, elemT > &v)
Replace elements by their logarithm, 1D version.
template<int num_dimensions, class elemT >
Array< num_dimensions, elemT > & in_place_log (Array< num_dimensions, elemT > &v)
apply log to each element of the multi-dimensional array
template<class elemT >
Array< 1, elemT > & in_place_exp (Array< 1, elemT > &v)
Replace elements by their exponentiation, 1D version.
template<int num_dimensions, class elemT >
Array< num_dimensions, elemT > & in_place_exp (Array< num_dimensions, elemT > &v)
apply exp to each element of the multi-dimensional array
template<class elemT >
Array< 1, elemT > & in_place_abs (Array< 1, elemT > &v)
Replace elements by their absolute value, 1D version.
template<int num_dimensions, class elemT >
Array< num_dimensions, elemT > & in_place_abs (Array< num_dimensions, elemT > &v)
store absolute value of each element of the multi-dimensional array
template<class T , class FUNCTION >
T & in_place_apply_function (T &v, FUNCTION f)
apply any function(object) to each element of the multi-dimensional array
template<int num_dim, typename elemT , typename FunctionObjectPtr >
void in_place_apply_array_function_on_1st_index (Array< num_dim, elemT > &array, FunctionObjectPtr f)
Apply a function object on all possible 1d arrays extracted by keeping all indices fixed, except the first one.
template<int num_dim, typename elemT , typename FunctionObjectPtr >
void apply_array_function_on_1st_index (Array< num_dim, elemT > &out_array, const Array< num_dim, elemT > &in_array, FunctionObjectPtr f)
apply any function(object) to each element of the multi-dimensional array, storing results in a different array
template<int num_dim, typename elemT , typename FunctionObjectPtrIter >
void in_place_apply_array_functions_on_each_index (Array< num_dim, elemT > &array, FunctionObjectPtrIter start, FunctionObjectPtrIter stop)
Apply a sequence of 1d array-function objects on every dimension of the input array.
template<typename elemT , typename FunctionObjectPtrIter >
void in_place_apply_array_functions_on_each_index (Array< 1, elemT > &array, FunctionObjectPtrIter start, FunctionObjectPtrIter stop)
1d specialisation of the above.
template<int num_dim, typename elemT , typename FunctionObjectPtrIter >
void apply_array_functions_on_each_index (Array< num_dim, elemT > &out_array, const Array< num_dim, elemT > &in_array, FunctionObjectPtrIter start, FunctionObjectPtrIter stop)
Apply a sequence of 1d array-function objects on every dimension of the input array, store in output array.
template<int num_dim, typename elemT >
void apply_array_functions_on_each_index (Array< num_dim, elemT > &out_array, const Array< num_dim, elemT > &in_array, ActualFunctionObjectPtrIter start, ActualFunctionObjectPtrIter stop)
Apply a sequence of 1d array-function objects of a specific type on every dimension of the input array, store in output array.
template<typename elemT >
void apply_array_functions_on_each_index (Array< 1, elemT > &out_array, const Array< 1, elemT > &in_array, ActualFunctionObjectPtrIter start, ActualFunctionObjectPtrIter stop)
1d specialisation of above
template<typename elemT , typename FunctionObjectPtrIter >
void apply_array_functions_on_each_index (Array< 1, elemT > &out_array, const Array< 1, elemT > &in_array, FunctionObjectPtrIter start, FunctionObjectPtrIter stop)
1d specialisation for general function objects
template<int num_dim, typename elemT >
void transform_array_to_periodic_indices (Array< num_dim, elemT > &out_array, const Array< num_dim, elemT > &in_array)
template<int num_dim, typename elemT >
void transform_array_from_periodic_indices (Array< num_dim, elemT > &out_array, const Array< num_dim, elemT > &in_array)
template<class elemT >
void assign_to_subregion (Array< 3, elemT > &input_array, const BasicCoordinate< 3, int > &mask_location, const BasicCoordinate< 3, int > &half_size, const elemT &value)
assign a value to a sub-region of an array
template<int num_dimensions, typename coordT >
coordT inner_product (const BasicCoordinate< num_dimensions, coordT > &p1, const BasicCoordinate< num_dimensions, coordT > &p2)
compute sum_i p1[i] * p2[i]
template<int num_dimensions, typename coordT >
double norm_squared (const BasicCoordinate< num_dimensions, coordT > &p1)
compute (inner_product(p1,p1))
template<int num_dimensions, typename coordT >
double norm (const BasicCoordinate< num_dimensions, coordT > &p1)
compute sqrt(inner_product(p1,p1))
template<int num_dimensions, typename coordT >
double angle (const BasicCoordinate< num_dimensions, coordT > &p1, const BasicCoordinate< num_dimensions, coordT > &p2)
compute angle between 2 directions
template<int num_dimensions, typename coordT >
double cos_angle (const BasicCoordinate< num_dimensions, coordT > &p1, const BasicCoordinate< num_dimensions, coordT > &p2)
compute cos of the angle between 2 directions
template<int num_dimensions, typename coordT >
BasicCoordinate< num_dimensions+1, coordT > join (const coordT &a, const BasicCoordinate< num_dimensions, coordT > &c)
make a longer BasicCoordinate, by prepending c with the single coordT
template<int num_dimensions, class coordT >
BasicCoordinate< num_dimensions+1, coordT > join (const BasicCoordinate< num_dimensions, coordT > &c, const coordT &a)
make a longer BasicCoordinate, by appending the coordT to c
template<int num_dimensions, class coordT >
BasicCoordinate< num_dimensions-1, coordT > cut_last_dimension (const BasicCoordinate< num_dimensions, coordT > &c)
make a shorter BasicCoordinate, by cutting the last element from c
template<int num_dimensions, typename coordT >
BasicCoordinate< num_dimensions-1, coordT > cut_first_dimension (const BasicCoordinate< num_dimensions, coordT > &c)
make a shorter BasicCoordinate, by cutting the first element from c
template<int num_dimensions>
BasicCoordinate< num_dimensions, float > convert_int_to_float (const BasicCoordinate< num_dimensions, int > &cint)
converts a BasicCoordinate<int> to BasicCoordinate<float>
template<class NUMBER >
NUMBER square (const NUMBER &x)
returns the square of a number, templated.
template<int num_dimensions, class T1 , class T2 , class scaleT >
void find_scale_factor (scaleT &scale_factor, const Array< num_dimensions, T1 > &data_in, const NumericInfo< T2 > info_for_out_type)
A function that finds a scale factor to use when converting data to a new type.
template<int num_dimensions, class T1 , class T2 , class scaleT >
Array< num_dimensions, T2 > convert_array (scaleT &scale_factor, const Array< num_dimensions, T1 > &data_in, const NumericInfo< T2 > info2)
A function that returns a new Array (of the same dimension) with elements of type T2.
template<int num_dimensions, class T1 , class T2 , class scaleT >
void convert_array (Array< num_dimensions, T2 > &data_out, scaleT &scale_factor, const Array< num_dimensions, T1 > &data_in)
Converts the data_in Array to data_out (with elements of different types) such that data_in == data_out * scale_factor.
template<class InputIteratorT , class T2 , class scaleT >
void find_scale_factor (scaleT &scale_factor, const InputIteratorT &begin, const InputIteratorT &end, const NumericInfo< T2 > info_for_out_type)
A function that finds a scale factor to use when converting data to a new type.
template<class OutputIteratorT , class InputIteratorT , class scaleT >
void convert_range (const OutputIteratorT &out_begin, scaleT &scale_factor, const InputIteratorT &in_begin, const InputIteratorT &in_end)
Converts the data in the input range to the output range (with elements of different types) such that data_in == data_out * scale_factor.
template<class coordT >
CartesianCoordinate3D< coordT > cross_product (const CartesianCoordinate3D< coordT > &a, const CartesianCoordinate3D< coordT > &b)
the cross-product for 3-dimensional coordinates.
double decay_correction_factor (const double isotope_halflife, const double start_time, const double end_time)
Compute decay-correction factor for a time frame.
double decay_correction_factor (const double isotope_halflife, const double rel_time)
Computes the decay-correction factor for activity at a given time point.
template<class elemT , class scaleT , class CHARP >
void display (const Array< 3, elemT > &plane_stack, const VectorWithOffset< scaleT > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi, const char *const title, int zoom)
template<class elemT , class scaleT , class CHARP >
void display (const Array< 3, elemT > &plane_stack, const VectorWithOffset< scaleT > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi, const char *const title)
template<class elemT , class scaleT , class CHARP >
void display (const Array< 3, elemT > &plane_stack, const VectorWithOffset< scaleT > &scale_factors, const VectorWithOffset< CHARP > &text, double maxi)
template<class elemT , class scaleT , class CHARP >
void display (const Array< 3, elemT > &plane_stack, const VectorWithOffset< scaleT > &scale_factors, const VectorWithOffset< CHARP > &text)
template<class elemT >
void display (const Array< 3, elemT > &plane_stack, double maxi, const char *const title, int zoom)
template<class elemT >
void display (const Array< 3, elemT > &plane_stack, double maxi, const char *const title)
template<class elemT >
void display (const Array< 3, elemT > &plane_stack, double maxi)
template<class elemT >
void display (const Array< 3, elemT > &plane_stack)
template<class elemT >
void display (const Array< 2, elemT > &plane, const char *const text, double maxi, int zoom)
template<class elemT >
void display (const Array< 2, elemT > &plane, const char *const text, double maxi)
template<class elemT >
void display (const Array< 2, elemT > &plane, const char *const text)
template<class elemT >
void display (const Array< 2, elemT > &plane)
template<class STRING >
void error (const STRING &string)
Use this function for writing error messages and throwing an exception.
template<class elemT >
Array< 1, elemT > extract_line (const Array< 3, elemT > &, const BasicCoordinate< 3, int > &index, const int dimension)
extracts a line from an array in the direction of the specified dimension.
template<class RandomAccessIterType >
float find_level_width (const RandomAccessIterType &begin_iterator, const RandomAccessIterType &max_iterator, const RandomAccessIterType &end_iterator, const float level_height)
find width at a level
template<class RandomAccessIterType >
float find_level_width (const RandomAccessIterType &begin_iterator, const RandomAccessIterType &end_iterator, const float level_height)
find width at a level
template<class coordT >
coordT coordinate_between_2_lines (CartesianCoordinate3D< coordT > &result, const LORAs2Points< coordT > &line0, const LORAs2Points< coordT > &line1)
find a point half-way between 2 lines and their distance
template<class coordT >
coordT distance_between_line_and_point (const LORAs2Points< coordT > &line, const CartesianCoordinate3D< coordT > &r1)
find the distance between a point and a line
template<class elemT >
int index_at_maximum (const VectorWithOffset< elemT > &v)
Finds the index where the maximum occurs in a (1-dimensional) vector.
template<class elemT >
BasicCoordinate< 3, int > indices_at_maximum (const Array< 3, elemT > &input_array)
Finds the first (3-dimensional) index where the maximum occurs in a (3-dimensional) array.
template<class STRING >
void info (const STRING &string, const int verbosity_level=1)
Use this function for writing informational messages.
bool is_interfile_signature (const char *const signature)
Checks if the signature corresponds to the start of an interfile header.
VoxelsOnCartesianGrid< float > * read_interfile_image (std::istream &input, const std::string &directory_for_data="")
This reads the first 3d image in an Interfile header file, given as a stream.
VoxelsOnCartesianGrid< float > * read_interfile_image (const std::string &filename)
This reads the first 3d image in an Interfile header file, given as a filename.
DynamicDiscretisedDensity * read_interfile_dynamic_image (std::istream &input, const std::string &directory_for_data)
Read dynamic image.
DynamicDiscretisedDensity * read_interfile_dynamic_image (const std::string &filename)
Read dynamic image.
ParametricDiscretisedDensity< VoxelsOnCartesianGrid< KineticParameters< 2, float > > > * read_interfile_parametric_image (std::istream &input, const std::string &directory_for_data)
Read parametric image.
ParametricDiscretisedDensity< VoxelsOnCartesianGrid< KineticParameters< 2, float > > > * read_interfile_parametric_image (const std::string &filename)
Read parametric image.
Succeeded write_basic_interfile_image_header (const std::string &header_file_name, const std::string &image_file_name, const ExamInfo &exam_info, const IndexRange< 3 > &index_range, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type, const ByteOrder byte_order, const VectorWithOffset< float > &scaling_factors, const VectorWithOffset< unsigned long > &file_offsets, const std::vector< std::string > &data_type_descriptions=std::vector< std::string >())
This outputs an Interfile header for an image.
const VectorWithOffset< unsigned long > compute_file_offsets (int number_of_time_frames, const NumericType output_type, const Coordinate3D< int > &dim, unsigned long initial_offset=0)
a utility function that computes the file offsets of subsequent images
template<class elemT >
Succeeded write_basic_interfile (const std::string &filename, const Array< 3, elemT > &image, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
This outputs an Interfile header and data for a Array<3,elemT> object.
template<class elemT >
Succeeded write_basic_interfile (const std::string &filename, const ExamInfo &exam_info, const Array< 3, elemT > &image, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
This outputs an Interfile header and data for a Array<3,elemT> object.
template<class elemT >
Succeeded write_basic_interfile (const std::string &filename, const Array< 3, elemT > &image, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
This outputs an Interfile header and data for a Array<3,elemT> object, assuming unit voxel sizes.
Succeeded write_basic_interfile (const std::string &filename, const VoxelsOnCartesianGrid< float > &image, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
This outputs an Interfile header and data for a VoxelsOnCartesianGrid<float> object.
Succeeded write_basic_interfile (const std::string &filename, const DiscretisedDensity< 3, float > &image, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
This outputs an Interfile header and data for a DiscretisedDensity<3,float> object.
Succeeded write_basic_interfile (const std::string &filename, const ParametricDiscretisedDensity< VoxelsOnCartesianGrid< KineticParameters< 2, float > > > &image, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
Succeeded write_basic_interfile (const std::string &filename, const DynamicDiscretisedDensity &image, const NumericType output_type=NumericType::FLOAT, const float scale=0, const ByteOrder byte_order=ByteOrder::native)
ProjDataFromStream * read_interfile_PDFS (std::istream &input, const std::string &directory_for_data="", const std::ios::openmode openmode=std::ios::in)
This reads the first 3D sinogram from an Interfile header, given as a stream.
ProjDataFromStream * read_interfile_PDFS (const std::string &filename, const std::ios::openmode open_mode)
This reads the first 3D sinogram from an Interfile header, given as a filename.
Succeeded write_basic_interfile_PDFS_header (const std::string &header_filename, const std::string &data_filename, const ProjDataFromStream &pdfs)
This writes an Interfile header appropriate for the ProjDataFromStream object.
Succeeded write_basic_interfile_PDFS_header (const std::string &data_filename, const ProjDataFromStream &pdfs)
This function writes an Interfile header for the pdfs object.
template<int num_dimensions, class IStreamT , class elemT >
Succeeded read_data (IStreamT &s, Array< num_dimensions, elemT > &data, const ByteOrder byte_order=ByteOrder::native)
Read the data of an Array from file.
template<int num_dimensions, class IStreamT , class elemT , class InputType , class ScaleT >
Succeeded read_data (IStreamT &s, Array< num_dimensions, elemT > &data, NumericInfo< InputType > input_type, ScaleT &scale_factor, const ByteOrder byte_order=ByteOrder::native)
Read the data of an Array from file as a different type.
template<int num_dimensions, class IStreamT , class elemT , class ScaleT >
Succeeded read_data (IStreamT &s, Array< num_dimensions, elemT > &data, NumericType type, ScaleT &scale, const ByteOrder byte_order=ByteOrder::native)
Read the data of an Array from file as a different type.
template<class DataT , class FileT >
unique_ptr< DataT > read_from_file (const FileSignature &signature, FileT file)
Function that reads data from file using the default InputFileFormatRegistry, using the provided FileSignature to find the matching file format.
template<class DataT , class FileT >
unique_ptr< DataT > read_from_file (FileT file)
Function that reads data from file using the default InputFileFormatRegistry.
template<int num_dimensions, class OStreamT , class elemT >
Succeeded write_data (OStreamT &s, const Array< num_dimensions, elemT > &data, const ByteOrder byte_order=ByteOrder::native, const bool can_corrupt_data=false)
Write the data of an Array to file.
template<int num_dimensions, class OStreamT , class elemT , class OutputType , class ScaleT >
Succeeded write_data (OStreamT &s, const Array< num_dimensions, elemT > &data, NumericInfo< OutputType > output_type, ScaleT &scale_factor, const ByteOrder byte_order=ByteOrder::native, const bool can_corrupt_data=false)
Write the data of an Array to file as a different type.
template<int num_dimensions, class OStreamT , class elemT , class OutputType , class ScaleT >
Succeeded write_data_with_fixed_scale_factor (OStreamT &s, const Array< num_dimensions, elemT > &data, NumericInfo< OutputType > output_type, const ScaleT scale_factor, const ByteOrder byte_order=ByteOrder::native, const bool can_corrupt_data=false)
Write the data of an Array to file as a different type but using a given scale factor.
template<int num_dimensions, class OStreamT , class elemT , class ScaleT >
Succeeded write_data (OStreamT &s, const Array< num_dimensions, elemT > &data, NumericType type, ScaleT &scale, const ByteOrder byte_order=ByteOrder::native, const bool can_corrupt_data=false)
Write the data of an Array to file as a different type.
template<class DataT >
std::string write_to_file (const std::string &filename, const DataT &data)
Function that writes data to file using the default OutputFileFormat.
template<class Value , class DataType , class CoordinatesType >
void linear_regression (Value &constant, Value &scale, Value &chi_square, Value &variance_of_constant, Value &variance_of_scale, Value &covariance_of_constant_with_scale, const VectorWithOffset< DataType > &measured_data, const VectorWithOffset< CoordinatesType > &coordinates, const VectorWithOffset< float > &weights, const bool use_estimated_variance=true)
Implements standard linear regression on VectorWithOffset data.
template<class Value , class DataIter , class CoordinatesIter , class WeightsIter >
void linear_regression (Value &constant, Value &scale, Value &chi_square, Value &variance_of_constant, Value &variance_of_scale, Value &covariance_of_constant_with_scale, DataIter measured_data_begin, DataIter measured_data_end, CoordinatesIter coords_begin, WeightsIter weights_begin, const bool use_estimated_variance=true)
Implements standard linear regression.
template<class ValueIter , class DataIter , class CoordinatesIter , class WeightsIter >
void linear_regression (ValueIter regression_values_begin, DataIter data_begin, DataIter data_end, CoordinatesIter coords_begin, WeightsIter weights_begin, const bool use_estimated_variance=true)
template<class coordT1 , class coordT2 >
Succeeded find_LOR_intersections_with_cylinder (LORInCylinderCoordinates< coordT1 > &, const LORAs2Points< coordT2 > &, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class coordT1 , class coordT2 >
Succeeded find_LOR_intersections_with_cylinder (LORAs2Points< coordT1 > &intersection_coords, const LORAs2Points< coordT2 > &coords, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class coordT1 , class coordT2 >
Succeeded find_LOR_intersections_with_cylinder (LORInAxialAndNoArcCorrSinogramCoordinates< coordT1 > &lor, const LORAs2Points< coordT2 > &cart_coords, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class coordT1 , class coordT2 >
Succeeded find_LOR_intersections_with_cylinder (LORInAxialAndSinogramCoordinates< coordT1 > &lor, const LORAs2Points< coordT2 > &cart_coords, const double radius)
Given an LOR, find its intersection with a (infintely long) cylinder.
template<class T >
VectorWithOffset< T > make_vector (const T &a0)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6, const T &a7)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6, const T &a7, const T &a8)
template<class T >
VectorWithOffset< T > make_vector (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6, const T &a7, const T &a8, const T &a9)
template<class T >
Array< 1, T > make_1d_array (const T &a0)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6, const T &a7)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6, const T &a7, const T &a8)
template<class T >
Array< 1, T > make_1d_array (const T &a0, const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6, const T &a7, const T &a8, const T &a9)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2, const Array< num_dimensions, T > &a3)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2, const Array< num_dimensions, T > &a3, const Array< num_dimensions, T > &a4)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2, const Array< num_dimensions, T > &a3, const Array< num_dimensions, T > &a4, Array< num_dimensions, T > &a5)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2, const Array< num_dimensions, T > &a3, const Array< num_dimensions, T > &a4, Array< num_dimensions, T > &a5, const Array< num_dimensions, T > &a6)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2, const Array< num_dimensions, T > &a3, const Array< num_dimensions, T > &a4, Array< num_dimensions, T > &a5, const Array< num_dimensions, T > &a6, const Array< num_dimensions, T > &a7)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions, T > &a0, const Array< num_dimensions, T > &a1, const Array< num_dimensions, T > &a2, const Array< num_dimensions, T > &a3, const Array< num_dimensions, T > &a4, Array< num_dimensions, T > &a5, const Array< num_dimensions, T > &a6, const Array< num_dimensions, T > &a7, const Array< num_dimensions, T > &a8)
template<int num_dimensions, class T >
Array< num_dimensions+1, T > make_array (const Array< num_dimensions-1, T > &a0, const Array< num_dimensions-1, T > &a1, const Array< num_dimensions-1, T > &a2, const Array< num_dimensions-1, T > &a3, const Array< num_dimensions-1, T > &a4, Array< num_dimensions-1, T > &a5, const Array< num_dimensions-1, T > &a6, const Array< num_dimensions-1, T > &a7, const Array< num_dimensions-1, T > &a8, const Array< num_dimensions-1, T > &a9)
template<typename ForwardIter_t >
ForwardIter_t min_positive_element (ForwardIter_t start, ForwardIter_t end)
Finds where the smallest strictly positive element occurs.
float KL (const float a, const float b, const float threshold_a=0)
template<int num_dimensions, typename elemT >
float KL (const Array< num_dimensions, elemT > &a, const Array< num_dimensions, elemT > &b, const float threshold_a=0)
template<int num_dimensions, class T , class T2 >
void assign (KineticParameters< num_dimensions, T > &v, const T2 &y)
template<class iterT >
iterT abs_max_element (iterT start, iterT end)
Like std::max_element, but comparing after taking absolute value.
template<class IterT , class elemT >
elemT sum (IterT start, IterT end, elemT init)
Compute the sum of a sequence using operator+=(), using an initial value.
template<class IterT >
std::iterator_traits< IterT >::value_type sum (IterT start, IterT end)
Compute the sum of a sequence using operator+=().
template<class IterT >
std::iterator_traits< IterT >::value_type average (IterT start, IterT end)
Compute the average of a sequence using sum(start,end).
template<class elemT >
elemT determinant (const Array< 2, elemT > &m)
Compute the determinant of a matrix.
template<class NumeratorIterT , class DenominatorIterT , class small_numT >
void divide (const NumeratorIterT &numerator_begin, const NumeratorIterT &numerator_end, const DenominatorIterT &denominator_begin, const small_numT small_num)
division of two ranges, 0/0 = 0
template<typename T >
void fourier (T &c, const int sign=1)
Compute multi-dimensional discrete fourier transform.
template<typename T >
void inverse_fourier (T &c, const int sign=1)
Compute the inverse of the multi-dimensional discrete fourier transform.
template<typename T >
void fourier_1d (T &c, const int sign)
Compute one-dimensional discrete fourier transform of an array.
template<typename T >
void inverse_fourier_1d (T &c, const int sign=1)
Compute the inverse of the one-dimensional discrete fourier transform.
template<typename T >
Array< 1, std::complex< T > > fourier_1d_for_real_data (const Array< 1, T > &c, const int sign=1)
Compute one-dimensional discrete fourier transform of a real array (of even size).
template<typename T >
Array< 1, T > inverse_fourier_1d_for_real_data (const Array< 1, std::complex< T > > &c, const int sign=1)
Compute the inverse of the one-dimensional discrete fourier transform of a real array (of even size).
template<typename T >
Array< 1, T > inverse_fourier_1d_for_real_data_corrupting_input (Array< 1, std::complex< T > > &c, const int sign)
As inverse_fourier_1d_for_real_data(), but avoiding the copy of the input array.
template<int num_dimensions, typename T >
Array< num_dimensions, std::complex< T > > fourier_for_real_data (const Array< num_dimensions, T > &c, const int sign=1)
Compute discrete fourier transform of a real array (with the last dimensions of even size).
template<int num_dimensions, typename T >
Array< num_dimensions, T > inverse_fourier_for_real_data (const Array< num_dimensions, std::complex< T > > &c, const int sign=1)
Compute the inverse of the discrete fourier transform of a real array (with the last dimension of even size).
template<int num_dimensions, typename T >
Array< num_dimensions, T > inverse_fourier_for_real_data_corrupting_input (Array< num_dimensions, std::complex< T > > &c, const int sign=1)
As inverse_fourier_for_real_data(), but avoiding the copy of the input array.
template<int num_dimensions, typename T >
Array< num_dimensions, std::complex< T > > pos_frequencies_to_all (const Array< num_dimensions, std::complex< T > > &c)
Adds negative frequencies to the last dimension of a complex array by complex conjugation.
template<typename elemT >
elemT integrate_discrete_function (const std::vector< elemT > &coordinates, const std::vector< elemT > &values, const int interpolation_order=1)
numerical integration of a 1D functionThis is a simple integral implementation using rectangular (=0) or trapezoidal (=1) approximation. It currently integrates over the complete range specified.
template<class RandIter1 , class RandIter2 , class RandIter3 , class RandIter4 >
void IIR_filter (RandIter1 output_begin_iterator, RandIter1 output_end_iterator, const RandIter2 input_begin_iterator, const RandIter2 input_end_iterator, const RandIter3 input_factor_begin_iterator, const RandIter3 input_factor_end_iterator, const RandIter4 pole_begin_iterator, const RandIter4 pole_end_iterator, const bool if_initial_exists)
template<class RandIter1 , class RandIter2 , class RandIter3 >
void FIR_filter (RandIter1 output_begin_iterator, RandIter1 output_end_iterator, const RandIter2 input_begin_iterator, const RandIter2 input_end_iterator, const RandIter3 input_factor_begin_iterator, const RandIter3 input_factor_end_iterator, const bool if_initial_exists)
template<class elemT >
Succeeded absolute_max_eigenvector_using_power_method (elemT &max_eigenvalue, Array< 1, elemT > &max_eigenvector, const Array< 2, elemT > &m, const Array< 1, elemT > &start, const double tolerance=.01, const unsigned long max_num_iterations=10000UL)
Compute the eigenvalue with the largest absolute value and corresponding eigenvector of a matrix by using the power method.
template<class elemT >
Succeeded absolute_max_eigenvector_using_shifted_power_method (elemT &max_eigenvalue, Array< 1, elemT > &max_eigenvector, const Array< 2, elemT > &m, const Array< 1, elemT > &start, const elemT shift, const double tolerance=.03, const unsigned long max_num_iterations=10000UL)
Compute the eigenvalue with the largest absolute value and corresponding eigenvector of a matrix by using the shifted power method.
template<class elemT >
Succeeded max_eigenvector_using_power_method (elemT &max_eigenvalue, Array< 1, elemT > &max_eigenvector, const Array< 2, elemT > &m, const Array< 1, elemT > &start, const double tolerance=.03, const unsigned long max_num_iterations=10000UL)
Compute the eigenvalue with the largest value and corresponding eigenvector of a matrix by using the power method.
template<typename out_iter_t , typename out_coord_iter_t , typename in_iter_t , typename in_coord_iter_t >
void overlap_interpolate (const out_iter_t out_begin, const out_iter_t out_end, const out_coord_iter_t out_coord_begin, const out_coord_iter_t out_coord_end, const in_iter_t in_begin, in_iter_t in_end, const in_coord_iter_t in_coord_begin, const in_coord_iter_t in_coord_end, const bool only_add_to_output=false, const bool assign_rest_with_zeroes=true)
'overlap' interpolation for iterators, with arbitrary 'bin' sizes.
template<class FunctionType , class elemT , class positionT >
void sample_function_on_regular_grid (Array< 3, elemT > &out, FunctionType func, const BasicCoordinate< 3, positionT > &offset, const BasicCoordinate< 3, positionT > &step)
Generic function to get the values of a 3D function on a regular grid.
void setup_distributable_computation (const shared_ptr< ProjectorByBinPair > &proj_pair_sptr, const shared_ptr< ExamInfo > &exam_info_sptr, const ProjDataInfo *const proj_data_info_ptr, const shared_ptr< DiscretisedDensity< 3, float > > &target_sptr, const bool zero_seg0_end_planes, const bool distributed_cache_enabled)
set-up parameters before calling distributable_computation()
void end_distributable_computation ()
clean-up after a sequence of computations
void distributable_computation (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &symmetries_sptr, DiscretisedDensity< 3, float > *output_image_ptr, const DiscretisedDensity< 3, float > *input_image_ptr, const shared_ptr< ProjData > &proj_data_ptr, const bool read_from_proj_data, int subset_num, int num_subsets, int min_segment_num, int max_segment_num, bool zero_seg0_end_planes, double *double_out_ptr, const shared_ptr< ProjData > &additive_binwise_correction, const shared_ptr< BinNormalisation > normalise_sptr, const double start_time_of_frame, const double end_time_of_frame, RPC_process_related_viewgrams_type *RPC_process_related_viewgrams, DistributedCachingInformation *caching_info_ptr)
This function essentially implements a loop over segments and all views in the current subset.Output is in output_image_ptr and in float_out_ptr (but only if they are not NULL). What the output is, is really determined by the call-back function RPC_process_related_viewgrams.
void RayTraceVoxelsOnCartesianGrid (ProjMatrixElemsForOneBin &lor, const CartesianCoordinate3D< float > &start_point, const CartesianCoordinate3D< float > &end_point, const CartesianCoordinate3D< float > &voxel_size, const float normalisation_constant=1.F)
RayTraceVoxelsOnCartesianGrid finds the Length of Intersections (LOIs) of an LOR with a grid of voxels and appends them to the ProjMatrixElemsForOneBin object.
VoxelsOnCartesianGrid< float > warp_image (const shared_ptr< DiscretisedDensity< 3, float > > &density_sptr, const shared_ptr< DiscretisedDensity< 3, float > > &motion_x_sptr, const shared_ptr< DiscretisedDensity< 3, float > > &motion_y_sptr, const shared_ptr< DiscretisedDensity< 3, float > > &motion_z_sptr, const BSpline::BSplineType spline_type, const bool extend_borders)
template<typename elemT >
std::ostream & operator<< (std::ostream &str, const VectorWithOffset< elemT > &v)
Outputs a VectorWithOffset to a stream.
template<int num_dimensions, typename coordT >
std::ostream & operator<< (std::ostream &str, const BasicCoordinate< num_dimensions, coordT > &v)
Outputs a BasicCoordinate to a stream.
template<typename elemT >
std::ostream & operator<< (std::ostream &str, const std::vector< elemT > &v)
Outputs a vector to a stream.
template<typename elemT >
std::istream & operator>> (std::istream &str, std::vector< elemT > &v)
Inputs a vector from a stream.
template<typename elemT >
std::istream & operator>> (std::istream &str, VectorWithOffset< elemT > &v)
Inputs a VectorWithOffset from a stream.
template<int num_dimensions, typename coordT >
std::istream & operator>> (std::istream &str, BasicCoordinate< num_dimensions, coordT > &v)
Inputs a coordinate from a stream.
char * strupr (char *const str)
make C-string uppercase
template<class STRING >
void warning (const STRING &string)
Use this function for writing warning messages.
void four1 (Array< 1, float > &data, int nn, int isign)
1-dimensional FFT
void fourn (Array< 1, float > &data, Array< 1, int > &nn, int ndim, int isign)
n-dimensional FFT
void convlvC (Array< 1, float > &data, const Array< 1, float > &filter, int n)
Convolve data with a filter which is given in frequency space.
void rlft3 (Array< 3, float > &data, Array< 2, float > &speq, int nn1, int nn2, int nn3, int isign)
3D FFT of real numbers
void realft (Array< 1, float > &data, int n, int isign)
Calculates the Fourier Transform of a set of 2n real-valued data points.
void fwd_project (ProjData &proj_data, VoxelsOnCartesianGrid< float > *vox_image_ptr, const int start_segment_num, const int end_segment_num, const int start_axial_pos_num, const int end_axial_pos_num, const int start_view, const int end_view, const int start_tang_pos_num, const int end_tang_pos_num)
Coordinate4D< int > sign (const Coordinate4D< float > &c)
Coordinate4D< float > abs (const Coordinate4D< float > &c)
void add_to_bin (VectorWithOffset< shared_ptr< SegmentByView< float > > > &segments, const Bin &bin, const float value)
template<class ObjectTransformationT , class PushInterpolatorT >
Succeeded transform_3d_object_push_interpolation (DiscretisedDensity< 3, float > &out_density, const DiscretisedDensity< 3, float > &in_density, const ObjectTransformationT &transformation_in_to_out, const PushInterpolatorT &interpolator, const bool do_jacobian)
transform image data
template<class ObjectTransformationT , class PullInterpolatorT >
Succeeded transform_3d_object_pull_interpolation (DiscretisedDensity< 3, float > &out_density, const DiscretisedDensity< 3, float > &in_density, const ObjectTransformationT &transformation_out_to_in, const PullInterpolatorT &interpolator, const bool do_jacobian)
transform image data
template<class T2 >
void assign (std::pair< BasicCoordinate< 3, float >, float > &x, T2 y)
template<typename in_elemT >
void linear_extrapolation (std::vector< in_elemT > &input_vector)
template<class elemT , class positionT >
elemT pull_nearest_neighbour_interpolate (const Array< 3, elemT > &in, const BasicCoordinate< 3, positionT > &point_in_input_coords)
Pull value from the input array using nearest neigbour interpolation.
template<int num_dimensions, class elemT , class positionT , class valueT >
void push_nearest_neighbour_interpolate (Array< num_dimensions, elemT > &out, const BasicCoordinate< num_dimensions, positionT > &point_in_output_coords, valueT value)
Push value into the output array using nearest neigbour interpolation.
template<class elemT , class positionT >
elemT pull_linear_interpolate (const Array< 3, elemT > &in, const BasicCoordinate< 3, positionT > &point_in_input_coords)
Returns an interpolated value according to point_in_input_coords.
template<class elemT , class positionT , class valueT >
void push_transpose_linear_interpolate (Array< 3, elemT > &out, const BasicCoordinate< 3, positionT > &point_in_output_coords, valueT value)
Push value into the output array using the transpose of linear interpolation.
template<typename coordT >
Quaternion< coordT > conjugate (const Quaternion< coordT > &)
template<typename coordT >
Quaternion< coordT > inverse (const Quaternion< coordT > &)
template<typename coordT >
coordT norm_squared (const Quaternion< coordT > &q)
template<typename coordT >
coordT norm (const Quaternion< coordT > &q)
template<class NUMBER >
Succeeded write_basic_interfile (const string &filename, const ExamInfo &exam_info, const Array< 3, NUMBER > &image, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type, const float scale, const ByteOrder byte_order)
template<class NUMBER >
Succeeded write_basic_interfile (const string &filename, const Array< 3, NUMBER > &image, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type, const float scale, const ByteOrder byte_order)
Succeeded write_basic_interfile (const string &filename, const ParametricVoxelsOnCartesianGrid &image, const NumericType output_type, const float scale, const ByteOrder byte_order)
ProjDataFromStream * read_interfile_PDFS_Siemens (istream &input, const string &directory_for_data, const ios::openmode open_mode)
ProjDataFromStream * read_interfile_PDFS (istream &input, const string &directory_for_data, const ios::openmode open_mode)
ProjDataFromStream * read_interfile_PDFS (const string &filename, const ios::openmode open_mode)
template Succeeded write_basic_interfile (const string &filename, const Array< 3, signed short > &, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type, const float scale, const ByteOrder byte_order)
template Succeeded write_basic_interfile (const string &filename, const Array< 3, unsigned short > &, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type, const float scale, const ByteOrder byte_order)
template Succeeded write_basic_interfile (const string &filename, const Array< 3, float > &, const CartesianCoordinate3D< float > &voxel_size, const CartesianCoordinate3D< float > &origin, const NumericType output_type, const float scale, const ByteOrder byte_order)
template Succeeded write_basic_interfile (const string &filename, const Array< 3, signed short > &image, const NumericType output_type, const float scale, const ByteOrder byte_order)
template Succeeded write_basic_interfile (const string &filename, const Array< 3, unsigned short > &image, const NumericType output_type, const float scale, const ByteOrder byte_order)
template Succeeded write_basic_interfile (const string &filename, const Array< 3, float > &image, const NumericType output_type, const float scale, const ByteOrder byte_order)
void find_segment_sequence (vector< int > &segment_sequence, VectorWithOffset< int > &sorted_num_rings_per_segment, VectorWithOffset< int > &sorted_min_ring_diff, VectorWithOffset< int > &sorted_max_ring_diff, vector< int > &num_rings_per_segment, const vector< int > &min_ring_difference, const vector< int > &max_ring_difference)
template<>
STIRImageMulti::full_value_type ITK_pixel_to_STIR_pixel (typename ITKImageMulti::PixelType itk_pixel, const STIRImageMulti &stir_image, bool is_displacement_field)
template<typename ITKImageType >
ITKImageType::Pointer orient_ITK_image (const typename ITKImageType::Pointer itk_image_orig, const shared_ptr< ExamInfo > exam_info_sptr)
template<>
STIRImageSingle * read_file_itk (const std::string &filename)
template<>
STIRImageMulti * read_file_itk (const std::string &filename)
template float determinant (const Array< 2, float > &)
template double determinant (const Array< 2, double > &)
template std::complex< float > determinant (const Array< 2, std::complex< float > > &)
template std::complex< double > determinant (const Array< 2, std::complex< double > > &)
template void fourier (Array< 3, std::complex< float > > &c, const int sign)
template void fourier (Array< 2, std::complex< float > > &c, const int sign)
template void fourier (Array< 1, std::complex< float > > &c, const int sign)
template void fourier (VectorWithOffset< std::complex< float > > &c, const int sign)
INSTANTIATE (1, float)
INSTANTIATE (2, float)
INSTANTIATE (3, float)
void check_values (const ProjDataInfoCylindricalArcCorr *proj_data_info_ptr, const float delta, const double cphi, const double sphi, const int s, const int ring0, const int X1, const int Y1, const int Z1, const double ds, const double dz, const float num_planes_per_axial_pos, const float axial_pos_to_z_offset)
void distributable_compute_gradient (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &symmetries_sptr, DiscretisedDensity< 3, float > &output_image, const DiscretisedDensity< 3, float > &input_image, const shared_ptr< ProjData > &proj_dat, int subset_num, int num_subsets, int min_segment, int max_segment, bool zero_seg0_end_planes, double *log_likelihood_ptr, shared_ptr< ProjData > const &additive_binwise_correction, DistributedCachingInformation *caching_info_ptr)
void distributable_accumulate_loglikelihood (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &symmetries_sptr, const DiscretisedDensity< 3, float > &input_image, const shared_ptr< ProjData > &proj_dat, int subset_num, int num_subsets, int min_segment, int max_segment, bool zero_seg0_end_planes, double *log_likelihood_ptr, shared_ptr< ProjData > const &additive_binwise_correction, shared_ptr< BinNormalisation > const &normalisation_sptr, const double start_time_of_frame, const double end_time_of_frame, DistributedCachingInformation *caching_info_ptr)
void distributable_sensitivity_computation (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &symmetries_sptr, DiscretisedDensity< 3, float > &sensitivity, const DiscretisedDensity< 3, float > &input_image, const shared_ptr< ProjData > &proj_dat, int subset_num, int num_subsets, int min_segment, int max_segment, bool zero_seg0_end_planes, double *log_likelihood_ptr, shared_ptr< ProjData > const &additive_binwise_correction, shared_ptr< BinNormalisation > const &normalisation_sptr, const double start_time_of_frame, const double end_time_of_frame, DistributedCachingInformation *caching_info_ptr)
void RPC_process_related_viewgrams_gradient (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, RelatedViewgrams< float > *measured_viewgrams_ptr, int &count, int &count2, double *log_likelihood_ptr, const RelatedViewgrams< float > *additive_binwise_correction_ptr, const RelatedViewgrams< float > *mult_viewgrams_ptr)
void RPC_process_related_viewgrams_accumulate_loglikelihood (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, RelatedViewgrams< float > *measured_viewgrams_ptr, int &count, int &count2, double *log_likelihood_ptr, const RelatedViewgrams< float > *additive_binwise_correction_ptr, const RelatedViewgrams< float > *mult_viewgrams_ptr)
void RPC_process_related_viewgrams_sensitivity_computation (const shared_ptr< ForwardProjectorByBin > &forward_projector_sptr, const shared_ptr< BackProjectorByBin > &back_projector_sptr, RelatedViewgrams< float > *measured_viewgrams_ptr, int &count, int &count2, double *log_likelihood_ptr, const RelatedViewgrams< float > *additive_binwise_correction_ptr, const RelatedViewgrams< float > *mult_viewgrams_ptr)
void do_segments (DiscretisedDensity< 3, float > &image, ProjData &proj_data_org, const int start_segment_num, const int end_segment_num, const int start_axial_pos_num, const int end_axial_pos_num, const int start_tang_pos_num, const int end_tang_pos_num, const int start_view, const int end_view, BackProjectorByBin *back_projector_ptr, bool fill_with_1)
void set_Gaussian_filter_fwhm (SeparableCartesianMetzImageFilter< float > &filter, const float fwhm_z, const float fwhm_y, const float fwhm_x)
void michelogram (const ProjDataInfoCylindrical &proj_data_info)
void update_comparison (SegmentByView< float > &input1, const SegmentByView< float > &input2, float &max_pos_error, float &max_neg_error, float &amplitude)
void do_math (enum options operation, SegmentByView< float > &sino1, SegmentByView< float > &sino2, float &accum_max, float &accum_min, float &accum_sum, bool accumulators_initialized)
void do_math (enum options operation, SegmentByView< float > &sino1, SegmentBySinogram< float > &seg_sinogram, float &accum_max, float &accum_min, float &accum_sum, bool accumulators_initialized, float scalar=0.0)
void make_buffer_header (const char *data_filename, const char *header_filename, ProjData &input_sino, int limit_segments, NumericType::Type output_type=NumericType::FLOAT)
void show_math_menu ()
float pos_indicate (float x)
shared_ptr< ProjData > ask_proj_data (const char *const input_query)
template<typename STIRImageType >
STIRImageType * ask_image (const char *const input_query)
template<typename STIRImageType >
shared_ptr< OutputFileFormat< STIRImageType > > set_up_output_format (const std::string &filename)
Array< 3, float > extend_segment_in_views (const SegmentBySinogram< float > &sino, const int min_view_extension, const int max_view_extension)
Extension of direct projection data in view direction.
Array< 2, float > extend_sinogram_in_views (const Sinogram< float > &sino, const int min_view_extension, const int max_view_extension)
Succeeded interpolate_projdata (ProjData &proj_data_out, const ProjData &proj_data_in, const BSpline::BSplineType spline_type, const bool remove_interleaving=false, const bool use_view_offset=false)
Perform B-Splines Interpolation.
Succeeded interpolate_projdata (ProjData &proj_data_out, const ProjData &proj_data_in, const BasicCoordinate< 3, BSpline::BSplineType > &these_types, const bool remove_interleaving, const bool use_view_offset)
Functions for user input
bool ask (const std::string &prompt, bool default_value)
A function to ask a yes/no question from the user.
string ask_string (const std::string &prompt, const std::string &default_value="")
A function to ask a string from the user.
string ask_filename_with_extension (const std::string &prompt, const std::string &default_extension)
Asks for a filename (appending an extension if none is provided).
char * ask_filename_with_extension (char *file_in_directory_name, const std::string &prompt, const std::string &default_extension)
Asks for a filename (appending an extension if none is provided) and stores the string where file_in_directory_name points to.
template<class NUMBER >
NUMBER ask_num (const std::string &prompt, NUMBER minimum_value, NUMBER maximum_value, NUMBER default_value)
A function to ask a number from the user.
template<class FSTREAM >
void ask_filename_and_open (FSTREAM &s, const std::string &prompt, const std::string &default_extension, std::ios::openmode mode, bool abort_if_failed)
Asks for a filename (with default extension) and opens the stream s with mode giving the specifics.
template<class FSTREAM >
void ask_filename_and_open (FSTREAM &s, const std::string &prompt, const std::string &default_extension, std::ios::openmode mode)
as above, but with default abort_if_failed = true
Functions for stream/file manipulations
FILE *& open_read_binary (FILE *&fptr, const std::string &name)
opens a FILE for reading binary data. Calls error() when it does not succeed.
FILE *& open_write_binary (FILE *&fptr, const std::string &name)
opens a FILE for writing binary data. Calls error() when it does not succeed.
void close_file (FILE *&fptr)
closes a FILE without error checking.
streamsize find_remaining_size (std::istream &input)
Find number of remaining characters in the stream.
void * read_stream_in_memory (std::istream &input, std::streamsize &file_size)
reads data into memory, returning a pointer to the memory
template<class IFSTREAM >
IFSTREAM & open_read_binary (IFSTREAM &s, const std::string &name)
opens a stream for reading binary data. Calls error() when it does not succeed.
template<class OFSTREAM >
OFSTREAM & open_write_binary (OFSTREAM &s, const std::string &name)
opens a stream for writing binary data. Calls error() when it does not succeed.
template<class FSTREAM >
void close_file (FSTREAM &s)
closes a stream without error checking.
Functions for filename manipulations
These functions work on different platforms, i.e. Unix, VAX, Windows. Also on older MacOS versions.
Warning
Functions that work on char* might be removed at some point.
const char * find_filename (const char *const filename_with_directory)
return a pointer to the start of the filename (i.e. after directory specifications)
string::size_type find_pos_of_filename (const std::string &filename_with_directory)
return the position of the start of the filename (i.e. after directory specifications)
string get_filename (const std::string &filename_with_directory)
return a std::string containing only the filename (i.e. after directory specifications)
char * get_directory_name (char *directory_name, const char *const filename_with_directory)
Copies the directory part from 'filename_with_directory' into 'directory_name' and returns the 'directory_name' pointer.
string get_directory_name (const std::string &filename_with_directory)
Returns a string with the directory part from 'filename_with_directory'.
string::size_type find_pos_of_extension (const std::string &file_in_directory_name)
find the position of the '.' of the extension
string & add_extension (std::string &file_in_directory_name, const std::string &extension)
Append extension if none present.
string & replace_extension (std::string &file_in_directory_name, const std::string &extension)
Replace extension (or append if none present)
bool is_absolute_pathname (const char *const filename_with_directory)
Checks if the filename points to an absolute location, or is a relative (e.g. to current directory) pathname.
bool is_absolute_pathname (const std::string &filename_with_directory)
Checks if the filename points to an absolute location, or is a relative (e.g. to current directory) pathname.
char * prepend_directory_name (char *filename_with_directory, const char *const directory_name)
Prepend directory_name to the filename, but only if !is_absolute_pathname(filename_with_directory)
Functions for interpolating data to new pixel/bin sizes
void zoom_viewgrams (RelatedViewgrams< float > &viewgrams, const float zoom, const int min_tang_pos_num, const int max_tang_pos_num, const float x_offset_in_mm=0, const float y_offset_in_mm=0)
zoom a RelatedViewgrams object, replacing it with the new data
void zoom_viewgram (Viewgram< float > &viewgram, const float zoom, const int min_tang_pos_num, const int max_tang_pos_num, const float x_offset_in_mm=0, const float y_offset_in_mm=0)
zoom viewgram, replacing it with the new data
void zoom_viewgram (Viewgram< float > &out_viewgram, const Viewgram< float > &in_viewgram, const float x_offset_in_mm=0, const float y_offset_in_mm=0)
zoom in_viewgram, replacing out_viewgram with the new data
void zoom_image_in_place (VoxelsOnCartesianGrid< float > &image, const float zoom, const float x_offset_in_mm, const float y_offset_in_mm, const int new_size, const ZoomOptions=ZoomOptions::preserve_sum)
zoom image, replacing the first argument with the new data
VoxelsOnCartesianGrid< float > zoom_image (const VoxelsOnCartesianGrid< float > &image, const float zoom, const float x_offset_in_mm, const float y_offset_in_mm, const int new_size, const ZoomOptions=ZoomOptions::preserve_sum)
zoom image, replacing the first argument with the new data
void zoom_image_in_place (VoxelsOnCartesianGrid< float > &image, const CartesianCoordinate3D< float > &zooms, const CartesianCoordinate3D< float > &offsets_in_mm, const BasicCoordinate< 3, int > &new_sizes, const ZoomOptions=ZoomOptions::preserve_sum)
zoom image, replacing the first argument with the new data. Full 3D shifts and zooms.
VoxelsOnCartesianGrid< float > zoom_image (const VoxelsOnCartesianGrid< float > &image, const CartesianCoordinate3D< float > &zooms, const CartesianCoordinate3D< float > &offsets_in_mm, const BasicCoordinate< 3, int > &new_sizes, const ZoomOptions=ZoomOptions::preserve_sum)
zoom image, returning the new image
void zoom_image (VoxelsOnCartesianGrid< float > &image_out, const VoxelsOnCartesianGrid< float > &image_in, const ZoomOptions=ZoomOptions::preserve_sum)
zoom image_in according to dimensions, origin and voxel_size of image_out.
void zoom_image (PixelsOnCartesianGrid< float > &image2D_out, const PixelsOnCartesianGrid< float > &image2D_in, const ZoomOptions=ZoomOptions::preserve_sum)
zoom image2D_in according to dimensions, origin and pixel_size of image2D_out.
Functions to compute ROI values
Shapes are first discretised using Shape3D::construct_volume. This can make fuzzy boundaries (when the num_samples argument is not (1,1,1), or when DiscretisedShape3D needs zooming). Mean and stddev are computed using weighted versions, taking this smoothness into account, while ROI_min and max are ignore those weights.
void compute_ROI_values_per_plane (VectorWithOffset< ROIValues > &values, const DiscretisedDensity< 3, float > &density, const Shape3D &shape, const CartesianCoordinate3D< int > &num_samples)
ROIValues compute_total_ROI_values (const VectorWithOffset< ROIValues > &values)
ROIValues compute_total_ROI_values (const DiscretisedDensity< 3, float > &image, const Shape3D &shape, const CartesianCoordinate3D< int > &num_samples)
void compute_plane_range_ROI_values_per_plane (VectorWithOffset< ROIValues > &values, const DiscretisedDensity< 3, float > &density, const CartesianCoordinate2D< int > &plane_range, const Shape3D &shape, const CartesianCoordinate3D< int > &num_samples)
float compute_CR_hot (ROIValues &val1, ROIValues &val2)
float compute_CR_cold (ROIValues &val1, ROIValues &val2)
float compute_uniformity (ROIValues &val)
VectorWithOffset< float > compute_CR_hot_per_plane (VectorWithOffset< ROIValues > &val1, VectorWithOffset< ROIValues > &val2)
VectorWithOffset< float > compute_CR_cold_per_plane (VectorWithOffset< ROIValues > &val1, VectorWithOffset< ROIValues > &val2)
VectorWithOffset< float > compute_uniformity_per_plane (VectorWithOffset< ROIValues > &val)
numerical operations for arrays of complex numbers
template<int num_dimensions, typename elemT >
Array< num_dimensions, std::complex< elemT > > & operator*= (Array< num_dimensions, std::complex< elemT > > &lhs, const elemT &rhs)
template<int num_dimensions, typename elemT >
Array< num_dimensions, std::complex< elemT > > & operator/= (Array< num_dimensions, std::complex< elemT > > &lhs, const elemT &rhs)
template<int num_dimensions, typename elemT >
Array< num_dimensions, std::complex< elemT > > & operator+= (Array< num_dimensions, std::complex< elemT > > &lhs, const elemT &rhs)
template<int num_dimensions, typename elemT >
Array< num_dimensions, std::complex< elemT > > & operator-= (Array< num_dimensions, std::complex< elemT > > &lhs, const elemT &rhs)
void assign (std::complex< double > &x, const int y)
void assign (std::complex< float > &x, const int y)
template<int num_dimensions, int num_dimensions2, typename elemT >
const Array< num_dimensions-num_dimensions2, elemT > & get (const Array< num_dimensions, elemT > &a, const BasicCoordinate< num_dimensions2, int > &c)
an alternative for array indexing using BasicCoordinate objects
template<int num_dimensions, typename elemT >
const elemT & get (const Array< num_dimensions, elemT > &a, const BasicCoordinate< num_dimensions, int > &c)
an alternative for array indexing using BasicCoordinate objects
template<int num_dimensions, typename T >
BasicCoordinate< num_dimensions, int > get_min_indices (const Array< num_dimensions, T > &a)
Get the first multi-dimensional index of the array.
template<int num_dimensions, typename T , int num_dimensions2>
bool next (BasicCoordinate< num_dimensions, int > &indices, const Array< num_dimensions2, T > &a)
Given an index into an array, increment it to the next one.
templated functions for assigning values
When writing templated code, it is sometimes not possible to use operator=() for assignment, e.g. when the classes do not support that operator. The assign template tries to alleviate this problem by providing several overloads when the first argument is a (STIR) container.
Usage
assign(x,y); // logically equivalent to x=y;
Design consideration
We could have overloaded operator=() instead, but that would probably lead to surprising conversions.
template<class T , class T2 >
void assign (T &x, const T2 &y)
template<class T , class T2 >
void assign (std::vector< T > &v, const T2 &y)
template<int num_dimensions, class T , class T2 >
void assign (BasicCoordinate< num_dimensions, T > &v, const T2 &y)
template<class T , class T2 >
void assign (VectorWithOffset< T > &v, const T2 &y)
template<int num_dimensions, class T , class T2 >
void assign (Array< num_dimensions, T > &v, const T2 &y)
void assign (double &x, const int y)
void assign (float &x, const int y)
Utility functions to make BasicCoordinate objects.
Warning
Because of template rules of C++, all arguments of the make_coordinate function have to have exactly the same type. For instance,
const BasicCoordinate<3,float> a = make_coordinate(1.F,2.F,0.F);
template<class T >
BasicCoordinate< 1, T > make_coordinate (const T &a1)
template<class T >
BasicCoordinate< 2, T > make_coordinate (const T &a1, const T &a2)
template<class T >
BasicCoordinate< 3, T > make_coordinate (const T &a1, const T &a2, const T &a3)
template<class T >
BasicCoordinate< 4, T > make_coordinate (const T &a1, const T &a2, const T &a3, const T &a4)
template<class T >
BasicCoordinate< 5, T > make_coordinate (const T &a1, const T &a2, const T &a3, const T &a4, const T &a5)
template<class T >
BasicCoordinate< 6, T > make_coordinate (const T &a1, const T &a2, const T &a3, const T &a4, const T &a5, const T &a6)
testing of (smart) pointers
A utility function that checks if an ordinary or smart pointer is null with identical syntax for all types.
template<typename T >
bool is_null_ptr (T const *const ptr)
template<typename T >
bool is_null_ptr (shared_ptr< T > const &sptr)
template<typename T >
bool is_null_ptr (unique_ptr< T > const &aptr)
bool is_null_ptr (const std::nullptr_t)
/*! This can be used as alternative to the parsing mechanism.
Warning
Be careful with setting shared pointers. If you modify the objects in one place, all objects that use the shared pointer will be affected. */ // void set_anatomical_prior_sptr(shared_ptr<TargetT>, int index); //! sets all elements of vector anatomical_prior to the same value void set_anatomical_prior_sptr(shared_ptr<TargetT> arg); void set_anatomical_image_filename(const std::string&, const int index); void set_anatomical_image_filename(const std::string&);
void set_num_neighbours(const int); void set_num_non_zero_feat(const int); void set_sigma_m(const double, const int index); //! sets all elements of vector sigma_m to the same value void set_sigma_m(const double); void set_sigma_p(const double); void set_sigma_dp(const double); void set_sigma_dm(const double); void set_only_2D(const bool); void set_hybrid(const bool);
//! boolean value to determine if the update images have to be written to disk void set_write_update_image(const int); //
void compute_kernelised_image (TargetT &kernelised_image_out, const TargetT &image_to_kernelise, const TargetT &current_alpha_estimate)
double calc_emission_kernel (const double current_alpha_estimate_zyx, const double current_alpha_estimate_zyx_dr, const double distance_dzdydx, const bool use_compact_implementation, const int l, const int m)
double calc_anatomical_kernel (const double anatomical_prior_zyx, const double anatomical_prior_zyx_dr, const double distance_dzdydx, const bool use_compact_implementation, const int l, const int m, const int index)
double calc_kernel_from_precalculated (const double precalculated_norm_zxy, const double sq_sigma_int, const double sq_sigma_dist, const double sq_distance_dzdydx, const double precalc_denom)
double calc_kernel_compact (const double prior_image_zyx_diff, const double sq_sigma_int, const double sq_sigma_dist, const double sq_distance_dzdydx, const double precalc_denom)
Functions for modulo computations
double modulo (const double a, const double b)
Like std::fmod() but with guaranteed nonnegative result.
float modulo (const float a, const float b)
modulo for floats
int modulo (const int a, const int b)
Like the normal modulus operator (%) but with guaranteed nonnegative result.
template<int num_dimensions, typename T >
BasicCoordinate< num_dimensions, T > modulo (const BasicCoordinate< num_dimensions, T > &a, const BasicCoordinate< num_dimensions, T > &b)
Performs the modulus operation on each element of the coordinates.
template<typename FloatOrDouble >
FloatOrDouble from_min_pi_plus_pi_to_0_2pi (const FloatOrDouble phi)
A function to convert an angle from one range to another.
template<typename FloatOrDouble >
FloatOrDouble to_0_2pi (const FloatOrDouble phi)
Convert angle to standard range.
A collection of error functions.
The erf() is a high precision implementation of the error function. The erfc() is the complementary of the erf(), which should be equal to 1-erf(), but with higher precision when erf is close to 1.
Todo:
replace with boost::erf
double erf (double)
double erfc (double)
functions specific for 1D Arrays
template<class elemT >
elemT inner_product (const Array< 1, elemT > &v1, const Array< 1, elemT > &v2)
Inner product of 2 1D arrays.
template<class elemT >
double angle (const Array< 1, elemT > &v1, const Array< 1, elemT > &v2)
angle between 2 1D arrays
functions for matrices
template<class elemT >
Array< 1, elemT > matrix_multiply (const Array< 2, elemT > &m, const Array< 1, elemT > &vec)
matrix with vector multiplication
template<int dimension, class elemT >
BasicCoordinate< dimension, elemT > matrix_multiply (const Array< 2, elemT > &m, const BasicCoordinate< dimension, elemT > &vec)
matrix multiplication with vector (given as BasicCoordinate)
template<class elemT >
Array< 2, elemT > matrix_multiply (const Array< 2, elemT > &m1, const Array< 2, elemT > &m2)
matrix multiplication
template<class elemT >
Array< 2, elemT > matrix_transpose (const Array< 2, elemT > &m)
matrix transposition
template<class elemT >
Array< 2, elemT > diagonal_matrix (const unsigned dimension, const elemT value)
construct a diagonal matrix with all elements on the diagonal equal
template<int dimension, class elemT >
Array< 2, elemT > diagonal_matrix (const BasicCoordinate< dimension, elemT > &values)
construct a diagonal matrix
Functions to compute the norm
template<typename elemT >
double norm_squared (const elemT t)
Returns the square of the norm of a number.
template<typename elemT >
double norm (const elemT t)
Returns the norm of a number.
double norm (const double t)
double norm (const float t)
template<class Iter >
double norm_squared (Iter begin, Iter end)
Returns the square of the l2-norm of a sequence.
template<class Iter >
double norm (Iter begin, Iter end)
Returns the l2-norm of a sequence.
template<class elemT >
double norm (const Array< 1, elemT > &v1)
l2 norm of a 1D array
template<class elemT >
double norm_squared (const Array< 1, elemT > &v1)
square of the l2 norm of a 1D array
functions to convert from data in Numerical Recipes format to STIR arrays.
void stir_to_nr (const VectorWithOffset< std::complex< float > > &c, VectorWithOffset< float > &nr_data)
void stir_to_nr (const Array< 2, std::complex< float > > &c2d, VectorWithOffset< float > &nr_data)
void stir_to_nr (const VectorWithOffset< Array< 1, std::complex< float > > > &c2d, VectorWithOffset< float > &nr_data)
void nr_to_stir (const VectorWithOffset< float > &nr_data, VectorWithOffset< std::complex< float > > &c)
void nr_to_stir (const VectorWithOffset< float > &nr_data, Array< 2, std::complex< float > > &c2d)
void nr_to_stir (const VectorWithOffset< float > &nr_data, VectorWithOffset< Array< 1, std::complex< float > > > &c2d)
int distributable_main (int argc, char **argv)
void distributable_computation_cache_enabled (const shared_ptr< ForwardProjectorByBin > &forward_projector_ptr, const shared_ptr< BackProjectorByBin > &back_projector_ptr, const shared_ptr< DataSymmetriesForViewSegmentNumbers > &symmetries_ptr, DiscretisedDensity< 3, float > *output_image_ptr, const DiscretisedDensity< 3, float > *input_image_ptr, const shared_ptr< ProjData > &proj_data_sptr, const bool read_from_proj_data, int subset_num, int num_subsets, int min_segment_num, int max_segment_num, bool zero_seg0_end_planes, double *double_out_ptr, const shared_ptr< ProjData > &additive_binwise_correction, const shared_ptr< BinNormalisation > normalise_sptr, const double start_time_of_frame, const double end_time_of_frame, RPC_process_related_viewgrams_type *RPC_process_related_viewgrams, DistributedCachingInformation *caching_info_ptr)
This function essentially implements a loop over segments and all views in the current subset in the parallel case.
void test_image_estimate (shared_ptr< stir::DiscretisedDensity< 3, float > > input_image_ptr)
Functions for rounding floating point numbers
int round (const float x)
Implements rounding of floating point numbers.
int round (const double x)
Implements rounding of double numbers.
template<int num_dimensions, class elemT >
BasicCoordinate< num_dimensions, int > round (const BasicCoordinate< num_dimensions, elemT > &x)
Implements rounding of a BasicCoordinate object.
template<typename integerT >
void round_to (integerT &result, const float x)
Implements rounding of floating point numbers to other integer types.
template<int num_dimensions, class integerT , class elemT >
void round_to (BasicCoordinate< num_dimensions, integerT > &result, const BasicCoordinate< num_dimensions, elemT > &x)
Implements rounding of a BasicCoordinate object to other integer types.
Functions for thresholding numbers and sequences
template<typename forw_iterT , typename elemT >
void threshold_upper_lower (forw_iterT begin, forw_iterT end, const elemT new_min, const elemT new_max)
Threshold a sequence from above and below.
template<typename forw_iterT , typename elemT >
void threshold_upper (forw_iterT begin, forw_iterT end, const elemT new_max)
Threshold a sequence from above.
template<typename forw_iterT , typename elemT >
void threshold_lower (forw_iterT begin, forw_iterT end, const elemT new_min)
Threshold a sequence from below.
template<typename ForwardIter_t , typename elemT >
void threshold_min_to_small_positive_value (ForwardIter_t begin, ForwardIter_t end, const elemT &small_number)
sets non-positive values in the sequence to small positive ones
Variables
const int LINE_ERROR =-1
const int LINE_OK = 0
const float SMALL_NUM = 0.000001F
const float ZERO_TOL = 0.000001F
const double TPI =6.28318530717958647692
template DAVArrayFilter3D< float >
template DAVImageFilter3D< float >
template ModifiedInverseAveragingImageFilterAll< float >
template ModifiedInverseAverigingArrayFilter< 3, float >
template ModifiedInverseAverigingImageFilter< float >
template NonseparableSpatiallyVaryingFilters< float >
template NonseparableSpatiallyVaryingFilters3D< float >
template SeparableLowPassArrayFilter< 3, float >
template SeparableLowPassImageFilter< float >
const int FORWARDFFT =1
const int INVERSEFFT =-1
const int max_filename_length = 1000
some large value to say how long filenames can be in the (deprecated) function ask_filename_with_extension(char *,const std::string&, const std::string&)
const int rim_truncation_sino = 0
const float cache_init_value = -1234567.89E10F
Task-ids currently understood by stir::DistributedWorker
const int task_stop_processing =0
const int task_setup_distributable_computation =200
const int task_do_distributable_gradient_computation =42
const int task_do_distributable_loglikelihood_computation =43
const int task_do_distributable_sensitivity_computation =44
Tag-names currently used by stir::distributable_computation and related functions0
const int AVAILABLE_NOTIFICATION_TAG =2
const int END_ITERATION_TAG =3
const int END_RECONSTRUCTION_TAG =4
const int END_NOTIFICATION_TAG =5
const int BINWISE_CORRECTION_TAG =6
const int BINWISE_MULT_TAG =66
const int REUSE_VIEWGRAM_TAG =10
const int NEW_VIEWGRAM_TAG =11
const int USE_DOUBLE_ARG_TAG =70
const int USE_OUTPUT_IMAGE_ARG_TAG =71
Detailed Description
Namespace for the STIR library (and some/most of its applications)
Test class for exporting and importing ProjData as arrays.
Addition for SAFIR listmode input file format.
Declaration of class stir::DistributedCachingInformation.
This namespace encompasses the whole library. All classes, functions and symbols are in this namespace. This has the effect that conflicts with any other library is impossible (except if that library uses the same namespace...).
Author
Tobias Beisel
Kris Thielemans
Addition for ROOT support - Nikos Efthimiou
Author
Nikos Efthimiou
Typedef Documentation
AxTangPosNumbers
typedef Coordinate2D<int> stir::AxTangPosNumbers
AxTangPosNumbers as a class that provides the 2 remaining coordinates for a Bin, aside from ViewSegmentNumbers.
TODO? something more sofisticated than a typedef
Function Documentation
standardise_interfile_keyword()
std::string stir::standardise_interfile_keyword (const std::string & keyword)
Put a (Interfile) keyword into a standard form.
This follows Interfile 3.3 conventions:
The characters space, tab, underscore, ! are all treated as white space.
Starting and trailing white space is trimmed.
Repeated white space is replaced with a single space
All letters are made lowercase.
Referenced by stir::SAFIRCListmodeInputFileFormat::can_read(), stir::Scanner::get_scanner_from_name(), stir::ImagingModality::ImagingModality(), is_interfile_signature(), stir::InterfileRawDataHeaderSiemens::post_processing(), stir::InterfilePDFSHeaderSiemens::post_processing(), stir::ProjMatrixByBinFromFile::ProjMatrixByBinFromFile(), and stir::KeyParser::standardise_keyword().
ask()
bool stir::ask (const std::string & prompt, bool default_value)
A function to ask a yes/no question from the user.
Parameters
prompt a text string which is supposed to be a question
default_value When set to true , the default is Yes.
The question is currently presented as
prompt [Y/N D:default_value]:
Simply pressing 'enter' will select the default value. Otherwise, the first charachter of the response will be checked against y/Y/n/N to determine the return value. If it is none of these, the question will be asked again.
Referenced by stir::ProjDataInfo::ask_parameters(), stir::OSSPSReconstruction< TargetT >::ask_parameters(), stir::OSMAPOSLReconstruction< TargetT >::ask_parameters(), stir::IterativeReconstruction< TargetT >::ask_parameters(), stir::VoxelsOnCartesianGrid< elemT >::grow_z_range(), and stir::ProjDataFromStream::set_segment().
open_read_binary() [1/2]
FILE *& stir::open_read_binary (FILE *& fptr, const std::string & name)
opens a FILE for reading binary data. Calls error() when it does not succeed.
Warning
probably does not work if you are not in the C-locale
References error().
Referenced by stir::FileSignature::FileSignature(), and stir::ProjDataFromStream::set_segment().
open_write_binary() [1/2]
FILE *& stir::open_write_binary (FILE *& fptr, const std::string & name)
opens a FILE for writing binary data. Calls error() when it does not succeed.
Warning
probably does not work if you are not in the C-locale
References error().
Referenced by stir::ProjMatrixByBin::get_cached_proj_matrix_elems_for_one_bin().
close_file() [1/2]
void stir::close_file (FILE *& fptr)
closes a FILE without error checking.
This function is only provided in case you need to write code that works with both std::fstream and stdio FILE.
find_filename()
const char * stir::find_filename (const char *const filename_with_directory)
return a pointer to the start of the filename (i.e. after directory specifications)
The returned pointer is between filename_with_directory and (filename_with_directory+strlen(filename_with_directory)+1). This highest value is used when it looks like a directory name.
Deprecated:
use find_pos_of_filename()
Warning
This function works only with string manipulations. There is no check if the 'filename' part actually corresponds to a directory on disk.
Referenced by add_extension(), find_pos_of_extension(), get_directory_name(), stir::FilenameTests::run_tests(), stir::ecat::ecat7::write_basic_interfile_header_for_ECAT7(), and write_basic_interfile_PDFS_header().
find_pos_of_filename()
std::string::size_type stir::find_pos_of_filename (const std::string & filename_with_directory)
return the position of the start of the filename (i.e. after directory specifications)
The returned number is between 0 and filename_with_directory.size()+1. This highest value is used when it's a directory name.
Warning
This function works only with string manipulations. There is no check if the 'filename' part actually corresponds to a directory on disk.
Referenced by find_pos_of_extension(), get_directory_name(), get_filename(), and stir::FilenameTests::run_tests().
get_filename()
std::string stir::get_filename (const std::string & filename_with_directory)
return a std::string containing only the filename (i.e. after directory specifications)
Warning
This function works only with string manipulations. There is no check if the 'filename' part actually corresponds to a directory on disk.
References find_pos_of_filename().
Referenced by stir::FilePath::get_filename_no_extension(), and stir::RigidObject3DMotionFromPolaris::synchronise().
get_directory_name() [1/2]
char * stir::get_directory_name (char * directory_name, const char *const filename_with_directory)
Copies the directory part from 'filename_with_directory' into 'directory_name' and returns the 'directory_name' pointer.
Warning
This function works only with string manipulations. There is no check if the 'filename' part actually corresponds to a directory on disk.
assumes that directory_name points to enough allocated space
Deprecated:
Use get_directory_name(const std::string&)
References find_filename().
Referenced by stir::ecat::CListModeDataECAT8_32bit::get_empty_record_sptr(), read_interfile_dynamic_image(), read_interfile_image(), read_interfile_parametric_image(), stir::FilenameTests::run_tests(), and stir::ecat::BinNormalisationFromECAT8::set_up().
get_directory_name() [2/2]
std::string stir::get_directory_name (const std::string & filename_with_directory)
Returns a string with the directory part from 'filename_with_directory'.
If there was no directory information present, the return value is the string "." (i.e. the current directory). (It was the empty string prior to STIR 3.0).
Warning
This function works only with string manipulations. There is no check if the 'filename' part actually corresponds to a directory on disk.
References find_pos_of_filename().
find_pos_of_extension()
std::string::size_type stir::find_pos_of_extension (const std::string & file_in_directory_name)
find the position of the '.' of the extension
If no '.' is found in the filename part (i.e. ignoring the directory name), the function returns std::string::npos
References add_extension(), find_filename(), and find_pos_of_filename().
Referenced by stir::FilePath::add_extension(), add_extension(), stir::FilePath::get_extension(), stir::FilePath::get_filename_no_extension(), stir::ecat::ecat7::ECAT966ListmodeInputFileFormat::read_from_file(), stir::FilePath::replace_extension(), replace_extension(), and write_basic_interfile_PDFS_header().
prepend_directory_name()
char * stir::prepend_directory_name (char * filename_with_directory, const char *const directory_name)
Prepend directory_name to the filename, but only if !is_absolute_pathname(filename_with_directory)
If necessary, a directory separator is inserted. If 'directory_name' == 0, nothing happens.
Returns
a pointer to the start of the new filename
Warning
this function assumes that filename_with_directory points to sufficient allocated space to contain the new string.
References is_absolute_pathname().
Referenced by stir::ecat::CListModeDataECAT8_32bit::get_empty_record_sptr(), stir::FilenameTests::run_tests(), and stir::ecat::BinNormalisationFromECAT8::set_up().
ask_filename_with_extension() [1/2]
std::string stir::ask_filename_with_extension (const std::string & prompt, const std::string & default_extension)
Asks for a filename (appending an extension if none is provided).
Example:
std::string filename =
ask_filename_with_extension("Input file name ?", ".img");
Warning
starting or ending spaces are NOT stripped.
References add_extension().
Referenced by stir::OSSPSReconstruction< TargetT >::ask_parameters(), stir::IterativeReconstruction< TargetT >::ask_parameters(), stir::AnalyticReconstruction::initialise_keymap(), and stir::ProjDataFromStream::set_segment().
ask_filename_with_extension() [2/2]
char * stir::ask_filename_with_extension (char * file_in_directory_name, const std::string & prompt, const std::string & default_extension)
Asks for a filename (appending an extension if none is provided) and stores the string where file_in_directory_name points to.
Deprecated:
Use ask_filename_with_extension(const std::string&, const std::string&);
Example:
char filename[max_filename_length];
ask_filename_with_extension(filename, "Input file name ?", ".img");
Warning
file_in_directory_name has to be preallocated (with size max_filename_length)
starting or ending spaces are NOT stripped.
find_remaining_size()
std::streamsize stir::find_remaining_size (std::istream & input)
Find number of remaining characters in the stream.
At the end of this function, the 'input' stream will be positioned at the original_position.
Warning
Works only properly for binary streams.
Referenced by ask_filename_and_open(), stir::VoxelsOnCartesianGrid< elemT >::grow_z_range(), and stir::ProjDataFromStream::set_segment().
zoom_viewgrams()
void stir::zoom_viewgrams (RelatedViewgrams< float > & viewgrams, const float zoom, const int min_tang_pos_num, const int max_tang_pos_num, const float x_offset_in_mm = 0, const float y_offset_in_mm = 0)
zoom a RelatedViewgrams object, replacing it with the new data
See also
zoom.h for parameter info
References stir::RelatedViewgrams< elemT >::begin(), stir::ProjDataInfo::clone(), stir::RelatedViewgrams< elemT >::end(), error(), stir::RelatedViewgrams< elemT >::get_basic_view_segment_num(), stir::RelatedViewgrams< elemT >::get_proj_data_info_ptr(), stir::RelatedViewgrams< elemT >::get_symmetries_ptr(), stir::ProjDataInfo::set_max_tangential_pos_num(), stir::ProjDataInfo::set_min_tangential_pos_num(), and zoom_viewgram().
Referenced by stir::BackProjectorByBinUsingInterpolation::use_piecewise_linear_interpolation().
zoom_viewgram() [1/2]
void stir::zoom_viewgram (Viewgram< float > & viewgram, const float zoom, const int min_tang_pos_num, const int max_tang_pos_num, const float x_offset_in_mm = 0, const float y_offset_in_mm = 0)
zoom viewgram, replacing it with the new data
See also
zoom.h for parameter info
References stir::ProjDataInfo::clone(), error(), stir::Viewgram< elemT >::get_max_tangential_pos_num(), stir::Viewgram< elemT >::get_min_tangential_pos_num(), stir::Viewgram< elemT >::get_proj_data_info_ptr(), stir::Viewgram< elemT >::get_segment_num(), stir::Viewgram< elemT >::get_view_num(), stir::ProjDataInfo::set_max_tangential_pos_num(), stir::ProjDataInfo::set_min_tangential_pos_num(), and zoom_viewgram().
zoom_viewgram() [2/2]
void stir::zoom_viewgram (Viewgram< float > & out_viewgram, const Viewgram< float > & in_viewgram, const float x_offset_in_mm = 0, const float y_offset_in_mm = 0)
zoom in_viewgram, replacing out_viewgram with the new data
This version of zoom_viewgram gets the info on the new sizes, sampling etc. from out_viewgram.
See also
zoom.h for parameter info
References error(), stir::Viewgram< elemT >::get_max_axial_pos_num(), stir::Viewgram< elemT >::get_max_tangential_pos_num(), stir::Viewgram< elemT >::get_min_axial_pos_num(), stir::Viewgram< elemT >::get_min_tangential_pos_num(), stir::ProjDataInfo::get_num_segments(), stir::ProjDataInfo::get_num_views(), stir::Viewgram< elemT >::get_proj_data_info_ptr(), stir::Viewgram< elemT >::get_segment_num(), stir::ProjDataInfoCylindricalArcCorr::get_tangential_sampling(), stir::Viewgram< elemT >::get_view_num(), and overlap_interpolate().
Referenced by zoom_viewgram(), and zoom_viewgrams().
zoom_image_in_place() [1/2]
void stir::zoom_image_in_place (VoxelsOnCartesianGrid< float > & image, const float zoom, const float x_offset_in_mm, const float y_offset_in_mm, const int new_size, const ZoomOptions = ZoomOptions::preserve_sum)
zoom image, replacing the first argument with the new data
See also
zoom.h for parameter info
References zoom_image().
zoom_image() [1/4]
VoxelsOnCartesianGrid< float > stir::zoom_image (const VoxelsOnCartesianGrid< float > & image, const float zoom, const float x_offset_in_mm, const float y_offset_in_mm, const int new_size, const ZoomOptions = ZoomOptions::preserve_sum)
zoom image, replacing the first argument with the new data
See also
zoom.h for parameter info
References stir::VoxelsOnCartesianGrid< elemT >::get_x_size().
Referenced by stir::DiscretisedShape3D::construct_volume(), stir::ScatterSimulation::downsample_density_image_for_scatter_points(), and stir::ScatterSimulation::downsample_images_to_scanner_size().
zoom_image_in_place() [2/2]
void stir::zoom_image_in_place (VoxelsOnCartesianGrid< float > & image, const CartesianCoordinate3D< float > & zooms, const CartesianCoordinate3D< float > & offsets_in_mm, const BasicCoordinate< 3, int > & new_sizes, const ZoomOptions = ZoomOptions::preserve_sum)
zoom image, replacing the first argument with the new data. Full 3D shifts and zooms.
See also
zoom.h for parameter info.
Zooming is done such that the physical coordinates of a point (as returned by DiscretisedDensity<3,float>::get_physical_coordinates_for_indices) remain the same.
The index range of the new image is according to the standard STIR conventions (z starts from 0, but x and y from -(new_size/2)). The origin is then chosen such that the geometric centres of the images satisfy
offsets_in_mm == new_middle - old_middle
The geometric centre is determined by the average of the physical coordinates of the min and max indices.
Warning
: For even-sized images, this convention can lead to somewhat non-intuitive results (half-pixel shifts etc).
References zoom_image().
zoom_image() [2/4]
VoxelsOnCartesianGrid< float > stir::zoom_image (const VoxelsOnCartesianGrid< float > & image, const CartesianCoordinate3D< float > & zooms, const CartesianCoordinate3D< float > & offsets_in_mm, const BasicCoordinate< 3, int > & new_sizes, const ZoomOptions = ZoomOptions::preserve_sum)
zoom image, returning the new image
See also
zoom.h for parameter info
zoom_image_in_place
zoom_image() [3/4]
void stir::zoom_image (VoxelsOnCartesianGrid< float > & image_out, const VoxelsOnCartesianGrid< float > & image_in, const ZoomOptions = ZoomOptions::preserve_sum)
zoom image_in according to dimensions, origin and voxel_size of image_out.
See also
zoom.h for parameter info
Zooming is done such that the physical coordinates of a point (as returned by DiscretisedDensity<3,float>::get_physical_coordinates_for_indices) remain the same.
The code also provides for three possible rescaling options: (i) preserving the image values: should be used when zooming an attenuation image (ii) preserving the image projectors: should be used when zooming an activity image (iii) preserving the image sum: default
References stir::ExamData::set_exam_info().
zoom_image() [4/4]
void stir::zoom_image (PixelsOnCartesianGrid< float > & image2D_out, const PixelsOnCartesianGrid< float > & image2D_in, const ZoomOptions = ZoomOptions::preserve_sum)
zoom image2D_in according to dimensions, origin and pixel_size of image2D_out.
See also
zoom.h for parameter info
References stir::DiscretisedDensity< num_dimensions, elemT >::get_origin(), stir::PixelsOnCartesianGrid< elemT >::get_pixel_size(), overlap_interpolate(), and stir::ExamData::set_exam_info().
Referenced by zoom_image_in_place().
get() [1/2]
template<int num_dimensions, int num_dimensions2, typename elemT > const Array<num_dimensions-num_dimensions2,elemT>& stir::get (const Array< num_dimensions, elemT > & a, const BasicCoordinate< num_dimensions2, int > & c) inline
an alternative for array indexing using BasicCoordinate objects
Case where the index has lower dimension than the array
Referenced by info().
get() [2/2]
template<int num_dimensions, typename elemT > const elemT& stir::get (const Array< num_dimensions, elemT > & a, const BasicCoordinate< num_dimensions, int > & c) inline
an alternative for array indexing using BasicCoordinate objects
Case where the index has the same dimension as the array
get_min_indices()
template<int num_dimensions, typename T > BasicCoordinate<num_dimensions, int> stir::get_min_indices (const Array< num_dimensions, T > & a) inline
Get the first multi-dimensional index of the array.
Todo:
If the array
a is empty, we return an object where all indices are 0. It would be better to throw an exception.
next()
template<int num_dimensions, typename T , int num_dimensions2> bool stir::next (BasicCoordinate< num_dimensions, int > & indices, const Array< num_dimensions2, T > & a) inline
Given an index into an array, increment it to the next one.
Returns
true if the next index was still within the array, false otherwise
This can be used to iterate through an array using code such as
Array<num_dimensions2, T> array = ...;
BasicCoordinate<num_dimensions, int> indices =
   get_min_indices(array);
do
{ something with indices }
while (next(indices, array));
Warning
The above loop will fail for empty arrays
index_at_maximum()
template<class elemT > int stir::index_at_maximum (const VectorWithOffset< elemT > & v)
Finds the index where the maximum occurs in a (1-dimensional) vector.
If the maximum occurs more than once, the smallest index is returned.
If the vector is empty, the function returns 0.
Todo:
make iterator version, or something that works on std::vector
indices_at_maximum()
template<class elemT > BasicCoordinate<3,int> stir::indices_at_maximum (const Array< 3, elemT > & input_array)
Finds the first (3-dimensional) index where the maximum occurs in a (3-dimensional) array.
Todo:
generalise to arbitrary dimensions
implementation currently cycles through the data twice
References stir::Array< num_dimensions, elemT >::find_max(), stir::VectorWithOffset< T >::get_max_index(), and stir::VectorWithOffset< T >::get_min_index().
Referenced by maximum_location_per_slice(), and stir::MatchTrackerAndScanner::run().
compute_kernelised_image()
void stir::KOSMAPOSLReconstruction::compute_kernelised_image (TargetT & kernelised_image_out, const TargetT & image_to_kernelise, const TargetT & current_alpha_estimate)
//! prompts the user to enter parameter values manually virtual void ask_parameters();
protected: //! Filename with input projection data std::string input_filename,kernelised_output_filename_prefix; std::string current_kimage_filename; std::string sens_filenames;
//! Anatomical image filename std::vector<std::string> anatomical_image_filenames;
std::vector<shared_ptr<TargetT> > anatomical_prior_sptrs,kmnorm_sptrs; shared_ptr<TargetT> kpnorm_sptr; //kernel parameters int num_neighbours,num_non_zero_feat,num_elem_neighbourhood,num_voxels,dimz,dimy,dimx; std::vector<double> sigma_m; bool only_2D; bool hybrid; double sigma_p; double sigma_dp, sigma_dm; BasicCoordinate<3,int> min_ind, max_ind;
//! boolean value to determine if the update images have to be written to disk int write_update_image;
virtual void set_defaults(); virtual void initialise_keymap(); virtual bool post_processing();
private: friend void do_sensitivity(const char * const par_filename);
//! operations prior to the iterations virtual Succeeded set_up(shared_ptr <TargetT > const& target_image_sptr);
//! the principal operations for updating the image iterates at each iteration virtual void update_estimate (TargetT& current_image_estimate);
int subiteration_counter; std::vector<double> anatomical_sd; mutable Array<3,float> distance; /*! Create a matrix containing the norm of the difference between two feature vectors, . */ /*! This is done for the emission image which keeps changing*/ void calculate_norm_matrix(TargetT &normp, const int dimf_row, const int dimf_col, const TargetT& emission);
/*! Create a matrix similarly to calculate_norm_matrix() but this is done for the anatomical image, */ /*! which does not change over iteration.*/ void calculate_norm_const_matrix(std::vector<shared_ptr<TargetT> > &normm, const int dimf_row, const int dimf_col);
/*! Estimate the SD of the anatomical image to be used as normalisation for the feature vector */ void estimate_stand_dev_for_anatomical_image(std::vector<double> &SD);
/*! Compute for each voxel, jl, of the emission image the linear combination between the coefficient and the kernel matrix
The information is stored in the image, kImage
Similar to compute_kernelised_image() but this is the special case when the feature vectors contains only one non-zero element.
The computation becomes faster because we do not need to create norm matrixes
choose between compact_compute_kernelised_image() and full_compute_kernelised_image()
References error().
modulo() [1/4]
double stir::modulo (const double a, const double b) inline
Like std::fmod() but with guaranteed nonnegative result.
std::fmod(a,b) return a number of the same sign as a. This is often inconvenient as the result of this is that the range of std::fmod(a,b) is from -fabs(b) to +fabs(b).
In contrast, modulo(a,b) always returns a nonnegative result. To be precise:
modulo(a,b) returns the value a-i*b, for the integer i such that, if b is nonzero, the result is greater or equal to 0 and less than the magnitude of b.
Error handling (i.e. b=0) is as for std::fmod().
Warning
When assigning the result to a float, the implied rounding might give you float which is (a tiny bit) larger than fabs(b).
Referenced by stir::ProjDataInfoCylindricalNoArcCorr::find_scanner_coordinates_given_cartesian_coordinates(), and stir::ProjDataInfoCylindricalNoArcCorr::get_bin().
modulo() [2/4]
float stir::modulo (const float a, const float b) inline
modulo for floats
See also
modulo(double,double) The reason for this function is that rounding from double to float might make the result of the calculation with doubles larger than b.
Warning
Because of C++ promotion of floats to doubles, it is very easy to call the modulo(double,double) version inadvertently. So, you should probably not rely too much on the result being less than b.
References modulo().
modulo() [3/4]
int stir::modulo (const int a, const int b) inline
Like the normal modulus operator (%) but with guaranteed nonnegative result.
Result will be larger than or equal to 0, and (strictly) smaller than abs(b).
modulo() [4/4]
template<int num_dimensions, typename T > BasicCoordinate<num_dimensions, T> stir::modulo (const BasicCoordinate< num_dimensions, T > & a, const BasicCoordinate< num_dimensions, T > & b) inline
Performs the modulus operation on each element of the coordinates.
Returns
A BasicCoordinate such that for all d
result[d] = modulo(a[d], b[d]
References num_dimensions.
Referenced by modulo(), and to_0_2pi().
from_min_pi_plus_pi_to_0_2pi()
template<typename FloatOrDouble > FloatOrDouble stir::from_min_pi_plus_pi_to_0_2pi (const FloatOrDouble phi) inline
A function to convert an angle from one range to another.
This is mainly useful for converting results from e.g. std::atan2 to a range .
References _PI.
to_0_2pi()
template<typename FloatOrDouble > FloatOrDouble stir::to_0_2pi (const FloatOrDouble phi) inline
Convert angle to standard range.
Identical to modulo(phi, static_cast<FloatOrDouble>(2*_PI))
References _PI, and modulo().
matrix_multiply() [1/3]
template<class elemT > Array<1,elemT> stir::matrix_multiply (const Array< 2, elemT > & m, const Array< 1, elemT > & vec) inline
matrix with vector multiplication
Index ranges have to be compatible (checked with assert).
Referenced by absolute_max_eigenvector_using_power_method(), stir::RigidObject3DTransformation::transform_point(), and stir::Shape3DWithOrientation::transform_to_shape_coords().
matrix_multiply() [2/3]
template<int dimension, class elemT > BasicCoordinate<dimension,elemT> stir::matrix_multiply (const Array< 2, elemT > & m, const BasicCoordinate< dimension, elemT > & vec) inline
matrix multiplication with vector (given as BasicCoordinate)
matrix size has to be compatible with dimension. Matrix index range has to start from 1. All of this is only checked with assert().
matrix_multiply() [3/3]
template<class elemT > Array<2,elemT> stir::matrix_multiply (const Array< 2, elemT > & m1, const Array< 2, elemT > & m2) inline
matrix multiplication
Index ranges have to be compatible (checked with assert).
diagonal_matrix() [1/2]
template<class elemT > Array<2,elemT> stir::diagonal_matrix (const unsigned dimension, const elemT value) inline
construct a diagonal matrix with all elements on the diagonal equal
Parameters
[in] dimension specifies the size of the matrix
[in] value gives the value on the diagonal. Note that its type determines the type of the return value.
Example
// a 3x3 identity matrix
Array<2,float> iden = diagonal_matrix(3, 1.F);
Index-range of the matrix will be 0 till dimensions-1.
Referenced by absolute_max_eigenvector_using_shifted_power_method(), stir::Shape3DWithOrientation::get_direction_vectors(), and stir::Shape3DWithOrientation::set_defaults().
diagonal_matrix() [2/2]
template<int dimension, class elemT > Array<2,elemT> stir::diagonal_matrix (const BasicCoordinate< dimension, elemT > & values) inline
construct a diagonal matrix
Parameters
[in] values gives the values on the diagonal. Note that its type determines the type of the return value.
Example
// a 3x3 diagonal matrix with values 1,2,3 on the diagonal
Array<2,float> diag = diagonal_matrix(Coordinate3D<float>(1,2,3));
Index-range of the matrix will be 0 till dimensions-1. (Note that this is different from values).
norm_squared() [1/3]
template<typename elemT > double stir::norm_squared (const elemT t) inline
Returns the square of the norm of a number.
See also
norm(elemT)
norm() [1/3]
template<typename elemT > double stir::norm (const elemT t) inline
Returns the norm of a number.
This is the same as the absolute value, but works also for std::complex<T>.
norm_squared() [2/3]
template<class Iter > double stir::norm_squared (Iter begin, Iter end) inline
Returns the square of the l2-norm of a sequence.
The l2-norm is defined as the sqrt of the sum of squares of the norms of each element in the sequence.
norm() [2/3]
template<class Iter > double stir::norm (Iter begin, Iter end) inline
Returns the l2-norm of a sequence.
The l2-norm is defined as the sqrt of the sum of squares of the norms of each element in the sequence.
See also
norm(const Array<1,elemT>&) for a convenience function for Array objects.
norm() [3/3]
template<class elemT > double stir::norm (const Array< 1, elemT > & v1) inline
l2 norm of a 1D array
This returns the sqrt of the sum of the square of the absolute values of the elements of v1.
norm_squared() [3/3]
template<class elemT > double stir::norm_squared (const Array< 1, elemT > & v1) inline
square of the l2 norm of a 1D array
This returns the sum of the square of the absolute values of the elements of v1.
round() [1/3]
int stir::round (const float x) inline
Implements rounding of floating point numbers.
round() has the property that
round(x) == -round(-x)
The usual (int)(x+.5) has machine dependent behaviour for negative numbers.
.5 is rounded to 1 (and hence -.5 to -1).
Warning
There is no check on overflow (i.e. if x is too large to fit in an int).
Referenced by stir::DataSymmetriesForBins_PET_CartesianGrid::DataSymmetriesForBins_PET_CartesianGrid(), stir::DataSymmetriesForDensels_PET_CartesianGrid::DataSymmetriesForDensels_PET_CartesianGrid(), stir::ScatterSimulation::downsample_density_image_for_scatter_points(), stir::ScatterSimulation::downsample_scanner(), stir::FBP2DReconstruction::FBP2DReconstruction(), stir::ProjDataInfoCylindricalNoArcCorr::find_scanner_coordinates_given_cartesian_coordinates(), stir::ProjDataInfoCylindricalArcCorr::get_bin(), stir::ProjDataInfoCylindricalNoArcCorr::get_bin(), stir::ForwardProjectorByBinUsingRayTracing::get_symmetries_used(), stir::DiscretisedShape3D::get_voxel_weight(), stir::NonseparableConvolutionUsingRealDFTImageFilter< elemT >::NonseparableConvolutionUsingRealDFTImageFilter(), stir::ProjDataInfoCylindrical::ProjDataInfoCylindrical(), stir::ecat::ecat7::SinglesRatesFromSglFile::rebin(), stir::coordinateTests::run_tests(), stir::GeneralisedPoissonNoiseGenerator::seed(), stir::ForwardProjectorByBinUsingRayTracing::set_up(), stir::BackProjectorByBinUsingInterpolation::set_up(), SSRB(), and stir::BackProjectorByBinUsingInterpolation::use_piecewise_linear_interpolation().
round() [2/3]
int stir::round (const double x) inline
Implements rounding of double numbers.
See also
round(const float)
round() [3/3]
template<int num_dimensions, class elemT > BasicCoordinate<num_dimensions,int> stir::round (const BasicCoordinate< num_dimensions, elemT > & x) inline
Implements rounding of a BasicCoordinate object.
See also
round(const float)
round_to() [1/2]
template<typename integerT > void stir::round_to (integerT & result, const float x) inline
Implements rounding of floating point numbers to other integer types.
This function is templated in the output type for convenience of implementation.
Warning
if an unsigned type is used for integerT, the result for negative x will be system dependent
See also
round(const float)
Todo:
add code to check that integerT is really an integer type at compilation time
Referenced by stir::DynamicDiscretisedDensity::write_to_ecat7().
round_to() [2/2]
template<int num_dimensions, class integerT , class elemT > void stir::round_to (BasicCoordinate< num_dimensions, integerT > & result, const BasicCoordinate< num_dimensions, elemT > & x) inline
Implements rounding of a BasicCoordinate object to other integer types.
See also
round_to(integerT, float)
operator<<() [1/3]
template<typename elemT > std::ostream& stir::operator<< (std::ostream & str, const VectorWithOffset< elemT > & v) inline
Outputs a VectorWithOffset to a stream.
Output is of the form
{1, 2, 3}
with an endl at the end.
This can be used for higher dimensional arrays as well, where each 1D subobject will be on its own line.
operator<<() [2/3]
template<int num_dimensions, typename coordT > std::ostream& stir::operator<< (std::ostream & str, const BasicCoordinate< num_dimensions, coordT > & v) inline
Outputs a BasicCoordinate to a stream.
Output is of the form
{1, 2, 3}
with no endl at the end.
operator<<() [3/3]
template<typename elemT > std::ostream& stir::operator<< (std::ostream & str, const std::vector< elemT > & v) inline
Outputs a vector to a stream.
Output is of the form
{1, 2, 3}
with an endl at the end.
For each element of the vector std::ostream::operator<<() will be called.
operator>>() [1/3]
template<typename elemT > std::istream& stir::operator>> (std::istream & str, std::vector< elemT > & v) inline
Inputs a vector from a stream.
Input is of the form
{1, 2, 3}
Input is stopped when either the beginning '{', an intermediate ',' or the trailing '}' is not found. The size of the vector will be the number of correctly read elemT elements.
For each element of the vector std::istream::operator>>(element) will be called.
elemT needs to have a default constructor.
operator>>() [2/3]
template<typename elemT > std::istream& stir::operator>> (std::istream & str, VectorWithOffset< elemT > & v) inline
Inputs a VectorWithOffset from a stream.
Input is of the form
{1, 2, 3}
As Array<>'s are constructed from nested VectorWithOffset objects, you can input say a 2d array as
{{1,2}, {2,4,5}, {5}}
Input is stopped when either the beginning '{', an intermediate ',' or the trailing '}' is not found. The size of the vector will be the number of correctly read elemT elements.
v.get_min_index() will be 0 at the end of the call.
For each element of the vector std::istream::operator>>(element) will be called.
elemT needs to have a default constructor.
operator>>() [3/3]
template<int num_dimensions, typename coordT > std::istream& stir::operator>> (std::istream & str, BasicCoordinate< num_dimensions, coordT > & v) inline
Inputs a coordinate from a stream.
Input is of the form
{1, 2, 3}
Input is stopped when either the beginning '{', an intermediate ',' or the trailing '}' is not found. If the number of correctly read elements is not num_dimensions, the last few will have undefined values.
For each element of the vector std::istream::operator>>(element) will be called.
elemT needs to have a default constructor.
threshold_upper_lower()
template<typename forw_iterT , typename elemT > void stir::threshold_upper_lower (forw_iterT begin, forw_iterT end, const elemT new_min, const elemT new_max) inline
Threshold a sequence from above and below.
Type requirements:
forw_iterT is a forward iterator
elemT must be assignable to *forw_iterT
bool operator>(*forw_iterT, elemT) must exist
Referenced by stir::stir_mathTests::run_tests(), and stir::OSSPSReconstruction< TargetT >::update_estimate().
threshold_upper()
template<typename forw_iterT , typename elemT > void stir::threshold_upper (forw_iterT begin, forw_iterT end, const elemT new_max) inline
Threshold a sequence from above.
See also
threshold_upper_lower for type requirements
Referenced by stir::ScatterEstimation::upsample_and_fit_scatter_estimate().
threshold_lower()
template<typename forw_iterT , typename elemT > void stir::threshold_lower (forw_iterT begin, forw_iterT end, const elemT new_min) inline
Threshold a sequence from below.
See also
threshold_upper_lower for type requirements
Referenced by stir::MatchTrackerAndScanner::run(), threshold_min_to_small_positive_value(), and stir::ScatterEstimation::upsample_and_fit_scatter_estimate().
threshold_min_to_small_positive_value()
template<typename ForwardIter_t , typename elemT > void stir::threshold_min_to_small_positive_value (ForwardIter_t begin, ForwardIter_t end, const elemT & small_number)
sets non-positive values in the sequence to small positive ones
Thresholds the sequence from below to *min_positive_element()*small_number. However, if all values are less than or equal to 0, they are set to small_number.
Parameters
begin start of the sequence. Usually object.begin().
end end of the sequence in iterator sense (so actually one beyond the last element). Usually object.end().
small_number see above
The iterator type has to satisfy the requirements of a forward iterator, and its value_type has to be comparable using < and <=.
References min_positive_element(), and threshold_lower().
Referenced by stir::OSSPSReconstruction< TargetT >::update_estimate().
ask_filename_and_open()
template<class FSTREAM > void stir::ask_filename_and_open (FSTREAM & s, const std::string & prompt, const std::string & default_extension, std::ios::openmode mode, bool abort_if_failed)
Asks for a filename (with default extension) and opens the stream s with mode giving the specifics.
Example: open a binary input file, aborting if it is not found
ifstream in;
ask_filename_and_open(s, "Input file ?", ".hv", std::ios::in | std::ios::binary);
Note: this function is templated to allow s to be of different types ifstream, ofstream, fstream
read_stream_in_memory()
void* stir::read_stream_in_memory (std::istream & input, std::streamsize & file_size)
reads data into memory, returning a pointer to the memory
If the file_size parameter is zero, the stream is read till EOF and 'file_size' is set to the number of bytes in the file. Otherwise 'file_size' bytes are read.
The data is read from the current position in the stream. At the end of this function, the 'input' stream will be positioned at original_position + file_size.
Referenced by ask_filename_and_open().
open_read_binary() [2/2]
template<class IFSTREAM > IFSTREAM& stir::open_read_binary (IFSTREAM & s, const std::string & name) inline
opens a stream for reading binary data. Calls error() when it does not succeed.
Warning
probably does not work if you are not in the C-locale
Referenced by ask_filename_and_open().
open_write_binary() [2/2]
template<class OFSTREAM > OFSTREAM& stir::open_write_binary (OFSTREAM & s, const std::string & name) inline
opens a stream for writing binary data. Calls error() when it does not succeed.
Templated such that it works on std::ofstream and std::fstream.
Warning
probably does not work if you are not in the C-locale
Referenced by ask_filename_and_open().
close_file() [2/2]
template<class FSTREAM > void stir::close_file (FSTREAM & s) inline
closes a stream without error checking.
Templated such that it works on std::ofstream, std::ifstream and std::fstream.
This function is only provided in case you need to write code that works with both std::fstream and stdio FILE.
Referenced by ask_filename_and_open().
four1()
void stir::four1 (Array< 1, float > & data, int nn, int isign)
1-dimensional FFT
Replaces data by its discrete Fourier transform, if isign is input as 1; or replaces data by nn times its inverse discrete Fourier transform, if isign is input as -1. data is a complex array of length nn, input as a real array data[1..2*nn]. nn MUST be an integer power of 2 (this is not checked for !).
fourn()
void stir::fourn (Array< 1, float > & data, Array< 1, int > & nn, int ndim, int isign)
n-dimensional FFT
Replaces data by its ndim-dimensional discrete Fourier transform, if isign is input as 1. nn[1..ndim] is an integer array containing the lengths of each dimension (number of complex values), which MUST all be powers of 2. data is a real array of length twice the product of thes lengths, in which the data are stored as in a multidimensional complex array: real and imaginary parts of each element are in consecutive locations , and the rightmost index of the array increases most rapidly as one proceeds along data. For a two-dimensional array, this is equivalent to storing the array by rows . If isign is in input as -1 , data is replaced by its inverse transform time the product of the lengths of all dimensions.
convlvC()
void stir::convlvC (Array< 1, float > & data, const Array< 1, float > & filter, int n)
Convolve data with a filter which is given in frequency space.
Parameters
data has to have a min_index == 1
filter has to in the format produced by realft.
n has to be equal to th elength of data
Warning
Currently, only the real elements of the filter will be used. (Historical reason?) So, the result will be incorrect of the filter has complex components (i.e. its spatial kernel is not symmetric).
realft()
void stir::realft (Array< 1, float > & data, int n, int isign)
Calculates the Fourier Transform of a set of 2n real-valued data points.
Replaces this data (which is stored in array data[1..2n]) by the positive frequency half of its complex Fourier Transform. The real-valued first and last components of the complex transform are returned as element data[1] and data[2] respectively. n must be a power of 2. The routine also calculates the inverse transform of a complex data array if it is the transform of real data. (Result in this case must be multiplied by 1/n.)