STIR: /home/sirfuser/devel/STIRdistrib/STIR/src/include/stir/IO/stir_AVW.h File Reference
stir_AVW.h File Reference
STIR » STIR library » Input/Output Library
routines to convert AVW data structures to STIR
#include "AVW.h"
#include "stir/common.h"
Classes
class stir::VoxelsOnCartesianGrid< elemT >
This class is used to represent voxelised densities on a cuboid grid (3D).
Namespaces
stir
Namespace for the STIR library (and some/most of its applications)
Functions
VoxelsOnCartesianGrid< float > * stir::AVW::AVW_Volume_to_VoxelsOnCartesianGrid (AVW_Volume const *const avw_volume, const bool flip_z=false)
A routine that converts AVW volume to stir::VoxelsOnCartesianGrid.
Detailed Description
routines to convert AVW data structures to STIR
Author
Kris Thielemans
Function Documentation
AVW_Volume_to_VoxelsOnCartesianGrid()
VoxelsOnCartesianGrid< float > * stir::AVW::AVW_Volume_to_VoxelsOnCartesianGrid (AVW_Volume const *const avw_volume, const bool flip_z = false)
A routine that converts AVW volume to stir::VoxelsOnCartesianGrid.
Will return a null pointer if the convertion failed for some reason.
References stir::AVW::AVW_Volume_to_VoxelsOnCartesianGrid(), and stir::warning().
Referenced by stir::AVW::AVW_Volume_to_VoxelsOnCartesianGrid().